### ISSUE TITLE
¿Como obtener el nombre de el Backup realizado en laravel?

### ISSUE THREAD

**Issue by XeguisX** [spatie/laravel-backup#1001]
Funciona hacer mi backup desde el controlador, pero no sé como tomar su nombre para permitir la descarga de este mismo...

**Comment by freekmurze** [comment]
Please use english on this issue tracker.

**Comment by XeguisX** [comment]
I do not speak English, and its package is supposed to be used globally, I feel disrespectful not to respond to Developers who speak Spanish as well as to respond to Developers who speak with a high level of English ...
Thanks for your attention..
@freekmurze
