### ISSUE TITLE
[ADVICE] Exclude directories and/or files using wildcards or partial matches

### ISSUE THREAD

**Issue by AforDesign** [spatie/laravel-backup#1002]
First of all, thank you for this great package.
It makes me sleep better at night.
The backups work great so far, but I'm struggling to exclude non-specific directories.

For example, I'm als using your media-library package.
In my backups, I'd like to include my original images, but exclude all conversions.
These conversions take up a lot of space and can easily be regenerated.

In my setup, conversions are saved in a subdirectory named 'conversions' per image.
So far I've not been able to exclude those, without specifying each directory separately.

What do I have to add to the exclude array to achieve this?

**Comment by apocalyarts** [comment]
I have the same question :D
