### ISSUE TITLE
The tests are failing

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-backup#1006]
This should be fixed.

**Comment by rubenvanassche** [comment]
Sqlite 3 was missing, added it to the workflow in the `github-actions` branch. But this https://github.community/t5/GitHub-Actions/ubuntu-latest-Apt-repository-list-issues/td-p/41122/page/2 problem keeps existing, will check next week to see if it is fixed.

**Comment by rubenvanassche** [comment]
Seems fixed!
