### ISSUE TITLE
No service provider

### ISSUE THREAD

**Issue by Tjoosten** [spatie/laravel-backup#101]
Hi i followed the installation manual. ***Version 3.2*** 

But when i do the `vendor:publish` no service provider nor config will be migrated. 

<img width="955" alt="schermafbeelding 2016-03-24 om 19 41 34" src="https://cloud.githubusercontent.com/assets/5157609/14027586/a87d09c2-f1f8-11e5-8629-22d0575fade8.png">

**Comment by freekmurze** [comment]
Did you add the service provider provided by the package to your `config/app.php` file?

**Comment by Tjoosten** [comment]
yes

**Comment by freekmurze** [comment]
Cool you set a `dd("hellow");` inside the service provider to make 100% sure that is being called?

**Comment by tylercd100** [comment]
Also try `php artisan vendor:publish --force --provider="Spatie\Backup\BacupServiceProvider"`

**Comment by Tjoosten** [comment]
php artisan vendor:publish --force --provider="Spatie\Backup\BacupServiceProvider" @tylercd100 didn't work

**Comment by Tjoosten** [comment]
@freekmurze dd('hellow') also didn't work

**Comment by freekmurze** [comment]
If putting `dd('hellow');` in the constructor of the service provider, it means that it is not been loaded by Laravel. Could you please post your `config/app.php` file?

**Comment by Tjoosten** [comment]
https://gist.github.com/510c9af11ad4e4c9f8d8 here we go!

**Comment by freekmurze** [comment]
do the backup commands show up when running `php artisan`?

**Comment by Tjoosten** [comment]
Nope nothing

2016-03-24 22:24 GMT+01:00 Freek Van der Herten <notifications@github.com>:

**Comment by freekmurze** [comment]
It seems like the service provider is not getting registered. I'm assuming this is caused by something special in your particular app or environment.

Could you try to install it into a fresh copy of Laravel?

**Comment by rawzone** [comment]
Have the same issue in a setup I'm currently working on... Will try to set it up in a clean Laravel install

Btw. the development is done in a homestead box...

**Comment by rawzone** [comment]
@Tjoosten Are you by any chance using the [AdminLTE](https://github.com/acacha/adminlte-laravel) package?

It seems it removes the backup commands from artisan when installed on top of the fresh Laravel install i just made.

**Comment by Tjoosten** [comment]
Hi guys thx for the support but i'm closing this issues. I woke up random and it worked
