### ISSUE TITLE
PHP Parse error:  syntax error, unexpected ':', expecting '{' in /home/admin/domains/domain.com/domain/vendor/spatie/laravel-backup/src/Helpers/functions.php on line 5

### ISSUE THREAD

**Issue by arbabi2010** [spatie/laravel-backup#1018]
Hi. Please help me. I'm using php 7.2 and v4 of this package but i have this issue for a long time
![image](https://user-images.githubusercontent.com/5072444/72063364-e8596780-32ee-11ea-8036-a326311ad87e.png)

**Comment by vdbelt** [comment]
Check if the version of PHP running your backups is the same as the one you are using for cli.

**Comment by arbabi2010** [comment]
> Check if the version of PHP running your backups is the same as the one you are using for cli.

How can i see the version of php running my backups?
