### ISSUE TITLE
 Class 'League\CommonMark\Environment' not found , on sending email i think

### ISSUE THREAD

**Issue by rajatvermaiam** [spatie/laravel-backup#1019]
Class 'League\CommonMark\Environment' not found (View: /home/videocyp/app/vendor/laravel/framework/src/Illuminate/Mail/resources/views/html/footer.blade.php) {"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): Class 'League\\CommonMark\\Environment' not found (View: /home/videocyp/app/vendor/laravel/framework/src/Illuminate/Mail/resources/views/html/footer.blade.php) at /home/videocyp/app/vendor/laravel/framework/src/Illuminate/Mail/Markdown.php:103)

**Comment by watercayman** [comment]
Had this same issue after updating to Laravel 6.10, 6.11.  No change to composer for me, but this is inside Laravel.  Files are there, and appear namespaced correctly, so not sure what's going on.

**Comment by yaim** [comment]
@rajatvermaiam this seems to be completely unrelated to spatie/laravel-backup. If you are still facing the problem, I guess make an issue in laravel/framework (with a proper reproduce definition).

**Comment by CrytexEngineer** [comment]
asshole so whats the solution?

**Comment by CrytexEngineer** [comment]
lol give me the solution
