### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by peterbata** [spatie/laravel-backup#102]
Hello. I am new to Laravel 5.2 and Laravel backup v3. Would someone be kind enough to assist me in setting up / understanding the backup configuration file. Thank you all in advance. Peter

**Comment by freekmurze** [comment]
The [default configuration](https://github.com/spatie/laravel-backup/blob/master/config/laravel-backup.php) contain some sensible default. Comments to explain the options are provided. The [documentation](https://docs.spatie.be/laravel-backup/v3/installation-and-setup) provides some more info.

What specific aspect are you struggeling with?

**Comment by peterbata** [comment]
What section(s) of the config file need or need not be modified?

Do I execute php artisan:back run with the default config?

Eg. Database credentials, backup paths, etc.

The docs might be useful to someone who has had more experience with the framework.

I am just starting off here. So, please bear with me.

Thank you.

Peter

**Comment by freekmurze** [comment]
If you run `backup:run` it'll run with the values specified in the config file. The all files/directories in the include key (excluding the ones in the exclude key) will be backuped up. By default your database will be backuped as well. It'll use the values specified in `config/database.php`.

For the basic understanding of Laravel, I highly recommend viewing the [fundamentals course](https://laracasts.com/series/laravel-5-fundamentals) on Laracasts.

**Comment by peterbata** [comment]
Luckily I was able to figure this one on my own. Thank you for closing the issue.
