### ISSUE TITLE
Install crashed with "Target [Spatie\Backup\Tasks\Cleanup\CleanupStrategy] is not instantiable while building [Spatie\Backup\Commands\CleanupCommand]"

### ISSUE THREAD

**Issue by helix4d** [spatie/laravel-backup#1022]
laravel 6.12

```
> @php artisan package:discover

In Container.php line 978:
Target [Spatie\Backup\Tasks\Cleanup\CleanupStrategy] is not instantiable while building [Spatie\Backup\Commands\CleanupCommand].                        
                                                                               
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.
```

**Comment by AEK-BKF** [comment]
Same error with me !
L ^6.2

**Comment by AEK-BKF** [comment]
Got it,
@helix4d  Check here : https://github.com/spatie/laravel-backup/issues/957#issuecomment-538835302

**Comment by sizrar** [comment]
Same resolution as  #957   for me as well. Delete the bootstrap/cache/config.php file unlocks the correct installation of spatie/laravel-backup with composer and thus fixes artisans commands launch.

**Comment by jpmurray** [comment]
Adding my voice to those. I can't believe the only solution is just manually delete the cache config file on _every_ deployment... !

**Comment by freekmurze** [comment]
I cannot reproduce this, I'm thinking you might have been doing something wrong when installing/updating the package. Please remove the package and try installing it again. Make sure to clear the config cache.

**Comment by jpmurray** [comment]
I understand you can't reproduce it, it's ok. But just to make it clear, what could have I do wrong while installing the package? I mean, this happened to me while running `composer require spatie/laravel-backup`...

I'll try to install in on other smaller project that doesn't require it just to check, if anything pops out, I'll get back.

**Comment by kroobeet** [comment]
> Same resolution as #957 for me as well. I deleted the bootstrap/cache/config.php file unlocks the correct installation of spatie/laravel-backup with composer and thus fixes artisans commands launch.

Thanks. It helped me

**Comment by talha2k** [comment]
https://github.com/spatie/laravel-backup/issues/957#issuecomment-538835302
