### ISSUE TITLE
Google Drive backup error

### ISSUE THREAD

**Issue by salioudiabate** [spatie/laravel-backup#1027]
Hi I need help, I want to backup my database on Google Drive but I have this error :

Copying zip failed because: {
"error": {
"errors": [
{
"domain": "global",
"reason": "notFound",
"message": "File not found: Gelico.",
"locationType": "parameter",
"location": "fileId"
}
],
"code": 404,
"message": "File not found: Gelico."
}
}
Sending notification failed

**Comment by mndeto** [comment]
Hello @salioudiabate ,

[Here is your solution](https://github.com/spatie/laravel-backup/issues/468#issuecomment-328912896).

**Comment by officialprazol** [comment]
Just use this on  

 \Config::set('backup.backup.name', env('GOOGLE_DRIVE_FOLDER_ID'));

env('GOOGLE_DRIVE_FOLDER_ID') is the folder ID of drive folder
