### ISSUE TITLE
Backups are unhealthy when they are not

### ISSUE THREAD

**Issue by Christophvh** [spatie/laravel-backup#1028]
Versions:
Laravel: 6.13.1
Laravel backup: 6.7.7
PHP: 7.3

Using S3 for back-ups
```

`  'destination' => [
            /*
             * The filename prefix used for the backup zip file.
             */
            'filename_prefix' => '',

            /*
             * The disk names on which the backups will be stored.
             */
            'disks' => [
                'backup-s3',
            ],
        ]
```
```
'monitorBackups' => [
        [
            'name' => config('app.name'),
            'disks' => ['backup-s3'],
            'health_checks' => [
                \Spatie\Backup\Tasks\Monitor\HealthChecks\MaximumAgeInDays::class => 1,
                \Spatie\Backup\Tasks\Monitor\HealthChecks\MaximumStorageInMegabytes::class => 5000,
            ],
        ],
`
```

Scheduler
```
     if ('production' === app()->environment()) {
            $schedule->command('backup:clean')->daily()->at('01:00');
            $schedule->command('backup:run')->daily()->at('02:00');
            $schedule->command('backup:monitor')->daily()->at('03:00');
     }
```

When I look in S3 everything is working as expected, but we keep getting a notice that the backup is unhealthy.

The unhealthy notice keeps saying it is unhealthy for the local disk, but I do not back-up to the local disk.
![Screenshot 2020-01-31 at 10 38 31](https://user-images.githubusercontent.com/9588070/73528836-f09c5280-4415-11ea-8ec4-526d16bd1e76.png)

**Comment by carduz** [comment]
I have the same issue

**Comment by carduz** [comment]
I've solved, creating a new backup configuration starting from the original configuration (retrieved from github)

**Comment by Christophvh** [comment]
> I've solved, creating a new backup configuration starting from the original configuration (retrieved from github)

I already checked the config on GitHub, I have exactly the same except that I use a custom file-driver.

**Comment by rocramer** [comment]
Same for me. I'm using the latest version 6.7.7 and the latest config template.

I back up to an own minio server (s3). The `backup:run` works as expected. The backups are healthy but the command backup:list shows:

```
+----------------------+-------+-----------+---------+--------------+--------------------+--------------+
| Name                 | Disk  | Reachable | Healthy | # of backups | Newest backup      | Used storage |
+----------------------+-------+-----------+---------+--------------+--------------------+--------------+
| App                | local | ✅          | ❌       | 0                           | No backups present | 0 B        |
+----------------------+-------+-----------+---------+--------------+--------------------+--------------+

```

**Comment by rocramer** [comment]
Okay, it seems that you have to specify `local` as backup destination as well. After that the health check marks my `local` and `minio` destination as healthy.
