### ISSUE TITLE
Is there already a check that fails when .sql file is empty ?

### ISSUE THREAD

**Issue by smknstd** [spatie/laravel-backup#1043]
If not, what do you think of adding it as default healthcheck ?

**Comment by vdbelt** [comment]
`spatie/db-dumper` returns an [exception](https://github.com/spatie/db-dumper/blob/e167b8bf925c5da553f885326bb7bfaed3f95d15/src/DbDumper.php#L254) if the generated sql dump is empty or fails for another reason.

So that should automatically result in a BackupHasFailed event.

**Comment by smknstd** [comment]
Excellent !

I was wondering if comparison with 0 is not too strict maybe. As sometimes while backup failed, it seems file could be just a few bytes (as reported here https://github.com/spatie/laravel-backup/issues/931). What do you think ?

**Comment by freekmurze** [comment]
Feel free to PR improvements around this!
