### ISSUE TITLE
Accessing details of backups 

### ISSUE THREAD

**Issue by ssmusoke** [spatie/laravel-backup#1048]
I am using the library to backup databases - I am looking for a way to get the details of the last backup including the path of the backup so that I can pass that to a command to download the file from the disk where it was stored

**Comment by freekmurze** [comment]
Take a look at this code snippet from our nova-backup-tool package: https://github.com/spatie/nova-backup-tool/blob/b868cb71643cf691eb0ccab36b9c5038f07165e4/src/Http/Controllers/BackupsController.php#L22-L34

**Comment by ssmusoke** [comment]
@freekmurze Interesting do you think it makes sense to add an option to download the latest backup to the artisan command - helps with automation for restores

**Comment by freekmurze** [comment]
Thanks for the suggestion, but I want to stay clear of all restoring behaviour in this package. Don't want to maintain that.

**Comment by ssmusoke** [comment]
Oh I totally get it makes a lot of sense
