### ISSUE TITLE
3.3.0 is failing

### ISSUE THREAD

**Issue by tylercd100** [spatie/laravel-backup#105]
Hey @freekmurze you forgot to implement `setDefaultValuesForNewConfigValues` method in the service provider! 3.3.0 is failing

**Comment by tylercd100** [comment]
Looks like you fixed it

**Comment by freekmurze** [comment]
Whoops, yeah I just noticed it. Sorry about that. That'll teach me not to wait on Travis before tagging. 

I removed the `setDefaultValuesForNewConfigValues` entirely. Because we use `mergeConfigFrom` it is not need.

**Comment by tylercd100** [comment]
Oh wow that method is extremely useful! Good to know for when I contribute next time :)
