### ISSUE TITLE
Cleanup failed because: Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required ".

### ISSUE THREAD

**Issue by ValleyInforge** [spatie/laravel-backup#1054]
When I lunching "php artisan backup:clean" I got this error:

Starting cleanup...
Cleaning backups of "_MY-SITE_" on disk local...
**Cleanup failed because: Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required".**

"php artisan backup:run" it work.

I think that the problem is the SMPT server

**Comment by ValleyInforge** [comment]
Fixed! It was a wrong SMTP configuration

**Comment by JorgeMiguelDelgado** [comment]
Que cambiaste ?
