### ISSUE TITLE
External backup sources

### ISSUE THREAD

**Issue by OppPMatos** [spatie/laravel-backup#1056]
Hi.

I'm currently using the package to backup my site's files and BD to an external location.
But I also have been trying to setup external file sources to be in the backup, but I can't seem to do it.

Is it possible to use a disk driver as a source? If so, how?
I've tryed setting up in the filesystem an FTP driver to a another site, but I can't get it to work in the includes array.

Thanks in advance.

**Comment by freekmurze** [comment]
This currently is not possible. I'm currently working on the spiritual successor of this package that will enable to backup external sources. ETA: a couple of months.

**Comment by marnickmenting** [comment]
I would be interested in this too, I would like to back-up from S3 storage to FTPS disk of the customer (in a multi-tenant setup).
