### ISSUE TITLE
Cleanup seem to ignore my settings

### ISSUE THREAD

**Issue by grayfella** [spatie/laravel-backup#1057]
I am using default install setup. Running on Ubuntu 18.04.4 LTS via AWS.
I just edited the backup.php config file in the config folder 

            'keepAllBackupsForDays' => 7,
            'keepDailyBackupsForDays' => 14,

This is backing up S3. The backup works everytime to S3 without issues.
When I run cleanup task from command line or via schedule it will delete all file except today's.
Am I missing something?

The monitor task has been set as 

    'monitorBackups' => [
        [
            'name' => config('app.name'),
            'disks' => ['s3'],
            'newestBackupsShouldNotBeOlderThanDays' => 1,
            'storageUsedMayNotBeHigherThanMegabytes' => 50,
        ],

That when run from command line shows issues with 'local' disk which at no point have I setup in the config.
Odd.

Thanks in advance.

**Comment by freekmurze** [comment]
Probably you should clear the config cache with `php artisan clear:config`
