### ISSUE TITLE
Backup to Dropbox gives 429 Too Many Requests

### ISSUE THREAD

**Issue by dash8x** [spatie/laravel-backup#1059]
I'm using spatie/laravel backup v5.12.1 on Laravel 5.5 to make daily backups to Dropbox using  spatie/flysystem-dropbox.

It's been running perfectly for more than 2 years now without much issues. But recently we are getting '429 Too Many Requests' from Dropbox when the backup is run. The backup file is still generated and it's successfully uploaded to Dropbox, but I think somethings getting wrong while checking the backups health.

Assuming that it's caused by too many previous backup files in the Dropbox folder, I had permanently deleted most of the previous backups. But the issue still hasn't resolved.

**Comment by yagrasdemonde** [comment]
Same issue for me !

**Comment by freekmurze** [comment]
I accept a PR that improves on this behaviour.

**Comment by patriziotomato** [comment]
Maybe duplicate to #1067

**Comment by freekmurze** [comment]
Closing this for now. Reopen if #1084 didn't fix this.
