### ISSUE TITLE
separate  cleanup command for File and Database backup.

### ISSUE THREAD

**Issue by ajaymakwana01** [spatie/laravel-backup#1066]
if you are providing backup:run for --db-only and --file-only, then why single cleanup command for both?
currently, the issue is that in my requirement I want to backup file and database separately but due to the large size of file backup I have to delete file backup after 3 days and database backup for 7 days. Is there any way to do that?

**Comment by freekmurze** [comment]
The package doesn't do that out of the package. You will need to write your own cleanup strategy (see the docs on how to do that).
