### ISSUE TITLE
Event BackupWasSuccessful no working

### ISSUE THREAD

**Issue by chelohl11** [spatie/laravel-backup#1069]
In my EventServiceProvider

use App\Listeners\RegisterInDatabaseBackup;

protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        \Spatie\Backup\Events\BackupWasSuccessful::class => [
            RegisterInDatabaseBackup::class,
        ],
    ];
RegisterInDatabaseBackup : 
use Spatie\Backup\Events\BackupWasSuccessful;

public function handle(BackupWasSuccessful $event)
    {
        $file = $event->backupDestination->backups()->first();
        $request = request()->input();
        $request['user_id'] = auth()->user()->id;
        $request['name'] = substr($file->path(), -23);
        $request['size'] = $file->size();
        $backup = Backup::create($request);
}

In other project working (Laravel 6.2 and laravel-backup 6.8), but in Laravel 7.10.3 with laravel-backup 6.9.0 not

**Comment by freekmurze** [comment]
Our tests prove that this is working correctly, please PR a failing test for us to fix.
