### ISSUE TITLE
Backup faild

### ISSUE THREAD

**Issue by steenrabol** [spatie/laravel-backup#107]
[2016-03-30 07:51:39] local.ERROR: http://kp.dev backups : error: Failed to backup  because: RecursiveDirectoryIterator::__construct(C:\webdev\kpdev\node_modules\laravel-elixir\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\node_modules\babel-code-frame\node_modules\chalk\node_modules\strip-ansi\node_modules\ansi-regex,C:\webdev\kpdev\node_modules\laravel-elixir\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\node_modules\babel-code-frame\node_modules\chalk\node_modules\strip-ansi\node_modules\ansi-regex): The system cannot find the path specified. (code: 3)  

what path is missing ?

**Comment by freekmurze** [comment]
Were you changes these files when backing up?

I don't think backing up `node_modules` is necessary, you can easily recreate that folder by running `npm install`. If you agree, then add that directory to the excluded paths in the config and try backing up again.

**Comment by steenrabol** [comment]
Hi
It's my first time using this package ad it was part of the Laravel-5-Boiler plate so I 'simply' assume that it was correctly configured - My mistake

'exclude' => [
                    base_path('vendor'),
                    storage_path(),
                    base_path('node_modules'),
                ],

still the same result :(

**Comment by freekmurze** [comment]
Is `C:\webdev\kpdev` the root of your project? Then the error message your getting can't be `C:\webdev\kpdev\node_modules` as you've just excluded that directory.

**Comment by steenrabol** [comment]
yes c:\webdev\kpdev is the root

I added base_path('node_modules') the the config file c:webde\kpdev\conig\laravel-backup.php
then:
php artisan clear-compiled
php artisan cache:clear
php artisan optimize
php artisan backup:run

and then I get the error

Anything I can do to provide more information ?

**Comment by freekmurze** [comment]
Are you still getting the same error message? If so could you try exclude the entire base directory?

**Comment by steenrabol** [comment]
'exclude' => [
                    base_path('vendor'),
                    storage_path(),
                    base_path(),
                    'c:/webdev/kpdev/',
                    'c:/webdev/kpdev/nodes_modules/',
                    'c:/webdev/kpdev/nodes_modules/laravel-elixir/',
                    'c:/webdev/kpdev/nodes_modules/laravel-elixir/nodes_modules',
                    'C:\webdev\kpdev\node_modules\laravel-elixir\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\node_modules\babel-code-frame\node_modules\chalk\node_modules\strip-ansi\node_modules\ansi-regex',
                ],

and still the same error

Will try to create a 'clean' laravel app and only the backup package

**Comment by sebastiandedeyne** [comment]
Some Windows commands have issues with file paths longer than 256 characters. That's probably why you're getting the obscure error, successfully excluding `node_modules` should fix the issue (not sure why that's going wrong though).

**Comment by steenrabol** [comment]
sorry, but excluding node_modules, doe not work

I have just made a fresh laravel

Did this:
laravel new test
created a mysql DB
updated .env
composer require spatie/laravel-backup
updated config/app.php to include the service provider

php artisan cleat-compiled
php artisan optimize
php artisan make:auth
php migrate:install
php migrate
php backup:run

C:\webdev\test>php artisan backup:run
Starting backup...
Dumping database test...
Determining files to backup...
Zipping 81 files...
Copying 2016-03-30-090812.zip (size: 58.03 KB) to disk named local...
Successfully copied .zip file to disk named local.
Backup completed!

now...
npm install

php artisan backup:run

then I get all kinds of errors

**Comment by steenrabol** [comment]
I think I have found something...

                'exclude' => [
                    base_path('vendor'),
                    storage_path(),
                    'C:/webdev/kpdev/node_modules/',
                ],


but the error is showing
c:\webdev\kpdev\node_modules....

I'm thinking... \n is newline, maybe the path names separator needs to be / and not \ ?

**Comment by steenrabol** [comment]
Please forgive me, but there must be a design flaw in the backup
If base_path() is in the 'Exclude' array, then no files should be included, or do I miss the point ?

**Comment by sebastiandedeyne** [comment]
No that sounds right. Just added a test to double check and it seems to pass (https://github.com/spatie/laravel-backup/blob/master/tests/Unit/FileSelectionTest.php#L106).

Could you somehow log `filesToBeIncluded` and `filesToBeExcluded` here: https://github.com/spatie/laravel-backup/blob/master/src/Tasks/Backup/FileSelection.php#L66-L72

Might be some small error comparing the paths, but we need to find out which ones break the function first.

**Comment by steenrabol** [comment]
well...

$filesToBeIncluded = $this->getAllFilesFromPaths($this->includeFilesAndDirectories);

in the method getSeletecdFiles never completes

**Comment by sebastiandedeyne** [comment]
Ok I think I know what's going on. Whether the backup happens or not, the command has to go through all of the directories to determine what it wants to back up. I have a pretty big hunch it breaks here due to Windows' 260-character path limit.

Possible solutions:

a) Don't include everything and exclude, just include what you want to back up
b) Update npm to v3+, since it introduced a new directory structure you most likely won't be hitting the character limit anymore

**Comment by steenrabol** [comment]
updating npm did help, but....
the 'recommended' version is not the latest :)
the recommended version is 4.4.1 from (https://nodejs.org/en/)

why even look at the files in the 'Exclude directory'?

so next, small thing... I would have assumed that the backup file would be in /storage/laravel-backup, but instead it is in /storage/app/http---kp.dev/

I do understand that it takes the destination directory from my /config/filesystems.php, but where does it get the sub-directory from ?

i also tried to 

have this:
                'include' => [
                    base_path('app'),
                    base_path('config'),
                ],

and

                'exclude' => [
                ],

i would then assume that only 'app' and 'config' was in the backup file... wrong, it also contains a lot of other files, why ?

**Comment by steenrabol** [comment]
sorry... must have looked at the wrong zip file... only contains the included directories

**Comment by freekmurze** [comment]
Closing this for now. Reopen if you are still having problems.
