### ISSUE TITLE
Which file we should modify for use this library on windows server ?

### ISSUE THREAD

**Issue by rizkiheryandi** [spatie/laravel-backup#1071]
Hi guys, i appreciate this library so much,

But after read the documentation, it said not compatible on windows server.

So Which file we should modify for use this library on windows server ?

Or 

There's other libarary like this and compatible with windows server ?

Thanks

**Comment by freekmurze** [comment]
I'm not a windows user, so I can't help you there. 

My suggestion would be to just try it out, and see which parts work for you and which don't.

**Comment by rizkiheryandi** [comment]
After we run backup on windows server, we got these errors :

`Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the p
h specified.
.
#0 C:\inetpub\stage.something.com\vendor\spatie\db-dumper\src\DbDumper.php(246): Spatie\DbDumper\Exceptions\
mpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))
#1 C:\inetpub\stage.something.com\vendor\spatie\db-dumper\src\Databases\MySql.php(148): Spatie\DbDumper\DbDu
er->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), 'C:\\inetpub\\stag...')
#2 C:\inetpub\stage.something.com\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(246): Spatie\D
umper\Databases\MySql->dumpToFile('C:\\inetpub\\stag...')
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Sp
ie\DbDumper\Databases\MySql), 'mysql')
#4 C:\inetpub\stage.something.com\vendor\laravel\framework\src\Illuminate\Support\Collection.php(948): array
ap(Object(Closure), Array, Array)
#5 C:\inetpub\stage.something.com\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(249): Illumina
\Support\Collection->map(Object(Closure))
#6 C:\inetpub\stage.something.com\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(166): Spatie\B
kup\Tasks\Backup\BackupJob->dumpDatabases()
#7 C:\inetpub\stage.something.com\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(142): Spatie\B
kup\Tasks\Backup\BackupJob->createBackupManifest()
#8 C:\inetpub\stage.something.com\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(52): Spatie\Ba
up\Tasks\Backup\BackupJob->run()
#9 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#10 C:\inetpub\stage.something.com\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): ca
_user_func_array(Array, Array)
#11 C:\inetpub\stage.something.com\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Il
minate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 C:\inetpub\stage.something.com\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Il
minate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closu
))
#13 C:\inetpub\stage.something.com\vendor\laravel\framework\src\Illuminate\Container\Container.php(564): Ill
inate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#14 C:\inetpub\stage.something.com\vendor\laravel\framework\src\Illuminate\Console\Command.php(183): Illumin
e\Container\Container->call(Array)
#15 C:\inetpub\stage.something.com\vendor\symfony\console\Command\Command.php(251): Illuminate\Console\Comma
->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#16 C:\inetpub\stage.something.com\vendor\laravel\framework\src\Illuminate\Console\Command.php(170): Symfony
omponent\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\C
sole\OutputStyle))
#17 C:\inetpub\stage.something.com\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(16): Illuminate
onsole\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Outp
\ConsoleOutput))
#18 C:\inetpub\stage.something.com\vendor\symfony\console\Application.php(886): Spatie\Backup\Commands\BaseC
mand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Console
tput))
#19 C:\inetpub\stage.something.com\vendor\symfony\console\Application.php(262): Symfony\Component\Console\Ap
ication->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\A
vInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\inetpub\stage.something.com\vendor\symfony\console\Application.php(145): Symfony\Component\Console\Ap
ication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Co
oleOutput))
#21 C:\inetpub\stage.something.com\vendor\laravel\framework\src\Illuminate\Console\Application.php(89): Symf
y\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Compo
nt\Console\Output\ConsoleOutput))
#22 C:\inetpub\stage.something.com\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122
 Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Compo
nt\Console\Output\ConsoleOutput))
#23 C:\inetpub\stage.something.com\artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\
mponent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}
Backup failed because: The dump process failed with exitcode 1 : General error : The system cannot find the
th specified.
.
`

It's also happen if we only use --only-db option

before, i think it's just for files backup, but it's also database, because database is more important

Anyone can help please ?

**Comment by rizkiheryandi** [comment]
@freekmurze

**Comment by rizkiheryandi** [comment]
if still there's no solution for this

I think we should share our database and running backup on separate server, absolutely that server will use linux server, like ubuntu.

**Comment by rizkiheryandi** [comment]
i found this thread https://github.com/spatie/laravel-backup/issues/370 and has same error with me

like it's compatible with windows server since spatie/laravel-backup:4.4.9

and we using "spatie/laravel-backup": "^5.0.0" now, it should contained same MR
