### ISSUE TITLE
What can be done if windows server ? ( It’s not compatible with Windows servers.)

### ISSUE THREAD

**Issue by GRIMaxx** [spatie/laravel-backup#1073]
What can be done if windows server, is there a solution?

**Comment by freekmurze** [comment]
I don't use Windows, so I'm not going to invest my time on it. If there are things not working for you send a PR.

**Comment by alcarazolabs** [comment]
The documentation of spatie should say "this tool doesn't work for windows users"

**Comment by freekmurze** [comment]
@alcarazolabs it does say that 👍 
https://spatie.be/docs/laravel-backup/v7/requirements

**Comment by alcarazolabs** [comment]
@freekmurze thanks, I will try using Linux. But spatie laravel backup works using php 7.4 running php artisan backup:run
