### ISSUE TITLE
Run Command on shared server

### ISSUE THREAD

**Issue by amanrabby** [spatie/laravel-backup#1079]
how to run command on shared server. 
Note: I can run 
```
Route::get('storage_link', function() {
			$status = Artisan::call('storage:link');
			return '<h1>Storage Linked</h1>';
		});
```
it's working fine. but when I use laravel backup package & try to run

```
	Route::get('backup', function() {
			$status =Artisan::call('backup:run');
		    return '<h1>backup complete</h1>';
		});

```
it gives an error "The command "backup:run" does not exist.". Can anyone please help me out

**Comment by freekmurze** [comment]
The commands this package provides are only registered in console invocations by default.
https://github.com/spatie/laravel-backup-server/blob/12326b31e3ce26cd31e5177e786a56d07f129443/src/BackupServerServiceProvider.php#L65

If you want to use the commands in a web request, you need to register these commands in the console kernel.
