### ISSUE TITLE
ftp functionality

### ISSUE THREAD

**Issue by DorienCragen** [spatie/laravel-backup#109]
ability to add application from another server, connect to it via sftp add files zip and store zip to cloud or somewhere would be brilliant.

**Comment by freekmurze** [comment]
I'm not sure what you mean. Could you please explain your idea in greater detail?

**Comment by DorienCragen** [comment]
i meant thing like so:

`
'source' => [
            'files' => [
                'include' => [
                    'ftp://username:userpass@ftphost.com/path/to/extra/app/'
]]]
`
this ability would by very powerfull

**Comment by freekmurze** [comment]
I think this is out of scope for this package. If you need to backup other servers, look at something like [backuppc](http://backuppc.sourceforge.net/).
