### ISSUE TITLE
Wildcard exclude

### ISSUE THREAD

**Issue by genesiscz** [spatie/laravel-backup#1099]
There was a pull request which was merged https://github.com/spatie/laravel-backup/pull/128

but this does not seem to be the current state because its not included in the config file nor working. What happeneD?

**Comment by freekmurze** [comment]
Seems like the tests is still in there, and passing: https://github.com/spatie/laravel-backup/blob/5474020f3b26e0d6b30d41af4be8f133d7202e60/tests/FileSelectionTest.php#L72

**Comment by genesiscz** [comment]
Is there a reason it was removed from the config commend?
