### ISSUE TITLE
Error translate

### ISSUE THREAD

**Issue by tongvanduc** [spatie/laravel-backup#1101]
![image](https://user-images.githubusercontent.com/18494990/88451680-c8e8ed00-ce82-11ea-9a7f-eb5d51e40190.png)

**Comment by cristianofromagio** [comment]
All values on this (probably) mail template seems like default values. The `trans()` helper call happens [here](https://github.com/spatie/laravel-backup/blob/85d6710ce77176ce926268a22825f9f70afb7aae/src/Notifications/Notifications/BackupWasSuccessful.php#L26). The notification subject also did not get translated?

```php
    ->subject(trans('backup::notifications.backup_successful_subject', ['application_name' => $this->applicationName()]))
    ->line(trans('backup::notifications.backup_successful_body', ['application_name' => $this->applicationName(), 'disk_name' => $this->diskName()]));
```

Saw by your profile that you're from Việt Nam. At the moment `laravel-backup` does not have a vietnamese (`vi`) [language file](https://github.com/spatie/laravel-backup/tree/master/resources/lang). Maybe check the values for `locale` and `fallback_locale` at your `config/app.php`.

**Comment by andersespedalen** [comment]
In that case it would be great to be able to specify in config/backup.php what language to use (that is supported by the package) instead of defaulting to the app locale.
