### ISSUE TITLE
attach backup to email notification

### ISSUE THREAD

**Issue by HerlyOlivares** [spatie/laravel-backup#1104]
Hello, is there a way to attach the backup to the notification via email or to create a custom notification? Thank you.

**Comment by omidMolaverdi** [comment]
How did you do that?

**Comment by HerlyOlivares** [comment]
Hello, I leave you the link to the article where they explain it in more detail.

https://medium.com/@DaveAbiola/laravel-database-backup-backup-mail-dcb4074aa9d7
