### ISSUE TITLE
Issue: Cannot select disk for backups

### ISSUE THREAD

**Issue by amberlampsio** [spatie/laravel-backup#111]
Having a small issue, running command,
`php artisan backup:run --only-to-disk=local
`

`[RuntimeException]                                    
  The "--only-to-disk" option does not accept a value.`

version 3.4

documentation states you can provide a disk name.

**Comment by amberlampsio** [comment]
possible fix, by adding '=' after only-to-disk parameter in BackupCommand.php

`    protected $signature = 'backup:run {--only-db} {--only-files} {--only-to-disk=}';
`

**Comment by sebastiandedeyne** [comment]
That was a bug indeed. Fixed and tagged as 3.4.1!
