### ISSUE TITLE
Bug: rmdir: directory is not empty

### ISSUE THREAD

**Issue by jorenvh** [spatie/laravel-backup#1111]
This is a duplicate of issue #393 

I was able to reproduce the issue and resolve it based on this PR https://github.com/spatie/laravel-db-snapshots/pull/78.

I'm happy to create a PR to fix the issue, however it could be fixed on 2 different levels for that reason I'm opening this issue to make sure I fix it on the desired level.

1. Laravel backup
In `src/Tasks/Backup/BackupJob.php` on line 158 & 164 `gc_collect_cycles();` should be added

2. spatie/temporary-directory
In `TemporaryDirectory.php` in the `deleteDirectory` method on line 163 `gc_collect_cycles();` should be added

If you could point out what your desired solution is, then I'm happy to create a PR for it.

**Comment by freekmurze** [comment]
Thanks for having investigated this. Could you give more info on how calling `gc_collect_cycles` fixed the issue?

**Comment by jorenvh** [comment]
To be honest I'm still trying to figure out what `gc_collect_cycles` exactly does, it has something todo with garbage collecting though.  

I do know that calling `gc_collect_cycles` fixes the issue, same as it did for spatie/laravel-db-snapshots#78.
 
Source I already read trying to understand the solution: 
- https://www.php.net/manual/en/function.gc-collect-cycles.php
- https://www.php.net/manual/en/features.gc.collecting-cycles.php

**Comment by freekmurze** [comment]
Ok, a good explanation is written in the snapshot issue

```
By forcing a php garbage collection cycle using gc_collect_cycles() we can ensure that the rmdir function called in spatie/temporary-directory/TemporaryDirectory does not fail due to files still being reserved in memory (in the garbage due to fclose, but reserved nonetheless).
```

Let's fix it in `spatie/temporary-directory`. Send a PR to that package, closing this issue here.

**Comment by metaversedataman** [comment]
Using Laravel 10, I found a solution to the error: Backup failed because: rmdir(backup-temp\temp): Directory not empty

See [](https://github.com/spatie/laravel-db-snapshots/pull/78)
