### ISSUE TITLE
PROCESS privilege required for mysql 14.14

### ISSUE THREAD

**Issue by anchetaWern** [spatie/laravel-backup#1132]
Hello! I'm getting the following error when trying to backup:

```
The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
mysqldump: Got error: 1044
```

I looked it up (https://dba.stackexchange.com/questions/271981/access-denied-you-need-at-least-one-of-the-process-privileges-for-this-ope), and it seems like, we now need to add `--no-tablespaces` option. I don't really have the permission to do the alternative which is to add the PROCESS privilege to the user.

**Comment by freekmurze** [comment]
In the config file, you can add extra options that will be passed to the dp dumper.

There's an example in our docs: https://spatie.be/docs/laravel-backup/v6/installation-and-setup#dumping-the-database

**Comment by rickgoemans** [comment]
I still wonder how such options would be achieved, is it just add `--no-tablespaces` to the `dump` option of the connection in `database.php` file?

For example:
```php
<?php

return [
    'connections' => [
        'mysql' => [
            'driver'         => 'mysql',
            'url'            => env('DATABASE_URL'),
            'host'           => env('DB_HOST', '127.0.0.1'),
            'port'           => env('DB_PORT', '3306'),
            'database'       => env('DB_DATABASE', 'forge'),
            'username'       => env('DB_USERNAME', 'forge'),
            'password'       => env('DB_PASSWORD', ''),
            'unix_socket'    => env('DB_SOCKET', ''),
            'charset'        => 'utf8mb4',
            'collation'      => 'utf8mb4_unicode_ci',
            'prefix'         => '',
            'prefix_indexes' => true,
            'strict'         => true,
            'engine'         => null,
            'options'        => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
            'dump'           => [
                'useSingleTransaction' => true,
                '--no-tablespaces', // THIS?
            ],
        ],
        // ..
    ],

    // ...

];
```

The documentation on options is lacking for options in my opinion.

I've checked the https://github.com/spatie/db-dumper repo and that it has the `->addExtraOption(...)` function but not how this is used in this package.

**Comment by kovkor** [comment]
@rickgoemans 

use this format in your config file:

```
 'dump' => [
                'addExtraOption' => '--no-tablespaces --column-statistics=0',
            ],
```
