### ISSUE TITLE
Support nonstandard ports for database connections

### ISSUE THREAD

**Issue by colin-c** [spatie/laravel-backup#114]
If a port is set in config/database.php, this package should respect that.

A setPort method already exists for your database classes; it just needs to be used in BackupJobFactory.

**Comment by freekmurze** [comment]
You're correct, I'll fix it in the coming days. If you needs this quick, submit a PR.

**Comment by freekmurze** [comment]
Fixed in v3.4.2.

**Comment by colin-c** [comment]
Correct me if I'm wrong, but it looks like you've only added support for this in the MySQL, and _not_ for PostgreSQL.

**Comment by freekmurze** [comment]
And fixed in v3.4.3
