### ISSUE TITLE
Exeptions on bavkup

### ISSUE THREAD

**Issue by errogaht** [spatie/laravel-backup#115]
Laravel 5.2
`
[2016-04-12 06:07:04] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Foundation\Application::backupWasSuccessful()' in /home/admin/web/laravel/public_html/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php:29
Stack trace:
#0 {main}  
[2016-04-12 06:10:38] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Foundation\Application::cleanupWasSuccessFul()' in /home/admin/web/laravel/public_html/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php:45
Stack trace:
#0 {main}  
[2016-04-12 06:11:23] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Foundation\Application::unHealthyBackupWasFound()' in /home/admin/web/laravel/public_html/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php:69
Stack trace:
#0 {main}  
`

**Comment by freekmurze** [comment]
I can't replicate this. 

When are you seeing this error?

Are you using a fresh copy of Laravel and this package? 

Please included all info that could help me solve this issue.

**Comment by errogaht** [comment]
`php artisan backup:clean`

and i see 

`[Symfony\Component\Debug\Exception\FatalErrorException]                             
  Call to undefined method Illuminate\Foundation\Application::cleanupWasSuccessFul()`

this is fresh installation

**Comment by errogaht** [comment]
and my config is

`
<?php

return [

    'backup' => [

        /*
         * The name of this application. You can use this name to monitor
         * the backups.
         */
        'name' => 'all',

        'source' => [

            'files' => [

                /*
                 * The list of directories that should be part of the backup. You can
                 * specify individual files as well.
                 */
                'include' => [
                    '/home/admin/web/laravel/public_html'
                ],

                /*
                 * These directories will be excluded from the backup.
                 * You can specify individual files as well.
                 */
                'exclude' => [
                    '/home/admin/web/laravel/public_html/vendor',
                    '/home/admin/web/site/public_html/.git',
                    '/home/admin/web/site/public_html/vendor',
                    '/home/admin/web/site/public_html/app/cache',
                    '/home/admin/web/site/public_html/thumbs',
                ],
            ],

            /*
             * The names of the connections to the databases that should be part of the backup.
             * Currently only MySQL- and PostgreSQL-databases are supported.
             */
            'databases' => [
                'site',
            ],
        ],

        'destination' => [

            /*
             * The disk names on which the backups will be stored.
             */
            'disks' => [
                'backup',
            ],
        ],
    ],

    'cleanup' => [
        /*
         * The strategy that will be used to cleanup old backups.
         * The youngest backup will never be deleted.
         */
        'strategy' => \Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy::class,

        'defaultStrategy' => [

            /*
             * The amount of days that all daily backups must be kept.
             */
            'keepAllBackupsForDays' => 7,

            /*
             * The amount of days that all daily backups must be kept.
             */
            'keepDailyBackupsForDays' => 16,

            /*
             * The amount of weeks of which one weekly backup must be kept.
             */
            'keepWeeklyBackupsForWeeks' => 8,

            /*
             * The amount of months of which one monthly backup must be kept.
             */
            'keepMonthlyBackupsForMonths' => 4,

            /*
             * The amount of years of which one yearly backup must be kept
             */
            'keepYearlyBackupsForYears' => 2,

            /*
             * After cleaning up the backups remove the oldest backup until
             * this amount of megabytes has been reached.
             */
            'deleteOldestBackupsWhenUsingMoreMegabytesThan' => 10000
        ]
    ],


    /*
     *  In this array you can specify which backups should be monitored.
     *  If a backup does not meet the specified requirements the
     *  UnHealthyBackupWasFound-event will be fired.
     */
    'monitorBackups' => [
        [
            'name' => 'all',
            'disks' => ['backup'],
            'newestBackupsShouldNotBeOlderThanDays' => 1,
            'storageUsedMayNotBeHigherThanMegabytes' => 10000,
        ],

        /*
        [
            'name' => 'name of the second app',
            'disks' => ['local', 's3'],
            'newestBackupsShouldNotBeOlderThanDays' => 1,
            'storageUsedMayNotBeHigherThanMegabytes' => 5000,
        ],
        */
    ],

    'notifications' => [

        /*
         * This class will be used to send all notifications.
         */
        'handler' => Spatie\Backup\Notifications\Notifier::class,

        /*
         * Here you can specify the ways you want to be notified when certain
         * events take place. Possible values are "log", "mail", "slack" and "pushover".
         *
         * Slack requires the installation of the maknz/slack package.
         */
        'events' => [
            'whenBackupWasSuccessful'     => ['log'],
            'whenCleanupWasSuccessful'    => ['log'],
            'whenHealthyBackupWasFound'   => ['log'],
            'whenBackupHasFailed'         => ['log', 'mail'],
            'whenCleanupHasFailed'        => ['log', 'mail'],
            'whenUnhealthyBackupWasFound' => ['log', 'mail'],
        ],

        /*
         * Here you can specify how emails should be sent.
         */
        'mail' => [
            'from' => 'your@email.com',
            'to'   => 'your@email.com',
        ],

        /*
         * Here you can specify how messages should be sent to Slack.
         */
        'slack' => [
            'channel'  => '#backups',
            'username' => 'Backup bot',
            'icon'     => ':robot:',
        ],

        /*
         * Here you can specify how messages should be sent to Pushover.
         */
        'pushover' => [
            'token'  => env('PUSHOVER_APP_TOKEN'),
            'user'   => env('PUSHOVER_USER_KEY'),
            'sounds' => [
                'success' => env('PUSHOVER_SOUND_SUCCESS','pushover'),
                'error'   => env('PUSHOVER_SOUND_ERROR','siren'),
            ],
        ],
    ],
    'notifications' => ''
];

`

**Comment by freekmurze** [comment]
Thanks for the info.

Fixed in v3.4.4

**Comment by errogaht** [comment]
sorry, but after update i have same issue when im run backup:run
`PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::backupHasFailed() in /home/admin/web/laravel/public_html/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php on line 37
                                                                                 
  [Symfony\Component\Debug\Exception\FatalErrorException]                        
  Call to undefined method Illuminate\Foundation\Application::backupHasFailed()`

http://share.q9x.ru/roBV657.png
http://share.q9x.ru/xt7K8z9.png
http://share.q9x.ru/vSRsLRH.png

**Comment by freekmurze** [comment]
I can't seem to replicate this either. Do you see any casing weirdness that might cause your issue?
