### ISSUE TITLE
option for creating the backup table wise

### ISSUE THREAD

**Issue by pavankumarkatakam** [spatie/laravel-backup#116]
I Mean full database want to be backed up but rather than generating the one .sql file, generate the table wise sql file so that it is usefull in some times where only one table is loss.

**Comment by freekmurze** [comment]
Not sure about this. I think not many users are waiting on this feature. You could create the dumb yourself and [use the `BackupZipWasCreated`-event](https://docs.spatie.be/laravel-backup/v3/advanced-usage/adding-extra-files-to-the-zip) to add it to the zip.

**Comment by pavankumarkatakam** [comment]
OK. .
