### ISSUE TITLE
Using --single-transaction for large databases

### ISSUE THREAD

**Issue by trevorgehman** [spatie/laravel-backup#119]
I was wondering whether by default the `mysqldump` command is using `--single-transaction`? I have a fairly large database (~5gb) and it takes two minutes to perform the backup. I'm not sure whether it is locking the tables or not, but from what I've read the `--lock-tables` is enabled by default.

Can you confirm this?

**Comment by freekmurze** [comment]
I believe `--lock-tables` is indeed used by default. If you need some options that arent't available now I'd accept PR's a both the pakackage and [db-dumper](https://github.com/spatie/db-dumper).

**Comment by emohamed** [comment]
Came to this issue from Google and wanted to share some finding for other people experiencing "freezing" of their applications while a backup is being performed.

Here is a good resource on the underlying issue:
https://serversforhackers.com/c/mysqldump-with-modern-mysql

What you should know:

 * if you're using MyISAM for some of your tables you should either migrate to InnoDB, live with the tables locking during the backup, or use different backup approach(like https://www.percona.com/software/mysql-database/percona-xtrabackup)
 * if you have only InnoDB tables in your database, change your `config/database.php` connection to include this: `'dump' => [ 'add_extra_option' => '--single-transaction --skip-lock-tables' ]
`, e.g.:

```
    'connections' => [
        'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
            'dump' => [
                'add_extra_option' => '--single-transaction --skip-lock-tables'
            ]
        ],
// ....
```

**Note:** if you do have MyISAM tables, and add the `--single-transaction` flag, you will end up with inconsistent dump, and you will not see an error during the backup or restore process; however, if you restore and try to work with the application, the table rows that were added / deleted while the backup had been performed will not match between various tables.
