### ISSUE TITLE
syntax error, unexpected 'protected' (T_PROTECTED), expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by notbotman** [spatie/laravel-backup#1201]
Getting this after updating to 7.0.2 via dependabot

For now, I rollbacked to 6.14.2

![image](https://user-images.githubusercontent.com/74244707/104037144-4f5b7600-51fa-11eb-94eb-0b4856dd5944.png)

Here is the CI Log https://gitlab.com/taskord/taskord/-/jobs/951963913

How can I fix this?

**Comment by freekmurze** [comment]
Please upgrade to the latest PHP version.

**Comment by notbotman** [comment]
> Please upgrade to the latest PHP version.

My PHP version is 8.0

**Comment by freekmurze** [comment]
I don't think so, because of that syntax error. Please check it both on the web and cli.

**Comment by notbotman** [comment]
@freekmurze Here is the sentry log

Do I need to republish the config, it works with the previous version 🤔 

![image](https://user-images.githubusercontent.com/74244707/104089673-a6af2400-5296-11eb-9af7-6781417760a2.png)

![image](https://user-images.githubusercontent.com/74244707/104089659-98610800-5296-11eb-9368-45727c7df912.png)

**Comment by Al3xR0** [comment]
Hey,

I have the same problem. How did you fix it?

`syntax error, unexpected 'protected' (T_PROTECTED), expecting variable (T_VARIABLE)`
`…/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php19`
```
class EventHandler
{
    public function __construct(
        **protected Repository $config**
    ) {
    }
....
```

I have:
- spatie/laravel-backup v 7.2.1
- PHP 8.0.0
