### ISSUE TITLE
Backup Events not fire when useing --disable-notifications flag

### ISSUE THREAD

**Issue by AltiumWilliam** [spatie/laravel-backup#1209]
Hi
I'm using **BackupZipWasCreated** Event to encrypt backup files, I found that when I use **_--disable-notifications_** flag, Events not fire but when I clear the flag, all events fire normally.
I register Event in **EventServiceProvider** and every thing is ok, only flag make the event not firing.

Laravel version: 5.8.38
PHP version: 7.4
Laravel spatie-backup version: 6.12.0

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.

**Comment by FelipeVeiga** [comment]
same problem here

**Comment by acabutto** [comment]
> Hi
> I'm using **BackupZipWasCreated** Event to encrypt backup files, I found that when I use **_--disable-notifications_** flag, Events not fire but when I clear the flag, all events fire normally.
> I register Event in **EventServiceProvider** and every thing is ok, only flag make the event not firing.
> 
> Laravel version: 5.8.38
> PHP version: 7.4
> Laravel spatie-backup version: 6.12.0

I may be wrong but after having a quick look at the code I think this is not a bug but a by design behavior instead. The misunderstanding here could be related to naming of the switch **_--disable-notifications_**. It should be named **_--disable-event-firing_** because that is exactly what it does:

```
[...]
$this->sendNotification(new BackupZipWasCreated($pathToZip));
[...]

protected function sendNotification($notification)
    {
        if ($this->sendNotifications) {
            rescue(function () use ($notification) {
                event($notification);
            }, function () {
                consoleOutput()->error('Sending notification failed');
            });
        }
    }
```
Whether to notify the user or not after an event is something that should be handled in your project possibly in `config/backups.php`

```
    'notifications'   => [
        'notifications' => [
            BackupHasFailed::class         => ['mail'],
            UnhealthyBackupWasFound::class => ['mail'],
            CleanupHasFailed::class        => ['mail'],
            BackupWasSuccessful::class     => ['mail'],
            HealthyBackupWasFound::class   => ['mail'],
            CleanupWasSuccessful::class    => ['mail'],
        ],
```
Am I right?

**Comment by freekmurze** [comment]
It seems you are right, and I'll consider improving this name/behaviour in the next major version.

**Comment by AltiumWilliam** [comment]
I think, It must be separated, disable events and disable notifications. User must to able to select whether to send notification (broadcast, email,...) or events. Sometimes I need Events and Sometime I need Notifications.
For example, I plan to backup DB every day, If I enable notification, lots of notification I get because of daily backup, So here I need to disabled notification, but to set password on zip files, I need BackupZipWasCreated  event. here issue shown! If I disable notification, I don't get event, so my daily backups does not have password, If I enable it, password set but I get lots of notification, If I disable BackupWasSuccessful (the place I send Notification to users) to disable notification, for monthly backups that I want to notify admin, this notification disable and admin don't notify!!!
Please Help me to have all feathers! Set Password and ability's to select send notification or not

**Comment by acabutto** [comment]
@AltiumWilliam I strongly agree with you. Having separated events and notifications options would be the best, @freekmurze could you consider this design for the next major release? I would happily contribute to this development.

**Comment by AltiumWilliam** [comment]
> @AltiumWilliam I strongly agree with you. Having separated events and notifications options would be the best, @freekmurze could you consider this design for the next major release? I would happily contribute to this development.

Thank you

**Comment by freekmurze** [comment]
Feel free to send a PR that fixes this, make sure to include tests.
