### ISSUE TITLE
Issue when there is no .env

### ISSUE THREAD

**Issue by xoco70** [spatie/laravel-backup#121]
For all my servers, I use Elastic Beanstalk, and define .env variables in configuration management in server side. 

So, basically, if I copy a .env in my rep, it will work, but if not, it will not see my environment variables defined in server and give me a:

`Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) when trying to connect`

**Comment by sebastiandedeyne** [comment]
I'm not sure if the issue is with the package. The only place `.env` variables are used here are in the configuration file, which can be overridden in your application. Are you sure this isn't caused by Laravel's default usage of `env` in the database configuration?

**Comment by xoco70** [comment]
I'm not sure I understand it. I use the default env() in my database configuration, but it still work when defining Environment variables in Elastic Beanstalk.

About my app, I never override those vars :(

**Comment by sebastiandedeyne** [comment]
Hmm not sure what could be going wrong here, did you manage to resolve it?

**Comment by xoco70** [comment]
nop :( I don't really know what's going on... at the moment you use env() method, it should be ok, I don't really know why is it happening... It s a bad news because your plugin is exactly what I need...

**Comment by xoco70** [comment]
tarting backup...
Dumping database forge...
Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) when trying to connect
.
Backup failed because: No supported encrypter found. The cipher and / or key length are invalid..

**Comment by freekmurze** [comment]
Ah ha!

```php
No supported encrypter found. The cipher and / or key length are invalid..
```

You'll have to generate a valid key and put it in `config/app.php`.  More info in [Laravel's installation instructions](https://laravel.com/docs/master#installing-laravel).

**Comment by xoco70** [comment]
This is not the issue. In my config/app.php, I have:     'key' => env('APP_KEY', 'SomeRandomString'),
And I have APP_KEY defined in my Elastic Beanstalk config, I doubled check it.
Besides, if APP_KEY is not defined, my app wouldn't be running.
So, if APP_KEY is empty, this is because env() is not resolving environment variables when .env is not present

**Comment by freekmurze** [comment]
Sometimes the `SomeRandomString` is causing values. It has not the correct length when using certain ciphers.

Could you try these values in your config file:

key: `vp8WfwdsUqBpiqjs4NR5z12TddbOelGg` <-- just a randomly generated key with the right size
cipher: `AES-256-CBC`

**Comment by xoco70** [comment]
When I put a default key, it doesn't give me the 

` No supported encrypter found. The cipher and / or key length are invalid..`

But I still have : 

`Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) when trying to connect`

What it is telling is env(APP_KEY) is not finding anything, so it is giving me the default.

But as it happens to all vars, it is not due to APP_KEY but to env().

The big question is why env() works well in my app, and is not working when invoking the plugin.

It seems that the plugin NEEDS a .env to work. when I put a .env, it works well...

**Comment by xoco70** [comment]
It appears to be a common issue with Server variables. 
Basically, what I understand is the webserver user and the cli user are differents, so, when cli runs, it doesn't find env variables... 

http://stackoverflow.com/questions/21587320/laravel-enviroment-when-on-command-line-different-to-in-browser

**Comment by freekmurze** [comment]
I highly suspect that your issue is not with this package but it's caused by your specific environment.

**Comment by xoco70** [comment]
Yes, it is true. I tried php artisan migrate, and it didn't work neither! Sorry for bothering!
