### ISSUE TITLE
Should I exclude my .env file?

### ISSUE THREAD

**Issue by jorenvanhee** [spatie/laravel-backup#122]
Would you recommend excluding .env files from the backup? I'm not sure if I'm ok with passwords being stored in the backups. Thanks!

**Comment by freekmurze** [comment]
All I can say is that I do backup the `env`-files. In case of [a catastrophic failure](https://murze.be/2016/02/today-digitalocean-lost-our-entire-server/) the .env file will allow restoring a site faster.
