### ISSUE TITLE
Asking for password (Postgres)

### ISSUE THREAD

**Issue by SuddenlyRust** [spatie/laravel-backup#1220]
I will get prompted to enter my database user password when I run `php artisan backup:run`. Anyone else experienced this problem? 

![image](https://user-images.githubusercontent.com/14092921/105961629-0a9b6000-607f-11eb-8fd4-485af4e54cc1.png)

When I run `php artisan backup:run --only-files` it works fine and I am not asked for any password:

![image](https://user-images.githubusercontent.com/14092921/105962397-0cb1ee80-6080-11eb-8930-d0f4051becd6.png)

PHP: v7.4
Postgres: v12.5
spatie/laravel-backup: 6.14.3
laravel/framework: v8.24.0

My database and application are on different servers (not sure if this is helpful).

I know v6 is no longer supported but maybe other people experienced the same error? Currently I have to run the backup manually.

**Comment by freekmurze** [comment]
Could you reopen this in as a discussion in the Q&A category? Thanks!

**Comment by SuddenlyRust** [comment]
Sure. No problem. See https://github.com/spatie/laravel-backup/discussions/1221

Thank you for this awesome package 🙏
