### ISSUE TITLE
Backup failed: Could not open required defaults file: 

### ISSUE THREAD

**Issue by Draesia** [spatie/laravel-backup#1222]
Hi!

Love this package so much, and have been using it for my production server; I haven't changed anything but today I got the notification that the backup failed. After running the command myself, I get the following error message

`Starting backup...
Dumping database craftopia...
Backup failed because The dump process failed with exitcode 1 : General error : Could not open required defaults file: /tmp/php8DXAUX
Fatal error in defaults handling. Program aborted
.
#0 /var/www/html/SERVERREDACTED/vendor/spatie/db-dumper/src/DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))
#1 /var/www/html/SERVERREDACTED/vendor/spatie/db-dumper/src/Databases/MySql.php(197): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), '/var/www/html/c...')
#2 /var/www/html/SERVERREDACTED/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(253): Spatie\DbDumper\Databases\MySql->dumpToFile('/var/www/html/c...')
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\DbDumper\Databases\MySql), 'mysql')
#4 /var/www/html/SERVERREDACTED/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(630): array_map(Object(Closure), Array, Array)
#5 /var/www/html/SERVERREDACTED/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(256): Illuminate\Support\Collection->map(Object(Closure))
#6 /var/www/html/SERVERREDACTED/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(170): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()
#7 /var/www/html/SERVERREDACTED/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(146): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#8 /var/www/html/SERVERREDACTED/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(56): Spatie\Backup\Tasks\Backup\BackupJob->run()
#9 /var/www/html/SERVERREDACTED/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle()
#10 /var/www/html/SERVERREDACTED/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#11 /var/www/html/SERVERREDACTED/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#12 /var/www/html/SERVERREDACTED/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#13 /var/www/html/SERVERREDACTED/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#14 /var/www/html/SERVERREDACTED/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call(Array)
#15 /var/www/html/SERVERREDACTED/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#16 /var/www/html/SERVERREDACTED/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /var/www/html/SERVERREDACTED/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/SERVERREDACTED/vendor/symfony/console/Application.php(971): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/SERVERREDACTED/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/SERVERREDACTED/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/SERVERREDACTED/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/SERVERREDACTED/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/SERVERREDACTED/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}
Backup failed because: The dump process failed with exitcode 1 : General error : Could not open required defaults file: /tmp/php8DXAUX
Fatal error in defaults handling. Program aborted`

Tracking this down, it is failing to read the file within /tmp.

I'm not sure the reason for why it cannot read it. 

I tried some basic debugging within MySql.php; 

`        $tempFileHandle = tmpfile();
        fwrite($tempFileHandle, $this->getContentsOfCredentialsFile());
        $temporaryCredentialsFile = stream_get_meta_data($tempFileHandle)['uri'];
        dd(file_get_contents($temporaryCredentialsFile));`

The dd works successfully, which implies the file does exist, and it is readable by the current process. (Though I understand that the created process might be different).

My only implication is that perhaps the temp file is being deleted before it is able to be read by mysqldump. I dont know why this may be.

A temporary fix for this has been to create the file manually in a location, and have it read that file instead. i.e.

        $temporaryCredentialsFile = '/var/www/html/SERVERREDACTED/.my.cnf';

I have googled everywhere for this issue, I cannot find any solutions, and it seems to be an issue with the package itself under some strange circumstance; any direction or help with debugging this issue is very much appreciated.

Thank you kindly, and thank you for making this.

**Comment by vicentemachado** [comment]
I also started to experience this issue a couple of days ago.

**Comment by AllCdnBoy** [comment]
ditto.  Started a couple days ago for me as well.

**Comment by AllCdnBoy** [comment]
Composer updated solved the problem.  

laravel-backup didn't need a version update, but the dependency spatie/db-dumper went from 2.19 => 2.21 and the problem stopped.
