### ISSUE TITLE
Socket connection not recognised

### ISSUE THREAD

**Issue by jimping** [spatie/laravel-backup#1223]
When I try to backup the database i receive a connection error:

`Could not connect to 127.0.0.1`

Laravel is running in a docker container and the mariadb server is running on the host system. Connection in general works fine with the socket except the backup.

```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_SOCKET=/run/mysqld/mysqld.sock
DB_USERNAME=root
DB_PASSWORD=root
DB_DATABASE=db
```

Any idea whats wrong?

**Comment by freekmurze** [comment]
Could you please add this as a discussion in the Q&A category?
