### ISSUE TITLE
is it possible to email multiple emails?

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-backup#123]
couldn't find this in the docs or existing issues. Can I pass an array of emails if I want emails to be sent to two emails or more upon certain events completion?

**Comment by freekmurze** [comment]
Currently this is not possible. 

On first thought it would be nice if you could do this in the config:

```
'whenBackupHasFailed'         => ['log', 'mail:freek@spatie.be', 'mail:someone-else@spatie.be'],
```

It could be a while before I find the fime to make this adjustment. If you need this quick. I'd accept a PR that adds a more flexible way of emailing to the package (in a non breaking way).

If you control your emailserver you could also just use a forwarder.
