### ISSUE TITLE
Port "Allow to encrypt backup archives" PR to v7

### ISSUE THREAD

**Issue by patinthehat** [spatie/laravel-backup#1245]
The PR #1239 was submitted for v6 and needs to be ported to v7.

I'm currently working on this issue.

This issue is to help keep track of who's working on the port.

@freekmurze @Gummibeer

**Comment by Gummibeer** [comment]
I've added some comments to my PR so you can better see why/what was changed. As there were some changes related to a general cleaning and not directly to that PR.

**Comment by patinthehat** [comment]
That's really helpful, thank you!
