### ISSUE TITLE
[Backup failed] mysqldump: Empty value for 'port' specified

### ISSUE THREAD

**Issue by jagroop** [spatie/laravel-backup#125]
> Backup failed because The dump process failed with exitcode 5 : Unknown error : mysqldump: [ERROR] mysqldump: Empty value for 'port' specified

why i am getting this error ?? .. any solution ??

Thanks !

**Comment by freekmurze** [comment]
Did you specify a port in your database config?

**Comment by jagroop** [comment]
@freekmurze 
hmm that solved the problem thanks ..

but i am getting another error

> Backup failed because The process "mysqldump --defaults-extra-file="/tmp/phpwMnGID" --skip-comments --extended-insert laravel > "/var/www/html/dev/blog/storage/laravel-backups/temp//laravel.sql"" exceeded the timeout of 60 seconds..

**Comment by freekmurze** [comment]
The docs mention [how to increase the timeout]. See the little example below the page.
