### ISSUE TITLE
Destination path points to filesystem config

### ISSUE THREAD

**Issue by frozonfreak** [spatie/laravel-backup#127]
destination path for backup takes the path set in filessystem default and not laravel-backup destination

I have local path set in filesystem and s3 set in laravel-backup . All backups are stored in local and not s3. Changing filessystem path to s3 saves all backup to s3. 

Any suggestions

**Comment by freekmurze** [comment]
Are you using v3 of this package? In that version you can only specify the disks. The path is indeed taken from the `filesystem.php` config.
