### ISSUE TITLE
Undefined constant "Spatie\Backup\Commands\SIGINT"

### ISSUE THREAD

**Issue by TylerVigario** [spatie/laravel-backup#1288]
Since 7.3.4 I get this error in the console from composer install/update and any artisan commands.

```
  Undefined constant "Spatie\Backup\Commands\SIGINT"

  at C:\inetpub\wwwroot\laravel\vendor\laravel\framework\src\Illuminate\Container\Container.php:877
    873▕         }
    874▕
    875▕         array_pop($this->buildStack);
    876▕
  ➜ 877▕         return $reflector->newInstanceArgs($instances);
    878▕     }
    879▕
    880▕     /**
    881▕      * Resolve all of the dependencies from the ReflectionParameters.

  1   C:\inetpub\wwwroot\laravel\vendor\laravel\framework\src\Illuminate\Container\Container.php:877
      ReflectionClass::newInstanceArgs()

  2   C:\inetpub\wwwroot\laravel\vendor\laravel\framework\src\Illuminate\Container\Container.php:714
      Illuminate\Container\Container::build()
```
I reverted to 7.3.3, and it worked, so I think it may be an issue or conflict.

IIS
PHP 8.0.3
laravel/framework 8.36.2
spatie/laravel-backup 7.4

**Edit:** This may be because of my Windows (development) environment. PCNTL does not work on Windows and is a requirement from the new upstream [`spatie/laravel-signal-aware-command`](https://github.com/spatie/laravel-signal-aware-command).

**Comment by krismanning** [comment]
I have the same issue after upgrading. I'm also running a windows dev environment. I see that Laravel Backup doesnt support windows servers but I' hopeful theres a fix that allows me to continue using windows to develop even if it can't ultimately take a backup.

**Comment by HDVinnie** [comment]
Same here

**Comment by eliasjtg** [comment]
![image](https://user-images.githubusercontent.com/22435698/114948479-b3529380-9e14-11eb-93f5-1c5e6ccd7eaf.png)

**Comment by freekmurze** [comment]
This particular error is caused by SIGINT not being available on Windows. I'd accept a PR that adds a check for windows to avoid that particular piece of code. 

If the fix is not too ugly, I'll consider merging it in 👍

**Comment by SuddenlyRust** [comment]
I have encountered the same problem on my forge machine (linux). It happens when I use the `Artisan`-Facade to call any command.

Reproduction:

1. Add a random route to your `web.php`-file:

```php
Route::get('/reproduction', function () {
    Artisan::call(MyCommand::class);

    return '👋 Do you throw Undefined constant "Spatie\Backup\Commands\SIGINT"?';
});
```

2. Visit `/reproduction` with your browser.

3. Following exception is thrown:
`Undefined constant "Spatie\Backup\Commands\SIGINT"`

---

OS: Ubuntu 20.04.2 LTS
PHP: v8.0.3
Webserver: nginx/1.18.0
Laravel: v8.37.0
spatie/laravel-backup: v7.5.1

**Comment by fibis** [comment]
Having also the same problem in our CI, running composer in the `composer:2` docker container.

**Comment by fibis** [comment]
For those who got the same error, since linux php alpine image doesn't have the `pcntl` package installed: Run `docker-php-ext-install pcntl` to install this package. @freekmurze it would be cool if there was a check for that.

**Comment by freekmurze** [comment]
Feel free to PR improvements!

**Comment by pedami** [comment]
Hola, yo tengo el mismo problema, la extensión está instalada correctamente y el entorno está en producción con la última versión de Laravel Nova:

[2022-08-13 04:12:13] local.ERROR: Undefined constant "Spatie\Backup\Tasks\Backup\SIGINT" {"userId":1,"exception":"[object] (Error(code: 0): Undefined constant \"Spatie\\Backup\\Tasks\\Backup\\SIGINT\" at /home/*************************/public_html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php:148)

Gracias.

**Comment by elmarzouguidev** [comment]
I fixed this issue by disabling Signals

 $backupJob = BackupJobFactory::createFromArray(config('backup'));

 $backupJob->disableSignals();
$backupJob->run();
