### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by timleland** [spatie/laravel-backup#130]
I keep having memory errors and have to increase the memory for the backup job. Currently I'm having to override it to  to 1824M.

Currently mysql dump is 22mb and the project zipped is 9mb.

**Errors:**
- PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 8192 bytes) in /bootstrap/cache/compiled.php on line 16692
- PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32768 bytes) in /vendor/symfony/debug/Exception/FatalErrorException.php on line 1

What could be causing this?

**Comment by freekmurze** [comment]
Other uses have reported memory issues too. Unfortunately I don't know the cause yet. Which instruction do you see at `/bootstrap/cache/compiled.php` on line 16692?

**Comment by timleland** [comment]
![image](https://cloud.githubusercontent.com/assets/1711910/15219069/64394768-1830-11e6-991f-76d1bef0b9bc.png)

**Comment by timleland** [comment]
I remove all folders from the backup and the sql dump worked fine. Must be something with files/folders? My project is small

**Comment by freekmurze** [comment]
We'll continue this issue in #131
