### ISSUE TITLE
Artisan::call() throws a SIGINT undefined error

### ISSUE THREAD

**Issue by jacob-hyde** [spatie/laravel-backup#1309]
Using the Artisan facade to make a call to a command with this package installed throws an error: Undefined constant \"Spatie\\Backup\\Commands\\SIGINT\"

Is there any known workarounds for this?

Related issue: https://github.com/spatie/laravel-backup/issues/1288

@SuddenlyRust comment:

I have encountered the same problem on my forge machine (linux). It happens when I use the `Artisan`-Facade to call any command.

Reproduction:

1. Add a route to your `web.php`-file:

```php
use App\Console\Commands\MyCommand;
use Illuminate\Support\Facades\Artisan;

Route::get('/reproduction', function () {
    Artisan::call(MyCommand::class);

    return '👀';
});
```

2. Visit `/reproduction` with your browser.

3. Following exception is thrown:
`Undefined constant "Spatie\Backup\Commands\SIGINT"`

---

OS: Ubuntu 20.04.2 LTS
PHP: v8.0.3
Webserver: nginx/1.18.0
Laravel: v8.37.0
spatie/laravel-backup: v7.5.1

_Originally posted by @SuddenlyRust in https://github.com/spatie/laravel-backup/issues/1288#issuecomment-821182809_

**Comment by medvinator** [comment]
Same error on Ubuntu

**Comment by JuanDMeGon** [comment]
Can confirm. It happens when calling any command using the Artisan facade (for some reason).
