### ISSUE TITLE
--disable-notifications also disable encryption

### ISSUE THREAD

**Issue by fab2s** [spatie/laravel-backup#1312]
Hello, 

When backups are run with `--disable-notifications` options, the resulting zip file is never encrypted.

It looks like this is coming from the fact encryption occurs as an event wrapped in the send notification method in `BackupJob.php`:
```php
    protected function sendNotification($notification): void
    {
        if ($this->sendNotifications) {
            rescue(
                fn () => event($notification),
                fn () => consoleOutput()->error('Sending notification failed')
            );
        }
    }
````

Thus never throwing the `BackupZipWasCreated `event triggering encryption:
```php
    $this->sendNotification(new BackupZipWasCreated($pathToZip));
````

Hope this helps, and keep up with the good work 👍

**Comment by freekmurze** [comment]
Feel free to send a PR to fix this 👍

**Comment by erikn69** [comment]
@freekmurze must be closed
https://github.com/spatie/laravel-backup/blob/11eb9f82bc0bd25ec69f5c169dde07290d913ce8/tests/Commands/BackupCommandTest.php#L380-L395
https://github.com/spatie/laravel-backup/blob/11eb9f82bc0bd25ec69f5c169dde07290d913ce8/src/Tasks/Backup/BackupJob.php#L230-L234
