### ISSUE TITLE
404 Error when use with google drive fly system

### ISSUE THREAD

**Issue by MazeWorksSuriya** [spatie/laravel-backup#1313]
But Issue Solved By Adding underscore(_) charecter on constructor function  on src/BackupDestination/BackupDestination.php File.

```
    public function __construct(Filesystem $disk = null, string $backupName, string $diskName)
    {
        $this->disk = $disk;

        $this->diskName = $diskName;

        $this->backupName = preg_replace('/[^a-zA-Z0-9.]/', '-', $backupName);
    }

```
To 
```
    public function __construct(Filesystem $disk = null, string $backupName, string $diskName)
    {
        $this->disk = $disk;

        $this->diskName = $diskName;

        $this->backupName = preg_replace('/[^a-zA-Z0-9._]/', '-', $backupName);
    }

```

**Comment by MazeWorksSuriya** [comment]
> But Issue Solved By Adding underscore(_) charecter on constructor function on src/BackupDestination/BackupDestination.php File.
> 
> ```
>     public function __construct(Filesystem $disk = null, string $backupName, string $diskName)
>     {
>         $this->disk = $disk;
> 
>         $this->diskName = $diskName;
> 
>         $this->backupName = preg_replace('/[^a-zA-Z0-9.]/', '-', $backupName);
>     }
> ```
> 
> To
> 
> ```
>     public function __construct(Filesystem $disk = null, string $backupName, string $diskName)
>     {
>         $this->disk = $disk;
> 
>         $this->diskName = $diskName;
> 
>         $this->backupName = preg_replace('/[^a-zA-Z0-9._]/', '-', $backupName);
>     }
> ```

using nao-pon/flysystem-google-drive package for google drive backup

**Comment by freekmurze** [comment]
Feel free to submit a PR that solves the issue.
