### ISSUE TITLE
Backup fails on Vapor - mysqldump not found

### ISSUE THREAD

**Issue by iAmKevinMcKee** [spatie/laravel-backup#1321]
I'm getting the following error on an application deployed to Vapor with an RDS database. 

`Backup failed because The dump process failed with exitcode 127 : Command not found : sh: mysqldump: not found`

I see in the docs that I may need to find the path to the mysqldump binary. Does anyone know what that path is on Vapor?

https://spatie.be/docs/laravel-backup/v7/installation-and-setup#dumping-the-database

**Comment by freekmurze** [comment]
This is probably a question that should be asked to the Vapor support 👍

**Comment by michaelrimbach** [comment]
(For the record)

The Laravel Vapor support replied this:
"Our native runtime doesn't have mysqldump installed. You will need to run the Docker runtime and install yourself if this is a requirement. It's also worth noting the maximum execution time on Lambda is 15 mins so if your backup is large, you could run into issues."
