### ISSUE TITLE
PackageServiceProvider error during installation

### ISSUE THREAD

**Issue by ElaheSoleimani** [spatie/laravel-backup#1336]
My php version is PHP 7.3.24 and Laravel version is 8.12.
But it gives this error when installing the package.
```
In PackageServiceProvider.php line 14:
syntax error, unexpected 'Package' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) 
```

**Comment by freekmurze** [comment]
The tests prove the package doesn’t have a syntax error. You’re probably not using the PHP version you think you are using.
