### ISSUE TITLE
Symlinks not supported

### ISSUE THREAD

**Issue by goatatwork** [spatie/laravel-backup#134]
Hello,

I have need for a symlink in a few projects. It links in a file from outside my project, into storage/app/<filename>.

I noticed that I get this error if that is present:

```
Unreachable backup destinations
-------------------------------
Could not reach backups for  on disk local because:
Links are not supported, encountered link at /home/vagrant/Code/access2/storage/app//<filename>
```

I am not trying to back this file up, only to skip it. Unless I'm using it incorrectly, the `exclude` array in `laravel-backup.php` does not get the job done.

I see that that's coming from Flysystem's Local class.  I also see that if SKIP_LINK is used in the constructor (third argument in constructor) in Local.php instead of DISALLOW_LINKS, things work well. I'm not sure if that's creating some problem for future-me though.

Question: I am trying to locate which method in laravel-backup to alter (overwrite at runtime?) to use in order to give the Local class that $linkHandling parameter.

Thoughts?  Reasons not to do this?

**Comment by freekmurze** [comment]
Under the hood this package just used the Cloud Filesystem that is provided by Laravel. Underneath that Flysystem is used. Laravel doesn't seem to have and option to pass options to the Local driver itself.

You could try excluding the symlinks via the `laravel-backup` config file.

**Comment by freekmurze** [comment]
Turns out there is a way to get to the parameters of a certain disk. You could try to create your own disk by [using a custom Filesystem](https://laravel.com/docs/5.1/filesystem#custom-filesystems).

**Comment by goatatwork** [comment]
Oh sweet. Thanks. I wasn't grasping how the pieces fit together. I'll give that a shot. I did verify changing $linkHandling in Local.php (vendor/league/flysystem/src/Adapter/Local.php) to SKIP_LINKS works. I just know better than to make changes under `vendor`.  Also, unless I did it incorrectly, it seems that excluding via the `laravel-backup` config file didn't work. In fact, after explicitly excluding my link, I realized it was by default already excluding storage_path.

Thanks for the suggestions. I'll try using a custom Filesystem.

~cheers

**Comment by gonzzza007** [comment]
Not sure if my issue is relevant, but for some reason my backups started to fail.
CentOS 6, Ext4 filesystem:

Starting backup...
Backup failed because: Undefined index: followLinks.

Couldn't get any more details on this issue.

**Comment by freekmurze** [comment]
This bug should be fixed in the latest version. Could you check the version
numer you're currentlu running?

On Saturday, 14 May 2016, gonzzza007 <notifications@github.com> wrote:

> Not sure if my issue is relevant, but for some reason my backups started
> to fail.
> CentOS 6, Ext4 filesystem:
>
> Starting backup...
> Backup failed because: Undefined index: followLinks.
>
> Couldn't get any more details on this issue.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/spatie/laravel-backup/issues/134#issuecomment-219210152>
>


-- 
Freek Van der Herten
https://spatie.be
+32 495 84 27 91

**Comment by gonzzza007** [comment]
Yes, updating from 3.7.0 to 3.7.1 solved my problem. I guess there was no update when i did my last check 3 days ago. Thanks a lot for a geat product!
