### ISSUE TITLE
backup command not working

### ISSUE THREAD

**Issue by Ani-Soft** [spatie/laravel-backup#1344]
Hi 

I am trying to run command "php artisan backup:run"
It is not working neither giving any error ( See screenshot).

![Screenshot 2021-07-05 at 13-28-42 WHM  ip-172-31-12-57  Terminal - 96 0 11](https://user-images.githubusercontent.com/69421501/124437713-f4fc3600-dd94-11eb-9bd9-aafaedf16b2e.png)

I am on EC2 instance,

When i update dump_binary_path = "" (empty string) giving me below error.
![Screenshot 2021-07-05 at 13-40-03 WHM  ip-172-31-12-57  Terminal - 96 0 11](https://user-images.githubusercontent.com/69421501/124439155-b23b5d80-dd96-11eb-9283-21a563540918.png)

but when updating dump_binary_path = "/usr/bin/" or  "/" then  no error just print "Starting Backup..." and exit. see above screenshot.

I have also checked if mysqldump available in every directory and found yes mysqldump option is globally available.

Note: On my localhost it is  working fine.

Please let me if there is a way, i can enable log to record any error for backup command.

**Comment by sabin5t5** [comment]
`'mysql' => [
            'driver' => 'mysql',
           .......
           
            'dump' => [
                'dump_binary_path' => '/usr/local/mysql/bin', // only the path, so without `mysqldump` or `pg_dump`
                'use_single_transaction',
                'timeout' => 60 * 5, // 5 minute timeout
                'exclude_table' => [],
                'add_extra_option' => '--optionname=optionvalue', // for example '--column_statistics=0'
             ]
        ],`
Just Make add dump on config/database.php it works for me. :)
