### ISSUE TITLE
Maximum execution time (and --timeout flag) is overridden to 300 seconds

### ISSUE THREAD

**Issue by JackWH** [spatie/laravel-backup#1349]
I'm re-opening the earlier issue #1297, which seems to have been closed mistakenly.

The bug is still there in the current release — the `--timeout` flag is either not being applied, or is being reset back to 300 seconds somewhere in the package.

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.

**Comment by matical** [comment]
The `--timeout` flag only applies to the artisan command and not the underlying symfony/process that runs the actual dumps. That's passed on by the 'dump' [config](https://github.com/spatie/laravel-backup/blob/555718d1cfeab7ef10f83a97595ec57310101cfb/docs/installation-and-setup.md) -> db-dumper -> symfony/process.

Maybe `backup:run` or the docs should clarify this? It's worth noting that PHP's CLI (and subsequently artisan) already defaults to a timeout of 0; and ProcessTimedOutException from 'dump.timeout' would halt the execution of backup:run regardless.

**Comment by JackWH** [comment]
@matical Oh, thank you so much! I totally missed that — fixing the `dump` parameter in `database.php` has solved it for me. 

Thanks for pointing that out!
