### ISSUE TITLE
Failed to backup because: Undefined index: followLinks

### ISSUE THREAD

**Issue by Frozire** [spatie/laravel-backup#135]
Running into a problem with the following error:

`Undefined index: followLinks`

Appears to be on `line 36` in `BackupJobFactory.php` 

`->shouldFollowLinks($sourceFiles['followLinks']);`

in following

```
protected static function getFileSelection(array $sourceFiles)
{
    return (new FileSelection($sourceFiles['include']))
        ->excludeFilesFrom($sourceFiles['exclude'])
        ->shouldFollowLinks($sourceFiles['followLinks']);
}
```

As of right now, the cause is unknown. 

I will debug a bit later to try and provide clear instructions on how to replicate.

Running: 
Laravel 5.2.31
Laravel-backup: 3.7.0

**Comment by freekmurze** [comment]
This has been fixed in [v3.7.1](https://github.com/spatie/laravel-backup/blob/master/CHANGELOG.md#371---2016-05-13). Running `composer update` should fix the problem. If not, reopen this issue.
