### ISSUE TITLE
File exclusion logic excludes files with same prefix

### ISSUE THREAD

**Issue by tpetry** [spatie/laravel-backup#1357]
If you have a basic configuration like this which should backup everything but excludes the `.env` file (in reality more needs to be excluded) the `.env` file is correctly excluded but the `.env.example` too. So everything with the same prefix is excluded:

```php
'files' => [
    /*
     * The list of directories and files that will be included in the backup.
     */
    'include' => [
        base_path(),
    ],

    /*
     * These directories and files will be excluded from the backup.
     *
     * Directories used by the backup process will automatically be excluded.
     */
     'exclude' => [
        base_path('.env'), // .env.example
        base_path('.git'), // .git folder is excluded but .gitignore and .gitattributes too
    ],
```

**Comment by erikn69** [comment]
Fixed, and added test where `'.dot'` does not exclude`' .dotfile'`
https://github.com/spatie/laravel-backup/blob/11eb9f82bc0bd25ec69f5c169dde07290d913ce8/tests/Commands/BackupCommandTest.php#L95-L102

**Comment by freekmurze** [comment]
Thank for the fix @erikn69
