### ISSUE TITLE
Notifications fails if you have a queued event handler for NotificationSent event

### ISSUE THREAD

**Issue by mixdf** [spatie/laravel-backup#1360]
I have a queued event handler listening to the `\Illuminate\Notifications\Events\NotificationSent` event. This causes notifications to fail with the error message `Serialization of 'Generator' is not allowed`.

Steps to reproduce:
1. Create an event handler and register it in the service provider.
`final class NotificationSentHandler implements ShouldQueue {}`
`Event::listen(NotificationSent::class, NotificationSentHandler::class)`
2. Setup any type of notification in the backups (mine is slack notification)
3. Create a backup (mine was failing to create the backup, but the notification failed with an additional exception).

Update: It only happens when the backup fails to be created (`\Spatie\Backup\Events\BackupHasFailed`)

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this!

**Comment by erikn69** [comment]
Maybe i can make a fix, but i don't have a queued event handler listening, could you create a minimal Laravel app that demonstrates the issue? Or maybe create a failing tests to look at?

**Comment by mixdf** [comment]
@erikn69 I wasn't able to reproduce the initial bug, but I came across a new one. They might be related.
Here's a link to the test repo:
https://github.com/mixdf/test-laravel-backup-notification-failure

I'll try to reproduce the other issue as well.

**Comment by erikn69** [comment]
@mixdf 
```php
// backup.php
slack' => [
    'webhook_url' => env('SLACK_WEBHOOK_URL')
```
You don't  have `SLACK_WEBHOOK_URL` on your `.env`, also set a default **`env('SLACK_WEBHOOK_URL','')`**

**Comment by erikn69** [comment]
> Update: It only happens when the backup fails to be created (\Spatie\Backup\Events\BackupHasFailed)

```php
/** @test */
public function failing_test_BackupHasFailed(): void
{
    try {
        throw new \Exception('Test error!');
    } catch(\Exception $e) {
        $event = new (\Spatie\Backup\Events\BackupHasFailed($e);
        event($event);
    }
}
```
```
Illuminate\Notifications\Events\NotificationSent^ {#692
  +notifiable: Spatie\Backup\Notifications\Notifiable^ {#691}
  +notification: Spatie\Backup\Notifications\Notifications\BackupHasFailedNotification^ {#681
    +event: Spatie\Backup\Events\BackupHasFailed^ {#690
      +exception: Exception
```
I didn't find the bug

**Comment by freekmurze** [comment]
Closing as the bug is not reproducible.
