### ISSUE TITLE
Exit Code: 127(Command not found)

### ISSUE THREAD

**Issue by mohhamedion** [spatie/laravel-backup#1364]
Hello, am having this issue, 
all i do is 
```
(new Pdf)->setPdf($path_to_pdf)->text();
```

The command "'/usr/bin/pdftotext' '/var/www/html/wp-content/uploads/pdf_articles/2-4 Россети_Минэнерго.pdf' '-'" failed.

Exit Code: 127(Command not found)

Working directory: /var/www/html/wp-admin

Output:
================

Error Output:
================
sh: 1: exec: /usr/bin/pdftotext: not found

**Comment by erikn69** [comment]
???

**Comment by erikn69** [comment]
setPdf??? This is `laravel-backup` package, nothing to do here

**Comment by PaolaRuby** [comment]
@freekmurze [pdf-to-text](https://github.com/spatie/pdf-to-text) question, this question does not belong here
