### ISSUE TITLE
Error thrown when specifying customization options for databases

### ISSUE THREAD

**Issue by Patabugen** [spatie/laravel-backup#1368]
Using version 7.6.4.

Turning the 'databases' value into an array to be able to specify customisation options (as documented in the comments immediately above them `backup:run` throws an error because something down the line is expecting a string, not an array.

Documentation:

https://github.com/spatie/laravel-backup/blob/main/config/backup.php#L62

`config/backup.php`:
```php
<?php
return [
    'backup' => [
        'source' => [
            'databases' => [
                'mysql' => [
                    'dump' => [
                        'excludeTables' => [
                            'telescope_entries',
                            'telescope_entries_tags',
                            'telescope_monitoring',
                        ]
                    ]
                ],
            ],
        ],
];
```

I've done a little bit of digging and I have a suggestion about the solution:

https://github.com/spatie/laravel-backup/blob/main/src/Tasks/Backup/BackupJobFactory.php#L29

I believe we need to be more inteligent than simply `collect($dbConnectionNames)`. In my particular instance `collect(array_keys($dbConnectionNames))` fixes the problem, but I imagine a more universal solution would need to pick values if they're only strings, and the keys of items which are arrays.

I can add that and send a PR if that sounds correct? (I'd be happy to hear of any Laravel-specific helpers which might be handy)

**Comment by erikn69** [comment]
@Patabugen @jenriquez-bit
It is because you are editing `config/backup.php`, wrong, you must edit **`config/database.php`** https://github.com/spatie/laravel-backup/blob/1aa4394e8dd619a2a2cbd480240148ace5f643f4/config/backup.php#L57

**Comment by Patabugen** [comment]
Ah! Thanks @erikn69 !
