### ISSUE TITLE
Failed to backup because: filesize(): stat failed

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-backup#137]
Error:

    Failed to backup  because: filesize(): stat failed for /Users/<username>/Workspace/<project>/storage/laravel-backups/temp//2016-05-24-121909.zip

What am I doing wrong? Or is this a bug?

**Comment by freekmurze** [comment]
That path sure looks kinda strange with `//` in it.

**Comment by georgeboot** [comment]
I also get this error every now and then (say 2 times a week):

```
Failed to backup  because: filesize(): stat failed for /home/forge/<domain>/releases/20160527114409/storage/laravel-backups/temp//2016-05-29-010008.zip
```

Also, now and then (also about 2 times weekly) we get:
```
Failed to backup  because: ZipArchive::close(): No error
```

We're running our backups every 30 minutes.

**Comment by freekmurze** [comment]
Do you have enough free space on your disk?

**Comment by georgeboot** [comment]
Yes, plenty available:

```
forge@server1 ~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.7G   12K  7.7G   1% /dev
tmpfs           1.6G  600K  1.6G   1% /run
/dev/md2        916G   95G  776G  11% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            7.7G  8.0K  7.7G   1% /run/shm
none            100M     0  100M   0% /run/user
/dev/md1        488M  159M  304M  35% /boot
```

**Comment by freekmurze** [comment]
Are you running the latest version of the package? There were some memory improvements made a few days ago.

**Comment by freekmurze** [comment]
The newly tagged version `3.8.1` should resolve most memory use and speed issues. Upgrade to that version and let me know if your problems persist or not.
