### ISSUE TITLE
Backup failed because ZipArchive::close(): Read error: No such file or directory.

### ISSUE THREAD

**Issue by eickhardt** [spatie/laravel-backup#138]
Been using your great package for a few weeks now. Started getting this error:

```
Starting backup...
Dumping database sumopix...
Determining files to backup...
Zipping 51845 files...
Backup failed because ZipArchive::close(): Read error: No such file or directory.
Backup completed!
```

As you can see there are a lot of files. This is because laravel is creating session files all the time. Could this be the problem? And if so, should I use a different session driver? Redis? Database?

These backups are going to grow a lot, since we are doing a lot of image processing that we also need to keep backups of for several months.

Any advice is greatly appreciated. Thank you for this awesome package!

**Comment by sebastiandedeyne** [comment]
I assume you don't really need to backup the session data. In that case, I'd start out by excluding it, and see how it goes afterwards.

https://github.com/spatie/laravel-backup/blob/master/config/laravel-backup.php#L29

**Comment by eickhardt** [comment]
That did the trick! Thanks a bunch for the help on a saturday evening. Should have thought of that myself though.

**Comment by Younesi** [comment]
Hi I am excluding vendor and all other unnecessary files and folders like so:

`      'exclude' => [
                    base_path('vendor'),
                    base_path('node_modules'),
                    base_path('public'),
                    base_path('etc'),
                    base_path('logs'),
                    base_path('ssl'),
                    base_path('tmp'),
                ],`

**But Laravel-backup is trying to make a backup of those.** 
Still getting the same error.

**Comment by AliRazaLilani** [comment]
Resolved : I was uploading it to google drive and there was not enough space on my drive.

**Comment by Sairahcaz** [comment]
I know it's an old issue. But I had the some issue for a client who still uses file based sessions. Wouldn't it be a good idea to add `storage/framework/sessions` by default to the `exclude` array?

![image](https://github.com/user-attachments/assets/27d4fcc4-8732-4e5e-bb7b-f5fdce65acd0)

It took a while until I found this solution. And it's a tricky one, since the error you get when the backup fails dose not really help :D
