### ISSUE TITLE
Folder structure changed

### ISSUE THREAD

**Issue by Livijn** [spatie/laravel-backup#1389]
I recently noticed that the folder structure for my backups has changed. I only backup my database, and the ZIP-file used to look like this: `db-dumps/mysql-forge.sql`. Now however, it looks like this: `home/forge/website.com/storage/temp/temp/db-dumps/mysql-forge.sql`.

I have a command that downloads the production database locally so I can test thing with real world data. But this change has broken that command. I've tried to find information about this change but haven't found any. Is it supposed to be like that or can I change it back to how it was before?

**Comment by Livijn** [comment]
So I noticed that if I set `'relative_path' => storage_path('app/backup-temp/temp')` I get the result I want. Still feels strange though. I'll leave this issue open so I can hear your take on it.

**Comment by PaolaRuby** [comment]
Fixed on #1386

**Comment by Livijn** [comment]
I'll close this when PR is merged

**Comment by PaolaRuby** [comment]
Must be closed now
