### ISSUE TITLE
Run "php artisan backup:run --only-db" commands form route or controller

### ISSUE THREAD

**Issue by dukenst2006** [spatie/laravel-backup#140]
Hi all,
Thanks @freekmurze for this great work, 
In a small project, i want to take backups with a button in the dashboard and show notifications (backup was Successful or has fail) to the user , any idea? please help me
and I think that it is usefull when you don't have access to the console in share hosting environments.
Thanks !!

**Comment by freekmurze** [comment]
You can do all that in a Laravel app. The explanation of how it should be coded in detail is bit out of scope for this issue tracker, but here are a few things you can research:
- you can use `Artisan::call` to excute Artisan tasks for code: https://laravel.com/docs/5.1/artisan#calling-commands-via-code
- there are events being fired which you can leverage to display a notification: `https://docs.spatie.be/laravel-backup/v3/taking-backups/events`.

**Comment by polodev** [comment]
@freekmurze `Artisan::call('backup:run')` only work in localhost. From localhost it sends backup to s3. However same code not working in the server. (aws lightsail server).  Not getting any error, just executed on server without error and no file found in s3 

~~~php
 if ($request->backup_type == 'only_db') {
      // Artisan::call('backup:run --only-db');
      Artisan::call('backup:run', ['--only-db'=>true]);
      session()->flash('message.content', 'Successfully Database Backed Up');
    } else if ( $request->backup_type == 'full_site' ) {
      Artisan::call('backup:run');
      session()->flash('message.content', 'Successfully Full Site Backed Up');
    }
~~~~
