### ISSUE TITLE
Exclude is being ignored from backup config

### ISSUE THREAD

**Issue by AmrSubZero** [spatie/laravel-backup#1400]
I'm setting exclude list to not be included with the backup using :

```
'source' => [

    'files' => [

        'include' => [
            base_path(),
        ],

        'exclude' => [
            base_path('vendor'),
            base_path('node_modules'),
            storage_path(),
            base_path('.git'),
            base_path('.idea')
        ],
```

with `mysqldump` in `database.php` : 

```
'dump' => [
    'dump_binary_path' => 'c:/xampp/mysql/bin/',
    'use_single_transaction',
    'timeout' => 60 * 5, // 5 minute timeout
    // 'exclude_tables' => ['table1', 'table2'],
    // 'add_extra_option' => '--optionname=optionvalue',
],
```

The generated backup file is literally the entire base directory of the project with all it's directories/files.

when i browse the zipped backup file, it's structured like : 

```
/> C: => xampp => htdocs => "The entire project folders/files"
/> db-dumps => mysql-mydbname.sql
```

It seemed the `exclude` part is completly being ignored. i've searched the entire web for a solution but i feel this is a bug.

`Laravel 8.60.0` with :

```
"backpack/backupmanager": "^3.0",
"backpack/crud": "4.1.*",
"spatie/laravel-backup": "^6.16"
```

**_Notice_** : i'm using [Laravel-Backpack/BackpackManager](https://github.com/Laravel-Backpack/BackupManager) for `Laravel Backpack`

**Comment by freekmurze** [comment]
Can you write a test that proves that the current behaviour is wrong?

**Comment by erikn69** [comment]
That's is because you have windows OS, try my last PR, it will fix that
