### ISSUE TITLE
 exceeded the timeout of 60 seconds.

### ISSUE THREAD

**Issue by RonnieVisser** [spatie/laravel-backup#141]
Hi,

When backing up I receive following error message: Failed to backup because: The process "mysqldump --defaults-extra-file="/tmp/phpP9PAt1" --skip-comments --extended-insert soccersource > "/path_to_/storage/laravel-backups/temp//soccersource.sql"" exceeded the timeout of 60 seconds. 

What is a proper place to set this to 0, or is there any other way this can be achieved?

Thanks

**Comment by freekmurze** [comment]
You can set the timeout of the dump command to a higher value. More info at the bottom of this package in the documentation: https://docs.spatie.be/laravel-backup/v3/installation-and-setup

**Comment by eugenevdm** [comment]
I know  it's uncool to reply to closed posts, but if you're using Redis queues on Forge, do you also adjust the queue timeout? The default queue timeout on Redis on Forge appears to be 60 seconds....
