### ISSUE TITLE
Protected attribute in lower versions of PHP 7.8 does not work

### ISSUE THREAD

**Issue by fabegalo** [spatie/laravel-backup#1412]
Protected attribute in lower versions of PHP 7.8 does not work because this option was only implemented from PHP 8.0, making the project PHP 8.0 or above, taking the compatibility with other versions a very negative point for hosting plans that only provide PHP 7.4.

The problem happens on line 19 of the file "Spatie\Backup\Notifications\EventHandler"

    public function __construct(
        protected repository $config
    ) {
    }

**Comment by PaolaRuby** [comment]
there is only php 7.4, not 7.8, and you can use version 6.x of the package for support php 7.4
**V7**
https://github.com/spatie/laravel-backup/blob/1aa4394e8dd619a2a2cbd480240148ace5f643f4/composer.json#L20-L21
**V6**
https://github.com/spatie/laravel-backup/blob/e7324472d4384ef1dc089400723ff01745497625/composer.json#L20-L21
