### ISSUE TITLE
Failed to backup Authentication Required

### ISSUE THREAD

**Issue by mskenderian** [spatie/laravel-backup#142]
vagrant@homestead:~/Projects/sos$ artisan backup:run
Starting backup...
Dumping database sos...
Dumping database sos_general...
Determining files to backup...
Zipping 103 files...
Backup failed because ZipArchive::close(): Renaming temporary file failed: Operation not permitted.
Laravel-backup notifier failed because Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required
"

**Comment by freekmurze** [comment]
It seems like this has something to do with the permissions on your server.

**Comment by mskenderian** [comment]
Sometimes it runs fine. Sometimes it does not. And I have not changed
permissions. When I get this error. I also get a message that backup was
successful.
