### ISSUE TITLE
Option to change timezone

### ISSUE THREAD

**Issue by jlmmns** [spatie/laravel-backup#143]
It would be nice if we could set our local time for the timestamps.
Right now, all timestamps are in the UTC timezone.

Maybe by utilizing `->timezone('America/New_York');` on the cron command?

It would be even better if we could set the entire filename altogether.

**Comment by freekmurze** [comment]
You can change the timezone of the entire application in the `timezone` key in `config/app.php`.

**Comment by jlmmns** [comment]
Doh! Completely missed that one.
Thanks

**Comment by kapitannwel** [comment]
the timezone on my config>app is set to "asia/manila" but when i make a backup, the created_at field is still changing. any thoughts?
