### ISSUE TITLE
Can't get used storage from Dropbox

### ISSUE THREAD

**Issue by rezasys2** [spatie/laravel-backup#1434]
### Discussed in https://github.com/spatie/laravel-backup/discussions/1433
Note: I'm using version 6 on Laravel 7.

<div type='discussions-op-text'>

<sup>Originally posted by **rezasys2** November 25, 2021</sup>
Hi
I want to use the 'delete_oldest_backups_when_using_more_megabytes_than' option to automatically keep my Dropbox usage under 2 gigs, but it seems that the package can't get the used storage from Dropbox to do it. It always says "Used storage after cleanup: 0 B." for Dropbox disk. 
The other possible option for me is to keep backups for 4 hours, but I don't know how to implement it.
How can I tackle this issue?</div>

**Comment by erikn69** [comment]
V6 version is no longer supported, feel free to make your own PR to fix it
