### ISSUE TITLE
Include paths should overwrite exclude paths

### ISSUE THREAD

**Issue by jlmmns** [spatie/laravel-backup#144]
I have quite a few subdirectories in my `/storage` folder.
There's only 1 directory that I want to keep in my backup.

It would be helpful if we could:
-  exclude: `storage_path()`
-  include: `storage_path('my-folder')`

Then, only `my-folder` would be included in the backup.
Otherwise you would need to exclude every single folder you don't want, and with vendor packages that becomes a hassle.

**Comment by sebastiandedeyne** [comment]
On the other hand, if you'd want to include everything but one, it would be a hassle if include paths would overwrite exclude paths, so there's not really a winning strategy between the two.

Either way, this would be a pretty big breaking, so we can't change the behaviour until the next major version.

**Comment by jlmmns** [comment]
True, but wouldn't it be possible to overwrite one way or the other, by comparing the folder "scope"?

e.g.: `storage_path('my-folder')` *is more specific* than `storage_path()`

So in my case the include path would ~~overwrite~~ **bypass** the exclude path.
