### ISSUE TITLE
Undefined constant "Spatie\Backup\Tasks\Backup\SIGINT"

### ISSUE THREAD

**Issue by AlexHaible** [spatie/laravel-backup#1445]
Server config:
Laravel Forge managed Ubuntu 20.04 LTS
PHP 8.0

Stacktrace:
```php
Error Undefined constant "Spatie\Backup\Tasks\Backup\SIGINT"      
vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php:148 Spatie\Backup\Tasks\Backup\BackupJob::run     
vendor/shuvroroy/filament-spatie-laravel-backup/src/Jobs/CreateBackupJob.php:42 ShuvroRoy\FilamentSpatieLaravelBackup\Jobs\CreateBackupJob::handle     
vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}     
vendor/laravel/framework/src/Illuminate/Container/Util.php:40 Illuminate\Container\Util::unwrapIfClosure     
vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93 Illuminate\Container\BoundMethod::callBoundMethod     
vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37 Illuminate\Container\BoundMethod::call     
vendor/laravel/framework/src/Illuminate/Container/Container.php:653 Illuminate\Container\Container::call     
vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:128 Illuminate\Bus\Dispatcher::Illuminate\Bus\{closure}     
vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}     
vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103 Illuminate\Pipeline\Pipeline::then     
vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:132 Illuminate\Bus\Dispatcher::dispatchNow     
vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:266 Illuminate\Bus\Dispatcher::Illuminate\Bus\{closure}     
vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}     
vendor/laravel/framework/src/Illuminate/Container/Util.php:40 Illuminate\Container\Util::unwrapIfClosure     
vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:81 Illuminate\Container\BoundMethod::callBoundMethod     
vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37 Illuminate\Container\BoundMethod::call     
vendor/laravel/framework/src/Illuminate/Container/Container.php:653 Illuminate\Container\Container::call     
vendor/laravel/framework/src/Illuminate/Foundation/Application.php:1158 Illuminate\Foundation\Application::terminate     
vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:182 Illuminate\Foundation\Http\Kernel::terminate     
public/index.php:55 [main]
```

Oddly enough the package works just fine on my Macbook using Laravel Valet, but once it's live on the server, it breaks.
I did a `php artisan tinker` to see if SIGINT had somehow become undefined, but nope, still defined as 2.

**Comment by PaolaRuby** [comment]
It's not a bug, there is a lot of information about of this, only you have to read

**Comment by AlexHaible** [comment]
> It's not a bug, there is a lot of information about of this, only you have to read

The only information I've been able to find relates to Windows servers, or people using Alpine because pcntl isn't default on that. If you've got some sources of information I can take a look at, that'd be great.

**Comment by PaolaRuby** [comment]
[use-of-undefined-constant-sig](https://stackoverflow.com/questions/53669484/use-of-undefined-constant-sigkill-assumed-sigkill)
Yes, you have to install/update/activate pcntl extension https://www.php.net/manual/en/pcntl.constants.php

**Comment by PaolaRuby** [comment]
are you sure that the php installation of the console is the same of the running server?
once it happened to me that they were different versions

**Comment by AlexHaible** [comment]
There only is the one installation of PHP on the server, it's at version 8.0.14.

Though, it turned out, that while it worked just fine in CLI (and therefore also `php artisan tinker`) the module simply didn't exist at all for FPM. So I had to compile it on the server and move it into the requisite directories, etc etc. Long story short: The module now 100% exists, and works.

**Comment by elmarzouguidev** [comment]
I fixed this issue by disabling Signals

 $backupJob = BackupJobFactory::createFromArray(config('backup'));

 $backupJob->disableSignals();
