### ISSUE TITLE
backup mysql functions and procedures

### ISSUE THREAD

**Issue by bshbair** [spatie/laravel-backup#145]
How could I configure my backup to include MySQL routines?

**Comment by anandatheerthan** [comment]
In MySql.php, change line 212 from
`'--skip-comments',`
to 
`'--skip-comments --routines ',`

@Admin, since I am new to github, can you please update this in main branch.

**Comment by bshbair** [comment]
Thank you @anandatheerthan 
That would work, but it's a bad practice to modify this in core package files
I expected to handle this in "laravel-backup.php" configuration file

**Comment by freekmurze** [comment]
In v4 [you can pass extra parameters](https://docs.spatie.be/laravel-backup/v4/installation-and-setup#dumping-the-database) to the dumper using `add_extra_option`.
