### ISSUE TITLE
Disabling notification causes exception on PHP 8.1

### ISSUE THREAD

**Issue by IAmRGroot** [spatie/laravel-backup#1461]
The following config that is recommended in #613 to disable a single notification causes an error on Laravel Backup v7.7 running PHP 8.1. We do not have this error on PHP 7.4.

```php
    'notifications' => [
        'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class         => ['mail'],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class     => [],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class        => ['mail'],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class   => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class    => ['mail'],
        ],
```

The full exception can be seen here: https://sentry.io/share/issue/cc9b3968f1b4412d9b1c2a834c1e7fe8/

**Comment by freekmurze** [comment]
Could your PR a test to recreate the problem. If you know the fix, PR that too 👍

**Comment by erikn69** [comment]
Read documentation
> From v6 to v7
>- All notification class names got suffixed with 'Notification'. Make sure you update the classnames where you are using these notifications.

https://github.com/spatie/laravel-backup/blob/ce99f8abaf4856100f12d1279e83e36f952908ac/config/backup.php#L153-L160
