### ISSUE TITLE
PermanentRedirectException Backing Up To S3

### ISSUE THREAD

**Issue by warkior** [spatie/laravel-backup#147]
Hello,

I've been testing out your package and really like how it works and how configurable it is. However I'm being blocked by an S3 exception that I don't understand.

`Copying .zip file failed because: Could not connect to disk s3backups because: Aws\S3\Exception\PermanentRedirectException: Encountered a permanent redirect while requesting https://s3.amazonaws.com/my-bucket-name%2F?prefix=http---my.domain.com-%2F&encoding-type=url. Are you sure you are using the correct region for this bucket?`

I've double-checked the region and (though it was wrong at first), changing it to the right one didn't solve the issue. Nor did taking out the region entirely.

If you could point me in the right direction of a solution, I would greatly appreciate it.

Thanks,
James W.

**Comment by warkior** [comment]
@freekmurze ^^

**Comment by freekmurze** [comment]
I haven't got this error myself. Googling around the message points me in the direction that the provided credentials are wrong. http://stackoverflow.com/questions/19767832/set-proper-endpoint-in-for-s3-client-in-amazon-aws-php-sdk

Are you 100% sure the region is correct? What value have you set it to?

**Comment by warkior** [comment]
Hey, thanks for getting back to me. I found that article too and checked the values. As far as I can tell, it's set up correctly on us-west-2. I found this value based on this article:
http://www.bucketexplorer.com/documentation/amazon-s3--amazon-s3-buckets-and-regions.html

The strange thing is, I can log in directly with an S3 client and add/remove files from the bucket. No region is requested though by the S3 client. So I'm not sure how it determines the correct location.

**Comment by freekmurze** [comment]
Are you sure the bucket is in `us-west-2`?

Here's a list of possible values you could try: http://www.bucketexplorer.com/documentation/amazon-s3--amazon-s3-buckets-and-regions.html

**Comment by warkior** [comment]
I will confirm things, however I was fairly sure the region was Oregon, which would be `us-west-2` as far as I can tell.

**Comment by warkior** [comment]
@freekmurze - It must have been something related to the region. We did a bunch more tweaking and testing, and finally got it to work. Thank you for your help. I'm looking forward to using this tool. :)
