### ISSUE TITLE
Backup Email Template

### ISSUE THREAD

**Issue by mohssineAboutaj** [spatie/laravel-backup#1474]
### Discussed in https://github.com/spatie/laravel-backup/discussions/1473

<div type='discussions-op-text'>

<sup>Originally posted by **mohssineAboutaj** February  9, 2022</sup>
Hi everyone

Is there any way to **override** or **update** the **email** template for backup?
How can i send the backup file(s) as **attachment** 

Thanks in advance</div>

**Comment by erikn69** [comment]
Not an issue, nor a bug
You can make custom notifications, read the documentation
