### ISSUE TITLE
Installation in error with Laravel 9

### ISSUE THREAD

**Issue by foutesting** [spatie/laravel-backup#1476]
Environment :
Windows 10
PHP 8.1.2
Composer : 2.2.6
Node : 16.14.0
Npm : 6.14.5
Laravel : 9
Laravel framework : 9.0.1

When I run the following command on a clean installation :

`composer require spatie/laravel-backup       `

> Using version ^7.7 for spatie/laravel-backup
> ./composer.json has been updated
> Running composer update spatie/laravel-backup
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires spatie/laravel-backup ^7.7 -> satisfiable by spatie/laravel-backup[7.7.0, ..., v7.x-dev].
>     - spatie/laravel-backup[7.7.0, ..., v7.x-dev] require illuminate/console ^8.36 -> found illuminate/console[v8.36.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
> 
> You can also try re-running composer require with an explicit version constraint, e.g. "composer require spatie/laravel-backup:*" to figure out if any version is installable, or "composer require spatie/laravel-backup:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by Gjjansen** [comment]
Support for laravel 9 got added in version 8.0. 

Try installing using:
`composer require spatie/laravel-backup "^8.0"`

**Comment by foutesting** [comment]
Response received :

  [InvalidArgumentException]                                                                                                                   
  Package spatie/laravel-backup at version 8.0 has requirements incompatible with your PHP version, PHP extensions and Composer version:       
    - spatie/laravel-backup 8.0.0 requires ext-pcntl * but it is not present.

**Comment by Gjjansen** [comment]
> `composer require spatie/laravel-backup "^8.0"` Response received :
> 
> [InvalidArgumentException] Package spatie/laravel-backup at version 8.0 has requirements incompatible with your PHP version, PHP extensions and Composer version: - spatie/laravel-backup 8.0.0 requires ext-pcntl * but it is not present.

On windows you need to ignore ext-pcntl: `composer require spatie/laravel-backup "^8.0" --ignore-platform-reqs`

**Comment by erikn69** [comment]
On V7 `ext-pcntl` was optional
https://github.com/spatie/laravel-backup/blob/ce99f8abaf4856100f12d1279e83e36f952908ac/src/Commands/BaseCommand.php#L17-L19

**Comment by erikn69** [comment]
Fixed on [8.0.2](https://github.com/spatie/laravel-backup/releases/tag/8.0.2)
