### ISSUE TITLE
General error : could not find a "pg_dump" to execute pg_dump: invalid option -- 'd'

### ISSUE THREAD

**Issue by umarmw** [spatie/laravel-backup#148]
Hello,

I'm having a strange issue; got this error when running the following command:

`php artisan backup:run`

`
Starting backup...
Dumping database oasis...
Backup failed because The dump process failed with exitcode 1 : General error : could not find a "pg_dump" to execute
pg_dump: invalid option -- 'd'
Try "pg_dump --help" for more information.
.
`

And running the command
`pg_dump --version`

gives

`pg_dump (PostgreSQL) 9.2.15`

When I've search in the man pg_dump, it does support the '-d' parameter.

**Environment**

CentOS7, PHP 5.5.36, PostgreSQL 9.2.15

**What works**

Backup runs successfully on Laravel Vagrant image "PHP Version 7.0.1-1+deb.sury.org~trusty+2"

**Investigation**

I thought it was previously related to the PostgreSQL version (PostgreSQL 8.4) and moved to a new server, but the problem still persists.

@Rhincodon, I guess you may have an idea what wrong here.

**Comment by Rhincodon** [comment]
@umarmw  It seem's like `-d` flag is only available on 9.3+ versions.. Anyway, please create issue in [db-dumper](https://github.com/spatie/db-dumper) repository, it related to them. I will investigate the problem and make pull request as soon as possible.

**Comment by freekmurze** [comment]
The changes have been merged and tagged as `1.5.1`. Running composer update should resolve any `invalid option -- 'd'` errors.

**Comment by umarmw** [comment]
It now works flawlessly. Thank you @Rhincodon and @freekmurze 
:+1:
