### ISSUE TITLE
In Container.php line 879:  Target class [path.lang] does not exist. in Lumen

### ISSUE THREAD

**Issue by najathi** [spatie/laravel-backup#1484]
After I installed Laravel-Backup in lumen application. I got errors when running the `php artisan backup:run --only-db` command.
```
In Container.php line 879: Target class [path.lang] does not exist. 
In Container.php line 877: Class path.lang does not exist.
```
![image](https://user-images.githubusercontent.com/35753879/153745005-0ef7ecd3-3808-4691-8738-ea635d17a14d.png)

Already copy the lang file in the resource directory but even I got the error.

Do you have any solution to that?

**Comment by freekmurze** [comment]
We don't support Lumen. Best to upgrade to a full Laravel app.

**Comment by najathi** [comment]
Did it support the non laravel app like core PHP app?
