### ISSUE TITLE
backup only has db no files

### ISSUE THREAD

**Issue by sunnyjayjay** [spatie/laravel-backup#149]
My backup runs saying it is backing up 14660 files. When I find the zip (in storage/app) it has only the mysql db in it. 

My source section looks like this:

    'files' => [

                /*
                 * The list of directories that should be part of the backup. You can
                 * specify individual files as well.
                 */
                'include' => [
                    base_path(),
                    base_path('public')
                ],

                /*
                 * These directories will be excluded from the backup.
                 * You can specify individual files as well.
                 */
                'exclude' => [
                    base_path('vendor'),
                    base_path('node_modules'),
                    storage_path(),
                ],

**Comment by freekmurze** [comment]
That doesn't sound right. Could you try only backing up the `public` path, leaving the `exclude` array empty?

**Comment by sunnyjayjay** [comment]
Panic over, it's a Windows 10 Explorer problem. In Explorer only the .sql file shows. If I open the file with 7-zip then I can see everything. Sorry to bother you,

**Comment by freekmurze** [comment]
Phew! Glad our package didn't cause this problem 😄

**Comment by Francismori7** [comment]
How this is still a Windows issue is beyond me. Explorer crashes trying to open the ZIP on Windows 10, 7-zip is fine.

Can't believe it :/
