### ISSUE TITLE
Unresolvable dependency in class Spatie\Backup\BackupDestination\BackupDestination

### ISSUE THREAD

**Issue by rizkhal** [spatie/laravel-backup#1504]
I'am using Laraval 9 and Latest Version of this package..

The notification is successfully sended but the error `Sending notification failed` still showing in console..

So i am trying to do some chechk bellow in `BackupJob.php` https://github.com/spatie/laravel-backup/blob/14d27ec8157a8f563ce9ef8a80691019df9301de/src/Tasks/Backup/BackupJob.php#L307
```php
protected function sendNotification($notification): void
{
    try {
        event($notification);
    } catch (\Throwable $th) {
        dd($th->getMessage());
    }
}
```

The `Throwable` message is `Unresolvable dependency resolving [Parameter #1 [ <required> string $backupName ]] in class Spatie\Backup\BackupDestination\BackupDestination`.

And also i want to make other job when success event is fired so i add my custom listener in `EventServiceProvider.php`

```php
protected $listen = [
  \Spatie\Backup\Events\BackupWasSuccessful::class => [
      \App\Listeners\Backup\BackupHasSuccessful::class,
  ]
];
```

but the event is not fired..

Thanks 🍻

**Comment by freekmurze** [comment]
Did you upgrade the config file as well? Some config keys were renamed.

**Comment by rizkhal** [comment]
Yes, my config is fresh config copied from vendor

**Comment by freekmurze** [comment]
Did you clear the config with `php artisan config:clear`.

If that doesn't work, you'll need to research where `BackupDestination` gets `$backupName` and why it's empty there.

**Comment by rizkhal** [comment]
Thanks for this great package and your feedback. I will do it

**Comment by freekmurze** [comment]
Cool, let me know what the problem / fix was here. Your feedback might help other users of the package.

**Comment by rizkhal** [comment]
My mistake cause i put wrong parameter in `handle` method on my custom listener
```php
\App\Listeners\Backup\BackupHasSuccessful::class,
```

I apologize and thank you again
