### ISSUE TITLE
ContentMD5 is required when uploading to Amazon S3 with object lock

### ISSUE THREAD

**Issue by Xaero** [spatie/laravel-backup#1515]
Hi!

I'm trying to use Laravel backup together with an Amazon S3 Object Lock enabled bucket. However, Amazon requires that the uploaded data has a 'ContentMD5' value added to the config. 

In the BackupDestination class, the following could be added to the write method:
```
        $options['ContentMD5'] = base64_encode(md5_file($file, true));
```

However, this would only be used by Amazon (or any other cloud provider that uses ContentMD5). 

What would be the best way to accomplish adding the ContentMD5 header?

**Comment by freekmurze** [comment]
I guess this is an issue for the S3 filesystem driver, and not necessarily for this package.

**Comment by smknstd** [comment]
@Xaero Did you manage to make it work ?
