### ISSUE TITLE
BackupHasFailed fired twice

### ISSUE THREAD

**Issue by Xaero** [spatie/laravel-backup#1516]
When running the `laravel:backup` command, and something occurs in BackupJob that throws an exception, the BackupJob class sends a BackupHasFailed notification. However, the BackupCommand class also monitors for exceptions, and sends a BackupHasFailed notification. 

Is the above intentional?

**Comment by freekmurze** [comment]
I think so, as if there something going wrong dispatching the job in the command you want to get a notification. And also if the job itself fails you want to get a notification.

Should I not have understood you correctly, and you think the package is in error, feel free to PR a failing test to demonstrate the bug and a fix for the bug 👍
