### ISSUE TITLE
Fail to backup on controller call

### ISSUE THREAD

**Issue by dukenst2006** [spatie/laravel-backup#152]
public function backup(){
        Artisan::call('backup:run', [
            '--only-db' => true,
        ]);
Failed to backup  because: The dump process failed with exitcode 1 : Genera=
l error : 'mysqldump' is not recognized as an internal or external command,
operable program or batch file.
However via command line there is no error.
Any idea ?

**Comment by sebastiandedeyne** [comment]
First thing that comes to mind is that your web app is being run from a different user than the one you log in as.
