### ISSUE TITLE
Wrong Year-Week combination for first week of January

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-backup#1528]
As you can see below the current `YW` format results in wrong year week combinations for end/start of year days/weeks. A curent example 2021/2022 - the first days of January 2022 would be added to the end of 2022 dates. so it would delete the wrong backups at the end of the year.

The solution would be to use the `formatLocalized()` method instead with the `%G%V` format. This would put the start of January days but in the end of 2021 week.
As the format logic is abstracted it would require changing all formats - but this should be easy as all others use straight year, month, day stuff.

```php
Carbon::parse('2021-12-31')->format('YW'); // 202152
Carbon::parse('2021-12-31')->formatLocalized('%G%V'); // 202152

Carbon::parse('2022-01-01')->format('YW'); // 202252
Carbon::parse('2022-01-01')->formatLocalized('%G%V'); // 202152

Carbon::parse('2022-12-31')->format('YW'); // 202252
Carbon::parse('2022-12-31')->formatLocalized('%G%V'); // 202252
```

For all groups it would be:
```php
formatLocalized('%Y%m%d');
formatLocalized('%G%V');
formatLocalized('%Y%m');
formatLocalized('%Y');
```

And as we all like a good StackOverflow link, here you go: https://stackoverflow.com/a/64641985/4907524 😉

**Comment by freekmurze** [comment]
Thanks for reporting! If you already know where this can be fixed, feel free to send a PR. Otherwise, I'll have a look soon.

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-backup/blob/e011c04ef4aa6ba596321675d5f6a57863d25f4d/src/Tasks/Cleanup/Strategies/DefaultStrategy.php#L16-L38

One thing I'm not sure about is the deletion of old backups. As the current logic looks like it would delete the last monthly and yearly backup of 2021 in the weekly cleanup of 2022-01-01. 🤔

We've switched to a "keep-list" logic. So each period adds the `$group->shift()` to a `$keep` collection and at the end we do a `$backups->diff($keep)` and this we no backup is deleted by any period that should have been kept by another one.
https://github.com/spatie/laravel-backup/blob/e011c04ef4aa6ba596321675d5f6a57863d25f4d/src/Tasks/Cleanup/Strategies/DefaultStrategy.php#L77-L86

**Comment by Nielsvanpach** [comment]
`formatLocalized()` is marked as deprecated

**Comment by Gummibeer** [comment]
@Nielsvanpach `Use ->isoFormat() instead.` I think that the format would have to be changed but `isoFormat()` is capable to do the same as well.
