### ISSUE TITLE
BackupWasSuccessful event not firing in Laravel 9

### ISSUE THREAD

**Issue by AleJavierHY** [spatie/laravel-backup#1536]
Following the documentation I am trying to listen to the BackupWasSuccessful event but it does not fire. I am using version 9 of Laravel. How could I solve this problem?

```
protected $listen = [
      'Spatie\Backup\Events\BackupWasSuccessful' => [
            'App\Listeners\BackupWasSuccessfulListener',
   ],
];
```

**Comment by PaolaRuby** [comment]
>How could I solve this problem?

Making a PR with the fix

**Comment by freekmurze** [comment]
It seems like currently we only send events if notifications are set up. I'll fix this in the next major version.
