### ISSUE TITLE
Sending notification failed after updating laravel 8 to laravel 9

### ISSUE THREAD

**Issue by polodev** [spatie/laravel-backup#1537]
I have updated to laravel 9 from laravel 8.
In order to update laravel I had to update
* php version 8.1 from 7.4
* laravel backup version `"spatie/laravel-backup": "^8.1.2"`

<img width="893" alt="laravel_backup" src="https://user-images.githubusercontent.com/7695068/173768492-f0641974-e213-47d4-a114-c4b3fec8fa72.png">

**Comment by lukasboomstra** [comment]
I think you need to update your config/backup.php 'mail' key structure. It should be as following:
`
        'mail' => [
            'to' => 'victor@asdqwe.nl',
            'from' => [
                'name' => 'test',
                'address' => 'no-reply@mg.nieuw-energiecontract.nl'//config('valadi.mail-from'),
            ]
        ],
`

**Comment by polodev** [comment]
@lukasboomstra currently `config/backup.php` file having exactly same `mail` key structure. It used to be fine. After upgrading to laravel 9, php 8, and spatie laravel-backup: `Sending notification failed` message showing

**Comment by lukasboomstra** [comment]
> @lukasboomstra currently `config/backup.php` file having exactly same `mail` key structure. It used to be fine. After upgrading to laravel 9, php 8, and spatie laravel-backup: `Sending notification failed` message showing

Whats happens when you run `php artisan backup:clean`? This gave me a more detailed exception.

**Comment by PaolaRuby** [comment]
https://laravel.com/docs/9.x/upgrade#symfony-mailer

**Comment by webtarah** [comment]
Change:

\Spatie\Backup\Notifications\Notifications\BackupHasFailed::class => ['mail', 'slack'],
\Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail', 'slack'],
\Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class => ['mail', 'slack'],
\Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class => ['mail'],
\Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class => ['mail'],
\Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class => ['mail'],

To this:

\Spatie\Backup\Notifications\Notifications\BackupHasFailedNotification::class => ['mail', 'slack'],
\Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFoundNotification::class => ['mail', 'slack'],
\Spatie\Backup\Notifications\Notifications\CleanupHasFailedNotification::class => ['mail', 'slack'],
\Spatie\Backup\Notifications\Notifications\BackupWasSuccessfulNotification::class => ['mail'],
\Spatie\Backup\Notifications\Notifications\HealthyBackupWasFoundNotification::class => ['mail'],
\Spatie\Backup\Notifications\Notifications\CleanupWasSuccessfulNotification::class => ['mail'],

**Comment by erikn69** [comment]
@webtarah that was a V6 change
https://github.com/spatie/laravel-backup/blob/main/UPGRADING.md#from-v6-to-v7
**Close this if it is resolved**

**Comment by freekmurze** [comment]
You can probably fix this with @webtarah 's suggestion.

**Comment by i7strelok** [comment]
@webtarah I have the same problem but I use the version 8, could you help me? emails work well but notification by slack is the problem
