### ISSUE TITLE
Exclude tables from SQL

### ISSUE THREAD

**Issue by microdesign** [spatie/laravel-backup#154]
What is the reason we cannot point our path 'mysqldump' executable file and this way we can pass our custom arguments to the commands - such as ignoring not needed tables or something else?

Please let me know if there is option to exclude tables.

**Comment by freekmurze** [comment]
This package uses our own [db-dumper](https://github.com/spatie/db-dumper) to dump db's. I'll look into an option to pass arbitrary flags. 

The option to exclude tables is coming via #153 soon.

**Comment by microdesign** [comment]
Thanks

**Comment by mtx-z** [comment]
Anyway to use this option on laravel-backup 3 ? I'm on Laravel 5.1, and this option seems only available from package version 4. 
I tried upgrade from 3 to 4, but it failed on some dependencies... thx

**Comment by janokary** [comment]
Is this option supported after all?
`--ignore-table`
or this one?
`--exclude-tables`
