### ISSUE TITLE
Controller call backup failing.

### ISSUE THREAD

**Issue by curricula** [spatie/laravel-backup#155]
Might be similar to #152 

My Setup:
Laravel 5.2
Digital Ocean / Forge

Calling the following from a controller.
`$commandCall = Artisan::call('backup:run');`

Fails with "production.ERROR:  backups : error: Failed to backup  because: The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 1045: Access denied for user 'forge'@'localhost' (using password: NO) when trying to connect"

The scheduler and command line however perform the calls without any issue.

Some things that I have already tried but without any resolve.
- Doubled checked the .env files and variables are correct
- Verified the DB user has all access permissions through Sequel Pro
- Locally and on an alternative DigitalOcean server I am not having any issues.

Any ideas?

**Comment by sebastiandedeyne** [comment]
That `using password: NO` looks like a red flag to me. Could it be that the env file isn't getting loaded in that particular situation?

**Comment by curricula** [comment]
The .env variables seem to be accessible from that controller as well as the command line.

I think the issue is that the `Artisan::call` method can't access any .env variables and instead uses the defaults instead, which in my case is 'localhost' and a blank password.

Going to be performing some Ubuntu updates, will let you know if that solves anything.
