### ISSUE TITLE
In case of a backup failure, the BackupHasFailed event is fired twice

### ISSUE THREAD

**Issue by ffeytons** [spatie/laravel-backup#1553]
In case of a backup failure, the `BackupHasFailed` event is fired twice, resulting in receiving twice the notification each time (e.g. Slack or mail).

This is due to the fact that the `BackupHasFailed` event is fired:
1. At BackupJob.php:172
2. Because of the `throw $exception` at BackupJob.php:176, it is fired again at BackupCommand.php:67

**Comment by PaolaRuby** [comment]
Feel free to make a PR for fix that

**Comment by ffeytons** [comment]
@PaolaRuby I'm not sure to understand what you mean by "Also you can link lines"?

For the suggestion that the problem would come from the report that would send a double notification, it is not the case.
There are multiple firings of the `BackupHasFailed` event, we can even have 3 of them fired at once if the error happens during the copy of the backup to its destination, in which case it will happen:
1. First at `BackupJob.php:321` (`copyToBackupDestinations`)
2. Second at `BackupJob.php:168` (`run`, because the exception fired in `copyToBackupDestinations` exception)
3. Third at `BackupCommand.php:67`

Happy to do a PR for this. My opinion would be to remove the `BackupHasFailed` event from `BackupCommand` and only fire it from `BackupJob`. Do you agree with this?

**Comment by PaolaRuby** [comment]
Do you agree with this?

Not the best, because when the exception is outside of the `try` on `Backup Job.php`, it never notified

**Comment by ffeytons** [comment]
Indeed. However, this would mean having the `BackupWasSuccessful` managed by `BackupJob.php` along with all the other notifications while only `BackupHasFailed` would be handled on the upper layer (`BackupCommand`) -- which is not an ideal situation neither.
Looks like it'd be worth to refactor a bit the exception management of `BackupJob`/`BackupCommand` along with the fix of this bug.

**Comment by PaolaRuby** [comment]
>Looks like it'd be worth to refactor a bit the exception management

Yes, it could be the best on this case
