### ISSUE TITLE
php artisan backup:run --only-db is failing

### ISSUE THREAD

**Issue by amit-viacon** [spatie/laravel-backup#1555]
I have a cron job that runs the backup job every day. It was working fine but now it is throwing error `Backup failed because There are no files to be backed up` 
```
php artisan backup:run --only-db
Starting backup...
Dumping database xxxxxxxxx_xxxxxxxxxxxxxxxxxx...
Determining files to backup...
Backup failed because There are no files to be backed up..
```

**Comment by ultrono** [comment]
FYI there is some further discussion on this at https://github.com/spatie/laravel-backup/discussions/1554

**Comment by freekmurze** [comment]
We'll discuss this further in #1554
