### ISSUE TITLE
Wrong Filesystem while trying to make a Backup to Dropbox with flysystem-dropbox

### ISSUE THREAD

**Issue by JoelBeerDe** [spatie/laravel-backup#1568]
Laravel-Backup everything works nice as long as you only take local backups.
But after installing [flysystem-dropbox](https://github.com/spatie/flysystem-dropbox) i get the following error:
`Spatie\Backup\BackupDestination\BackupDestination::__construct(): Argument #1 ($disk) must be of type ?Illuminate\Contracts\Filesystem\Filesystem, League\Flysystem\Filesystem given`.

**Comment by fredsal** [comment]
That is not a bug or an issue, read documentation, your adapter implementation is wrong
also, this section is not to answer about third party packages problems

**Comment by JoelBeerDe** [comment]
> That is not a bug or an issue, read documentation, your adapter implementation is wrong also, this section is not to answer about third party packages problems, use discussions section

I added the dropbox filesystem exactly like in the Laravel docs. Also Laravel Backup returns the error so i don't know why it should be a third party problem.

If my adapter implementation is wrong how would it look correctly? And where can i find a documentation for the implementation? Only thing i found was on Laravel docs.

```
Storage::extend('dropbox', function ($app, $config) {
      $adapter = new DropboxAdapter(new DropboxClient(
        $config['authorization_token']
      ));

      return new FilesystemAdapter(
        new Filesystem($adapter, $config),
        $adapter,
        $config
      );
    });
```

**Comment by JoelBeerDe** [comment]
Unfortunately i had a provider for the filesystem and added it in AppServiceProvider. Because the provider class had errors it didn't work.

**Comment by fredsal** [comment]
> Because the provider class had errors it didn't work.

Because you didn't read laravel documentation
