### ISSUE TITLE
[3.8.0] backup:run save to S3 stopped working

### ISSUE THREAD

**Issue by jlmmns** [spatie/laravel-backup#157]
After version 3.8.0, my S3 backups suddenly stopped working, without any errors.

The backups are still in `/storage/laravel-backups/temp/`, but never got uploaded to S3.
Never received any warnings or error logs.

I only noticed because I stopped receiving Slack notifications.

`backup:clean` continues to work fine, with a Slack notification, saying it did a successful clean.

My backups are around 5MB.

Any ideas?

**Edit:**

`backup:list` shows the following:

```
+--------------+---------+-----------+---------+--------------+-------------------+--------------+
| Name         | Disk    | Reachable | Healthy | # of backups | Youngest backup   | Used storage |
+--------------+---------+-----------+---------+--------------+-------------------+--------------+
| app.dev      | backups | ✅        | ❌      | 8            | 8.16 (1 week ago) | 39.93 MB     |
+--------------+---------+-----------+---------+--------------+-------------------+--------------+
```

**Comment by freekmurze** [comment]
Tested it here and it seems to work... Maybe it has something to do with the amount of files being included / excluded? Could you try backing up only a few files to see if that works?

**Comment by jlmmns** [comment]
Hm, weird...
I recently upgraded Homestead and a composer update to the latest version of laravel-backup, and now it seems to be working fine with the same backup configuration.
