### ISSUE TITLE
Can't run from controller with --only-db option

### ISSUE THREAD

**Issue by cbcto** [spatie/laravel-backup#158]
Hi, I'd like to run 'backup:run --only-db' from the controller
I have tried \Artisan::call('backup:run',['--only'=>'-db']) but that gives me the error: 'InvalidArgument Exception The "--only" option does not exist.'
Any advice?

Thanks a lot

**Comment by freekmurze** [comment]
Take a look at [the tests](https://github.com/spatie/laravel-backup/blob/master/tests/Integration/BackupCommandTest.php#L22) to learn how to call `--only-db` from code.
