### ISSUE TITLE
Backup completed, but no files, only mysql dump

### ISSUE THREAD

**Issue by kskrlinnorth2** [spatie/laravel-backup#1589]
When I run this command `php artisan backup:run` on local machine (Windows 11 with Wamp) I get this output and email that backup was successful:

![image](https://user-images.githubusercontent.com/61736280/194585868-8ccfcb9b-a651-4b9c-acf5-55f72513f7a0.png)

There is zip file with same size:
![image](https://user-images.githubusercontent.com/61736280/194586062-349cd288-8a72-43d1-bb25-4b6c9ee57d93.png)

But inside zip is only db-dumps folder with less than 1 MB

**Comment by lcs13761** [comment]
set in config/backup

example
 'relative_path' => base_path(),
