### ISSUE TITLE
Backup not working on server

### ISSUE THREAD

**Issue by cappuc** [spatie/laravel-backup#159]
If I run "php artisan backup:now" it stops after Determing files to backup and it will not create the backup zip.
I tried with --only-db options and it works but with --only-files it doesn't works.
The files backup require some software installed on the server?
Thanks

**Comment by freekmurze** [comment]
Version 3.8.1 of this package has drastically lower memory requirements when backing up files.

Could you please upgrade to that version and try again?

**Comment by cappuc** [comment]
Now it works, thanks
