### ISSUE TITLE
How to get list of backups with path & backup file name.

### ISSUE THREAD

**Issue by IamSwap** [spatie/laravel-backup#160]
First of all, thanks for this awesome package. I am creating admin interface for a app which will show list of current backup on the disk. 

So far I have tried return collections using methods from ListCommand class : https://github.com/spatie/laravel-backup/blob/master/src/Commands/ListCommand.php

But I can not find the way show retrieve backup file path along with file name so that I can allow admin to download available backups. Any help?

**Comment by freekmurze** [comment]
Take a look at this code: https://github.com/spatie/laravel-backup/blob/master/src/BackupDestination/BackupDestination.php#L106-L114
