### ISSUE TITLE
spaces in .env DB_DUMP_PATH are causing mysqldump path not found errors on windows

### ISSUE THREAD

**Issue by BrettFagerlund** [spatie/laravel-backup#162]
Paths will change based on install, but paths here are example of 64bit mariaDB 10.1 install on server 2012R2.

When setting .env variables to
DB_DUMP_PATH="C:\program files\MARIADb 10.0\bin"
If I output the backupjob object, i can see the dumpBinaryPath= C:\program files\MARIADb 10.0\bin/ with no quotes, if i trace this through it will search folder C:\program and drop the rest of the path, then fail to find mysqldump.exe
To work with spaces that path needs quotes around it prior to searching for mysqldump

Existing code works with windows shortname directory such as
DB_DUMP_PATH=C:\progra~1\MARIAD~1.0\bin
This will search as C:\progra~1\MARIAD~1.0\bin/ which will result in finding mysqldump.exe

**Comment by freekmurze** [comment]
Though the package does not support WIndows, I'd accept a PR that fixes this.

**Comment by alcarazolabs** [comment]
Hi @BrettFagerlund did you solve this problem?
