### ISSUE TITLE
Backup fails when backing up MySql db which has read / write hosts

### ISSUE THREAD

**Issue by drawmyattention** [spatie/laravel-backup#163]
I have a database connection defined as follows:

    'mysql' => [
            'read' => [
                'host' => env('DB_READ_HOST', 'localhost'),
            ],
            'write' => [
                'host' => env('DB_WRITE_HOST', 'localhost')
            ],
            'driver'    => 'mysql',
            // Other parameters
        ],

When I try to run ```php artisan backup:run```, I see the ```Backup failed because: Undefined index: host.``` error, because I am not setting a host directly.

There should be a check performed to check if there is a ```read``` host first, and if there isn't, use the ```host``` value of the database connection.

**Comment by freekmurze** [comment]
Yup, this should be fixed. I'll try to make some time for this in the coming weeks. I'd also accept a PR if you need this quick.

**Comment by bhulsman** [comment]
So let's say https://github.com/spatie/laravel-backup/blob/master/src/Tasks/Backup/BackupJobFactory.php could use some spice from https://github.com/illuminate/database/blob/master/Connectors/ConnectionFactory.php.

I'm I right?

**Comment by freekmurze** [comment]
Support for read database connections has been added in `v4.1.0` of this package.
