### ISSUE TITLE
Mysql 5.7.41 & 8.0.32 backup error

### ISSUE THREAD

**Issue by monurakkaya** [spatie/laravel-backup#1636]
Hi everyone, 
For whom is facing an error like:
```txt
The dump process failed with a none successful exitcode.
Exitcode
========
2: Misuse of shell builtins
Output
======
<no output>
Error Output
============
mysqldump: Couldn't execute 'FLUSH TABLES': Access denied; you need (at least one of) the RELOAD or FLUSH_TABLES privilege(s) for this operation (1227)
```
there is a bug on mysql reported below:

https://bugs.launchpad.net/ubuntu/+source/mysql-5.7/+bug/2003866

As a workaround you can remove `useSingleTransaction => true` from database.mysql.dump config or downgrade your mysql version. 

Cheers,
Onur.

**Comment by PaolaRuby** [comment]
Duplicate of https://github.com/spatie/laravel-backup/discussions/1635
