### ISSUE TITLE
Backup of large databases fails

### ISSUE THREAD

**Issue by drawmyattention** [spatie/laravel-backup#165]
I'm having quite a lot of trouble getting this package to work when backing up larger databases (~2Gb).

The errors I tend to get are:

(most common - probably for over 90% of backups)

```
Failed to backup  because: The process "mysqldump --defaults-extra-file="/tmp/phpov7326" --skip-comments --skip-extended-insert --single-transaction mydbname > "/home/forge/mysite/releases/20160711150556/storage/laravel-backups/temp//mydbname.sql"" exceeded the timeout of 3600 seconds.
```

(occasional)
```
Failed to backup  because: The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Couldn't execute 'SELECT /*!40001 SQL_NO_CACHE */ * FROM `my_table_name`': Lost connection to MySQL server during query (2013)
```

If I manually export the database using Sequel Pro, it takes around 8 minutes, so I understand that the export process would be lengthy - but as I've set a timeout of 3600 seconds (one hour) I am struggling to understand what is causing the timeout.

**Comment by freekmurze** [comment]
Does exporting work if you use `mysqldump` directly?

**Comment by drawmyattention** [comment]
I've done some tests, and if I pipe ```mysqldump``` through ```gzip``` it takes over an hour to export the dump. If I pipe directly to a file, it takes around 8 minutes (which is on par with the time it roughly takes manually backing up using Sequel Pro).

You can see the data rate drop massively using:

```
mysqldump -P 3306 -h mydbhost -u myuser -pMyPassword --single-transaction --quick mydatabase | gzip | pv --progress --timer --eta --rate --bytes --size 2300M > /home/forge/dump.sql
```

compared with 

```
mysqldump -P 3306 -h mydbhost -u myuser -pMyPassword --single-transaction --quick mydatabase | pv --progress --timer --eta --rate --bytes --size 2300M > /home/forge/dump.sql
```

You may need to ```sudo apt-get install pv``` to get progress output.

The question remains whether or not this package is gziping mysqldump output or not?

**Comment by freekmurze** [comment]
The package will zip the sql dump together with the rest of the files to be backed up. The package also does not use the `--quick` option.

**Comment by anandatheerthan** [comment]
I am also facing same issue, using AWS for mysql and running laravel on VPS..
```
backup failed because The process "mysqldump --defaults-extra-file="/tmp/phpuFvvTt" --skip-comments --routines  --extended-insert que
usr/share/nginx/html/htdocs/jansoft/storage/laravel-backups/temp//questip3_qgen.sql"" exceeded the timeout of 300 seconds..
```
