### ISSUE TITLE
Can't open the generated .sql file

### ISSUE THREAD

**Issue by curricula** [spatie/laravel-backup#166]
After a DB backup is preformed ( without any errors ), I unzip the file and try and attempt to open it with the latest version of Sequel Pro but I get the following error.

The file “homestead.sql” couldn’t be opened using text encoding Unicode (UTF-8).

"The file may have been saved using a different text encoding, or it may not be a text file."

I will add that the file size of the .sql file leads me to believe it does contain my database information.

Any ideas?

**Comment by freekmurze** [comment]
What do you see when you open it up in a text editor like TextEdit, BBEdit or Vim?

**Comment by curricula** [comment]
In TextEdit, everything looks pretty much as expected and opened no problem.

Tried with Brackets and I got the error message that the file needs to be UTF-8 encoded for Brackets to be able to open it.

**Comment by freekmurze** [comment]
I guess that if it looks fine in TextEdit, the error lies more with `Brackets`.
