### ISSUE TITLE
Option to choose absolute path or relative path inside zip

### ISSUE THREAD

**Issue by welcoMattic** [spatie/laravel-backup#169]
Hi Spatie members!
Thanks for this package 😉 

I've a suggestion about the archived files paths. Actually, when I extract my backup, files are extracted in folder named like `/Users/welcomattic/workspace/_backups/myLaravelProject/`.

Well, it looks like the right way for most of people, but for my current needs, I want myLaravelProject to be extracted in folder named like `myLaravelProject`, in directory where I lunch the extraction.

Do you think it will be possible?

Thank you!

**Comment by freekmurze** [comment]
Hi, 

I'm glad you like that package. 😎 

we're probably not going to change the paths inside the zip as that would be a breaking change.

**Comment by welcoMattic** [comment]
Ok, thanks for answer, I understand.

I will trick my extraction script ;)
