### ISSUE TITLE
Notifier Initialization Fails When Using Bugsnag-Laravel 2.0+

### ISSUE THREAD

**Issue by aaronhuisinga** [spatie/laravel-backup#170]
Hey everyone,
With the new 2.0 release of Bugsnag for Laravel (https://github.com/bugsnag/bugsnag-laravel and http://docs.bugsnag.com/platforms/php/laravel/#basic-configuration), it appears they have moved from overriding the ExceptionHandler to now overriding the Logger to report bugs. 

After updating, I'm unable to use both Bugsnag and Laravel Backup together as the constructor for the Laravel Backup Notifier uses the type of "Illuminate\Contracts\Logging\Log". Attempting to boot gives me the error:
`Type error: Argument 1 passed to Spatie\Backup\Notifications\Notifier::__construct() must implement interface Illuminate\Contracts\Logging\Log, instance of Bugsnag\PsrLogger\MultiLogger given`

In order to deal with this for now, I've just disabled notifications for backups. I'm really not 100% sure if this is something that should be considered a Laravel Backup or a Bugsnag issue, but they're both very popular Laravel packages and as people upgrade this issue will likely become prevalent.

**Comment by freekmurze** [comment]
Checking this with the maintainers of the Bugsnag package...

**Comment by aaronhuisinga** [comment]
This will be fixed in the next Bugsnag Laravel release. Thanks @freekmurze for the help!
