### ISSUE TITLE
Cron job Not working

### ISSUE THREAD

**Issue by javedLive** [spatie/laravel-backup#174]
I want to keep download the database every hour for that i have done the following process. I have added the following line :

/ app/Console/Kernel.php

protected function schedule(Schedule $schedule)
{
   $schedule->command('backup:run')->hourly();
}

It should automatically download the database. But nothing happened.What should I do?

**Comment by freekmurze** [comment]
Did you add a cron entry to your server like [described in the Laravel docs](https://laravel.com/docs/5.2/scheduling)?

**Comment by javedLive** [comment]
What to add in server ?
I think by add the line $schedule->command('backup:run')->hourly(); in app/console/kernel.php it should update the database in every hour right?
if I'm not wrong

**Comment by freekmurze** [comment]
Did you sent up a cron job on your server that calls Laravel's scheduler every minute. The process is described here under the title "Starting the scheduler": https://laravel.com/docs/5.2/scheduling
