### ISSUE TITLE
How to write right daily

### ISSUE THREAD

**Issue by Takhir** [spatie/laravel-backup#175]
Hello!
I write **$schedule->command('backup:run');** and it is work
but this
**$schedule->command('backup:run')->dailyAt('11:00');** don't work
and this code
**$schedule->command('backup:run')->daily()->at('11:00');** don't work
what's the problem, what am I doing wrong?

**Comment by freekmurze** [comment]
Do you have this problem with all the commands?

 If so it's probably an issue with your app or with Laravel itself.

Try to install the package in a fresh installation of Laravel.
