### ISSUE TITLE
Is there anyway we can use the package to back in synchronous way instead of complete backup every time ?

### ISSUE THREAD

**Issue by evivz** [spatie/laravel-backup#176]
Is there anyway we can use the package to back in synchronous way instead of complete backup every time?

My DB size is 30GB and Media Files size is around 80GB so it takes up too much of time to back it up whole. So is there any way I can do synchronous backup using this package?

**Comment by freekmurze** [comment]
You mean an incremental backup? No, this package is meant to be used on small to medium sized applications. 

I can highly recommend taking a look at some of the alternatives like BackupPC, Bakula or Ottomatik.io
