### ISSUE TITLE
Alternate Configuration Files (Question/Enhancement Idea)

### ISSUE THREAD

**Issue by warkior** [spatie/laravel-backup#178]
I was just wondering if it is possible to manually override certain aspects of the backup process. For example, if I wanted to run weekly backups which exclude a certain (large) folder, but then every month back up the whole thing with the large folder as well. I would think this would be most easily accomplished by the ability to specify an alternative configuration file at run-time. Incidentally, this could give quite a lot more flexibility to the system over-all.

It would be run something like...
`php artisan backup:run -c laravel-backup-alternate`

**Comment by freekmurze** [comment]
Hi, that's a good suggestion.

You can do this more or less in the current version. You can conditionally [add more files to the zip](https://docs.spatie.be/laravel-backup/v3/advanced-usage/adding-extra-files-to-the-zip). 

I'm planning on creating a new major version of this package in the next couple of months. Right now I plan om making these changes:
- configurable backup jobs (a bit like you are describing)
- make use of L5.3's notification system
- make use of PHP 7 language features to clean up the code.
