### ISSUE TITLE
Types v9

### ISSUE THREAD

**Issue by rcerljenko** [spatie/laravel-backup#1808]
Hi,

This happens when you set `null` on that config in v9:

![image](https://github.com/spatie/laravel-backup/assets/16762056/7a1273ce-6fa4-49f9-ac1f-bf28499e9406)

**Comment by rcerljenko** [comment]
Also, `notifications.mail.to` used to accept `array` because Laravel accepts it too in mail handler so you could send notification to multiple emails at once, but now, via config DTO, it only accepts `string`.  :( could that be changed to also accept `string|array` ?

**Comment by rcerljenko** [comment]
I made a PR to fix this: https://github.com/spatie/laravel-backup/pull/1809

**Comment by freekmurze** [comment]
We'll handle this further in the PR
