### ISSUE TITLE
Mysqldump not found when using with MariaDB

### ISSUE THREAD

**Issue by gdarko** [spatie/laravel-backup#1820]
Hey, 

I am observing issues with the backup on servers that are running mariadb 11+.

As of MariaDB 11.0.1 the `mysqldump` utility was completely removed.  [Read more](https://mariadb.com/kb/en/mariadb-dump/). Previously as of 10.05 it was deprecated and symlinked.

As a result the database backup features does not work with mariadb 11+ because mariadb is now using `mariadb-dump`. One option is to symlink `mariadb-dump` but this is manual work which no one expects to do, the other way is to add support to this package.

Best Regards,
Darko

**Comment by freekmurze** [comment]
We're not using MariaDB ourselves.

Am I correct in assuming that MariaDB users now need to make sure `mysqldump` is available on their systems? 
If so, I'd appreciate a PR to our docs to make that clear.

**Comment by gdarko** [comment]
Hey @freekmurze - Yes, if they use 11.0.1 and onward they need to at least symlink mariadb-dump to mysqldump.
