### ISSUE TITLE
s3 File Not Found on backup:list

### ISSUE THREAD

**Issue by blisteringherb** [spatie/laravel-backup#183]
I'm able to run backup:run with no problems, and the files are appropriately saved to both s3 and the local disk, but when running backup:list I get the following error:
```
[League\Flysystem\FileNotFoundException]
File not found at path:
```
Removing "s3" from the monitoring config in laravel-backup.php makes the error disappear, but I need to make sure that backups are being saved to s3 properly.

Is there an additional configuration step that I might be missing?

And here's the first few lines of the stack trace.
```
Exception trace:
 () at /var/www/rogue/releases/20160804135947/vendor/league/flysystem/src/Filesystem.php:389
 League\Flysystem\Filesystem->assertPresent() at /var/www/rogue/releases/20160804135947/vendor/league/flysystem/src/Filesystem.php:298
 League\Flysystem\Filesystem->getTimestamp() at /var/www/rogue/releases/20160804135947/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:222
 Illuminate\Filesystem\FilesystemAdapter->lastModified() at /var/www/rogue/releases/20160804135947/vendor/spatie/laravel-backup/src/BackupDestination/Backup.php:47
 Spatie\Backup\BackupDestination\Backup->date() at /var/www/rogue/releases/20160804135947/vendor/spatie/laravel-backup/src/BackupDestination/BackupCollection.php:25
```

**Comment by freekmurze** [comment]
I can't seem to reproduce this error. Could you try to install the package and use your configuration in a vanilla Laravel installation?

**Comment by freekmurze** [comment]
Reopen if you're still having troubles.
