### ISSUE TITLE
Error while updating "Undefined array key "database_dump_filename_base"

### ISSUE THREAD

**Issue by unnathianalytics** [spatie/laravel-backup#1831]
Getting this error : 

"Undefined array key "database_dump_filename_base"  at vendor\spatie\laravel-backup\src\Config\BackupConfig.php:40"
Please help
Laravel version 11.20
PHP 8.3

**Comment by nikitabuida** [comment]
Well there are plenty of new keys in config so it is better to copy everything from latest version into your backup.php config file.

**Comment by JulianLlanten8** [comment]
In my case I was using Spatie Multitenancy, and I just had to switch. 
`database_dump_filename_base' => 'connection'.`

super easy 🐣♥️.
