### ISSUE TITLE
Vendor doesn't publish

### ISSUE THREAD

**Issue by essteffan** [spatie/laravel-backup#184]
Hello.
I have used the instructions from https://docs.spatie.be/laravel-backup/v3/installation-and-setup
But when i want to publish it doens't create config/laravel-backup.php 

vagrant@homestead:~/Code/laravel_cms$ php artisan vendor:publish --provider="Spatie\Backup\Bac
kupServiceProvider"
Nothing to publish for tag [].

I'm using homeatead

Also i don't have the command php artisan backup:run

Can you advice?

Thanks

**Comment by sebastiandedeyne** [comment]
Since the artisan command is missing, the service provider probably isn't registered, or isn't registered correctly.

https://docs.spatie.be/laravel-backup/v3/installation-and-setup

**Comment by essteffan** [comment]
It is registered, look here: http://screencast.com/t/c6zLG7nuM

Thanks

**Comment by essteffan** [comment]
Really strange: i have use php artisan cache:clear and config:cache and it  worked.

Thanks again
