### ISSUE TITLE
Local Backup Destination Problem

### ISSUE THREAD

**Issue by cihankusmez** [spatie/laravel-backup#185]
Hi,

I'm using version 3.9.0.

And i noticed that backup system creates a folder storage >> laravel-backup But backup folder is empty. I searched backup name and i found files in storage >> app >> http---localhost

How can we solve this problem ?

Thank you.

**Comment by sebastiandedeyne** [comment]
The backup is stored in the folder specified in the config file (in this case `storage/app/http---localhost`).

The `storage/laravel-backup` exists because the package creates some temporary files here to create the backup. I don't really think it's an issue, but maybe a temp folder should be created in the first location instead? Pinging @freekmurze

**Comment by freekmurze** [comment]
This issue will be resolved in `v4` of the package.

**Comment by bhavikshah9** [comment]
Hi @freekmurze,

Fantastic package. Thanks!

However, I am using v4 but still facing the exactly same issue. My backups are stored in "http---localhost" and there is an empty directory "laravel-backup". Can you please help?

**Comment by realcheese** [comment]
Same here. It isn't an issue since I leave the folder alone, just confusing at first.

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.

**Comment by keptdream** [comment]
Had this error on fresh installation. After 30 minutes of trying to figure out what was causing this and giving up twice I have cleared the configuration cache(because of other reasons)... and the error was gone... May be this will be useful for someone :D

**Comment by freekmurze** [comment]
To avoid confusion with real backup folder, the temporary folder that this package will now be named `backup-temp`.
