### ISSUE TITLE
backup:restore not found!

### ISSUE THREAD

**Issue by Tony921x** [spatie/laravel-backup#1850]
Hi.

I get bu database backup everyday on save it on another ftp server.
When I execute this command to restroe my last backup:
php artisan backup:restore --backup=latest

I got this:
 ERROR  Command "backup:restore" is not defined. Did you mean one of these?

Why this happened?
It's my first time using this package, what i did wrong?

**Comment by andreich1980** [comment]
There's no such a command. You should restore the backup manually

**Comment by AshrafBasry** [comment]
Try this package
https://github.com/stefanzweifel/laravel-backup-restore
