### ISSUE TITLE
Environment-Specific Commands

### ISSUE THREAD

**Issue by mansouralex** [spatie/laravel-backup#187]
Hello, 

Thanks for this great package. I have question regarding running the backup commands only in the production enviroment for example? 

Or does Laravel task scheduling offer a way to specify the enviroment ?

**Comment by freekmurze** [comment]
If you only want to schedule the commands in production environment you can just add an `if` statement in `app/Console/Kernel.php`

**Comment by mansouralex** [comment]
@freekmurze Thanks for your reply. 

Yes, that's will make it.
