### ISSUE TITLE
Failed to backup when using the SSL

### ISSUE THREAD

**Issue by pavankumarkatakam** [spatie/laravel-backup#192]
Hi, im using this package since 6 months and its working fine. Now , I have added SSL to my database server after that the laravel backup is getting error with this message

```
Failed to backup because: The dump process failed with exitcode 2 : Misuse of shell builtins : 

mysqldump: Got error: 1045: Access denied for user 'mysqlusername'@'xxxxxxxxxxx' (using password:

YES) when trying to connect
```

Actually my config in the `database.php` has added options arguments as show below

```
'mysql' => array(
        'driver'    => 'mysql',
        'host'      => 'localhost',
        'database'  => 'testDB',
        'username'  => 'root',
        'password'  => 'testPWD',
        'charset'   => 'utf8',
        'collation' => 'utf8_unicode_ci',
        'prefix'    => '',
                    'options'   => array(
                            PDO::MYSQL_ATTR_SSL_KEY    => '/var/www/cert/client-key.pem',
            PDO::MYSQL_ATTR_SSL_CERT    => '/var/www/cert/client-cert.pem',
            PDO::MYSQL_ATTR_SSL_CA    => '/var/www/cert/ca-cert.pem'                
                   ),
    ),

```

laravel application is working and im able to connect and execute queries, my problem is laravel backup is not working.

**Comment by pavankumarkatakam** [comment]
Is there any one?

**Comment by freekmurze** [comment]
The problem is that the actual backup of the db is done by `mysqldump` and not by PHP.  You probably need to pass your `mysqldump` binary the right parameters so that the certificate is used.

My suggestion: try to figure out the right parameters by using the `mysqldump` directly. If our `backup` or `db-dumper` packages needs be changed to support this, I'd gladly accept a pull request.

**Comment by mskenderian** [comment]
http://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_ssl

**Comment by pavankumarkatakam** [comment]
Yeah the command for this is 

```
mysqldump --ssl --ssl-ca=ca-cert.pem --ssl-cert=client-cert.pem  --ssl-key=client-key.pem --verbose -h hostname -u username -p db_name  > db_name.sql
```

ok, i will make PR for this.

**Comment by pavankumarkatakam** [comment]
As this package is using the `--defaults-extra-file` option in `mysqld`, we want to include the ssl options in the temporary file in `MySql.php` like

````
[client]
  host=
  user=
  password=
  port=
  ssl-ca=
  ssl-cert=
  ssl-key

````

**Comment by freekmurze** [comment]
In the latest version of the package `v4` you can now easily [pass through any command line option you](https://docs.spatie.be/laravel-backup/v4/installation-and-setup#dumping-the-database) want.

**Comment by pavankumarkatakam** [comment]
ok
