### ISSUE TITLE
Copying .zip file failed because: Instances of Aws\S3\S3Client cannot be serialized.

### ISSUE THREAD

**Issue by seivad** [spatie/laravel-backup#195]
Hey guys getting this error when putting in S3 under destination disks, the local backup works fine. I'm just trying to do the database only backup too, so it's not a big .zip file.

**Comment by freekmurze** [comment]
I cannot reproduce this in the latest version of the package. Please try to set the package up in a vanilla Laravel app to make sure nothing project specific is causing this error.

Reopen if the problem still occurs.

**Comment by tobz-nz** [comment]
@seivad Did you figure out this problem? I'm getting it at the moment.

**Comment by tobz-nz** [comment]
I'm still having this issue, haven't figured out the problem yet. `local` disk works fine, `s3` disk throws:

```
Starting backup...
Dumping database dovetailx...
Gzipping dovetailx...
Determining files to backup...
Zipping 1 files...
Created zip containing 1 files. Size is 39.18 KB
Copying zip to disk named backup...
Successfully copied zip to disk named backup.
Copying zip failed because: Instances of Aws\S3\S3Client cannot be serialized.
Backup failed because Instances of Aws\S3\S3Client cannot be serialized.
#0 [internal function]: Aws\AwsClient->__sleep()
....
```

Not sure if this is a configuration problem or what. 
My config is pretty much default though. S3 config works as I'm saving other stuff there(via media-library).

Just updated all my dependencies, so have latest laravel-backup, aws-sdk, etc on laravel 5.6

**Comment by tobz-nz** [comment]
Just realized the backup is uploading to S3 fine - success email is sent too.
Then 3 failed emails get sent after that regarding the serialization of `S3Client`

**Comment by lucadegasperi** [comment]
Getting the same issue here, has anyone solved this yet? Disabling notifications makes the backup run smoothly, but it's like running blind.

Here are the relevant packages I'm requiring.

```
"laravel/framework": "5.7.*",
"league/flysystem-aws-s3-v3": "^1.0",
"spatie/laravel-backup": "^6.0",
```

**Comment by lucadegasperi** [comment]
I've found the issue causing the problem to me:
In my `EventServiceProvider.php` I was listening on the `NotificationSent` event. The problem was that the listener was implementing `ShouldQueue` thus creating a problem with serializing the notification. Removing `ShouldQueue` made everything run fine.

**Comment by rubenvanassche** [comment]
@tobz-nz Just tried to backup to an S3 disk and everything worked fine. Do you still have the serialization problem? If so, can you please test this in a vanilla Laravel application? So we can try to find out what goes wrong without side effects.  I will close the issue for now.

**Comment by anroots** [comment]
Same problem, @lucadegasperi's note pinpointed the issue - I had implemented a `NotificationSent` Listener that had `ShouldQueue`. Removed `ShouldQueue` to be able to continue backups.

**Comment by tobz-nz** [comment]
@rubenvanassche Sorry I haven't had a chance to check yet - deadlines on other projects.
I think it was still having problems, but need to confirm. Will do asap.

**Comment by tobz-nz** [comment]
@rubenvanassche Yeah seems to be working without any problems now. 👍

**Comment by Giacomo92** [comment]
Hi, any updates on this?
My notifications does not implement `ShouldQueue`, but I got the error: 
_Backup failed because Instances of Aws\S3\S3Client cannot be serialized._

**Comment by Giacomo92** [comment]
Hi, I still have this problem. I have created a custom notifications that not implements `ShouldQueue`. How can I solve this?
