### ISSUE TITLE
AWS Curl Error 52 intermittently

### ISSUE THREAD

**Issue by sunnyjayjay** [spatie/laravel-backup#198]
I am getting the following from time to time. Any ideas?

Failed to backup  because: An exception occurred while uploading parts to a multipart upload. The following parts had errors:
- Part 234: Error executing "UploadPart" on "; AWS HTTP error: cURL error 52: Empty reply from server

**Comment by Frozire** [comment]
Consistently? We are having the same problem in a couple of our servers - so far we narrowed it down to just being amazon making a faulty response or throwing an internal server error.

**Comment by sunnyjayjay** [comment]
No. Every few days. I suppose it could be that. Is there any setting to help?  For example, if backup fails retry in an hour?

**Comment by freekmurze** [comment]
It think these are just Amazon hickups. Reopen this issue if there is a problem with our code.

**Comment by tihomiro** [comment]
Had this issue reoccurring and since it's a weird Amazon S3 service related issue, I switched from us-east to us-west hosted bucket and everything works normally so far.

Hope this helps someone.

**Comment by joydasolive** [comment]
We are also having it occasionally few times a month. It has to be with Amazon as it works most of the time. Will probably try to use us-west bucket as @tihomiro mentioned as currently on us-east one myself to see if it improves.

**Comment by mtx-z** [comment]
Same issue here on eu-central bucket. App web server also in EU.
