### ISSUE TITLE
Unhealthy backup found

### ISSUE THREAD

**Issue by ddmo** [spatie/laravel-backup#200]
Hi, I've received this error message: Unhealthy backup found for on s3-filesystem: The backup uses 4.92 GB which is more than the allowed 4.88 GB

What's the meaning???
Thanks
Stefano

**Comment by sebastiandedeyne** [comment]
You can specify the maximum amount of storage that should be used for backups in the config file:

https://github.com/spatie/laravel-backup/blob/master/config/laravel-backup.php#L114

This feature exists so you can receive a warning if you've got a limited amount of disk space. To get rid of the warning, either change your backup strategy so it deletes more backups, or simply increase the value of `storageUsedMayNotBeHigherThanMegabytes`.
