### ISSUE TITLE
libmysqlclient.so.16 not found

### ISSUE THREAD

**Issue by silentFred** [spatie/laravel-backup#252]
Hey guys,

I'm trying to use laravel-backup on heroku. I have installed a mysql build pack with all the binaries and specified the path too mysql bin in my connection: 'dump_command_path' => base_path().'/.heroku/vendor/mysql/bin',

It looks like the mysqlbinary cannot find the libmysqlclient.so.16 library.

Any ideas on how to specify the location? its situated one level up and in /lib so i know it's there

Any advice would be appreciated!

**Comment by solarsilk** [comment]
@silentFred did you ever get this to work? how did you do it? I can't seem to get it to dump anything. Tried all kinds of paths, including the one you suggested above. Any help is appreciated. Thanks!
