### ISSUE TITLE
OPTION deprecated

### ISSUE THREAD

**Issue by silentFred** [spatie/laravel-backup#253]
Hey guys, me again...

Is OPTION not a deprecated keyword?

I get the following when trying to run a backup.

mysqldump: Couldn't execute 'SET OPTION SQL_QUOTE_SHOW_CREATE=1': Unknown system
variable 'OPTION' (1193)

**Comment by freekmurze** [comment]
This seems like an error with your specific installation. Reopen if our package is causing this.
