### ISSUE TITLE
not find directory of mysqldump

### ISSUE THREAD

**Issue by NiltonMorais** [spatie/laravel-backup#265]
**My database.php:**
'mysql' => [
            'dump_command_path' => 'C:/Program Files/MySQL/MySQL Server 5.7/bin'

**Error:** Backup failed because The dump process failed with exitcode 1 : General error : 'C:/Program' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

**Comment by freekmurze** [comment]
This has been fixed in the underlying package `spatie/db-dumper`. Run `composer update` to pull in v2.0.1 of that package and try running the backup again.

Reopen if the problem persists.

**Comment by SilvaEngComp** [comment]
how to solve this: 
Backup failed because: The dump process failed with exitcode 1 : General error : '"mysqldump"' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

**Comment by SilvaEngComp** [comment]
I find the solution:

Em seu arquivo config / database.php, editar a configuração de banco de dados mysql e adicione:

'dump' => [
               'dump_binary_path' => 'C:/xampp/mysql/bin/', // only the path, so without `mysqldump` or `pg_dump`
               'use_single_transaction',
               'timeout' => 60 * 5, // 5 minute timeout
            ],
