### ISSUE TITLE
--filename option does nothing?

### ISSUE THREAD

**Issue by HipsterJazzbo** [spatie/laravel-backup#267]
I may just be being dumb, but it seems that the `--filename` option on the `backup:run` command does nothing.

It sets the `$filename` property in `BackupJob`, but then that property is never actually used for anything.

Am I missing something?

(This is the best laravel package that exists on earth btw ❤️ )

**Comment by freekmurze** [comment]
You're right, I'll remove that option soon.

**Comment by freekmurze** [comment]
And thank you for the kind words on this package 😍

**Comment by HipsterJazzbo** [comment]
@freekmurze FWIW, I'd rather have the option and it work. I run backups in a couple different scenarios, and it'd be great to be able to set the filename like that sometimes.

**Comment by freekmurze** [comment]
I'd accept a PR with tests that makes this work again.

**Comment by HipsterJazzbo** [comment]
Sweet. Incoming.
