### ISSUE TITLE
Failed to backup postgresql when DB port isn't 5432

### ISSUE THREAD

**Issue by kamilersz** [spatie/laravel-backup#268]
I can't backup postgresql if the port is not 5432. though I've changed DB_PORT on .env into other value

shown error message
`
Backup failed because The dump process failed with exitcode 1 : General error : pg_dump: [archiver (db)] connection to database "apps" failed: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?
`

**Comment by freekmurze** [comment]
This is fixed in the newly tagged version `4.0.1`

**Comment by perymerdeka** [comment]
how to check version?
