### ISSUE TITLE
Possibility to turn off backup cleanup megabythe threshold

### ISSUE THREAD

**Issue by jaaksarv** [spatie/laravel-backup#271]
I want to keep buckups as defined in my default strategy no matter how many megabytes it takes. It would be nice if there was a way to turn off deleteOldestBackupsWhenUsingMoreMegabytesThan option. Set it to 0 or null. Currently it will delete all backups.

**Comment by freekmurze** [comment]
You can do this by extending `[DefaultStrategy](https://github.com/spatie/laravel-backup/blob/master/src/Tasks/Cleanup/Strategies/DefaultStrategy.php)` and overriding `removeOldBackupsUntilUsingLessThanMaximumStorage` with an empty function.

Don't forget to put your custom Strategy classname in the config-file.
