### ISSUE TITLE
Failed installation using PHP7 and Laravel 5.1.44

### ISSUE THREAD

**Issue by Bobeta** [spatie/laravel-backup#272]
Running composer require spatie/laravel-backup using PHP7 and Laravel 5.1.44 ends up in this error for me:

 ```
 Problem 1
    - spatie/laravel-backup 4.0.1 requires illuminate/console ~5.3.8 -> satisfiable by illuminate/console[5.3.x-dev] but these conflict with your requirements or minimum-stability.
    - spatie/laravel-backup 4.0.0 requires illuminate/console ~5.3.8 -> satisfiable by illuminate/console[5.3.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for spatie/laravel-backup ^4.0 -> satisfiable by spatie/laravel-backup[4.0.0, 4.0.1].
```

Should I manually specify that it should use v3x?

**Comment by freekmurze** [comment]
I thought that composer could automatically pick the right version. Guess I was wrong.

The right command to install v3 is 

```bash
composer require "spatie/laravel-backup:^3.0.0"
```

I'll update this in the docs.

**Comment by Bobeta** [comment]
Yeah I thought so to, but it didn't work for me in this case. Worked fine adding it manually like you described. Thanks!
