### ISSUE TITLE
Exception thrown when trying to monitor backups

### ISSUE THREAD

**Issue by kfirba** [spatie/laravel-backup#274]
Hey.

I've just installed the package (V4) and tried playing with it for a bit.

# The Happy Path :smile:

<small>**Assumption: There are already few backups available**</small>

When I run `php artisan backup:monitor` I get the message that the backups are considered healthy/unhealthy and then an exception:

```
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Spatie\Backup\Tasks\Monitor\BackupDestinationStatus::getBackupDestination()
```

The fix is rather easy, seems like someone forgot to change the method call in `Spatie\Backup\Notifications\BaseNotification` on line 64:

```
// from:
return $this->event->backupDestinationStatus->getBackupDestination();

// to:
return $this->event->backupDestinationStatus->backupDestination();
```

However, unfortunately, this isn't all. Now when trying to run the monitor command I get the error:

```
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Return value of Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::toMail() m
  ust be an instance of Illuminate\Notifications\Messages\SlackMessage, instance of Illuminate\Notificati
  ons\Messages\MailMessage returned
```

I then took a look at `Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound` and found out that there is a mistake where someone who type-hinted the return type of the method `toMail` had type-hinted it to `SlackMessage` instead of `MailMessage`. To fix this we only need to fix the type-hinted return type:

```
// from:
public function toMail(): SlackMessage

// to:
public function toMail(): MailMessage
```

Now the errors are fixed and the notification will be triggered. I can see that the tests are WIP. Hopefully you add some tests to catch those tiny mistakes.

# The Sad Path :cry:

<small>**Assumption: There are no backups available**</small>

When trying to run the monitor command when there are no backups at all, the `UnhealthyBackupWasFound` event is fired. 

When the event is trying to build its problem description, it for some reason doesn't detect the fact that there are no backups yet. The reason is that for some reason someone negated the conditional on line 50:

```
// current:
if (! $backupStatus->amountOfBackups() === 0) {

// should be:
if ($backupStatus->amountOfBackups() === 0) {
```

The issue was that the above `if` statement returns a false positive just by accidentally adding the *!*. What happened then is it would fail on the condition on line 58:

```
if ($backupStatus->newestBackupIsTooOld()) {
```

Since the `newestBackupIsTooOld` method is also checking to see if there are backups and if there are none, it returns `true`.

The issue really lies here:

```
return "The latest backup made on {$backupStatus->dateOfNewestBackup()->format('Y/m/d h:i:s')} is considered too old.";
```

The problem with the method `newestBackupIsTooOld` returning `true` is that it then tries to build the description and calling the method `dateOfNewestBackup` which returns `null` since there are no backups. Then it tries to call the `format()` method on that returned `null` and hence generating the exception we saw earlier.

As mentioned before, the fix is to catch the proper error before it reaches the `newestBackupIsTooOld` check by fixing the negation of the conditional:

```
// from:
if (! $backupStatus->amountOfBackups() === 0) {

// to:
if ($backupStatus->amountOfBackups() === 0) {
```

Well, that's all. Let me know if you want me to make a pull request or you just want to add those fixes yourself.

P.S. I must ask, what is this `Postcardware` policy :sweat_smile:? Wonder if I can send something else instead as I've never sent a physical postcard before :hushed:

**Comment by kfirba** [comment]
PR was merged. Closing this.

**Comment by freekmurze** [comment]
Thanks again for your PR.

Instead of a postcard, we'd also accept a handwritten letter 😃
