### ISSUE TITLE
local.ERROR:  backups

### ISSUE THREAD

**Issue by alinasiri1367** [spatie/laravel-backup#276]
I am use this package but happening this error:
`local.ERROR:  backups : error: Failed to backup  because: The Process class relies on proc_open, which is not available on your PHP installation. `

I am use laravel 5.1 on linux server (directadmin).
` 'mysql' => [
	        'dump_command_path' =>'/usr/bin/',
            'driver'    => 'mysql',`

**Comment by freekmurze** [comment]
Under the hood the `db-dumper` package it used. That one uses [Symfony's process component](http://symfony.com/doc/current/components/process.html) to call `mysqldump`.

Like the error message says you need `proc_open` in your PHP installation.

**Comment by alinasiri1367** [comment]
How can I install it myself?
