### ISSUE TITLE
Slack notifications not working

### ISSUE THREAD

**Issue by lamberttraccard** [spatie/laravel-backup#283]
I did everything the documentation says, but the slack notifications doesn't send.
Any help ? 
Thanks.

**Comment by whereisjefe** [comment]
Figured i would add this for those of you that find yourself here (like me)

I had this same issue and for me it was cause i missed the setup...  by default the package has the notifications set like
``` php
\Spatie\Backup\Notifications\Notifications\BackupHasFailed::class => ['mail'],
```

what you need to do is slack to the array `['mail', 'slack'],`

hopefully someone will find this helpful :D
