### ISSUE TITLE
Misuse of shell builtin

### ISSUE THREAD

**Issue by longestdrive** [spatie/laravel-backup#285]
Hi

I've tried running the back up from the command line before I set up the tasks etc and have the same issue identified here: [Misuse of shell builtins. #92](https://github.com/spatie/laravel-backup/issues/92)

I've followed the steps within the thread and can confirm from the command line I can run mysqldump

I've added path to bin in the database config

So far the problem remains.

I am using version 3 php version 5.6 and mysql 5.6

What other steps can I check please

**Comment by freekmurze** [comment]
Is your php cli process able to execute mysqldump. You can check this by using the `exec` statement in a php script that you'll need to run in your command line.

**Comment by longestdrive** [comment]
Hi, I am able to run mysqldump direct from the command line. I will though try it again through a php script as suggested

**Comment by longestdrive** [comment]
ok eventualy got round to running via a php script as follows:

`$toDay = 'storage/test/'.date('d-m-Y-H-i-s');
$dbhost = 'localhost';
$dbuser = 'xxx';
$dbpass = 'xxx';
$dbname = 'xxx';

exec("mysqldump --user=$dbuser --password='$dbpass' --host=$dbhost $dbname > ".$toDay.".sql");`

this worked successfully

anything else I can test?

**Comment by longestdrive** [comment]
doh! resolved - the backup included two databases - after going back to basics I had one character out on the password on the second database and voila!
Thanks for the help
