### ISSUE TITLE
Authentication required

### ISSUE THREAD

**Issue by munkhorgil** [spatie/laravel-backup#286]
When I try to backup following error shows up.

Copying .zip file failed because: Could not connect to disk backups because the disk is not set..
Laravel-backup notifier failed because Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required

**Comment by icodebuster** [comment]
@munkhorgil I am getting the same issue, could you please share steps to fix this issue.

Thank you.

**Comment by kentsigurdsen** [comment]
What did you do to fix this?

**Comment by BirdyUK** [comment]
I am getting the same issue, I think this could be to do with the event's im going to look into it now. Could someone else shed some light on this?

**Comment by kentsigurdsen** [comment]
Hello!

For me this got solved by just having a SMTP server configured. :)

**Comment by BirdyUK** [comment]
@kentsigurdsen - Same here mate though i dont understand why so many people have an issue with SES because why has this not been fixed in laravel if there is a general issue with SES connections, So maybe it depends on your region, Mine is eu-west-1 is yours by any chance?

**Comment by munkhorgil** [comment]
I opened this issue in October 2016.Unfortunately, I couldn't solve and then closed issue. Anyway you guys found the solution thanks!

**Comment by christiantigre** [comment]
Yo configure el envío de correo y me soluciono ese error, luego me dio el siguiente error ssl y lo resolvi gracias a este link http://www.derekbliss.com/post/laravel-streamsocketenablecrypto-ssl-operation-failed-with-code-1

**Comment by karrarkazuya** [comment]
Sometimes the problem is as simple as forgetting to set the disk required in the backup.php

**Comment by doncadavona** [comment]
Solved mine by setting up my SMTP server. Used https://mailtrap.io.

**Comment by mehdimahanfar** [comment]
I use Laravel offline and I can not and do not need to be notified by email. For this type of case, you can empty your settings so that you do not encounter SMPT error and its obstacles.

` 'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class => [],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => [],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class => [],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class => [],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class => [],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class => [],
        ],`
