### ISSUE TITLE
`./artisan backup:list` cannot see remote files

### ISSUE THREAD

**Issue by hydrarulz** [spatie/laravel-backup#287]
Running 
`./artisan backup:run` works completely, it creates the archive and it uploads it on the FTP server.

However
`./artisan backup:list` has this output

```
❯ ./artisan backup:list                                                                                                                                                                5s 104ms
+----------------------+-------+-----------+---------+--------------+--------------------+--------------+
| Name                 | Disk  | Reachable | Healthy | # of backups | Newest backup      | Used storage |
+----------------------+-------+-----------+---------+--------------+--------------------+--------------+
| http---homestead.app | local | ✅         | ❌       | 0            | No backups present | 0 KB         |
+----------------------+-------+-----------+---------+--------------+--------------------+--------------+
```

Backups are in there but the cannot be listed (?)

I am running 
```
❯ ./artisan --version                                                                                                                                                                     12:18
Laravel Framework version 5.3.18
```
and
```
"spatie/laravel-backup": "^4.0"
```

BTW just saw your talk on laracon-eu about backups

**Comment by freekmurze** [comment]
The `list` command uses the `monitorBackups` key of the config file.

Did you add the name of the disk in the [`monitorBackups.disks` key](https://github.com/spatie/laravel-backup/blob/master/config/laravel-backup.php#L102)?

Hope you enjoyed the talk 😄

**Comment by hydrarulz** [comment]
That seemed to be the problem, thanks.

I really liked the talk, it was interesting finding out more things about your company and its philosophy.
