### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by amosmos** [spatie/laravel-backup#288]
The docs state the package require Laravel 5.3.x but when installing with composer I'm required to have at least 5.3.8 (since some of the required illuminate packages in composer.json ask for 5.3.8).

(Or am I missing something)

**Comment by freekmurze** [comment]
The `composer.json`is the source of truth regarding minimum requirements. If you're on a lower point release of L5.3, upgrading to the latest version is just a `composer update` away.

**Comment by amosmos** [comment]
Thanks. I'm always afraid the compose update would break something in my app, because of a breaking change to the laravel framework source code, or any other package. But I did it and it seems to work smoothly.

Still would suggest to update the docs... Just my 2 cents.

Thanks for this awesome package and all the other one you made!!
