### ISSUE TITLE
Change 'Application name' without changing Laravel's actual application name

### ISSUE THREAD

**Issue by NicolasVanhecke** [spatie/laravel-backup#291]
Is it possible to change the 'Application name' sent in the emails (succes or failed)? This without changing the Application name for laravel itself!  
  
I have found you can manually change it in the vendor/spatie directory, but that is probably not best practice..

![spatiabackup](https://cloud.githubusercontent.com/assets/9153781/19517927/5b8a80e4-9604-11e6-962f-0cc959f05ac9.jpg)

**Comment by ninthspace** [comment]
According to the Laravel docs, the purpose of the 'name' attribute in config/app.php is for notification. So I think you should change it in config/app.php accordingly.

**Comment by NicolasVanhecke** [comment]
Hmm, I can agree with that best practice, but I kind of like it that I always can include with 'app/...'.
But I have alot of code snippets that have shortcuts so I am able to setup a basic controller/model/... in practically 2 seconds. Changing the namespace would break that flow.

**Comment by ninthspace** [comment]
I think you're confusing the application's namespace with the application's name. The name is just a string you can change. For example, I have a name attribute in config/app.php like this which is built from two environment settings:

```php
'name' => env('APP_DOMAIN').'-'.env('APP_ENV'),
```

And in the same application the namespace is set in composer.json, e.g. (excerpted):

```json
"psr-4": {
  "App\\": "app/"
},
```

**Comment by freekmurze** [comment]
Like @ninthspace already mentioned you can change the value in the `name` key of `config/app.php`
