### ISSUE TITLE
Email error after zip to disk

### ISSUE THREAD

**Issue by michelveloso** [spatie/laravel-backup#294]
After zip to disk, I get a error like bellow: 

> PHP Fatal error:  Uncaught Error: Call to undefined function Tylercd100\Monolog\                                                                       Handler\curl_init() in /var/www/laravel/vendor/tylercd100/monolog-mailgun/src/Ha                                                                       ndler/MailgunHandler.php:50

![image](https://cloud.githubusercontent.com/assets/346317/19533335/0c1f8378-961e-11e6-9125-0efe460c620f.png)

**Comment by freekmurze** [comment]
It seems like this has something to do with how you configured the mail driver in your app.

Are you able to send out mails?

**Comment by michelveloso** [comment]
@freekmurze , thanks for your quick answer.

I use[ Laravel's Mail](https://laravel.com/docs/5.3/mail) with success.

Do you think I need a extra configuration?

![image](https://cloud.githubusercontent.com/assets/346317/19534013/db13b2a6-9620-11e6-929a-07143b20b35f.png)

Regards

**Comment by freekmurze** [comment]
Could you post the entire stack trace so we can see where the exception is originating?

**Comment by michelveloso** [comment]
Of course ;)

![image](https://cloud.githubusercontent.com/assets/346317/19536244/e210be7e-9629-11e6-910f-f61b81c44c8f.png)

**Comment by michelveloso** [comment]
@freekmurze I found the problem! 
I was the PHP7 curl extesion.

Thanks for you help ;)
