### ISSUE TITLE
Backup failed

### ISSUE THREAD

**Issue by Takhir** [spatie/laravel-backup#297]
Hello!
Help me please!
I have error, if some user, but not root
**Backup failed because ZipArchive::close(): Can't open file: Permission denied.**
I don't understand, where exactly you need the permissions of the directory.
on what kind of directory

**Comment by alexanderpostma** [comment]
Hello,

I also ran into this issue, and fixed it by replacing base_path() with an absolute path.
**from**:
```
'source' => [
            'files' => [
                /*
                 * The list of directories and files that will be included in the backup.
                 */
                'include' => [
                   base_path( 'to/backup')',
                ],
```
**to**:
```
'source' => [
            'files' => [
                /*
                 * The list of directories and files that will be included in the backup.
                 */
                'include' => [
                    '/home/user/folder/to/backup',
                ],
```

Does this by any chance resolve your issue?

**Comment by JonathanMH** [comment]
Hello Takhir,

I'm just another user but can you check the permissions of your directory `storage/app`?

**Comment by tcsehv** [comment]
make sure you're not backing any session files

**Comment by alexanderpostma** [comment]
Hi Takhir,

When i had this problem, there was one small file in some folder that had the wrong permissions. Try checking the permissions of every file or give every file in the backup folder the same permissions.

**Comment by freekmurze** [comment]
I suspect that this issue is indeed related to wrong permissions. If not, reopen this issue.

**Comment by saidbakr** [comment]
In my case backup works fine from the terminal `php artisan backup:run`. However, when I try to execute this command using PHP `passthru` or `exec`, I have got the permission error:
Backup failed because: mkdir(): Permission denied.


```
$command = 'cd '.base_path().'; /usr/local/bin/php artisan backup:run';
passthru($command);
// another try
$command = 'cd '.base_path().'; php artisan backup:run';
 echo  exec($command);
```
I also changed permissions of disks places to be writable by others but I could not able to get ride of this issue. the following is the full code:

```
$command = 'cd '.base_path().'; /usr/local/bin/php artisan backup:run';// > '.base_path().'/public/backuplog.txt 2>&1 &';
        try{
            passthru('whoami');
            echo "<br>";
            passthru($command);
            echo "<br>";
            echo $command."<br>";
            $command = 'cd '.base_path().'; php artisan backup:run';
           echo  exec($command);
           //$p = \Artisan::call('backup:run');
        }
        catch(\Exception $e){
            return $e;
        }
```
The output looks like:
```
www-data 
Starting backup... Backup failed because: mkdir(): Permission denied. 
cd /xxxx/some/path; /usr/local/bin/php artisan backup:run
Backup failed because: mkdir(): Permission denied.
```
I believe that there something is made in a directory which is not writable by the www-data user

**Comment by saidbakr** [comment]
It seems that the problem in `storage/app/laravel-backup` directory permission which has no write permissions for the user `www-data`.

It is used in line 118 @ BackupJob.php for `run` method. It will be better to make the exception through some info about the directory that mkdir failed to create.

**Comment by ilkermutlu** [comment]
@saidbakr I've come across this problem before. In my case, the permissions of the `backup-temp` directory under `storage/app` was problematic.

What I did was changing permissions to `some_ssh_user:www-data`. `some_ssh_user` exists in the `www-data` group as well.

Hope this sheds some light.

**Comment by Kamleshpaul** [comment]
@ilkermutlu  i give the permission `some_ssh_user:www-data` and `777` to `backup-temp` still same issue

**Comment by r0073rr0r** [comment]
> @ilkermutlu i give the permission `some_ssh_user:www-data` and `777` to `backup-temp` still same issue
same problem here, i also add my ssh_user to group www-data, and also same issue.

**Comment by Kamleshpaul** [comment]
@ilkermutlu  i solve my isse by checking what r the file include in backup if it try to take backup with  blongs to root user then it failed

**Comment by khbtechservices** [comment]
I had this issue as well; it was indeed a file permission issue.  I found the culprit file by running `find . ! -perm -g+r`.

**Comment by SPL3S** [comment]
@khbtechservices your tip helped me to find which files prevent the backup run, and indeed I found roundcube temp files blocking the backup

**Comment by DrAliRagab** [comment]
> I had this issue as well; it was indeed a file permission issue. I found the culprit file by running `find . ! -perm -g+r`.

Great
