### ISSUE TITLE
Help - Multiple backup configurations

### ISSUE THREAD

**Issue by watzing** [spatie/laravel-backup#299]
Hi all,

I'd like to separate db and file backups. For example I would like to backup the database daily and keep a long history (default settings). With files however, I'd only like to keep a couple backups which happen less frequently. I couldn't find anything like this docs apart from the --only-files operation, but I don't think that will quite do what I need it to do.

Has anyone found the need to do this and how did you overcome it? 

Cheers,
Dylan

**Comment by freekmurze** [comment]
Currently the package does not handle multiple configurations for backing up. 

You can however customize the cleaning strategy. The `Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy` is responsible for deleting old backups. You can set your own class that does the cleanup in the config file.

I'm assuming that the full backups will be much larger than the db backups. Your custom cleanup class could for example delete larger zips earlier than smaller ones.

**Comment by vesper8** [comment]
I too would like to be able to keep databases separate from files.. database tend to be a fraction of the size of the files... and its value tends to be a lot more precious. So I too would like to backup db much more often then everything else. Hopefully you can add something like this in the future.

Multiple configurations are not even needed.. I'd be happy with a simple option to "split files with db".. so create two zips everytime instead of one

**Comment by freekmurze** [comment]
> Multiple configurations are not even needed.. I'd be happy with a simple option to "split files with db".. so create two zips everytime instead of one

That's easy 😄   Just schedule two backup jobs: one that only backups the db, and another one that backups the files (that could run less frequently)

**Comment by rorymcdaniel** [comment]
> That's easy :smile: Just schedule two backup jobs: one that only backups the db, and another one that backups the files (that could run less frequently)
@freekmurze This is exactly what I'd like to do, but I'll admit I'm not sure how to do this. How do I schedule one backup that is database only and another that is all files?

**Comment by freekmurze** [comment]
Here's an example to put in your console kernel.

```php
    /**
     * Define the application's command schedule.
     *
     * @param \Illuminate\Console\Scheduling\Schedule $schedule
     */
    protected function schedule(Schedule $schedule)
    {
        $schedule->command(\Spatie\Backup\Commands\BackupCommand::class)->dailyAt('03:00');
        $schedule->command(\Spatie\Backup\Commands\BackupCommand::class, ['--only-db'])->hourly();
    }
```

**Comment by justRau** [comment]
Given you are doing backups using two Scheduler commands as Freek showed, and backing up database and files to separate disks...

```php
$schedule->command('backup:run --only-db --only-to-disk=r2-backup-database')->cron('1 * * * *')->runInBackground();
$schedule->command('backup:run --only-files --only-to-disk=r2-backup-files')->dailyAt('01:00')->runInBackground();
```

...here's how you could have different cleanup strategies (a.k.a. retention) for database and files:

```php
<?php

namespace App\Service\Backup;

use Illuminate\Support\Collection;
use Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy;

class DifferentiatedStrategy extends DefaultStrategy
{
    protected function calculateDateRanges(): Collection
    {
        if ($this->backupDestination->diskName() === 'r2-backup-database') {
            $this->config->set('backup.cleanup.default_strategy.keep_all_backups_for_days', 14);
            $this->config->set('backup.cleanup.default_strategy.keep_daily_backups_for_days', 30);
            $this->config->set('backup.cleanup.default_strategy.keep_weekly_backups_for_weeks', 52);
            $this->config->set('backup.cleanup.default_strategy.keep_monthly_backups_for_months', 24);
            $this->config->set('backup.cleanup.default_strategy.keep_yearly_backups_for_years', 10);
        }

        if ($this->backupDestination->diskName() === 'r2-backup-files') {
            $this->config->set('backup.cleanup.default_strategy.keep_all_backups_for_days', 1);
            $this->config->set('backup.cleanup.default_strategy.keep_daily_backups_for_days', 14);
            $this->config->set('backup.cleanup.default_strategy.keep_weekly_backups_for_weeks', 4);
            $this->config->set('backup.cleanup.default_strategy.keep_monthly_backups_for_months', 12);
            $this->config->set('backup.cleanup.default_strategy.keep_yearly_backups_for_years', 10);
        }

        return parent::calculateDateRanges();
    }
}
```

**Comment by ahmad-moussawi** [comment]
I have a similar case: I want to backup important tables frequently (every 3 hours) while backup low-priority with large data tables less frequently (every week).
It would be great if we have something like `backup:run --profile=important` with the ability to override the profile config
