### ISSUE TITLE
Is there a way to add entry to database in table backups ?

### ISSUE THREAD

**Issue by minedun6** [spatie/laravel-backup#301]
Is there a way to along with creating the backup, I want to create a record in my database in which I can store history of my backups ? and then delete them when there are removed due to them being old backups. My idea was to tackle this through out custom eventlisteners and listening to the events ?
Last but not least, is there a way to exclude "/vendor" and "/node_module" ....

**Comment by freekmurze** [comment]
Currently the `CleanupWasSuccessful` doesn't contain any info on which backups were deleted.  I'd accept a fully tested PR for that if the code for achieving this stays simple.

You can specify which files and folders in the config file.

**Comment by minedun6** [comment]
No answers for the other 2 questions

**Comment by freekmurze** [comment]
>Is there a way to along with creating the backup, I want to create a record in my database in > which I can store history of my backups ?

Yes, use the backup events for this: https://docs.spatie.be/laravel-backup/v4/taking-backups/events

> and then delete them when there are removed due to them being old backups

see previous answer: there is an event that runs after the clean up, but right now it doesn't contain which backups have been cleaned. 

> Last but not least, is there a way to exclude "/vendor" and "/node_module" ....

see previous answer.
