### ISSUE TITLE
Two files but the same

### ISSUE THREAD

**Issue by minedun6** [spatie/laravel-backup#302]
I just successfully update my backup to dropbox but the thing is I get two files instead of one.
The first file is - `http---invoice.app` , this is a directory which contains the actual zip but then again there is a second zip file within the root of my files which have the same names so why is that and can I prevent such behaviour ?

**Comment by minedun6** [comment]
hello, anybody got an answer ?

**Comment by bbashy** [comment]
Dropbox has a backup.zip in the root of your account?
