### ISSUE TITLE
No backups present on v3.10.2

### ISSUE THREAD

**Issue by kyranb** [spatie/laravel-backup#304]
I'm having trouble monitoring and verifying the health or presence of backups. 

Using laravel-backup v3.10.2 and Laravel v5.2.42 on PHP 7.0.4

running `php artisan backup:list`

shows:

```
+--------------------+-------+-----------+---------+--------------+--------------------+--------------+
| Name               | Disk  | Reachable | Healthy | # of backups | Youngest backup    | Used storage |
+--------------------+-------+-----------+---------+--------------+--------------------+--------------+
| https---app.com    | local | ✅        | ❌       | 0            | No backups present | 0 KB         |
+--------------------+-------+-----------+---------+--------------+--------------------+--------------+
```

the destination is set to local

```
'destination' => [

            /*
             * The disk names on which the backups will be stored.
             */
            'disks' => [
                'local'
            ],
        ],
```

and `app.com/storage/app/app-backups` shows a bunch of zip files generated from this package:

```
2016-04-05-172052.zip  2016-09-11-070002.zip  2016-10-11-070001.zip  2016-10-16-070002.zip  2016-10-22-070002.zip  2016-10-29-070002.zip
2016-08-14-070002.zip  2016-09-18-070002.zip  2016-10-12-070002.zip  2016-10-17-070002.zip  2016-10-23-070003.zip  2016-11-01-070002.zip
2016-08-21-070002.zip  2016-09-25-070001.zip  2016-10-13-070001.zip  2016-10-18-070002.zip  2016-10-24-070003.zip  2016-11-02-070003.zip
2016-08-28-070001.zip  2016-10-02-070002.zip  2016-10-14-070002.zip  2016-10-19-070002.zip  2016-10-25-070002.zip  2016-11-03-070002.zip
2016-09-04-070002.zip  2016-10-09-070003.zip  2016-10-15-070001.zip  2016-10-21-070002.zip  2016-10-28-070003.zip  2016-11-03-225519.zip
```

**Comment by anchepiece** [comment]
Just a quick question, do you have a folder like "storage/app/https---app.com"
In the latest version I am seeing backups placed in that folder, based on the app name.

**Comment by kyranb** [comment]
Yes, as above the `/storage/app/app-backups` contains backups, however `php artisan backup:list` is showing `No backups present`.

**Comment by sevmardi** [comment]
same here. Any ideas so far?

**Comment by sebastiandedeyne** [comment]
Is anyone still having this issue?

**Comment by kyranb** [comment]
Yes, still haven't figured out what the cause is.

**Comment by jfvoliveira** [comment]
I was having the same problem but my issue was the monitorBackups[ 'disks' ] in the config file was different that the destination['disks'].

**Comment by freekmurze** [comment]
Closing this because we won't actively support v3 anymore.

A good PR that fixes this, will most probably still be accepted though.
