### ISSUE TITLE
Mail not working with extra notification channel

### ISSUE THREAD

**Issue by lowerends** [spatie/laravel-backup#306]
I added an extra notification channel for HipChat, following the description at https://docs.spatie.be/laravel-backup/v4/sending-notifications/adding-extra-notification-channels. 

When I configure the notifications like this:
```\Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class   => ['mail'],```
I get an email on successful backup.

However, when configuring the notifications like this:
```\App\Notifications\BackupWasSuccessful::class => ['mail', HipChatChannel::class],```
no emails are sent but I do get notifications in HipChat.

What could be causing this?

**Comment by sebastiandedeyne** [comment]
Hi @lowerends, sorry for the late response, are you still having this issue?

Gonna close this for now since it's been a while, but feel free to reopen if necessary!

**Comment by lowerends** [comment]
Hi @sebastiandedeyne, actually I am still having this issue. I'll make some time in the coming weeks to investigate further and provide more info, so it would be great if you could reopen this issue.

**Comment by chrisrenga** [comment]
Hi @lowerends, I have just finished testing it with a custom and the HipChat channel. Everything seems to be working fine. I am getting both the email and HipChat notification

I am using laravel 5.5 and the latest package versions:

```json
        "laravel-notification-channels/hipchat": "^1.0",
        "laravel/framework": "5.5.*",
        "spatie/laravel-backup": "^5.0",
```

**Comment by introwit** [comment]
Hi @lowerends are you still facing this issue? If yes, have you registered the notifiable in the config file? Docs about it are [here](https://docs.spatie.be/laravel-backup/v5/sending-notifications/customizing-the-notifiable). Let us know how it goes :)

**Comment by freekmurze** [comment]
Closing this for now, reopen if this is still an issue.
