### ISSUE TITLE
 Failed to backup because: HTTP status 500

### ISSUE THREAD

**Issue by mansouralex** [spatie/laravel-backup#309]
I had 2 errors just happened 1 time since few months from having the package in place.

1) error: Failed to backup  because: HTTP status 500
{"error": "The server has either erred or is incapable of performing the requested operation."}

2) error: Failed to cleanup the backup because: HTTP status 500
{"api_error": true, "user_error": "An unexpected error has occured. Please try again later.", "error": "An unexpected error has occured.  Please try again later."}

What could be the reason ?

Thanks.

**Comment by freekmurze** [comment]
Could you provide more details to track down the cause of the issue? To which filesystem are you backing things up?

**Comment by mansouralex** [comment]
@freekmurze both local & dropbox

**Comment by freekmurze** [comment]
Do you know if the problem is related to local or dropbox? (I'm guessing Dropbox)

**Comment by mansouralex** [comment]
@freekmurze The first error should be related to both local and dropbox since it has two occurrences in RollBar.

The other error has only 1 occurrence which seems to be dropbox related since the error has api_error.

**Comment by freekmurze** [comment]
There's too little information for me to go on to determine a specific cause. Try to get as much info about the error as you can. I assume there has to be a stack trace somewhere pointing to the exact line of code that is causing the error.
