### ISSUE TITLE
Unexpected ':', expecting '{' in spatie/laravel-backup/src/Helpers/functions.php on line 5

### ISSUE THREAD

**Issue by guncebektas** [spatie/laravel-backup#310]
Package is great and working in my local but on server it throws an error "Unexpected ':', expecting '{' in spatie/laravel-backup/src/Helpers/functions.php on line 5"

**Comment by freekmurze** [comment]
You probably aren't running PHP 7 on your server.

**Comment by arbabi2010** [comment]
@freekmurze I have same problem.  my php version is 7.2 on centos7 server

**Comment by freekmurze** [comment]
Providing help on how to upgrade PHP on your server is out of scope for this issue tracker. Please Google a bit around for specific instructions for your environment.
