### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by oriceon** [spatie/laravel-backup#311]
Any chance to work on Windows?

**Comment by freekmurze** [comment]
I don't really support windows, but for basis use cases I think the package will just work.

**Comment by oriceon** [comment]
Nop, is not workin, i`m trying to figure what to do. As i`ve seen, in createFromConnection() should specify setDumpBinaryPath. Then, in dumpToFile() the getDumpCommand doesn`t know to read temporary file with credentials..
