### ISSUE TITLE
Dump with routines on MYSQL

### ISSUE THREAD

**Issue by rafwell** [spatie/laravel-backup#314]
Hi, using mysql i need put `--routines` as parameter for `mysqldump`. I've tried using this on the mysql connection at `app/database.php` but not work.
`    'dump' => [
                'add_extra_option' => '--routines'
            ]
`

I've created a PR to solve issue: https://github.com/spatie/laravel-backup/pull/315

**Comment by freekmurze** [comment]
v4 of the package can do this out of the box.
