### ISSUE TITLE
dump_command_path or dump_binary_path

### ISSUE THREAD

**Issue by semmais** [spatie/laravel-backup#316]
@ [`docs](https://docs.spatie.be/laravel-backup/v4/installation-and-setup#dumping-the-database)
refer the dump "dump_command_path" but i think it must be 'dump_binary_path'

like
`
'mysql' => [
...
            'dump' => [
               'dump_binary_path' => '/Applications/MAMP/Library/bin/', 
            ], 
`

setDumpBinaryPath exists at DbDumper

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention. `dump_binary_path` is the right value. I've correct this in the docs.
