### ISSUE TITLE
App storage never included in file backup

### ISSUE THREAD

**Issue by joevallender** [spatie/laravel-backup#320]
Hi, I'm having a bit of trouble getting file backups to work. I'm using v4 on Laravel 5.3 in Homestead

My intention is to back up user uploaded files from storage/app, without any existing backups.

I initially tried using storage path as the include, and trying to exclude the sub-paths.

```php
'include' => [
    storage_path(),
],
```

However, when I wasn't getting what I wanted I tried this include with no excludes

```php
'include' => [
    base_path(),
],
```

And the storage/app folder was missing from the resulting zip.

Any ideas? Thanks :)

I think perhaps I've misunderstood the

**Comment by freekmurze** [comment]
The package will automatically exclude the directory where the backups are stored. Where are your backups stored?

**Comment by joevallender** [comment]
Hi, thanks for the reply! In the default folder, a subfolder of storage/app

But its excluding the whole storage/app folder

**Comment by joevallender** [comment]
I would actually prefer to write the backups in an entirely different directory, but I couldn't see that as an option

**Comment by freekmurze** [comment]
The `disks` key in the `laravel-backup` configuration file refers to the name of a disk that has been setup in the `filesystems` config file. You can modify that path of the disk in that file.

**Comment by joevallender** [comment]
That's working perfectly Freek, thanks. 

I've now got an extra local disk in filesytems reading  `env('BACKUP_PATH')` to point to a test folder in Homestead, and the appropriate NAS mount when in production. Good solution, thanks for the advice.

**Comment by freekmurze** [comment]
👍  Np, have fun using the package.
