### ISSUE TITLE
"Metadata can't be parsed"  and  "There is no notification class"

### ISSUE THREAD

**Issue by scasic** [spatie/laravel-backup#323]
Using latest version of package. Still cannot perform successful backup. Currently there are two errors occur during backup:

> Starting backup...
> Dumping database weneda...
> Determining files to backup...
> Zipping 3458 files...
> Created zip containing 3458 files. Size is 743.87 MB
> Copying zip to disk named backup...
**> Copying zip failed because: Metadata can't be parsed from item 'ftpd: http---localhost/2016-12-07-23-19-51.zip: No such file or directory.' , not enough parts..**
**> Backup failed because There is no notification class that can handle event `Spatie\Backup\Events\BackupHasFailed`..**

**Comment by freekmurze** [comment]
Regarding the error concerning `Spatie\Backup\Events\BackupHasFailed` take a look at #322
