### ISSUE TITLE
Can't save storage/app folder

### ISSUE THREAD

**Issue by resethread** [spatie/laravel-backup#327]
Hi, 
I 'm trying your package, it's awesome but I meet a little problem: 
I can't save the folder app in storage.
What should I do to fix it ?
Thanks :)

Edit: I've not read the same issue before post.

**Comment by freekmurze** [comment]
I don't know if I understand your question correctly, but you can specify the destination of a backup by creating a disk in `config/filesystems.php` first and specifying the name of the disk in the `disks` key of `config/laravel-backup.php`
