### ISSUE TITLE
No commands defined in the "backup" 

### ISSUE THREAD

**Issue by munkhorgil** [spatie/laravel-backup#329]
When I try to backup I got following error in Laravel 5.3

`[Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "backup" namespace. `

I installed according to documentation. Why I got his error ?

**Comment by freekmurze** [comment]
Did you install the service provider?

**Comment by munkhorgil** [comment]
Yep, I put this `Spatie\Backup\BackupServiceProvider::class,` to service providers

**Comment by freekmurze** [comment]
could you put a `dd` statement inside the boot method of that class to see if it is actually being registered?

**Comment by munkhorgil** [comment]
@freekmurze Thanks for your help

I've just solved this when I publish it returns Nothing to publish for tag []. Thus I cleaned config cache as follows
```
php artisan config:cache
```
As a result successfully published and I got list of backup commands in php artisan.
