### ISSUE TITLE
There is no notification class that can handle event 

### ISSUE THREAD

**Issue by munkhorgil** [spatie/laravel-backup#330]
Backup returns following error `There is no notification class that can handle event Spatie\Backup\Events\BackupHasFailed`. Somehow backup successfully done, Is there any solution to get rid of this ?

**Comment by AlexVanderbist** [comment]
Hi @munkhorgil 

Could you post your `laravel-backup.php` config file here please? This makes it a bit easier to find the root of your problem.

Thanks!
