### ISSUE TITLE
Destination FTP

### ISSUE THREAD

**Issue by oriceon** [spatie/laravel-backup#334]
Hello, i edited config/filesystems.php with ftp disk info then i used in config/laravel-backup.php,
When i want to run a backup i receive message:

**Copying zip failed because: There is no disk set for the backup destination.**

Where i`m wrong?

**Comment by freekmurze** [comment]
Did you specify the name of your disk in [the `disks` key](https://github.com/spatie/laravel-backup/blob/d0b35fc/config/laravel-backup.php#L60) in the laravel-backup config file?

**Comment by oriceon** [comment]
@freekmurze  Sure i did

**Comment by freekmurze** [comment]
The error seems to point out that you specified a wrong value there.

Could you please post the content of `laravel-backup.php` and `filesystems.php`?

**Comment by oriceon** [comment]
[larave-backup.php.txt](https://github.com/spatie/laravel-backup/files/673882/larave-backup.php.txt)
[filesystems.php.txt](https://github.com/spatie/laravel-backup/files/673883/filesystems.php.txt)

**Comment by freekmurze** [comment]
Strange... Things you can try:

- try setting the `local` disk as a destination to see if that works.
- try verifying in a `php artisan tinker` session if the values of the config files are being read.

**Comment by oriceon** [comment]
@freekmurze i tryed another disk (partition) and is workin fine.
