### ISSUE TITLE
App.Name setting error

### ISSUE THREAD

**Issue by mitchellklijs** [spatie/laravel-backup#336]
Hey,

I've encountered a problem when using the `backup:run` command. I've found out what the problem was, but the packaged should have given an Error in my opinion.

I recently upgraded my application from Laravel 5.2 to Laravel 5.3. In Laravel 5.2 there was no setting for the application name (app.name). Therefore my config file didn't have that setting.
When I ran `backup:run` the process started without any problems but it never ended and gave no errors. Not even in the laravel log.
In my opinion the package should have given an error stating the value for 'app.name' was empty.

**Comment by freekmurze** [comment]
This is fixed in version `4.3.2`
