### ISSUE TITLE
Database wise backup

### ISSUE THREAD

**Issue by bhanushalimahesh3** [spatie/laravel-backup#342]
Hi people,

Is it possible to backup multiple database in their respective folder and respective zip file rather than in single zip file.
For eg. if I configure database1, database2, database3 for backup right now it zip all three database into single zip file. So is there any option to zip them individually and also in different folder. like database1/database1.zip, database2/database2.zip, database3/database3.zip

**Comment by bbashy** [comment]
It's possible.

**Comment by freekmurze** [comment]
Currently the package only has support for creating a single `.zip` file. You could use `Spatie\Backup\Events\BackupManifestWasCreated` and `BackupZipWasCreated` do do extra stuff when a backup is in progress. Take a look at the docs: https://docs.spatie.be/laravel-backup/v4/taking-backups/events

@bbashy what solution do you have in mind?

**Comment by bbashy** [comment]
I was just stating it's possible :)

**Comment by bhanushalimahesh3** [comment]
@freekmurze will take a look at that document. Thanks
