### ISSUE TITLE
FatalThrowableError maximumAllowedUsageInBytes() error

### ISSUE THREAD

**Issue by marioene** [spatie/laravel-backup#344]
Hi, 
I'm using your great package v.4 on Laravel 5.3.29 (environment: Laragon 2.1.5, PHP 7.0.12).
When I execute `php artisan backup:run`, everything works well.
When I execute `php artisan backup:monitor`, I am receving this error:

` [Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                                   
 Type error: Return value of Spatie\Backup\Tasks\Monitor\BackupDestinationStatus::maximumAllowedUsageInBytes() must be of the type integer, float returned`

Any solution for this error?

**Comment by freekmurze** [comment]
Check the value of `storageUsedMayNotBeHigherThanMegabytes` in your config file. This should be an int, not a float.
