### ISSUE TITLE
Not an 'issue' just a question.. - mysqldump not found on windows.

### ISSUE THREAD

**Issue by jackfruhecolab** [spatie/laravel-backup#345]
Running this on windows, I get this error that mysqldump is not recognized.
````
C:\inetpub\PHPBackupTool>php artisan backup:run
Starting backup...
Dumping database msol_license_tracker...
Backup failed because The dump process failed with exitcode 1 : General error : '"mysqldump"' is not recognized as an internal or external command,
operable program or batch file.
````

In my `config\database.php` I've added this
````
'dump' => [
    'dump_binary_path' => 'C:\\PROGRA~1\\MySQL\\MYSQLS~1.7\\bin\\',
],
````

Any thoughts on what I am getting wrong with the path formatting?

**Comment by freekmurze** [comment]
Are you using the latest version of the package?

**Comment by jackfruhecolab** [comment]
Hi Freek, I believe so, I just installed it recently and did a composer update.
Was there a known issue with this in the past?
- Jack

**Comment by freekmurze** [comment]
Fairly recently there have been changes to the underlying dumper package.

For Windows another kind of quote was used to be placed around the binary path because another user reported problems.

This is the function that determines the quote. 

https://github.com/spatie/db-dumper/blob/master/src/Databases/MySql.php#L188

Could you go into your vendor folder and manually change the result to `'`, `"` or an empty string. After each change, try to run the backup. Report back to me which characters works for you.

My apologies for letting you do the dirty work, I'm not a Windows user.

**Comment by oriceon** [comment]
I am using this package on a large number of Windows servers and it is working as it should with single quote.

**Comment by oriceon** [comment]
Double quote i mean

**Comment by jackfruhecolab** [comment]
**Thanks Freek and oriceon!**

I think it was the missing **set_** in front of dump_binary_path.

Freek, This is the page where I saw dump_binary_path: 
[https://docs.spatie.be/laravel-backup/v4/installation-and-setup](https://docs.spatie.be/laravel-backup/v4/installation-and-setup)  _Does this page need to be updated_ (if the correct string to pass is set_dump_binary_path)?

**Question for either of you...**
I'm trying to understand/trace the code so I can troubleshoot these kinds of things myself in the future.
I searched the vendors\spatie\* looking for the string "dump_binary_path" and "set_dump_binary_path"
I can find nether in the source code, I assume there must be some place where the src has logic like:

    if (isset(set_dump_binary_path)) 
    {  
      use that value instead
    }

**How/where does that value get used?**

**Comment by freekmurze** [comment]
Hi Jack,

the [`DbDumperFactory`](https://github.com/spatie/laravel-backup/blob/418c62e/src/Tasks/Backup/DbDumperFactory.php) contains the logic created a configured `DbDumper`.

It'll [loop over each value](https://github.com/spatie/laravel-backup/blob/418c62e/src/Tasks/Backup/DbDumperFactory.php#L64) in the `dump` keys of configured databases. It'll [check](https://github.com/spatie/laravel-backup/blob/418c62e/src/Tasks/Backup/DbDumperFactory.php#L100-L103) if that key name (or that key prepended with `set_` exists as a method on `DbDumper` 

So it's strange that appending `set_` in front of `dump_binary_path` fixed your error. Could you double check if that fixed your problem? If so, I'll try to recreate your problem locally and make a fix to the code.

**Comment by oriceon** [comment]
@freekmurze do you have ```set_```*** method(s) on DbDumper?

**Comment by jackfruh** [comment]
Hi Freek, 

I should have taken a screenshot, but can confirm that it did not work, and I added set_ to the value in the database.php file per @oriceon suggestion and it worked.

- Jack

**Comment by freekmurze** [comment]
@jackfruh I found and fixed a bug in `DbDumperFactory`.

In the newly tagged `v4.3.4` both `dump_binary_path` and `set_dump_binary_path` should now work. If not, reopen this issue.

**Comment by jackfruh** [comment]
Thanks Freek! YOU'RE THE BEST!!!

Quick question - I looked at the [check](https://github.com/spatie/laravel-backup/blob/418c62e/src/Tasks/Backup/DbDumperFactory.php#L100-L103) code.

I even tried method_exists in a little scratchpad php script.

How does method_exists() match 'set_dump_binary_path' to [setDumpBinaryPath(...)](https://github.com/spatie/db-dumper/blob/master/src/DbDumper.php#L148) ?

Is there a translation function somewhere I'm missing?

- Jack

**Comment by freekmurze** [comment]
`dump_binary_path` is being converted to `dumpBinaryPath` [here](https://github.com/spatie/laravel-backup/blob/45968cd/src/Tasks/Backup/DbDumperFactory.php#L65).

the `set` part is being prepended [here](https://github.com/spatie/laravel-backup/blob/45968cd/src/Tasks/Backup/DbDumperFactory.php#L100).

**Comment by jackfruh** [comment]
Ahh, that's starting to make sense now!

So before the 'set_' was pre-pended the string dump_binary_path had already been converted to DumpBinaryPath, and if I'm not mistaken, the code that checked for 'set' came after?
so the logic bug was that we were looking for set_DumpBinaryPath at that point.

Here's a question: Why go through all this in the first place?
ie Why not just make the value in database.php look like this:

     'dump' => [
       'setDumpBinaryPath' => 'C:\\PROGRA~1\\MySQL\\MYSQLS~1.7\\bin\\',
     ],

This way, a person trying to troubleshoot could just search the code for '**setDumpBinaryPath**' and find where it's used.

Is there a reason for the added complexity?

- Jack

**Comment by freekmurze** [comment]
> Why go through all this in the first place?

Sure, I could have gone with `setDumpBinaryPath`. But it's common for config values in Laravel to use underscores instead of using camelCasing. Having users set `dump_binary_path` is much more natural then letting them set `setDumpBinaryPath`.

**Comment by jackfruh** [comment]
Ok, thanks Freek!

**Comment by eumanito** [comment]
I was having this problem, I fixed updating and run:

`php artisan optimize
php artisan config:cache`

**Comment by kyledevelop** [comment]
`Too few arguments to function Spatie\DbDumper\DbDumper::excludeTables(), 0 passed in C:\xampp\htdocs\skill\larab2s3\vendor\spatie\laravel-backup\src\Tasks\Backup\DbDumperFactory.php on line 112 and exactly 1 expected
`
Fixed firs error but got this.

**Comment by aminladhari** [comment]
Class 'App\Console\Commands\Spatie\DbDumper\Databases\MySql' Not Found

- php version 7.2.19
- composer 1.8.6
- Laravel 5.7.29

**Comment by amidesfahani** [comment]
Hi I have problem with nova command.
artisan command works fine.

- Laravel 8
- Nova 3

The dump process failed with exitcode 1 : General error : '"mysqldump"' is not recognized as an internal or external command,operable program or batch file.
Spatie\DbDumper\Exceptions\DumpFailed
vendor\spatie\db-dumper\src\Exceptions\DumpFailed.php

**Comment by asus18019** [comment]
how to install mysqldump? help please

**Comment by Andres2503** [comment]
> I was having this problem, I fixed updating and run:
> 
> `php artisan optimize`
> `php artisan config:cache`

I fucking love you
