### ISSUE TITLE
Intermittent backup timeouts

### ISSUE THREAD

**Issue by JoeDawson** [spatie/laravel-backup#346]
Hey guys,

I'm not sure why, but I'm getting some intermittent backup failures relating to the MySQL dump.

Here's the error I'm seeing that we get emailed;

> Failed to backup  because: The process "mysqldump --defaults-extra-file="/tmp/phpo32vX4" --skip-comments --extended-insert site > "/home/forge/site.com/storage/laravel-backups/temp//site.sql"" exceeded the timeout of 180 seconds.

By default, I believe the timeout for database dumps is set to 60 seconds. I found somewhere in a previous issue yesterday that you can increase the timeout by adding;

```php
'dump_command_timeout' => 60 * 3
```

From what I can tell (looking at the error we got emailed) is that the timeout was increased, but sometimes it's still failing.

The backups run hourly, then get uploaded to S3 - as I mentioned though, these failures are intermittent and we're only getting possibly 2 failed backups a day.

But preferably we'd like none, any ideas on what we could do?

**We're using the latest version of the package and we're currently on Laravel 5.1**

Thanks!

**Comment by freekmurze** [comment]
Which error message are you getting now?

**Comment by JoeDawson** [comment]
It's above, I get an email saying the database dump times out. But before increasing the timeout to 180 seconds (when it was at the default of 60 seconds for a database dump), it was working fine most of the time.

> Failed to backup because: The process "mysqldump --defaults-extra-file="/tmp/phpo32vX4" --skip-comments --extended-insert site > "/home/forge/site.com/storage/laravel-backups/temp//site.sql"" exceeded the timeout of 180 seconds.

**Comment by freekmurze** [comment]
Could you try increasing the `dump_command_timeout` value to let's say `60 * 5` and see if that helps?

**Comment by JoeDawson** [comment]
Sure, will get back to you tomorrow :)

**Comment by JoeDawson** [comment]
Hello,

Sorry for the delay getting back to you (don't see my work emails over the weekend).

It seemed to fail again, but only once since the I increased it to 5 minutes.

```
Failed to backup  because: The process "mysqldump --defaults-extra-file="/tmp/phpVgs9Nf" --skip-comments --extended-insert regency > "/home/forge/rms.regencysecurity.co.uk/storage/laravel-backups/temp//regency.sql"" exceeded the timeout of 300 seconds.
```

**Comment by freekmurze** [comment]
I'm guessing on your system `mysqldump` sometimes can take a really long time to do its work. So my thinking is that this is issue is not caused by the package.

Reopen this issue if further investigation points to a bug in this package.

**Comment by JoeDawson** [comment]
Thanks for your help, will investigate with Digital Ocean to see if they can help.
