### ISSUE TITLE
Change s3 bucket

### ISSUE THREAD

**Issue by nam-co** [spatie/laravel-backup#347]
Hello freekmurze, I was wondering if there's a way to change the destination bucket with S3, it seems cloud front allows access to all the bucket and backups is something you don't want show the world, maybe adding a option in the config file?

Appreciate the help and the package
thanks

**Comment by freekmurze** [comment]
You can change the bucket name in the `filesystems.php` config file. 

On Amazon you can add a policy so all files in the specified bucket are private.
