### ISSUE TITLE
 Return value of Spatie\Backup\Tasks\Monitor\BackupDestinationStatus::maximumAllowedUsageInBytes() must be of the type integer, float returned  ?

### ISSUE THREAD

**Issue by vipin733** [spatie/laravel-backup#351]
I changed "BackupDestinationStatus.php" int to string on  line 109, 47, and its worked

**Comment by sebastiandedeyne** [comment]
What php version are you on?

And what value have you configured for `maximumAllowedUsageInBytes`?

**Comment by vipin733** [comment]
php 7 and 5000

**Comment by vipin733** [comment]
and Schedules commonds not working 
      `  $schedule->command('backup:clean')->everyTenMinutes();
        $schedule->command('backup:run')->everyTenMinutes();`

**Comment by sebastiandedeyne** [comment]
Hmm that's odd, what does this line return exactly? (you could wrap the statement in a `dd` to find out; `return dd($this->maximumStorageUsageInMegabytes * 1024 * 1024);`)

https://github.com/spatie/laravel-backup/blob/master/src/Tasks/Monitor/BackupDestinationStatus.php#L111

> and Schedules commonds not working

What's not working? Are there errors or are the backups not being made? Did you set up a cron job for the scheduler?

**Comment by vipin733** [comment]
its my fault i did not enable my artisan command I'm using windows. And when I run commond php artisan backup:run I got errors `Return value of Spatie\Backup\Tasks\Monitor\BackupDestinationStatus::maximumAllowedUsageInBytes() must be of the type integer, float returned ? #351`  then i ts errors occurs may problem that in changed its working may be problem is that in file "BackupDestinationStatus.php" on line 47 its returning float but on line 109 its int so i think it should be float or string

**Comment by freekmurze** [comment]
I've just tagged a new release `4.4.41` where the typehint of `setMaximumStorageUsageInMegabytes` was changed from `float` to `int`.

**Comment by limenet** [comment]
Unfortunately, I'm still getting this error with PHP 7.1.1 on a Raspberry Pi 3 (armv7l) and Laravel 5.4. My value for `maximumAllowedUsageInBytes` is also `5000`.

While debugging this method

```php
    public function maximumAllowedUsageInBytes(): int
    {
        return $this->maximumStorageUsageInMegabytes * 1024 * 1024;
    }
```

I found `$this->maximumStorageUsageInMegabytes * 1024` is still an `int` but after the second multiplication `* 1024` it gets converted to a `float`. This is probably due to the arm architecture.

A simple `(int)` cast fixes this problem however and I'll shortly send a PR.
