### ISSUE TITLE
[Suggestion] Making the config keys more readable

### ISSUE THREAD

**Issue by arcanedev-maroc** [spatie/laravel-backup#352]
Hi spatie,

I want to suggest a simplified names for config keys. 

**It's going to be a breaking change for a lot of packages!**

Instead of using names like this:

```php
'deleteOldestBackupsWhenUsingMoreMegabytesThan'
```

How about these formats:

```php
'delete-oldest-backups-when-using-more-megabytes-than'

// OR

'delete_oldest_backups_when_using_more_megabytes_than'
```

I don't know the downside of using these formats but it's more readable this way.

Thanks & Keep up the good work 👍 

Best regards

**Comment by freekmurze** [comment]
Good idea, I'll revisit this issue when creating a next major release
