### ISSUE TITLE
Emails are still send when the notification is set as an empty string

### ISSUE THREAD

**Issue by adrinavarro** [spatie/laravel-backup#355]
My config file is as follows:

```
    'notifications' => [
        'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class         => ['mail'],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class        => ['mail'],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class     => [''],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class   => [''],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class    => [''],
        ],
        /*
         * Here you can specify the notifiable to which the notifications should be sent. The default
         * notifiable will use the variables specified in this config file.
         */
        'notifiable' => \Spatie\Backup\Notifications\Notifiable::class,
```

I am still receiving emails for all events, not just those where the array is not an empty string. I'd say this is not expected behaviour. However, I cannot seem to find the part of the source of this package where this happens so I can debug it.

It is important to note that when setting the array as an empty array `[]` emails are indeed not sent. So it's a minor thing, but I don't think it should happen.

**Comment by bbashy** [comment]
Yeah I don't need notifications for some of my projects. Tried turning it to empty string, null, or false but still sends email :D

**Comment by freekmurze** [comment]
This is fixed in the latest version of the package.
