### ISSUE TITLE
Misuse of shell builtins : mysqldump: Got error: 1045: Access denied for user

### ISSUE THREAD

**Issue by juukie** [spatie/laravel-backup#365]
Using V4 I encountered this error. Having spent some time on it, I figured out that my password `x:Jk@8\n&YrFkmW=5%9` was the problem.
I've changed it to `x:Jk@8\n&YrFkmW=5%9` (changed `\n` to `\2`).

So the temp credentials file looks like this:
```
[client]
user = 'SpatieBeKudos'
password = 'x:Jk@8\2&YrFkmW=5%9'
host = '127.0.0.1'
port = '3306'
```

Failing temp credentials file looked like this:
```
[client]
user = 'SpatieBeKudos'
password = 'x:Jk@8\n&YrFkmW=5%9'
host = '127.0.0.1'
port = '3306'
```

mysqldump version:
`mysqldump  Ver 10.13 Distrib 5.5.52, for debian-linux-gnu (i686)`

I've tried changing the quotes to `""` but that didn't help. Seems like `\n` will just result in a newline or something :/.

**Comment by freekmurze** [comment]
Thanks for sharing your experience.

I'd accept a PR on [spatie/db-dumper](https://github.com/spatie/db-dumper) that fixes this.

**Comment by juukie** [comment]
I'll try to see if there is a need of escaping the password.

**Comment by LeShadow** [comment]
@juukie @freekmurze this depends on how the database user is created.
If it is created with a certain PHP script and the password has been sent to mysql (upon user creation) in double quotes, then the \n will be interpreted as a newline.
If it has been passed on to mysql in single quotes, PHP will not interpret the character as a newline and the password will be saved as it was meant to be.

I hope this helps a little bit :)

**Comment by juukie** [comment]
@LeShadow thanks for your information. The password has been created by Plesk 12.5. That may be the problem. I'll try to create a user via CLI and test it again!

**Comment by juukie** [comment]
@LeShadow I've changed the password via the CLI:
`update mysql.user set password=PASSWORD('x:Jk@8\n&YrFkmW=5%9') WHERE user='SpatieBeKudos';`
1 row affected.

Running the command still fails with the same error.

**Comment by freekmurze** [comment]
Yeah, PR a note on this in the docs.

**Comment by AlexVanderbist** [comment]
I opened a PR with a notice about escape sequences in mysql credentials: spatie/docs.spatie.be#120

**Comment by juukie** [comment]
Thanks @AlexVanderbist !
