### ISSUE TITLE
Nameless root folder in archive

### ISSUE THREAD

**Issue by dudedigital** [spatie/laravel-backup#367]
Is there any reason the root folder in the backup zip would be nameless? Is this by design?

I opened the ZIP file on Windows and it showed an empty directory. I kept thinking something was broken. Later, I tried opening the file with 7zip which shows a nameless root folder that contains the db-dumps and home folders.

**Comment by dudedigital** [comment]
Turns out this is due to the way file names are added to the ZipArchive. Since they all begin with a forward slash, this creates a nameless root folder.

https://github.com/spatie/laravel-backup/blob/master/src/Tasks/Backup/Zip.php#L103

Adding a left trim removes the first slash:
`$this->zipFile->addFile($file, ltrim($nameInZip, '/')).PHP_EOL;`

Now I can see the folders on both Windows and Linux.

**Comment by AlexVanderbist** [comment]
I faced the same issue on windows and created a PR here: 
https://github.com/spatie/laravel-backup/issues/369
