### ISSUE TITLE
Backup of postgres fails, but mysql works

### ISSUE THREAD

**Issue by tsawler** [spatie/laravel-backup#368]
I'm using laravel-backup 4.4.5. Running php artisan backup:run fails on Laravel 5.3.30 when postgres is backend db, but works when mysql is backend db. Here is a partial stack trace:

Backup failed because The dump process failed with exitcode 1 : General error : pg_dump: [archiver] could not open output file "/home/httpd/nbtap.ca/storage/laravel-backup-temporary/db-dumps/nbtap.sql": No such file or directory
.
#0 /home/httpd/nbtap.ca/vendor/spatie/db-dumper/src/DbDumper.php(222): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))
#1 /home/httpd/nbtap.ca/vendor/spatie/db-dumper/src/Databases/PostgreSql.php(55): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), '/home/httpd/nbt...')
#2 /home/httpd/nbtap.ca/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(203): Spatie\DbDumper\Databases\PostgreSql->dumpToFile('/home/httpd/nbt...')
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\DbDumper\Databases\PostgreSql), 0)
#4 /home/httpd/nbtap.ca/bootstrap/cache/compiled.php(12999): array_map(Object(Closure), Array, Array)
#5 /home/httpd/nbtap.ca/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(206): Illuminate\Support\Collection->map(Object(Closure))
#6 /home/httpd/nbtap.ca/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(136): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases('/home/httpd/nbt...')

**Comment by freekmurze** [comment]
Could you try upgrading to `v4.4.7`.

Reopen this issue if the problem persist.
