### ISSUE TITLE
Extra option for using gzip

### ISSUE THREAD

**Issue by afraca** [spatie/laravel-backup#372]
Hi, 

I have some large databases. When we do manual backup with PhpMyAdmin or Adminer, it's nice to see that when we tick the gzip box, we often get impressive compression (yes, that depends on the data, irrelevant). 

It would be great if there is some extra option we can pass to get the same with the backups we create with this package. Any thoughts?

**Comment by freekmurze** [comment]
By default this package will store the db dump in a zip file.

**Comment by afraca** [comment]
Yes, I know... The DB dumps from PMA and Adminer can be 
.sql
or
.sql.gz 

The latter are a lot more compact. The default zip from laravel-backup does NOT do compression as far as I know, it's simply bundling files.

**Comment by freekmurze** [comment]
I'd accept a PR that adds compression to the backups.

**Comment by afraca** [comment]
Originally I opened the issue in spatie/db-dumper because I think it's easier to redirect the sql dump file through gzip than to change how the zipping works in **this** package. For my particular use-case _that_ would still be viable work, and a lot of gain.

Changing how **this** package deals with zips, currently with the built-in ZipArchive is trickier I suspect. The easiest would be something like 
* Create the .zip normal
* Pipe the .zip through gzip to create a new .zip.gz file or something

It's not standard at all to do that. That's why 
https://github.com/spatie/db-dumper/issues/35

Is still the preferred place to begin with this, IMHO.

**Comment by freekmurze** [comment]
We'll handle this further in #424
