### ISSUE TITLE
Parse error: syntax error, unexpected ':', in functions.php

### ISSUE THREAD

**Issue by thinkstylestudio** [spatie/laravel-backup#380]
Hey guys running laravel 5.4 and laravel-backup 4.6. 

When i go to load any route i get the following error. 

`Parse error: syntax error, unexpected ':', expecting '{' in /vagrant/laravel/vendor/spatie/laravel-backup/src/Helpers/functions.php on line 5`

Any Ideas?

**Comment by sebastiandedeyne** [comment]
v4.x requires php 7.0, so you'll either need to upgrade your php version, or use v3 of this package.

**Comment by thinkstylestudio** [comment]
@sebastiandedeyne 

$ php -r \@phpinfo\(\)\; | grep 'PHP Version' -m 1
PHP Version => 7.0.12
