### ISSUE TITLE
Email content lost when upgrading from 4.4.9 to 4.6.0

### ISSUE THREAD

**Issue by leewillis77** [spatie/laravel-backup#381]
I've attached two screenshots below. This is the email from 4.4.9:

https://www.dropbox.com/s/kxqdf5eon3vgedk/Screenshot%202017-02-16%2008.55.39.png?dl=0

The next is after upgrading to 4.6.0

https://www.dropbox.com/s/tllogdfvba3mct8/Screenshot%202017-02-16%2008.55.57.png?dl=0

Notice that the subject and email content have gone away and been replaced with placeholders. I suspect that I just need to run the following to publish the language files?

```
$ php artisan vendor:publish --provider="Spatie\Backup\BackupServiceProvider"
```

Can you confirm? It would be good if that was mentioned in the release notes for 4.6.0

**Comment by sebastiandedeyne** [comment]
Hmm this isn't expected behaviour. What's your application's locale and fallback locale?

**Comment by ItsRD** [comment]
I've got the same issue, my locale is 'nl' and my fallback_locale is 'en'. 

When I change my locale to 'en', it gives the same result.

**Comment by leewillis77** [comment]
Hi, 

Both are just 'en'.

**Comment by sebastiandedeyne** [comment]
Just released v4.6.1, could you guys run `composer update` and see if this issue is resolved?

**Comment by ItsRD** [comment]
Works! Thanks :)

**Comment by sebastiandedeyne** [comment]
Nice, sorry for the hiccup!

**Comment by leewillis77** [comment]
Yep works - thanks for the fix!
