### ISSUE TITLE
Back up failed

### ISSUE THREAD

**Issue by dominicmuse** [spatie/laravel-backup#383]
hello.. so am running the back up on windows and this is what i get.

`D:\Projects\Nano-4>php artisan backup:run
Starting backup...
Dumping database new_site...
Backup failed because The dump process failed with exitcode 1 : General error : '"mysqldump"' is not recognized as an internal or external command,
operable program or batch file.
.
#0 D:\Projects\Nano-4\vendor\spatie\db-dumper\src\DbDumper.php(222): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))
#1 D:\Projects\Nano-4\vendor\spatie\db-dumper\src\Databases\MySql.php(111): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), 'D:\\Projects\\Nan...')
#2 D:\Projects\Nano-4\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(203): Spatie\DbDumper\Databases\MySql->dumpToFile('D:\\Projects\\Nan...')
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\DbDumper\Databases\MySql), 0)
#4 D:\Projects\Nano-4\vendor\laravel\framework\src\Illuminate\Support\Collection.php(613): array_map(Object(Closure), Array, Array)
#5 D:\Projects\Nano-4\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(206): Illuminate\Support\Collection->map(Object(Closure))
#6 D:\Projects\Nano-4\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(137): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()
#7 D:\Projects\Nano-4\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(117): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#8 D:\Projects\Nano-4\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(43): Spatie\Backup\Tasks\Backup\BackupJob->run()
#9 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#10 D:\Projects\Nano-4\vendor\laravel\framework\src\Illuminate\Container\Container.php(508): call_user_func_array(Array, Array)
#11 D:\Projects\Nano-4\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#12 D:\Projects\Nano-4\vendor\symfony\console\Command\Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 D:\Projects\Nano-4\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 D:\Projects\Nano-4\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(22): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 D:\Projects\Nano-4\vendor\symfony\console\Application.php(817): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 D:\Projects\Nano-4\vendor\symfony\console\Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 D:\Projects\Nano-4\vendor\symfony\console\Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 D:\Projects\Nano-4\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 D:\Projects\Nano-4\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}
Backup completed!`

in config/database.php i have ..

`'mysql' => [
            'dump_command_path' =>'C:\xampp\mysql\bin',
            'dump_using_single_transaction' => true,
            'driver' => 'mysql',`

could you please help me figure out why i get an error after following the installation instructiions?

**Comment by m1guelpf** [comment]
??

**Comment by dominicmuse** [comment]
sorry just edited the question... could you please address it?

**Comment by dominicmuse** [comment]
sorry sorted it
