### ISSUE TITLE
The process "mysqldump ..." exceeded the timeout of 60 seconds.

### ISSUE THREAD

**Issue by geomagilles** [spatie/laravel-backup#39]
Do you think it would be possible to add an entry in config to set timeout ?

**Comment by freekmurze** [comment]
I'll add this in the near future. If you need this quick, feel free to submit a pull request.

**Comment by freekmurze** [comment]
It's seems that mysqldump doesn't have a timeout option. Have you already tried to set `useExtendedInsert` to true in the config file?

**Comment by geomagilles** [comment]
I do not think it's a timeout of mysqldump. I think it's a console's timeout. When I increase timeout in Spatie\Backup\Console, it works.

**Comment by freekmurze** [comment]
Ah ok! I'll add an configuration option to change the timeout in the coming week.

**Comment by geomagilles** [comment]
great! thanks

**Comment by freekmurze** [comment]
This option is added in the newly released version 2.5.0.

**Comment by geomagilles** [comment]
:)

**Comment by eblount** [comment]
I'm getting this in V3. Is there still a way to set this configuration option?

**Comment by freekmurze** [comment]
Nope, it's gone :smile:  I'll add it back in the coming days.

**Comment by eblount** [comment]
Thanks!

**Comment by freekmurze** [comment]
The option has risen from the dead and is available again in v3.1.4

Documented at the bottom of [this page in the documentation](https://docs.spatie.be/laravel-backup/v3/installation-and-setup).
