### ISSUE TITLE
Parse error syntax error, unexpected ':' spatie/laravel-backup/src/Helpers/functions.php on line 5

### ISSUE THREAD

**Issue by mubashirsiddique** [spatie/laravel-backup#390]
I am running laravel-backup 4.6.6 with laravel framework version 5.4.14 and I am successfully running on my localhost with PHP ver=7.

But after deploying on hosting, I receive:
Parse error: syntax error, unexpected ':', expecting '{' in /home/xx/public_html/xx/vendor/spatie/laravel-backup/src/Helpers/functions.php on line 5

PHP version on host is: 5.6 (the most up available version on godaddy cp)

Please help anybody.

**Comment by mubashirsiddique** [comment]
I noticed the master branch  has the following syntax in a lot of functions:

function consoleOutput(**): ConsoleOutput**
{
    return app(ConsoleOutput::class);
}

which is yielding Parse / syntax error, but strangely not on my localhost  . does any one know Why!!!

**Comment by freekmurze** [comment]
`v4` of this package requires PHP 7

If you're stuck on a legacy version of PHP use `v3` of the package.

**Comment by canorioss** [comment]
Tengo la versión "spatie/laravel-backup": "^4.14", y tengo el mismo error que tiene @mubashirsiddique .
Ahora estoy trabajando en local y tengo las dos versiones de php, la 5.6 y la 7.0 por lo que no tengo problema en cambiar de versión. El problema sería al utilizar otro servidor, no es mi caso pero quise comentarlo por si es un bug o algo que se pueda corregir. Saludos y gracias a los que trabajan en este componente.

**Comment by MikkyX** [comment]
A colleague of mine is getting this error on PHP 7.1.4 - is there PHP syntax that was only available in 7.0.x?

**Comment by freekmurze** [comment]
If you are getting that error, you still are running PHP 5.6. Please check your PHP version. Cli version can differ from your web version.

**Comment by MikkyX** [comment]
Turns out they were still running 5.6 in Apache. Thanks for highlighting that and sorry to have troubled you!

**Comment by freekmurze** [comment]
No problem, glad you found a solution.

**Comment by christiantigre** [comment]
Tengo este error. en laravel 5.4 tengo php 7.1 y tengo el paquete spatie v4. la configuracion que tengo es 
'mysqldump' => [
'dump_binary_path' => env('DB_DUMP_COMMAND_PATH'), 
'dump_binary_path' => 'C:\\xampp\\mysql\\bin', 
'use_single_transaction',
'timeout' => 60 * 5, // 5 minute timeout
'exclude_tables' => ['table1', 'table2'],
'add_extra_option' => '--optionname=optionvalue', 
y el rato que ejecuto (php artisan backup:run --only-db
) 
me sale el siguiente error.
Backup failed because The dump process failed with exitcode 1 : General error :
"mysqldump" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
(Como lo puedo solucionar)

**Comment by nonoillora** [comment]
@christiantigre cambia el slash de windows (\) por el de linux (/) en la ruta de lampp y debería de funcionarte sin problema

**Comment by arbabi2010** [comment]
Hi. I'm using php 7.2 and laravel 5.5 but i have this error

**Comment by arbabi2010** [comment]
Hi. Please help me. I'm using  php 7.2 and v4 of this package but i have this issue for a long time 
![image](https://user-images.githubusercontent.com/5072444/72063229-a3353580-32ee-11ea-90ae-27ab1837787e.png)

**Comment by larios109** [comment]
If someone continue with this problem this was my solution:
in file config/database.php you need to have this:

    'dump' => [

        'dump_binary_path' => '/path/to/directory/', // only the path, without `mysqldump` or `pg_dump`
        // 'dump_binary_path' => '/Applications/MAMP/Library/bin/', // works for MAMP on Mac OS
        //'dump_binary_path' =>  'C:\xampp\mysql\bin', //for XAMPP on windows
        // 'dump_binary_path' => '/opt/homebrew/bin/', // works for Laravel Valet on Mac OS
        'use_single_transaction',
        'timeout' => 60 * 5, // 5 minute timeout
        // 'exclude_tables' => ['table1', 'table2'],
        // 'add_extra_option' => '--optionname=optionvalue',
    ],
