### ISSUE TITLE
Occasional error when uploading a large backup to S3

### ISSUE THREAD

**Issue by rickbolton** [spatie/laravel-backup#394]
Hey, love the package so thanks for making this available firstly!

I keep getting this error occasionally. My backup zip file has reached 14GB due to songs, videos and images. Have you had experience backing up an App of this size and would you split the jobs so the backups are smaller or is there a way to split the parts before uploading?

Any advice would be greatly appreciated. I understand this isn't an issue as such but I think I saw you tweet a while back that you find it easier to manage questions through here.

Thanks!

Rick

```
Exception message: An exception occurred while uploading parts to a multipart upload. The following parts had errors: - Part 516: Error executing &quot;UploadPart&quot; on
```

Let me know if you need the whole error. Think it exposes my Amazon backup location if I added it all

**Comment by freekmurze** [comment]
I haven't got experience with such big backups.

Your error looks very much like this one at the aws-sdk repo: https://github.com/aws/aws-sdk-php/issues/669

Are you using the latest versions of all packages?

**Comment by rickbolton** [comment]
<img width="677" alt="screen shot 2017-03-15 at 09 03 52" src="https://cloud.githubusercontent.com/assets/10371256/23940866/77e333f8-095e-11e7-89a8-7371251e9af6.png">

I've just ran a composer update which has ran a few updates including this package and aws package. Will keep an eye on it.

I guess it's going to be more AWS related than anything.

Thanks!

Rick

**Comment by jsartisan** [comment]
i am getting this error occasionally. any solution for this?
