### ISSUE TITLE
how can i get mysql binary path dynamically

### ISSUE THREAD

**Issue by ridislam** [spatie/laravel-backup#396]
i am working on a project that can be installed by anyone, and i don't know his computer or server mysqldump file path but they also can't change this line from database: 
` 'dump_command_path'=> '/Applications/MAMP/Library/bin/'` 
without this path file are not creating, 
so is there any way that can set this path automatically on any server or localhost ?

**Comment by freekmurze** [comment]
You could ask the users of the package to add the path to the `mysql` bin to their `$PATH` variable. Then you can leave the config option empty.

More info on `$PATH`: http://www.linfo.org/path_env_var.html
