### ISSUE TITLE
Not working if run with Artisan::call, Why?

### ISSUE THREAD

**Issue by adecma** [spatie/laravel-backup#398]
I write this on routes/web.php :

Route::get('/service/backup', function(){
	Artisan::call('backup:run', [
	       	'--only-db' => true
	]);
});

But, backup not working, not found backup file on storage. 

If i run Artisan::call('backup:run', ['--only-db' => true]); on tinker, working. 
And run php artisan backup:run --only-db on Terminal, working to.

Why this? any idea. 
I test on laravel 5.4
Thanks

**Comment by freekmurze** [comment]
I'm thinking the code in the route should just work. Is there an error code or message given?

**Comment by adecma** [comment]
No error message, i try with other command as Artisan::call('make:request', ['name' => 'AdecmaRequest']);
And then, that command is working.

So, i check on config database.php, add code on driver mysql as 
'dump' => [ 'dump_binary_path' => 'C:\laragon\bin\mysql\mariadb-10.1.9\bin']

Solved, it's working. So, add it to config database driver mysql.
Thanks, reference from https://docs.spatie.be/laravel-backup/v4/installation-and-setup#dumping-the-database
