### ISSUE TITLE
Spatie\Backup\Helpers\ConsoleOutput::__call() must be an instance of Spatie\Backup\Helpers\string, string given

### ISSUE THREAD

**Issue by munkhorgil** [spatie/laravel-backup#399]
It is working fine in local machine, But in my server it doesn't work and following error occurred

` ConsoleOutput.php line 27:`

`Argument 1 passed to Spatie\Backup\Helpers\ConsoleOutput::__call() must be an instance of Spatie\Backup\Helpers\string, string given`

**Comment by freekmurze** [comment]
You need to have PHP 7 to use v4 of the package.

If you're stuck on an older version of PHP, use v3 instead
