### ISSUE TITLE
File backup not working on webserver

### ISSUE THREAD

**Issue by kay899** [spatie/laravel-backup#40]
I try to use this package. Locally (with XAMPP) file and db backup is working.

On my webserver (Digital Ocean with Forge) only db backup is working.

Here is my config file:

http://laravel.io/bin/QNNeV

I have no idea why file backup is not working.

Thanks, kay899

**Comment by freekmurze** [comment]
If you remove `base_path()` from your exclusions then `base_path('public/images_static')` will be included in your backup.

**Comment by kay899** [comment]
it's working, thanks
Can you explain me why my old version is working on my local machine, but not on webserver?
I just want to know why it's like this.

**Comment by freekmurze** [comment]
I'm assuming that on your local machine you hadn't put `base_path()`in the exclusing list in the config file.

**Comment by kay899** [comment]
It was exactly the same configuration. 
That was why I was so confused.

**Comment by freekmurze** [comment]
That is very strange indeed. Could you make sure you are using the same config and the files in the included and excluded directories are the same.

If you still see strange results, let me know which files are present in the backup that should not be there.
