### ISSUE TITLE
Dump process failed with exitcode 2 : Misuse of shell builtins 

### ISSUE THREAD

**Issue by Bobin56** [spatie/laravel-backup#401]
Hi , 
I got this error when backup:run command is executed . 

Exception trace: #0 /home/bandali/public_html/ivc/vendor/spatie/db-dumper/src/DbDumper.php(222): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process)) #1 /home/bandali/public_html/ivc/vendor/spatie/db-dumper/src/Databases/MySql.php(111): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), '/home/bandali/p...')`

I know it has to do with permission to access the mysqldump file on the server . At the moment i am on shared hosting , and i talked with the support team and they said the user/bin directory can't be accessed on a shared hosting  . Is there any workaround to make this work ? If not  , how can i backup just the files without exporting the database ?
`

**Comment by freekmurze** [comment]
The package can look for the dump binary in another directory too. Look at this example in the docs where a custom location is used.
https://docs.spatie.be/laravel-backup/v4/installation-and-setup#dumping-the-database

The docs also mention how to backup only the files: 
https://docs.spatie.be/laravel-backup/v3/taking-backups/overview#taking-backups
