### ISSUE TITLE
Calling backup:run from another command stops execution of that command

### ISSUE THREAD

**Issue by RicLeP** [spatie/laravel-backup#408]
Hi,

I have a package that calls laravel-backup. The backup is successful but it stops execution of the package that called it.

    echo 'show';
    $this->call('backup:run', ['--only-db' => 1]);
    echo 'does not show';

Is there any way around this?

**Comment by AlexVanderbist** [comment]
Hi,

Do you see any output of the backup command? Like the 'Backup completed!' message at the end?
