### ISSUE TITLE
Call to undefined method League\Flysystem\Filesystem::createDriver

### ISSUE THREAD

**Issue by olimorris** [spatie/laravel-backup#41]
Since updating to ```league/flysystem-aws-s3-v3``` I get the following error:
```
[BadMethodCallException]
Call to undefined method League\Flysystem\Filesystem::createDriver
```

![screen shot 2015-06-19 at 07 02 25](https://cloud.githubusercontent.com/assets/9512444/8247985/2ba30600-1651-11e5-9662-b2866236c206.png)

**Comment by freekmurze** [comment]
I haven't run into that issue myself. I'll try to reproduce this soon.

**Comment by freekmurze** [comment]
Could you check if the configvalue `destination.filesystem` is an array? All elements of the array should match a disk that is configered in de `filesystems` config file.

**Comment by freekmurze** [comment]
Were you able to solve this issue? If so, what was the solution?

**Comment by jkmassel** [comment]
I had the same issue, had to do a few things to make it work:

1) file system couldn't be called 'backup'
2) Needed to set a path (can't put it in the root of an S3 bucket or you get an error saying:

>[ErrorException]      
Undefined index: Key  
                     

3) Made the `filesystem` key not an array
