### ISSUE TITLE
Backup error via cron

### ISSUE THREAD

**Issue by sarfraznawaz2005** [spatie/laravel-backup#410]
Hi Thanks for nice package!

When I run backup manually via `backup:run`, it works fine. However, I get following error when backup is run via cron at specified time:

`backups : error: Failed to backup because: include(/home/xyz/public_html/vendor/symfony/finder/Exception/AccessDeniedException.php): failed to open stream: Too many open files`

Here is code that is run via cron:

    $schedule->command('backup:clean')->daily()->at('01:00');
    $schedule->command('backup:run')->daily()->at('02:00');

I tried changing folder permission from 755 to 777 but that didn't work so seems like it is not permission issue. Also tried using `@exec('ulimit -S -n 2048');`.

FYI, I am using **Laravel 5.1.** and package version is **3.11.0**

Any idea please ?

Thanks

**Comment by AlexVanderbist** [comment]
Hi @sarfraznawaz2005 

Just some things that come to mind; do you have any other cron task running at exactly 2:00 that would use a lot of files or do you include the `vendor` or `node_modules` directories in your backups?

**Comment by sarfraznawaz2005** [comment]
Hi @AlexVanderbist , nope I don't have any other task running at that time, neither opening files.

**Comment by AlexVanderbist** [comment]
Hm, maybe another shot in the dark; have you tried setting the backup command to run every minute and then running the `schedule:run` yourself? Maybe the cron task is being ran by another user/process that has different permissions/limits/...

**Comment by sarfraznawaz2005** [comment]
Tried that still the same result :(

**Comment by freekmurze** [comment]
Pretty sure this is caused by something specific to your server/application.

Could you try setting up the package in a vanilla Laravel app?

**Comment by sarfraznawaz2005** [comment]
Yes I suspect issue is elsewhere in my app otherwise somebody else would also have posted the same issue for this package. I will close this. Thanks
