### ISSUE TITLE
Loses emoji

### ISSUE THREAD

**Issue by zvermafia** [spatie/laravel-backup#411]
After recovery the DB with a dump which was create with this package I lost emoji.

Laravel: 5.4
MySQL: 5.7.17
Laravel DB config:
```
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
```

I'm not sure, but I think the package takes dumps without the parameter `--default-character-set=utf8mb4`. I think like that, because I tried manually to take a dump and recovery with this dump and everything works well:
```
# To take a dump
mysqldump --default-character-set=utf8mb4 -uhomestead -psecret test > test.sql

# To create a DB
CREATE DATABASE test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

# To recovery DB with the dump
mysql -uhomestead -psecret test < test.sql
```

**Comment by zvermafia** [comment]
> After recovery the DB with a dump which was create with this package I lost emoji.

Emoji converted to '?' symbol.

**Comment by sebastiandedeyne** [comment]
The character set should automatically be passed from the config in this case. Created an issue on `db-dumper` to implement this soon.

https://github.com/spatie/db-dumper/issues/36

**Comment by freekmurze** [comment]
In `v2.5` of the `db-dumper` package there is a new function `setDefaultCharacterSet` to set the character set. Improvements have been made so that a dumping the database automatically detects the uses charset.

Just run `composer update` to pull in `v2.5` of `db-dumper`.

If that doesn't solve your problem, reopen this issue.
