### ISSUE TITLE
Suggestion: Add Backup type to filename

### ISSUE THREAD

**Issue by activemonkeys** [spatie/laravel-backup#416]
Thanks for providing this nice package! 

During development I create many backups daily. As I'm working with large databases, I sometimes prefer to only backup the database using the option '--only-db' => true or only files using '--only-files' => true. 

It would be nice to be able to see what kind of backup is being created, for instance by adding the type (files, database or full) to the backup filename.

**Comment by freekmurze** [comment]
I'm open to a PR that adds this to the package in a non-breaking way (+ tests 😄 )

**Comment by vesper8** [comment]
I'm achieving this with the code below:

```
$schedule->command('backup:run --only-db --db-name api --db-name data')
->hourly()
->before(function () {
    Config::set('backup.backup.destination.filename_prefix', 'db_web_');
});

$schedule->command('backup:run --only-db --db-name forums')
->daily()
->before(function () {
    Config::set('backup.backup.destination.filename_prefix', 'db_forums_');
});

$schedule->command('backup:run --only-files')
->daily()
->before(function () {
    Config::set('backup.backup.destination.filename_prefix', 'files_web_');
});
```
