### ISSUE TITLE
Swift_TransportException: Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required

### ISSUE THREAD

**Issue by phuongphally** [spatie/laravel-backup#417]
I am just finished set up your package . 

But when try to run  ```  php artisan backup:run ```

get errors
Swift_TransportException: Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required

**Comment by freekmurze** [comment]
Seems like sending mail is not properly configured in your app. Please verify all config values regarding sending mails are ok. Try sending a mail from your app manually to see if that works.

**Comment by phuongphally** [comment]
I config in localhost already . But can not get it work .
