### ISSUE TITLE
No Response by Artisan CLI command run

### ISSUE THREAD

**Issue by Bhoopathismash** [spatie/laravel-backup#421]
It backup my database perfectly when i use backup command "php artisan backup:run --only-db" in Terminal (or) CMD. But i use those command in route as Artisan CLI  like

Route::get('/backup', function() {
    //php artisan backup:run --only-db 
    try {
        $exitCode = Artisan::call('backup:run',['--only-db' => true]);        
        dd($exitCode);
        echo "Backup completed!";// return what you want        
    }catch (Exception $e) {
      Response::make($e->getMessage(), 500);
      dd($e);
    }
});

its returns 0 and no backup was created... Does the way i use the Artisan call is correct or wrong - ->  Artisan::call('backup:run',['--only-db' => true]);    

Please advice me how to handle this thank you..

**Comment by freekmurze** [comment]
I cannot reproduce this.

```php
\Artisan::call('backup:run',['--only-db' => true]);
```

seems to be working fine.

**Comment by Bhoopathismash** [comment]
Mr.freekmurze thank u for u replay

My laravel version is 5.2

Its create my_db.sql file in path storage/laravel-backups/temp/my_db.sql at 0-KiloByte, 
No query and data are extracted, file is empty...

**Comment by freekmurze** [comment]
Is your server configured in such a way that `mysqldump` can be called from within a web request?

**Comment by Bhoopathismash** [comment]
```
 'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('my_db', 'my_db'),
            'username' => env('root', 'root'),
            'password' => env('', ''),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
            'dump' => [
               'dump_binary_path' => 'D:\laragon\bin\mysql\mysql-5.7.13-win32\bin', 
                'use_single_transaction',
                'timeout' => 5,               
                'dump_command_timeout' => 60,
            ],           
        ],
```
my server config sir,
