### ISSUE TITLE
can't find backup

### ISSUE THREAD

**Issue by VitaliyLogvin** [spatie/laravel-backup#423]
destination is local. where is it? Searched everything. I can not find.

**Comment by freekmurze** [comment]
Check `config/filesystems.php`

**Comment by VitaliyLogvin** [comment]
`'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],`

/var/www/<project>/app   right?

But there's nothing like backup. 

Console
Events
Exceptions
Http
Listeners
Mail
Models
Providers
User.php

Backup process responded successfully
