### ISSUE TITLE
Too many command line arguments

### ISSUE THREAD

**Issue by babakshaban** [spatie/laravel-backup#428]
Hi,

I've been following the instructions for using V3 of laravel-backup as per 
https://docs.spatie.be/laravel-backup/v3/installation-and-setup

Most of it is fairly self explanatory but I am having an weird issue when running a manual backup.

I'm using laravel 5.2.45 and posgtresql installed on windows 10.

Initially I was not able to get the backup to recognise pg_dump unless I put the full location and pg_dump in (including pg_dump), not just finishing at the bin directory. Then when it did recognise pg_dump it outputted the last error, which is that there were too many command-line arguments. 

my database.php file looks 

`            'dump_command_path' =>  env('DB_DUMP_COMMAND_PATH', '"C:\Program Files\PostgreSQL\9.6\bin\pg_dump"'),
            'dump_command_timeout' => 60 * 5, // 5 minute timeout
            'dump_using_single_transaction' => true, // perform dump using a single transaction`

`$ php artisan backup:run
?[33mStarting backup...?[39m
?[32mDumping database postgres...?[39m
?[37;41mBackup failed because The dump process failed with exitcode 1 : General error : '"C:\Program Files\PostgreSQL\9.6\bin"' is not recognized as an internal or external command,
operable program or batch file.
.?[39;49m

bshaban@5210-N131079 MINGW64 /d/git/portal (master)
$ php artisan backup:run
?[33mStarting backup...?[39m
?[32mDumping database postgres...?[39m
?[37;41mBackup failed because The dump process failed with exitcode 1 : General error : pg_dump: too many command-line arguments (first is "-U")
Try "pg_dump --help" for more information.
.?[39;49m
`

Any help would be appreciated, thanks!

**Comment by freekmurze** [comment]
See #432
