### ISSUE TITLE
Strange insert query on backup!

### ISSUE THREAD

**Issue by microdesign** [spatie/laravel-backup#429]
Hi, I just try to backup my database but this is totality strange because backup failed because of insert query.

I`m not sure why there is insert query on just a dump database?!

See attachment:
![screen shot 2017-05-04 at 1 38 08 pm](https://cloud.githubusercontent.com/assets/3175952/25700160/1069843c-30cf-11e7-87a2-14312fb3ca34.png)

**Comment by freekmurze** [comment]
Pretty sure that this is caused by you application as this package doesn't insert any record into the db. Try installing the package in a vanilla version of Laravel.

**Comment by microdesign** [comment]
How my application can try to insert record on a dump action from you package ?

**Comment by microdesign** [comment]
How dump can follow to insert execution? @freekmurze
