### ISSUE TITLE
Destination SFTP

### ISSUE THREAD

**Issue by GKMelbo** [spatie/laravel-backup#436]
When I run `php artisan backup:run` I get the following error:
`Copying zip to disk named sftp...
Copying zip failed because: There is no disk set for the backup destination.`

I have configured the laravel-backup file to use sftp. Is there an extension in php I need to enable or something like that?

**Comment by freekmurze** [comment]
Do you have a disk named  `sftp` in `config/filesystems.php`?

**Comment by GKMelbo** [comment]
I managed to figure it out. I had added the disk correctly, but just forgot to register my custom service  provider. Sorry

**Comment by GKMelbo** [comment]
So now it says it succesfully copied the zip file to disk `sftp` but if I check the backup server there's nothing there and the report emailed to me shows `0 KB`

**Comment by freekmurze** [comment]
Did you specify the right disk name in the `monitorBackups` part of the config file?

**Comment by GKMelbo** [comment]
Yep

**Comment by GKMelbo** [comment]
Turns out the user didn|t have R/W access to the destination disk. Works great now :)
I was also wondering, is it possible to set up multiple backups? I couldn't find any documentation on how to do it.

**Comment by freekmurze** [comment]
👍 

You can only backup the database with the `--only-db`, and only files with the `--only-files` flags.

**Comment by TahsinAbrar** [comment]
I am facing this issue with SFTP driver, though FTP is working smoothly. I've set up the sftp driver in the `config/filesystems.php` like this:

```
    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],
        'sftp' => [
            'driver' => 'sftp',
            'host' => env('SFTP_HOST'),
            'username' => env('SFTP_USERNAME'),
            'password' => env('SFTP_PASSWORD'),

            // Settings for SSH key based authentication...
            // 'privateKey' => base_path() . '/key/backup_id_rsa', // also tried with this
           //  'password' => env('SFTP_ENCRYPTED_PASSWORD'),

            // Optional SFTP Settings...
            // 'port' => 22,
            // 'root' => storage_path('backup'),
            // 'timeout' => 30,
        ],
```

Also, updated the `config/backup.php` files like this:
```

        'destination' => [
            'disks' => [
                'local',
                'sftp'
            ],
        ],
```

```
    'monitorBackups' => [
        [
            'name' => config('app.name') . '_'. env('APP_ENV') . '_backup',
            'disks' => ['local', 'sftp'],
            'newestBackupsShouldNotBeOlderThanDays' => 1,
            'storageUsedMayNotBeHigherThanMegabytes' => 5000,
        ],
```

What is wrong in my case?
