### ISSUE TITLE
Saving to spatie/flysystem-dropbox

### ISSUE THREAD

**Issue by nam-co** [spatie/laravel-backup#438]
Hi Freek+, thanks for the package, hope you can help me, the package was working perfectly (v4) and saving the file to dropbox, but since I updated the filesystem to spatie/flysystem-dropbox, its stop, I was wondering if there something special I need to do? have you had a chance to test it?

Appreciate any help
Thanks

**Comment by freekmurze** [comment]
Take a look at the `Updating Laravel applications` section here: https://murze.be/2017/04/dropbox-will-turn-off-v1-of-their-api-soon-its-time-to-update-your-php-application/

**Comment by sudden-break** [comment]
I this issue still open? I have it working, maybe I can help.

**Comment by nam-co** [comment]
Hi Sudden for the help, I think the problem is in the DropboxFilesystemServiceProvider.php I didn't modify it, because I decided to wait for 5.5 so its integrated
