### ISSUE TITLE
mongodb backups have the .sql suffix in filename, leading to loss of backup if backing up dbs with same name

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-backup#439]
I am backing up both a mysql and mongodb database. As it happens, the name of the database is the same for both database systems "mydb". And I have gzip enabled

So first it backed up the mysql and gzipped it to mydb.sql.gz, then the mongodb was backed up and the name was the same mydb.sql.gz (should be mydb.mongo.gz)

then it was packaged into a file with datestamp, but by then the sql zipped had been overwritten

**Comment by freekmurze** [comment]
This is a bug. I'd accept a PR that makes sure that when backing up multiple databases with the same name, dump files don't get overwritten.

**Comment by vesper8** [comment]
haha I see what you did there ;)

there you go, my first spatie PR 

https://github.com/spatie/laravel-backup/pull/440
