### ISSUE TITLE
0 bytes file on S3

### ISSUE THREAD

**Issue by andriytkachiv** [spatie/laravel-backup#44]
Hi, I am using your great plugin with S3 filesystems. From some times when I have 3500 files zipped in backup it fails to upload it on S3 without any error. ZIp file on S3 has 0 bytes. php artisan backup:run doesn't show any error, it returns success.
I have enough space on s3 (it is empty right now) 
When I upload only mysql db without files (changed it in config) everything works.

Do you know what could cause it?

Regards

**Comment by freekmurze** [comment]
I don't know the reason why this would fail.

Could you please check if the backup contains 0 bytes when using the local filesystem? Are you sure that you've correctly setup the included and excluded files and directories in the config file?

**Comment by andriytkachiv** [comment]
It is set corrected. When there was less files it worked as a charm.
It's a pity but local also failed :( 

![screenshot from 2015-09-05 22 54 52](https://cloud.githubusercontent.com/assets/9977880/9701276/ee65f1c6-5421-11e5-9fca-6137e741a886.png)

**Comment by freekmurze** [comment]
Can you see an error in the log files?

**Comment by andriytkachiv** [comment]
No, there is no errors

**Comment by freekmurze** [comment]
'm not aware of any restriction on how many files this package can backup. I suspect there's something wrong at your end. Of course I cannot be 100% sure.

Could you try setting the package up in a way so it'll have to backup less files? Let me know if that works.

**Comment by andriytkachiv** [comment]
I tried it, yes it works with less files.

**Comment by freekmurze** [comment]
I'm trying to recreate your problem by backupping 5000 files on my local system and it worked without any problem. 

Can you tell me how MB you are trying to backup? Does the zipping the files take an unusual amount of time? Can you make sure your disk isn't full?

**Comment by andriytkachiv** [comment]
Holy cow.. You made my day! The problem was with free size on disk, because plugin doesn't remove temp files. I suggest to add error throwing in case of lack of space.

Thanks for helping!
