### ISSUE TITLE
BackupCollection size error

### ISSUE THREAD

**Issue by jjrob114** [spatie/laravel-backup#443]
Hello, I'm getting this error when I go to run a backup.  Most of the process appears to be running correctly, but I haven't been able to figure out why I'm getting this error and if it's going to effect trying to run backups in production.  Can you help?
```
Starting backup...
Dumping database mochamoes.dev...
Determining files to backup...
Zipping 7982 files...
Created zip containing 7982 files. Size is 1.77 GB
Copying zip to disk named local...
Successfully copied zip to disk named local.


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Return value of Spatie\Backup\BackupDestination\BackupCollection::size() must be of the type integer, float returned
```
Thanks in advance!

**Comment by freekmurze** [comment]
Hi, I've tagged an new release that fixes this.
