### ISSUE TITLE
[Question] Running only on specified Environment

### ISSUE THREAD

**Issue by lucadegasperi** [spatie/laravel-backup#448]
Hello,
Is there a way to run scheduled commands only on specified environment?
I want to run my backups only on the production environment but not on the staging one.
Is the following example sufficient?
```php
if(env('APP_ENV') == 'production') {
    $schedule->command('backup:run')->daily();
}
```

**Comment by freekmurze** [comment]
Look like you could do it that way yes.

You could try if this works (which is a bit cleaner imho)

```php
if(app()->environment('production')) {
    $schedule->command('backup:run')->daily();
}
```

Or you could opt not add the `schedule:run` to the cron in the environment where backups shouldn't run.

**Comment by lucadegasperi** [comment]
Fantastic, thanks!
