### ISSUE TITLE
Error in db backup

### ISSUE THREAD

**Issue by microdesign** [spatie/laravel-backup#45]
$ php artisan backup:run --only-db
Start backing up
Could not create backup of db - <br />//vendor/spatie/laravel-backup/src/BackupHandlers/Database/DatabaseBackupHandler.php - <br />44 - <br />

                                 
  [Exception]                    
  Could not create backup of db

**Comment by freekmurze** [comment]
Could you make sure that mysqldump is installed on your system?

**Comment by microdesign** [comment]
Yep and it is pointed in my config file: 
'dump_command_path' => '/Applications/MAMP/Library/bin/mysqldump',

**Comment by freekmurze** [comment]
That looks ok. Could you try to make a backup manually with mysqldump and see if that works?

**Comment by microdesign** [comment]
Work like machine if I manualy run backup in my terminal

**Comment by freekmurze** [comment]
Strange... do you have enough free space on your machine?

**Comment by microdesign** [comment]
:) yes of course I have - I run manual dump - I think to go to the place in code where this error is caused and see what is there.

Thanks

**Comment by freekmurze** [comment]
k cool, let me know what you find

**Comment by microdesign** [comment]
It was because I point to file not to directory of mysqldump file

'dump_command_path' => '/Applications/MAMP/Library/bin/mysqldump',

just change it to 

'dump_command_path' => '/Applications/MAMP/Library/bin/',

Maybe it is better for developer to know - when you throw the Exception to send also the  messaga
which is returned from $this->getDatabase()->dump($tempFile);


Now I have message in my terminal 


Database dumped
Start zipping 1 files...
Zip created!
Start uploading backup to local-filesystem...
Backup stored on local-filesystem in file "{PATH}/storage/backups/20150924172521.zip"

but no file actualy is there. Folder have writing permmisions.

**Comment by microdesign** [comment]
Anyone ?

**Comment by freekmurze** [comment]
What is the output of `config('laravel-backup')`?

**Comment by microdesign** [comment]
Array
(
    [source] => Array
        (
            [files] => Array
                (
                    [include] => Array
                        (
                            [0] => /Users/{user}/Desktop/Projects/{project}/
                        )

                    [exclude] => Array
                        (
                            [0] => /Users/{user}/Desktop/Projects/{project}/storage
                            [1] => /Users/{user}/Desktop/Projects/{project}/vendor
                        )

                )

            [backup-db] => 1
        )

    [destination] => Array
        (
            [filesystem] => Array
                (
                    [0] => local
                )

            [path] => /Users/{user}/Desktop/Projects/{project}/storage/backups
            [prefix] => 
            [suffix] => 
        )

    [clean] => Array
        (
            [maxAgeInDays] => 90
        )

    [mysql] => Array
        (
            [dump_command_path] => /Applications/MAMP/Library/bin/
            [useExtendedInsert] => 
            [timeoutInSeconds] => 2.13123123213E+20
        )

)

Note that I use database backup only

**Comment by freekmurze** [comment]
The path in `destination.filesystem.path` is relative to the path you specified for the `local` disk in `config/filesystems.php`. 

If you are using the Laravel defaults you'll find your backups in `storage_path() . '/app/backups'` if you specify 'backups' in `destination.filesystem.path`

**Comment by microdesign** [comment]
Thanks I understand now - how you build the path where file must be stored.

Thanks for help and keep going with the great work

**Comment by freekmurze** [comment]
:+1:

**Comment by microdesign** [comment]
Not sure where to put 'dump_command_path' => '/Applications/MAMP/Library/bin/mysqldump',
 this in your new version of the config

**Comment by projct1** [comment]
I use windows 10 and mysqldump places in `D:\WEB\modules\database\MySQL-5.7-x64\bin`
I trying this config in `database.php`:
```php
'connections' => [
    'mysql' => [
        'dump_command_path' => 'D:\WEB\modules\database\MySQL-5.7-x64\bin'
    ]
]
```
But anyway getting error `Backup failed because The dump process failed with exitcode 1 : General error : '"mysqldump"' is not recognized as an internal or external command, operable program or batch file.`
