### ISSUE TITLE
mongodb dump is gzipped twice

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-backup#451]
@SandeeshS @freekmurze 

just had a hell of a time restoring the mongodb dump and after 1 hour+ I realized the problem.

For some reason that I don't understand, gzip is applied twice.

in my laravel-backup.php I do have
```
'gzip_database_dump' => true,
```

When running the backup, both the mysql and mongodb are dumped, gzipped and then added to a timestamp zipped file

I downloaded this archive containing both database zips and unzipped it which produced

mongodb-mydb.sql.gz
and
mysql-mydb.sql.gz

I then unzipped each file. Whether I do it using Keka in OSX or using gunzip. The mysql file expands considerably, the sql is ~4 times bigger and is readable

I do the same thing on the mongodb-mydb.sql.gz and the .gz is removed but the file size is the same. I should have clued in to this faster but just did not expect this problem.

After much troubleshooting I decided to rename the .sql to .sql.gz and from this file I was able to restore using

```
mongorestore --drop --gzip --archive=./mongodb-mydb.sql.gz --db=mydb
```

Easy fix, just rename the file to mongodb-mydb.sql.gz.gz

Why it's happening exactly I'm not sure.

**Comment by SandeeshS** [comment]
@vesper8 @freekmurze This happens because of the default dumping command in the `db-dumper` package. Gzip compression is applied by default on the mongodb database with the package. You can check it here https://github.com/spatie/db-dumper/blob/master/src/Databases/MongoDb.php#L82.

Moving `--gzip` from the default command to an optional command should fix this.

**Comment by freekmurze** [comment]
I've tagged a new release of `spatie/db-dumpber` where MongoDb's won't be compressed anymore by default. 

After you've pulled that version in with `composer update` Mongo Db's won't be compressed twice anymore.
