### ISSUE TITLE
Encrypt backup

### ISSUE THREAD

**Issue by EmilMoe** [spatie/laravel-backup#452]
How about a config (or env) with an optional encryption key so the compressed file could be encrypted, so that in case any stranger finds the backups on the remote location, he can't access them without the key.

I was looking at the docs and it seems not to be possible at the moment:
* https://docs.spatie.be/laravel-backup/v4/taking-backups/overview
* https://github.com/spatie/laravel-backup/blob/master/config/laravel-backup.php

I would be happy to help implementing the feature, but let's agree on it first.

**Comment by freekmurze** [comment]
You already can do anything you want with the zip file, including encrypting it manually, by leveraging the [`BackupZipWasCreatedEvent`](https://docs.spatie.be/laravel-backup/v4/taking-backups/events#backupzipwascreated)

I'm open to a simple, fully tested PR that adds encryption out of the box. Unless it's very very simple, the actual code to encrypt files would live in a separate package, outside of laravel-backup. That encryption package could be pulled in as a dependency (maybe such a package exist already). Adding a config value to enable the feature sounds good.

**Comment by torrancemiller** [comment]
Let me know if anyone finds a package that does this like Freek is saying above.

Thanks in Advance!
-Tor

**Comment by EmilMoe** [comment]
I just wanted to update with the new PHP 7.2 feature for doing it. But as the package requirement is 7.0 I understand that it's not possible to implement this approach. I will be making a fix for myself and sharing it here.

https://stackoverflow.com/a/47589645

**Comment by EmilMoe** [comment]
@freekmurze 

I think you can edit `Zip.php` after `$this->zipFile->addFile($file, ltrim($nameInZip, DIRECTORY_SEPARATOR)).PHP_EOL;` at line `103` by inserting this after:

```
$this->zipFile->addFile($file, ltrim($nameInZip, DIRECTORY_SEPARATOR)).PHP_EOL;

if (config('backup.backup.password') !== '') {
  $zip->setEncryptionName($file, \ZipArchive::EM_AES_256, config('backup.backup.password');
}
```

It probably needs a few tweaks, but I hope you get the idea.

**Comment by olssonm** [comment]
I know that this issue is closed; but I have a package that does exactly this (uses BackupZipWasCreatedEvent to password-protect the backup). Just want to point it out here as the first Google-results lead here. Take a look at https://github.com/olssonm/laravel-backup-shield.

v1.1 supports even supports PHP5.6 (for Laravel 5.2) and after that PHP ^7.0. 

Ping @torrancemiller @EmilMoe.

**Comment by ultrono** [comment]
https://simonkollross.de/posts/creating-encrypted-backups-of-laravel-apps is a worth a read. No additional packages required.

**Comment by hsleewis** [comment]
@ultrono When using that exact example I get this error:

`ZipArchive::close(): Invalid argument`

That's on php7.4 any clue what could cause that?
