### ISSUE TITLE
Not registering backup command!

### ISSUE THREAD

**Issue by vipin733** [spatie/laravel-backup#455]
I'm using laravel 5.4.24 and php7.1 and i follow all instruction related installation and when i tried to publish "laravel-backup.php" , here what i got
```
php artisan vendor:publish --provider="Spatie\Backup\BackupServiceProvider"
Publishing complete.
```
but there is no file generated in my config folder even no backup command register 
whats wrong!

**Comment by freekmurze** [comment]
Try clearing your configuration cache

php artisan cache:clear

and try again
