### ISSUE TITLE
What do you use a PHP framework

### ISSUE THREAD

**Issue by hiwangqi** [spatie/laravel-backup#459]
American companies use most of the PHP framework is laravel？

**Comment by freekmurze** [comment]
This question is not relevant to laravel-backup. When using an issue tracker on GitHub try to stick to questions relevant to the repository.

If you have questions about Laravel in general it's best to use a general channels such as [Larachat](https://larachat.co/), [Laravel.io](https://laravel.io/forum) or the [Laracasts forums](https://laracasts.com/discuss) to ask questions.

That being said here is [a nice Google Trends graph showing which PHP frameworks are queried most in America](https://g.co/trends/3AxHV). Draw your own conclusions.
