### ISSUE TITLE
Multiple backups

### ISSUE THREAD

**Issue by eriktobben** [spatie/laravel-backup#46]
Hi!

Is it possible to create multiple backups?
I am running a job every night for the db, and one weekly for the whole base_path.

But I want to run a daily backup of uploaded files only. Could this be done with flags or some other solution?

**Comment by freekmurze** [comment]
I'm working on adding a "only-files" flag. Take a look here: https://github.com/spatie/laravel-backup/tree/feature/only-files

Still need to do tests. I'll release it in the coming week.

**Comment by freekmurze** [comment]
The "only-files" flag is available in version 2.7.0
