### ISSUE TITLE
Type error: Argument 2 passed to BackupDestination::create() must be of the type string, null given

### ISSUE THREAD

**Issue by JoeDawson** [spatie/laravel-backup#460]
Hello,

I'm trying to setup this package on one of my existing 5.4 projects, simply required using composer and registered the service provider.

Also published the config, kept as default.

When running a backup, I'm seeing this error?

```
php artisan backup:run
Starting backup...


[Symfony\Component\Debug\Exception\FatalThrowableError]
Type error: Argument 2 passed to Spatie\Backup\BackupDestination\BackupDestination::create() must be of the type string, null given, called in /Users/joedawson/Code/my-project/vendor/spatie/laravel
-backup/src/BackupDestination/BackupDestinationFactory.php on line 13
```

As I said, this is a fresh install of `laravel-backup` and I haven't touched any of the configuration options.

It's also worth noting, this error is thrown with any of the `php artisan backup:*` artisan commands.

Any ideas why I might be getting this?

Many thanks

**Comment by freekmurze** [comment]
Are you perhaps caching your config values?

Try running `php artisan config:clear` and try running the backup again.

**Comment by JoeDawson** [comment]
Hey Freek,

I don't believe so - I ran `php artisan config:clear` to be sure though.

```
$ php artisan config:clear
Configuration cache cleared!
$ php artisan backup:run
Starting backup...

[Symfony\Component\Debug\Exception\FatalThrowableError]
Type error: Argument 2 passed to Spatie\Backup\BackupDestination\BackupDestination::create() must be of the type string, null given, called in /Users/joedawson/Code/my-project/vendor/spatie/laravel
-backup/src/BackupDestination/BackupDestinationFactory.php on line 13
```

**Comment by freekmurze** [comment]
Perhaps you didn't set an `APP_URL` environment variable?

What's the value of `config('laravel-backup.backup.name')`?

**Comment by JoeDawson** [comment]
🙈 Oops! I didn't have an `APP_URL` set - never have lol. Mine's just hardcoded in `config/app.php` lol.

```
'url' => env('APP_URL', 'https://myproject.com'),
```

Appreciate the help!

**Comment by patriziotomato** [comment]
Falled into same problem wouldn't it better to use this in your default config file:

    config('app.name')

instead accessing .env directly?
