### ISSUE TITLE
Suppress email notification via command line

### ISSUE THREAD

**Issue by justinliebregts** [spatie/laravel-backup#461]
Hi,

I'm using the Laravel schedule() to schedule hourly database backups.  I'm using the 'backup:run --only-db' command.  Is there a way I can specify not to generate a notification for this?  e.g. 'backup:run --only-db --ignore-notification'.

I like receiving notifications when I do normal backups 'backup:run', but the hourly notification is a bit much.  Thanks!

**Comment by freekmurze** [comment]
I'd accept a backwards compatible fully tested PR that adds a `--no-notifications` option to all the relevant commands.

**Comment by justinliebregts** [comment]
This is amazing.  You guys rock!  My inbox and I thank you so much.  Also, really love this backup tool you've created.  Thanks again!
