### ISSUE TITLE
File Backup on Windows not working

### ISSUE THREAD

**Issue by sudden-break** [spatie/laravel-backup#463]
I was backing up the public folder + the db.
DB get's zipped without a problem and also the file zipping doesn't throw an error.
But in the end the zipped archive only contains the db dump.

![snag-0972](https://user-images.githubusercontent.com/1845379/27118672-ad74e816-50dc-11e7-84b1-08e8321f218f.jpg)
![snag-0970](https://user-images.githubusercontent.com/1845379/27118673-ad768022-50dc-11e7-8c5c-b5aeab576848.jpg)
![snag-0969](https://user-images.githubusercontent.com/1845379/27118674-ad789682-50dc-11e7-8336-530a31345399.jpg)

**Comment by freekmurze** [comment]
What is the size of the zip?

**Comment by sudden-break** [comment]
3.51mb

**Comment by sudden-break** [comment]
![image](https://user-images.githubusercontent.com/1845379/27128443-c504c4d4-50fe-11e7-94a5-655591247da1.png)
I was able to open the zip with 7zip and found the files, but they are not visible via the windows explorer

**Comment by freekmurze** [comment]
Not going to invest any time in this myself as this problem is something windows specific and the zip itself contains the right files.

If you find a solution I'm happy to merge a simple fix

**Comment by arcanedev-maroc** [comment]
Hi @freekmurze,

With the new GitHub Actions, you can test the package with multiple OS.

This is what i got after cloning the latest version & launching phpunit in windows:

![2019-10-13_23-12-08](https://user-images.githubusercontent.com/3282340/66723291-25f14600-ee0f-11e9-9d28-53389085bc5a.jpg)

**Comment by mrengineer19** [comment]
try this : https://github.com/spatie/laravel-backup/issues/540#issuecomment-461849217
