### ISSUE TITLE
Unable to use Database notifications

### ISSUE THREAD

**Issue by jove4015** [spatie/laravel-backup#466]
I struggled to implement database notifications with this class.  The key issues were:

a) The Notifiable class did not extend Model, which the DatabaseNotification class was expecting

b) There was no toArray or toDatabase method on the notifications

I'm working on a pull request now.  It may not be perfect but at least it allows it to work.  I also had to add a migration to allow for a NULL notifiable_id in the notifications table, since the Notifiable "Model" does not have any ID per se in this case.

Altogether, this feels clunky.  I think it may be worth updating the database notifications themselves to make such a relationship optional - they seem to assume that all notifications will go to Users of the application, which isn't really practical in the context of CLI command.

**Comment by freekmurze** [comment]
We'll handle this further in #467
