### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by microdesign** [spatie/laravel-backup#47]
Everything with this package run great on local environment, but when I upload it to my server - the server go down without error or something just 'error 500'.

Any ideas?

**Comment by microdesign** [comment]
Maybe your question will be if there is mysqldump installed - Yes there is.

**Comment by freekmurze** [comment]
Could you try looking in your app/server logs for a more specific error message? If nothing is there try to add a try catch statement to see where the code is failing.

**Comment by freekmurze** [comment]
Reopen this if still are having problem and have a bit more detail regarding the error.

**Comment by microdesign** [comment]
This is the problem - package throw unformative errors 'Could not create backup of db' . Other problem is it working well on my local machine and when I upload it to live website then the package stop working.

**Comment by microdesign** [comment]
This is from error log

[2015-10-23 09:55:52] production.ERROR: exception 'Exception' with message 'Could not create backup of db' in /var/www/getsmartfi.com/vendor/spatie/laravel-backup/src/BackupHandlers/Database/DatabaseBackupHandler.php:44
Stack trace:
#0 /var/www/getsmartfi.com/vendor/spatie/laravel-backup/src/BackupHandlers/Database/DatabaseBackupHandler.php(57): Spatie\Backup\BackupHandlers\Database\DatabaseBackupHandler->getDumpedDatabase()
#1 /var/www/getsmartfi.com/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(252): Spatie\Backup\BackupHandlers\Database\DatabaseBackupHandler->getFilesToBeBackedUp()
#2 /var/www/getsmartfi.com/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(68): Spatie\Backup\Commands\BackupCommand->getDatabaseDump(Array)
#3 /var/www/getsmartfi.com/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(35): Spatie\Backup\Commands\BackupCommand->getAllFilesToBeBackedUp()
#4 [internal function]: Spatie\Backup\Commands\BackupCommand->fire()
#5 /var/www/getsmartfi.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(526): call_user_func_array(Array, Array)
#6 /var/www/getsmartfi.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(115): Illuminate\Container\Container->call(Array)
#7 /var/www/getsmartfi.com/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Con$
#8 /var/www/getsmartfi.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\C$
#9 /var/www/getsmartfi.com/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutp$
#10 /var/www/getsmartfi.com/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\In$
#11 /var/www/getsmartfi.com/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Outp$
#12 /var/www/getsmartfi.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(94): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Ou$
#13 /var/www/getsmartfi.com/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}
