### ISSUE TITLE
The Dropbox SDK uses 64-bit integers

### ISSUE THREAD

**Issue by andikas** [spatie/laravel-backup#470]
Hi All,

I need help on this,
I got error when trying to backup my laravel apps to dropbox.

![image](https://user-images.githubusercontent.com/25953422/27378053-d7370926-56a0-11e7-9471-09f23a29d1c7.png)

if I follow a solution from stackoverflow, by disable function line 19 at requestutil.php it works.
Do I have to disable that function? does it will take any effect later?
Please help me how to solve this.

Thanks,
Cheers,

**Comment by freekmurze** [comment]
This error is not related to this package, but to [dropbox/dropbox-sdk](https://github.com/dropbox/dropbox-sdk-php). Better to post the issue there.

Or even better, upgrade to the latest version of their API. Dropbox will switch off v1 of the API in a few days. Here's how to upgrade: https://murze.be/2017/04/dropbox-will-turn-off-v1-of-their-api-soon-its-time-to-update-your-php-application/
