### ISSUE TITLE
Google drive message error

### ISSUE THREAD

**Issue by greatsami** [spatie/laravel-backup#472]
Hi, 

I setup google drive and its successful with upload any file to Google Drive storage.

when i setup it with laravel-backup i have error message when i run (php artisan backup:run):

```
/var/www/# php artisan backup:run

Starting backup...
Dumping database laravel_almeyyah...
Determining files to backup...
Zipping 3664 files...
Created zip containing 3664 files. Size is 482.71 MB
Copying zip to disk named google...

Copying zip failed because: Invalid request.  The number of bytes uploaded is required to be equal or greater than 262144, 
except for the final request (it's recommended to be the exact multiple of 262144).  
The received request contained 8192 bytes, which does not meet this requirement..

Backup completed!
```

I tried to solve this issue manually and i success in upload side, but the email received it tell me the backup is failed.

my solution is: edit (write function) in:
vendor/spatie/laravel-backup/src/BackupDestination/BackupDestination.php

```
if (is_null($this->disk)) {
	throw InvalidBackupDestination::diskNotSet();
}

$destination = pathinfo($file, PATHINFO_DIRNAME).'/'.pathinfo($file, PATHINFO_BASENAME);
\Storage::disk('google')->put(''.pathinfo($file, PATHINFO_BASENAME).'', file_get_contents($destination));

/*
$destination = $this->backupName.'/'.pathinfo($file, PATHINFO_BASENAME);
$handle = fopen($file, 'r+');
$this->disk->getDriver()->writeStream($destination, $handle);
if (is_resource($handle)) {
	fclose($handle);
}
*/
```

the laravel.log store error:
```
{
    "error": {
         "errors": [
             {
                 "domain": "global",
                 "reason": "notFound",
                 "message": "File not found: .",
                 "locationType": "parameter",
                 "location": "fileId"
            }
        ],
        "code": 404,
        "message": "File not found: ."
    }
}
```

Any solution for this issue?

Regards

**Comment by greatsami** [comment]
@freekmurze please can you see this issue.

**Comment by freekmurze** [comment]
Hi, I'm not a Google Drive user, so this issue is kinda low on my priority list. I suggest you Google a bit around for that error message and try to figure out why it's giving that error. Pretty sure it's something Google Drive specific. Please report back here if you find the root cause / solution.

**Comment by vitorfavila** [comment]
I have the same problem!

**Comment by sudar** [comment]
I am facing the same problem and may have found the reason. See https://github.com/spatie/laravel-backup/issues/468#issuecomment-316344650

But I am not sure how to solve it yet.

**Comment by introwit** [comment]
Let's keep both the similar discussions in a single thread : #468
