### ISSUE TITLE
Uncaught ReflectionException: Class mailer on composer install in the server

### ISSUE THREAD

**Issue by Otienoh** [spatie/laravel-backup#473]
Hello guys getting this error when I composer install, have come across this kind of thing?
PHP Fatal error:  Uncaught ReflectionException: Class mailer does not exist in /.../vendor/laravel/framework/src/Illuminate/Container/Container.php:719

**Comment by freekmurze** [comment]
Your problem is related to something that goes wrong very early on in the framework. It could be anything really: from a syntax error in a config file to service providers in the wrong order (or doing something nasty)

Closing this because it's probably not related to this package.
