### ISSUE TITLE
laravel-backup php version issue with laravel v5.4.

### ISSUE THREAD

**Issue by anmolio** [spatie/laravel-backup#474]
I am using laravel v5.4 but the php version in it is 5.6 and in that case laravel-backup v4 is not working. What should I do ? Do I need to switch to the lower version of laravel-backup ?

**Comment by freekmurze** [comment]
The best thing you could to is to upgrade the PHP version on your server. 

If you cannot do that, you can use `v3` of our backup package. It's not maintained anymore, but should be pretty stable.
