### ISSUE TITLE
Artisan call doesn't work

### ISSUE THREAD

**Issue by Cr1xusDigital** [spatie/laravel-backup#476]
If I run php artisan backup:run --only-db in the command line, it works perfectly, but if I try to do this with Artisan::call, nothing happens
PHP:
```
<?php

namespace App\Http\Controllers;
use Validator;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use DB;
use Artisan;

class CmsController extends Controller
{
    public function migrate(){
        $tmp=Artisan::call('backup:run',['--only-db'=>true]);
        dd($tmp);
    }
}
```
database.php: 
```
'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
            'dump' => [ 'dump_binary_path' => 'C:\Program Files\MySQL\MySQL Server 5.7\bin' ]
        ],
```
What am I doing wrong?

**Comment by Cr1xusDigital** [comment]
the problem seemed to be windows -_-

**Comment by PerJoy** [comment]
Today I also encountered this problem.
The query to the problem is 'mysqldump' does not have permission.
can't write sql in file

**Comment by Gogtsu** [comment]
ok so its server side permission i dont have access to. thanks ill talk to
the administration

**Comment by BashirRezaiee** [comment]
I have the same problem on windows, Is there any solution?

**Comment by ahnayem** [comment]
You need to create virtualHost first on your local server. Then It will work fine!

Follow the link for a details solution

[githubhot.com/repo/Codexshaper/laravel-database-manager/issues/11](https://githubhot.com/repo/Codexshaper/laravel-database-manager/issues/11)
