### ISSUE TITLE
Customizable username and icons for slack notifications

### ISSUE THREAD

**Issue by Hooolm** [spatie/laravel-backup#479]
Have you entirely disallowed customization for username and icon on the slack notifications? 

I have this is my config:
```php
'slack' => [
	'webhook_url' => '*MY_WEBHOOK*',

	/*
	 * If this is set to null the default channel of the webhook will be used.
	 */
	'channel' => null,
	'username' => 'Backup bot',
	'icon'     => 'robot',
],
```

Using version 4.18

**Comment by freekmurze** [comment]
I prefer to use separate webhooks for each application. In that way you can set the username, icon on the webhook itself when you create it on Slack.
