### ISSUE TITLE
Error getting database server config

### ISSUE THREAD

**Issue by omardavila64** [spatie/laravel-backup#48]
Sorry my English is bad.

I edit your code because i have multiple servers configurations, example:

config/database.php
         'default' => 'server1',

         'server1' => [
			'driver'    => 'mysql',
			'host'      => '127.0.0.1,
			'database'  => 'db_1',
			'username'  => 'user_1',
			'password'  => 'pass_1',
			'charset'   => 'utf8',
			'collation' => 'utf8_unicode_ci',
			'prefix'    => '',
			'strict'    => false,
		],

        'server2' => [
			'driver'    => 'mysql',
			'host'      => '127.0.0.1,
			'database'  => 'db_2',
			'username'  => 'user_2',
			'password'  => 'pass_2',
			'charset'   => 'utf8',
			'collation' => 'utf8_unicode_ci',
			'prefix'    => '',
			'strict'    => false,
		],

Your code:
File: Spatie\Backup\BackupHandlers\Database\DatabaseBackupHandler
$database = $database ?: config('database.default');

In my exaple $database = server1 and $database != "mysql" then error : laravel-backup can only backup mysql databases

My changes:
File: Spatie\Backup\BackupHandlers\Database\DatabaseBackupHandler

$db_server = config('database.default');

$database = $database ?: config('database.connections.' . $db_server . '.driver');

$database = mysql

Backup successfully completed.!!

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention. I'll fix it soon.

**Comment by freekmurze** [comment]
This is fixed in v2.8.1
