### ISSUE TITLE
Error with Dropbox

### ISSUE THREAD

**Issue by sairam2188** [spatie/laravel-backup#480]
Hi,
When i run the backup i'm getting the following error:

php artisan backup:run
Starting backup...
Dumping database asegurad_app-getklients...
Determining files to backup...
Zipped 646 files...
Copying 2017-07-13-162537.zip (size: 714.8 KB) to disk named dropbox...
**Copying .zip file failed because: Unexpected HTTP status 403
{"api_error": true, "user_error": "This app is currently disabled.", "error": "This app is currently disabled."}.**
Backup completed!

Any solution for this issue?
Regards

**Comment by freekmurze** [comment]
I'm thinking it has something to do with your specific app that you created on Dropbox. 

Is that app disabled?

**Comment by introwit** [comment]
It might be because of Incorrect app key or access token for Dropbox at your end. More info is [here](https://www.dropboxforum.com/t5/API-support/This-app-is-currently-disabled/td-p/159318).
