### ISSUE TITLE
Not excluding  vendor directory 

### ISSUE THREAD

**Issue by Younesi** [spatie/laravel-backup#481]
Hi, I've  set the config like below:

 `'exclude' => [
                    base_path('vendor'),
                    base_path('node_modules'),
                ],`

but when I try to create a backup it gives me this error:

`Backup failed because ZipArchive::close(): Read error: No such file or directory.`

It seems like it's **not excluding vendor directory** which causes the error

**Comment by freekmurze** [comment]
The test seem to indicate that file selection is working properly. Could you PR a failing test for me to work on?

Could this problem be cause by some cacheing directory that you're backing up that is changed while backing up?

**Comment by Younesi** [comment]
Unfortunately I could not test! would you show me how to do that?

Worth to mention: I am trying to create backup on shared-host with SSH access, my project  is in home directory of Cpanel and I have changed the root to public_html

FYI, **when I change config** to:
`'include' => [
                    base_path('app'),
                    base_path('bootstrap'),
                    base_path('config'),
                    base_path('database'),
                    base_path('public_html')
                ]`

which I'm not including **vendor** directory then **I get a successful backup** on my **Dropbox **

**Comment by freekmurze** [comment]
I could not recreate the problem with the latest version of the package. Could you try to see if the problem is also occurring when you use other hosting or a local machine?

**Comment by Younesi** [comment]
Unfortunately I'm on Windows OS and when I tried to run backup command it gave me _''mysqldump'' is not recognized as an internal or external command, operable program or batch file._
I will make a head of it and fix the problem. thanks
