### ISSUE TITLE
Issue with  $backups->oldest()->delete();

### ISSUE THREAD

**Issue by elnurxf** [spatie/laravel-backup#483]
Hi. Thanks for your package.

Default strategy throws an error:

Symfony\Component\Debug\Exception\FatalThrowableError
Call to a member function delete() on null

vendor/spatie/laravel-backup/src/Tasks/Cleanup/Strategies/DefaultStrategy.php in removeOldBackupsUntilUsingLessThanMaximumStorage at line 116

No issues with file permissions or related. All configurations are default. using local storage.

**Comment by freekmurze** [comment]
So you don't have taken any backups at all?

**Comment by elnurxf** [comment]
Backups are running as expected. Then It comes to delete outdated/reaching total backup limit It's throws an error.

Here is logs: https://pastebin.com/jWfJR0Mv

**Comment by freekmurze** [comment]
I can't recreate this problem. Could your PR a failing test?

**Comment by elnurxf** [comment]
Could you please point me how to do the test?

**Comment by freekmurze** [comment]
Take a look at the code contained in the `tests` directory. You can run all tests with `vendor/bin/phpunit`. If you need more info best to read some tutorials on PHPUnit.

**Comment by dgpro** [comment]
Same problem here. It looks like it fails to delete AWS S3 backups but it does delete my sftp files.
```
Symfony\Component\Debug\Exception\FatalThrowableError Call to a member function delete() on null 
```
[Full log](https://gist.github.com/dgpro/517e4e20177b4a528e3776a54854ec0a)

Ubuntu 16.04.2 LTS
Laravel Framework 5.4.28
PHP 7.1.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul  7 2017 09:41:45) ( NTS )
spatie/laravel-backup: 4.18.1
league/flysystem-aws-s3-v3: 1.0.18

[Laravel backup config](https://gist.github.com/dgpro/6bb9a2bfacfe33622203dae9be269b16)

**Comment by elnurxf** [comment]
In my case I use only local disk to store bu error occurs.

**Comment by freekmurze** [comment]
I can't recreate this problem. Could anyone that has this problem PR a failing test?

**Comment by biocoderh** [comment]
#491

**Comment by freekmurze** [comment]
This problem has been fixed by @biocoderh in the latest version of the package.
