### ISSUE TITLE
List command not working with custom disk

### ISSUE THREAD

**Issue by palpalani** [spatie/laravel-backup#484]
I am using custom disk called my_local with a folder with outside application. 

When i run ```php artisan backup:run``` it works perfectly. if i run ```php artisan backup:list```, it always checks with local disk and says no backups found.

**Comment by freekmurze** [comment]
Did you set the destination disk name in the monitoring settings to the one where your backups are stored?

https://github.com/spatie/laravel-backup/blob/d57d22b/config/laravel-backup.php#L116

**Comment by palpalani** [comment]
Thanks for the information.

Yes, It is working. I didn't notice this setting before.

I am closing this ticket.
