### ISSUE TITLE
How to listen BackupWasSuccessful event?

### ISSUE THREAD

**Issue by jerearaujo03** [spatie/laravel-backup#486]
I cant listen to BackupWasSuccessful event. I want to upload zip to Google Drive when the backup were created, but i don't know how to know when the BackupWasSuccessful was fired.

**Comment by sebastiandedeyne** [comment]
Please refer to Laravel's docs on events.

https://laravel.com/docs/5.4/events#registering-events-and-listeners

You could register a listener in your `EventServiceProvider`

```php
/**
 * The event listener mappings for the application.
 *
 * @var array
 */
protected $listen = [
   'Spatie\Backup\Events\BackupWasSuccessful' => [
        'App\Listeners\BackupWasSuccessfulListener',
    ],
];
```

**Comment by jerearaujo03** [comment]
And how can i get the name of the backup zip file?

**Comment by sebastiandedeyne** [comment]
In that case, you'll probably want to listen to the `BackupZipWasCreated` event, which has a `pathToZip` property which you can retrieve in your listener.

https://docs.spatie.be/laravel-backup/v4/taking-backups/events#backupzipwascreated

```php
namespace App\Listeners;

use Spatie\Backup\Events\BackupZipWasCreated;

class BackupZipWasCreatedListener
{
    public function handle(BackupZipWasCreated $event)
    {
        dd($event->pathToZip);
    }
}
```

**Comment by jerearaujo03** [comment]
But i'm on V3, because i'm on Laravel 5.2
The only solution is upgrading to V4?

**Comment by sebastiandedeyne** [comment]
In v3, you could listen to the `BackupWasSuccessful` event, and determine the zip file name using the `BackupDestination` instance in the event.

https://docs.spatie.be/laravel-backup/v3/taking-backups/events#backupwassuccessful

It's a bit more of a hassle, but it should be possible!

**Comment by jerearaujo03** [comment]
I'm doing:

    public function handle(\Spatie\Backup\Events\BackupWasSuccessful $event)
    {
        dd($event->backupDestination);

        //Upload to Google Drive
        //Artisan::call('respaldar:run');
    }


But i'm getting:

    Spatie\Backup\BackupDestination\BackupDestination {#740
      #disk: Illuminate\Filesystem\FilesystemAdapter {#739
        #driver: League\Flysystem\Filesystem {#736
          #adapter: League\Flysystem\Adapter\Local {#734
            #pathSeparator: "/"
            #permissionMap: array:2 [
              "file" => array:2 [
                "public" => 420
                "private" => 384
              ]
              "dir" => array:2 [
                "public" => 493
                "private" => 448
              ]
            ]
            #writeFlags: 2
            -linkHandling: 2
            #pathPrefix: "/Users/jeremias/Intranet-Bet-el/storage/app/"
          }
          #plugins: []
          #config: League\Flysystem\Config {#738
            #settings: []
            #fallback: null
          }
        }
      }
      #diskName: "local"
      #backupName: ""
      +connectionError: null
    }


How can i get the backupDestination from $event?

**Comment by jerearaujo03** [comment]
Now i'm doing 
`dd($event->backupDestination->getNewestBackup());`

And getting:
```
Spatie\Backup\BackupDestination\Backup {#748
  #disk: Illuminate\Filesystem\FilesystemAdapter {#739
    #driver: League\Flysystem\Filesystem {#736
      #adapter: League\Flysystem\Adapter\Local {#734
        #pathSeparator: "/"
        #permissionMap: array:2 [
          "file" => array:2 [
            "public" => 420
            "private" => 384
          ]
          "dir" => array:2 [
            "public" => 493
            "private" => 448
          ]
        ]
        #writeFlags: 2
        -linkHandling: 2
        #pathPrefix: "/Users/jeremias/Intranet-Bet-el/storage/app/"
      }
      #plugins: []
      #config: League\Flysystem\Config {#738
        #settings: []
        #fallback: null
      }
    }
  }
  #path: "2017-07-28-113229.zip"
}
```

I see the '#path' (the filename is correct), but how can I access it?

**Comment by jerearaujo03** [comment]
I done doing that:

`$event->backupDestination->getNewestBackup()->path()`

returning 

```
Starting backup...
Dumping database intranet...
Determining files to backup...
Zipped 1289 files...
Copying 2017-07-28-113809.zip (size: 32.29 MB) to disk named local...
Successfully copied .zip file to disk named local.
"2017-07-28-113809.zip"

```

**Comment by rizkhal** [comment]
> Please refer to Laravel's docs on events.
> 
> https://laravel.com/docs/5.4/events#registering-events-and-listeners
> 
> You could register a listener in your `EventServiceProvider`
> 
> ```
> /**
>  * The event listener mappings for the application.
>  *
>  * @var array
>  */
> protected $listen = [
>    'Spatie\Backup\Events\BackupWasSuccessful' => [
>         'App\Listeners\BackupWasSuccessfulListener',
>     ],
> ];
> ```

i do this on laravel 9 and last version of this package but not fired
