### ISSUE TITLE
exceeded the timeout of 60 seconds

### ISSUE THREAD

**Issue by waw3** [spatie/laravel-backup#487]
I keep getting this timeout error
Backup failed because The process "mysqldump --defaults-extra-file="/tmp/php7QNGCa" --skip-comments --extended-insert database > "/opt/laravel/backup/storage/laravel-backups/temp/database.sql"" exceeded the timeout of 60 seconds..
any help?

'dump' => [
			   'dump_binary_path' => '/usr/local/bin', // only the path, so without `mysqldump` or `pg_dump`
			   'use_single_transaction',
			   'dump_command_timeout' => 60 * 5, // 5 minute timeout
			   'timeout' => 60 * 5, // 5 minute timeout
			   'exclude_tables' => [],
			   'add_extra_option' => '--skip-network-timeout', 
			]

**Comment by freekmurze** [comment]
Are you backing up a large database? Then try to increase the timeout of the dumper.

The docs contain an example that shows how to do this.

https://docs.spatie.be/laravel-backup/v4/installation-and-setup#dumping-the-database
