### ISSUE TITLE
How to use ->excludeTables() from spatie/db-dumper into laravel-backup

### ISSUE THREAD

**Issue by blenderdeluxe** [spatie/laravel-backup#488]
Hi I need use excludeTables from spatie/db-dumper into laravel-backup it is possible?

REGARDS!

**Comment by darkhouse** [comment]
There's an example in the docs [https://docs.spatie.be/laravel-backup/v4/installation-and-setup#dumping-the-database](url)

**Comment by blenderdeluxe** [comment]
Oh! Wow so so so sorry I search in the documentation but I dont find maybe because I dont sleep much in days I dont see that.

Thanks so much @darkhouse !
Regards!
