### ISSUE TITLE
Restore a Backup

### ISSUE THREAD

**Issue by behind-design** [spatie/laravel-backup#490]
Hi there I was looking to add this amazing package to our Laravel application and I was wondering, is there an artisan command that could easily restore a specified backup? Or in the case that there's none, how would you go doing it (the easiest way possible)?

Thank you for your attention and help.

**Comment by freekmurze** [comment]
Hi,

restoring stuff is not supported by this package. When something goes wrong, sometimes is must restore the entire db, sometimes it's only a table of a column. Because it's a different solution every time I chose not to automate the restoration.
