### ISSUE TITLE
mongodb without auth

### ISSUE THREAD

**Issue by mostafamaklad** [spatie/laravel-backup#492]
if I have no username and password to the database it raises that error
`error parsing command line options: expected argument for flag -u, --username&#039;, but got option--password'`

**Comment by mostafamaklad** [comment]
In MongoDB@getDumpCommand 

change 
```
        if (isset($this->userName)) {
            $command[] = "--username {$this->userName}";
        }

        if (isset($this->password)) {
            $command[] = "--password {$this->password}";
        }
```
to 
```
        if (isset($this->userName) && !empty($this->userName)) {
            $command[] = "--username {$this->userName}";
        }

        if (isset($this->password) && !empty($this->password)) {
            $command[] = "--password {$this->password}";
        }
```

As the userName set to '' if it is null in DbDumperFactory@createFromConnection
```
        $dbDumper = static::forDriver($dbConfig['driver'])
            ->setHost($dbHost ?? '')
            ->setDbName($dbConfig['database'])
            ->setUserName($dbConfig['username'] ?? '')
            ->setPassword($dbConfig['password'] ?? '');
```

**Comment by freekmurze** [comment]
I'm not a MongoDB user, so I'd appreciate another MongoDB user chiming in here.

**Comment by mostafamaklad** [comment]
you could use
`$command[] = "--username '{$this->userName}'";`
`$command[] = "--password '{$this->password}'";`
instead of 
`$command[] = "--username {$this->userName}";`
`$command[] = "--password {$this->password}";`
As the command must be like this 
`mongodump --archive=test.20150715.archive --db test --username "" --password ""`
not empty space 
check here https://docs.mongodb.com/manual/reference/program/mongodump/

**Comment by AlexVanderbist** [comment]
Opened an issue on the db-dumper repo, feel free to PR a fix there.
