### ISSUE TITLE
AWS HTTP error: cURL error 56: SSL read

### ISSUE THREAD

**Issue by ghost** [spatie/laravel-backup#496]
I'm getting errors when uploading to Amazon S3. They seem to be related to the multipart upload functionality. I think it's unlikely to be the package itself, but rather the underlying AWS packages. Just looking for some clarification...

`Copying zip failed because: An exception occurred while uploading parts to a multipart upload. The following parts had errors:`

`Part 26: Error executing "UploadPart" on "https://[domain].s3.eu-west-2.amazonaws.com/https---www.[domain].com/2017-08-07-10-23-41.zip?partNumber=26&uploadId=W20CX4tN87bapnjzDEqBniRT2Nb8YcNAroP.yHI1CiEv1fxAe1vxQOAs5Bu4uCmtJz1ofGRVlDg0YyiL3A02GdxdNWvrZfLpDs2.U4qJ3fw-";`

`AWS HTTP error: cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)  (server): 100 Continue - `

`- Part 67: Error executing "UploadPart" on "https://[domain].s3.eu-west-2.amazonaws.com/https---[domain]/2017-08-09-18-07-29.zip?partNumber=67&uploadId=8QpZrjYN6C_UzDbMSNF8MWSObOBr.gvyLdZYhSgQbekI_rIzLTte4sCPoVeZgc6Z4Q1k4vR2ZF6RWJ64j3vlHX9phD_SE__cx_Gn8axfWxg-"; `

`AWS HTTP error: cURL error 55: SSL_write() returned SYSCALL, errno = 104 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)  (server): 100 Continue -`

I wondered if this was related to issue [#475](https://github.com/spatie/laravel-backup/issues/475), so I downgraded the AWS package to version 3.31.3, but the problem persists.

I'm running a Linode VPS on Laravel Forge.

Any ideas?

**Comment by thepenguin1** [comment]
Similar issues elsewhere (albeit not specifically laravel-backup):

https://stackoverflow.com/questions/32836603/amazon-s3-upload-error-an-exception-occurred-while-uploading-parts-to-a-multipa

**Comment by thepenguin1** [comment]
I've also been able to confirm that my setup is correct by uploading a file using AWS CLI.

**Comment by rorymcdaniel** [comment]
I'm having the exact same issue, but only on extremely large backups. My compressed backup file size is currently 157gb (lots and lots of user uploaded content we can't afford to lose). Whenever I do a database only backup, which is obviously much smaller, it uploads to S3 without any problems. I'm on an AWS EC2 instance provisioned by Laravel Forge. I also am able to transfer the file to S3 using AWS CLI.

**Comment by thepenguin1** [comment]
I gave up waiting for a reply and wrote my own backup solution that creates the zip file and uploads via aws cli. Surprisingly simple using terminal commands through shell-exec or symfony process.
