### ISSUE TITLE
backup:clean to S3 is not removing the old backups

### ISSUE THREAD

**Issue by chrisrenga** [spatie/laravel-backup#498]
Hi, I have been testing the package over the last month and noticed that all files are still in S3 even if I run backup:clean from the command line

### composer.json

```
"laravel/framework": "5.4.*",
"guzzlehttp/guzzle": "^6.2",
"spatie/laravel-backup": "^4.0.0",
"league/flysystem-aws-s3-v3": "^1.0",
```

### config/laravel-backup.php

```php

        'strategy' => \Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy::class,

        'defaultStrategy' => [

            /*
             * The number of days for which backups must be kept.
             */
            'keepAllBackupsForDays' => 14,

            /*
             * The number of days for which daily backups must be kept.
             */
            'keepDailyBackupsForDays' => 16,

            /*
             * The number of weeks for which one weekly backup must be kept.
             */
            'keepWeeklyBackupsForWeeks' => 8,

            /*
             * The number of months for which one monthly backup must be kept.
             */
            'keepMonthlyBackupsForMonths' => 4,

            /*
             * The number of years for which one yearly backup must be kept.
             */
            'keepYearlyBackupsForYears' => 2,

            /*
             * After cleaning up the backups remove the oldest backup until
             * this amount of megabytes has been reached.
             */
            'deleteOldestBackupsWhenUsingMoreMegabytesThan' => 5000,
        ],

```

### schedule

```php

        $schedule->command('backup:clean')
            ->dailyAt('01:00');
        
        $schedule->command('backup:run --only-db')
            ->dailyAt('02:00');

```

### backup:list

<img width="748" alt="screen shot 2017-08-10 at 17 15 43" src="https://user-images.githubusercontent.com/13778529/29180391-9be0ee16-7def-11e7-9069-8b46fc2e665d.png">

as you can see there are 32 backups in S3 but the scheduled clean command is not removing the old ones

Did I miss something in the config?

Thanks,

**Comment by freekmurze** [comment]
What happens if you run `php artisan backup:clean` from you command line?

**Comment by chrisrenga** [comment]
not much: 

Starting cleanup...
Cleaning backups of https---www on disk s3...
Used storage after cleanup: 191.33 KB.
Cleanup completed!

but none are actually deleted. 
How does the package know if its a daily, weekly or monthly backup?

**Comment by freekmurze** [comment]
It just used the last modified date on a file.

This is the class that does the cleaning: https://github.com/spatie/laravel-backup/blob/master/src/Tasks/Cleanup/Strategies/DefaultStrategy.php

Could you put a few `dd` statements here and there to figure out what is going wrong?

**Comment by chrisrenga** [comment]
nothing jumping out. Will do some testing over the next few days and maybe change the driver. I have also installed it on another site. Will keep you posted.
