### ISSUE TITLE
How to keep simple rotation of x backups?

### ISSUE THREAD

**Issue by websanova** [spatie/laravel-backup#503]
Hey,

Plugin works great, however I just want to keep a simple rotation of 50 latest backups. Don't really need stuff there for a year and it's just a preliminary backup strategy.

Right now I just have a scheduled task to backup every 10 minutes.

```
$schedule->command('backup:run')->cron('*/10 * * * * *');
```
The clean up I will run just like every hour or two. But I would just like it to to keep a rotation of the backups.

**Comment by freekmurze** [comment]
In the config file you can specify the class that responsible for cleaning up the backups:

https://github.com/spatie/laravel-backup/blob/edb6a3c0b9b290c81387f4f9c5fa7fb34ed65a40/config/laravel-backup.php#L92

You can specify your own class that extends [the `CleanupStrategy`  class](https://github.com/spatie/laravel-backup/blob/master/src/Tasks/Cleanup/CleanupStrategy.php).

Inside the `deleteOldBackups` you have access to all backups via the passed `backups` variable. Just skip the 50 first entries and delete the rest. Done. 😄
