### ISSUE TITLE
backup: clean to s3/local removing all files but one w/ error

### ISSUE THREAD

**Issue by mclapa** [spatie/laravel-backup#505]
Hello

Running backup:clean for the following config will result in an error

> Cleanup failed because: File not found at path: backups/site_2017-08-21-16-07-13.zip

For config

```
'cleanup' => [

        'strategy' => \Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy::class,

        'defaultStrategy' => [

            /*
             * The number of days for which backups must be kept.
             */
            'keepAllBackupsForDays' => 7,

            /*
             * The number of days for which daily backups must be kept.
             */
            'keepDailyBackupsForDays' => 16,

            /*
             * The number of weeks for which one weekly backup must be kept.
             */
            'keepWeeklyBackupsForWeeks' => 8,

            /*
             * The number of months for which one monthly backup must be kept.
             */
            'keepMonthlyBackupsForMonths' => 4,

            /*
             * The number of years for which one yearly backup must be kept.
             */
            'keepYearlyBackupsForYears' => 2,

            /*
             * After cleaning up the backups remove the oldest backup until
             * this amount of megabytes has been reached.
             */
            'deleteOldestBackupsWhenUsingMoreMegabytesThan' => 6000,
        ],
```

Whats actually happening is it removes that file that says it's missing (in fact, all the files except the newest one) and then tries to delete it again, and results an error.

I feel like the date created is not being properly used, it happens with both s3 and local storage

Will try to dd and figure out whats the problem with the date stamps

**Comment by mclapa** [comment]
I think the problem lies in the 

` 
protected function removeOldBackupsUntilUsingLessThanMaximumStorage(BackupCollection $backups)
    {
        if (! $oldest = $backups->oldest()) {
            return;
        }

        $maximumSize = $this->config->get('laravel-backup.cleanup.defaultStrategy.deleteOldestBackupsWhenUsingMoreMegabytesThan')
            * 1024 * 1024;

        if (($backups->size() + $this->newestBackup->size()) <= $maximumSize) {
            return;
        }

        $oldest->delete();
        
        $this->removeOldBackupsUntilUsingLessThanMaximumStorage($backups);
    }

`

Perhaps I'm missing something, but $backups never gets updated with the newest information after $oldest->delete() so it's deleting all the files as the size() never gets recalculated on the new collection

**Comment by introwit** [comment]
@mclapa Hey sorry for being late :) are you still facing the issue? If yes, what's the package & laravel version you are using?

**Comment by AlexVanderbist** [comment]
I think @mclapa has found the issue. `BackupCollection` size used to be calculated every time the method was called but a while back I cached the collection size to speed things up. This way the `removeOldBackupsUntilUsingLessThanMaximumStorage` method uses the same size every time.

I'll PR a fix + tests to make sure this doesn't happen again as it's quite destructive...

**Comment by chrisGeonet** [comment]
I am still getting this issue using 5.10.1.
I have two backups 2.6gb in size, and have deleteOldestBackupsWhenUsingMoreMegabytesThan set to 5000.
When i run a cleanup it deletes the oldest backup, then errors saying the same file cannot be found
