### ISSUE TITLE
Cleaning up error :application_name not substituted 

### ISSUE THREAD

**Issue by mclapa** [spatie/laravel-backup#506]
When receiving an error for cleaning, application_name doesn't get properly substituted for emails / slack

`An error occurred while cleaning up the backups of :application_name`

I looked through the code and the only difference between cleanup-error notifications and success-notifications is 

```
mailMessage = (new MailMessage)

            ->error()

            ->subject(trans('laravel-backup::notifications.cleanup_failed_subject', ['application_name', $this->applicationName()]))
```

vs 

```
$mailMessage = (new MailMessage)

            ->subject(trans('laravel-backup::notifications.backup_successful_subject', 

['application_name' => $this->applicationName()]))
```

perhaps error()-> pipe is messing up the substitution

**Edit**
Seems that it works for other errors, just not this. So for example instead of local backup I do local2 and forces an error the application_name gets substituted

**Comment by chrisrenga** [comment]
Hi @mclapa, had the same issue the other day and finally had some time to look into it.

In:

## src/Notifications/Notifications/CleanupHasFailed.php

change 

```php 
['application_name', $this->applicationName()]
```
to 

```php 
['application_name' => $this->applicationName()]
```

I have submitted a pull request https://github.com/spatie/laravel-backup/pull/536

**Comment by freekmurze** [comment]
We'll continue this in #536
