### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by hohl** [spatie/laravel-backup#510]
Laravel 5.5 just got officially released. Are there any plans to support the new version of Laravel?

**Comment by sebastiandedeyne** [comment]
There's already a `laravel-55` branch. We'll publish a stable release very soon.

**Comment by hohl** [comment]
Huh… I’ve missed that. Btw thank you for your awesome library.

**Comment by freekmurze** [comment]
`v5` which is compatible with Laravel 5.5 has been released.
