### ISSUE TITLE
Upgrading with Laravel 5.5 upgrade

### ISSUE THREAD

**Issue by chris-faulkner** [spatie/laravel-backup#515]
I've had an issues this morning trying to get the backup working with Dropbox since updating to laravel 5.5 and the latest version of laravel-backup.

It kept saying: Backup failed because: 

> There is not backup destination with a disk named `dropbox`.

Turns out it's looking for config/backup.php and not config/laravel-backup.php as it used to,
So after running this:
`php artisan vendor:publish --provider="Spatie\Backup\BackupServiceProvider"`

I simply changed the disk in backup.php to dropbox and everything is working now.
Thought this might catch someon else out so I've added it here.
Not sure if I missed this config file rename somewhere along the line or perhaps it should be aded somewhere?

Thanks for the great packages once again!

**Comment by freekmurze** [comment]
The name chance of the config file is mentioned in the upgrade guide: https://github.com/spatie/laravel-backup/blob/master/UPGRADING.md

**Comment by chris-faulkner** [comment]
As a bit of a github novice I didn't realise that file was there, maybe it's not an issue for everyone else.
Thanks for the quick response

**Comment by necenzurat** [comment]
![1vbf0q 1](https://user-images.githubusercontent.com/145449/30062568-51403686-9254-11e7-8a94-73ec0f440fd3.jpg)
