### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by chenweibo** [spatie/laravel-backup#516]
If i want to make a backup of the name of the external folder to be how to deal with

 Generate a backup directory     \storage\http---localhost\2017-09-02-142342.zip
How does the **http---localhost**  folder name specify it

**Comment by freekmurze** [comment]
Just change the `name` key in the config file.

https://github.com/spatie/laravel-backup/blob/581a21cffccab873fca96c8cdac65e6424689243/config/backup.php#L11
