### ISSUE TITLE
Type error when config repository is swapped for custom one.

### ISSUE THREAD

**Issue by mplodowski** [spatie/laravel-backup#527]
Hi,

I want to create a plugin for OctoberCMS based on this package. I have following error.

```
Type error: Argument 1 passed to Spatie\Backup\Notifications\EventHandler::__construct() must be an instance of Illuminate\Config\Repository, instance of October\Rain\Config\Repository given
```

I think we should use contract `Illuminate\Contracts\Config\Repository` on https://github.com/spatie/laravel-backup/blob/master/src/Notifications/EventHandler.php#L21 instead of concrete class.

What do you think?

**Comment by freekmurze** [comment]
Makes sense. I've changed this and tagged a new version.
