### ISSUE TITLE
rename file name

### ISSUE THREAD

**Issue by fayroz** [spatie/laravel-backup#530]
The specified databases will be dumped and, together with the selected files, zipped. The zip file will be named,  
how can i rename backup file

**Comment by introwit** [comment]
@fayroz Hi :) do you mean renaming the backup zip?

**Comment by fayroz** [comment]
@introwit  hi yes i want to rename  backup file for  users can download this backup

**Comment by freekmurze** [comment]
Take a look at the BackupWasSuccessful event: https://docs.spatie.be/laravel-backup/v5/taking-backups/events#backupwassuccessful

`newsetBackup` will return an instance of [`Backup`](https://github.com/spatie/laravel-backup/blob/master/src/BackupDestination/Backup.php). That contains a path to the zip file. 

You should do the renaming yourself, that's not supported in the package.

**Comment by fayroz** [comment]
thankes @freekmurze
