### ISSUE TITLE
Problem sending the file do Copy/FTP

### ISSUE THREAD

**Issue by thiagolovatine** [spatie/laravel-backup#54]
I using https://github.com/GrahamCampbell/Laravel-Flysystem on my project with Copy and FTP, both are working fine, but when I try to php artisan backup:run (With FTP) I get this message:

  [ErrorException]
  ftp_connect(): php_network_getaddresses: getaddrinfo failed: Nome ou serviço desconhecido

And with Copy:

  [BadMethodCallException]
  Call to undefined method League\Flysystem\Filesystem::createDriver

What am I doing wrong? :)

**Comment by freekmurze** [comment]
The error message indicates that the url you're connecting to is not ok. Are you sure the host specified in the ftp configuration exist?

**Comment by thiagolovatine** [comment]
It does exist, on the flysystem configuration file... the default laravel file doesn't have a Copy option.
