### ISSUE TITLE
backup:monitor error

### ISSUE THREAD

**Issue by nohumans** [spatie/laravel-backup#541]
The command backup:monitor return this error:

run laravel 5.5.14
spatie/laravel-backup ( 5.0.4)

```
./artisan backup:monitor
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 2 passed to Spatie\Backup\BackupDestination\BackupDestination::create() must be of the type string, null given, called in /var/app/current/vendor/spatie/laravel-backup/src/Tasks/Monitor/BackupDestinationStatusFactory.php on line 2
```

Eny idea ?
Thanxx

**Comment by freekmurze** [comment]
Please check if the monitoring config is set up properly for your disk

https://github.com/spatie/laravel-backup/blob/master/config/backup.php#L115-L118
