### ISSUE TITLE
Allow to use all available console output (command) methods.

### ISSUE THREAD

**Issue by mplodowski** [spatie/laravel-backup#543]
Not every method in class `Spatie\Backup\Helpers\ConsoleOutput` is called with exactly 1 argument.

Currently when you try to call method `options()` it will throw an error:

Code:
```
consoleOutput()->options();
```

Error:
```
Undefined offset: 0
```

To make it more generic I think we could use splat operator here:

https://github.com/spatie/laravel-backup/blob/master/src/Helpers/ConsoleOutput.php#L26

like so:

```
return $consoleOutput->output->$method(...$arguments);
```

We should also use `return` statement in this method.

**Comment by freekmurze** [comment]
Could you point me to where in the package this is currently causing problems?

**Comment by mplodowski** [comment]
It is not the problem inside the package itself.

I created backend management for backups and I would like to set backup type based on option specified in command. So if user type option `php artisan backup:run --only-db` it will set backup type to `db`.

I use `BackupWasSuccessfull` event to make it work, but there I can only have access to `$backupDestinantion`variable.

To make it work I can use:

```
consoleOutput()->options();
```
or
```
consoleOutput()->hasOption('only-db');
```

but current implementation in `ConsoleOutput` class does not allowed to use those functions.

**Comment by freekmurze** [comment]
`consoleOutput()` is only meant for outputting stuff to the screen. If you want to start artisan commands from code use `Artisan::call($yourCommand)`
