### ISSUE TITLE
[Ask] is this package support backup/restore remote database ?

### ISSUE THREAD

**Issue by imannms** [spatie/laravel-backup#544]
I think I didnt find this answer in the docs, or maybe I just missed them. 
so is this package support backup remote database?

**Comment by freekmurze** [comment]
Remote db’s are not supported

**Comment by jeff-h** [comment]
How are they not supported? I back up several databases from a separate (ie remote) mysql server using this package, as that's how my Laravel project runs in production — PHP on one VPS, MySQL on another.

Perhaps this aspect has changed since 2017?
