### ISSUE TITLE
Error v1_retired

### ISSUE THREAD

**Issue by sairam2188** [spatie/laravel-backup#545]
Hi,
Everything worked fine until recently.
Now I'm getting the following error:
**_Failed to backup  because: HTTP status 400
{"error": "v1_retired"}_**

I suppose it was because the Dropbox Api V1 was deprecated.
How can I solve that?

**Comment by freekmurze** [comment]
Here you go: https://murze.be/2017/04/dropbox-will-turn-off-v1-of-their-api-soon-its-time-to-update-your-php-application/
