### ISSUE TITLE
Bug using 'read' configuration in database connections

### ISSUE THREAD

**Issue by alberto-bottarini** [spatie/laravel-backup#547]
laravel-backup doesn't merge options as specified in Laravel documentation when tries to access to database connection parameters.

If exists, it gets host from ```read``` configuration but ignore other ```read``` parameters.

    $dbHost = array_get($dbConfig, 'read.host', array_get($dbConfig, 'host'));

It should merge ```read``` configuration with generic configuration as written in Laravel documentation:
    
     The rest of the database options for the read and write connections will be merged from the main mysql array.

**Comment by freekmurze** [comment]
I'd accept a PR with tests that fixes this.

**Comment by freekmurze** [comment]
We’ll handle this further in #549
