### ISSUE TITLE
Dump_binary_path is not set

### ISSUE THREAD

**Issue by highsolutions** [spatie/laravel-backup#548]
Hi @freekmurze,
we have problems with your package, but previously everything was working correctly.

After command:
`php artisan backup:run`

we get:

> Backup failed because The dump process failed with exitcode 1 : General error : '"mysqldump"' is not recognized as an internal or external command,
> operable program or batch file.

We have checked that `dump_binary_path` is not set according to config file (it's empty). We have cleared config and checked that adding line:

`$this->setDumpBinaryPath()` to `db-dumper/src/Databases/Mysql.php:118` do the job.

Is there any other way to set up this dump binary path?

**Comment by introwit** [comment]
@highsolutions Hi :) [Here are the docs](https://docs.spatie.be/laravel-backup/v5/installation-and-setup#dumping-the-database) for what you need. If you are using windows make sure to add double quotes around the path.

**Comment by highsolutions** [comment]
@introwit Hi, I've read the docs, I have set path via env and it had worked before. Like I said I've checked how package is working and I didn't found setting this path inside it. I double checked this. 

I am using newest version of package, so please check this also.

**Comment by introwit** [comment]
@highsolutions Can you elaborate a bit more what do you need or is the problem solved? You need to specify it in your app's database config as mentioned in the docs, the package would read the value from there.

**Comment by highsolutions** [comment]
@introwit I have specified everything in database config. It's working on production server on linux (because it doesn't need setting path), but on my local environment on Windows it doesn't. I have checked code of package and I found that this path is not set at all before starting dump of database.
