### ISSUE TITLE
Using S3, not possible to write direct to bucket

### ISSUE THREAD

**Issue by snapey** [spatie/laravel-backup#55]
I create S3 bucket dedicated for the backup and use IAM to provide permission to write to bucket.

Unfortunately it is not possible to set path='' to tell laravel-backup to write to the root of the bucket. Any slashes are removed and key is detected as being 0 characters long.

All works ok if folder is named but it mandates an extra folder level that otherwise is not required.

**Comment by freekmurze** [comment]
I've made a fix for this in de dev-master version of this package. Could you try if this fix solves the problem?

**Comment by snapey** [comment]
I copied the revised function getBackupDestinationFilename 

Line 192, I had to add a semi-colon

I then set path to empty string.  

AWS is throwing an error;

`  [Aws\S3\Exception\S3Exception]
  Error executing "PutObject" on "https://s3-eu-west-1.amazonaws.com/myproject/"; AWS HTTP error: Client error response [url] https://s3-eu-west-1.amazonaws.com/myproject/ [status code] 400 [reason p
  hrase] Bad Request IllegalLocationConstraintException (client): The unspecified location constraint is incompatible for the region specific endpoint this request was sent to. - <?xml version="1.0
  " encoding="UTF-8"?>
  <Code>IllegalLocationConstraintException</Code><Message>The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.</Message>

I'll research this further but not today.

**Comment by snapey** [comment]
The IllegalLocationConstraintException seems like a bug at AWS. There is very little online about this and the error is not one of those listed in the S3 API.

After some testing, I tracked the problem to the first two lines of the copyFile function in BackupCommand.php

```
        $destinationDirectory = dirname($destination);

        $disk->makeDirectory($destinationDirectory);
```
When specifying a path in the config, dirname returns the name of the folder and makeDirectory ensures that this folder exists.

When the destination.path is empty, dirname returns a period `"."`

When makeDirectory is called with period as the directory name, AWS throws the exception.

A workaround is to skip the makeDirectory call when dirname returns a period.

```
        if ($destinationDirectory!='.') {
            $disk->makeDirectory($destinationDirectory);
        }
```

**Comment by michellaurent** [comment]
I had the same issue but the fix proposed by @snapey doesn't solve it in my case.

If ``destination.path`` is empty (`` $path = ''``), dirname returns a slash ``"/"``

When makeDirectory is called with slash as the directory name, AWS throws the exception.

```
[InvalidArgumentException]
Found 1 error while validating the input provided for the PutObject operation:
[Key] must be at least 1 characters long. Value provided is 0 characters long.            
```

A workaround is to skip the makeDirectory call when dirname returns a slash.

```
if ($destinationDirectory != '/') {
    $disk->makeDirectory($destinationDirectory);
}
```
I have tested with local on homestead and forge with local and s3 filesystems.

**Comment by michellaurent** [comment]
Tested again on the latest 2.9.0, and what @snapey said is right and solved the issue.

Made pull request #62 with the fix.
