### ISSUE TITLE
How to set the name of the backup folder `http---localhost`

### ISSUE THREAD

**Issue by zwl1619** [spatie/laravel-backup#554]
I save the backup in  `/var/www-bak`,the folder name is `http---localhost`,like this:
```
/var/www-bak/http---localhost
```

config/backup.php
```
 'destination' => [
            'disks' => [
                'local2',
            ],
        ],
```

config/filesystems.php
```
        'local2' => [
            'driver' => 'local',
            'root' => '/var/www-bak',
        ],
```

if I have two projects, such as `peoject-one`,`peoject-two`,I want to set the backup folder name like this:

```
/var/www-bak/peoject-one
/var/www-bak/peoject-two
```
How to set it?

**Comment by freekmurze** [comment]
You have to set `APP_URL` env variable.
