### ISSUE TITLE
Rule of silence

### ISSUE THREAD

**Issue by gauravgupta123** [spatie/laravel-backup#556]
We are following the "Rule of silence" in our crons where no output is written if everything goes well and the crons only produce outputs incase of errors, which is sent to us over email.

Ref: https://sanctum.geek.nz/arabesque/cron-best-practices/ and http://www.linfo.org/rule_of_silence.html

How can we turn off the output of the backup script?

**Comment by freekmurze** [comment]
Laravel lets you configure the desired logging level

More info here: https://laravel.com/docs/5.5/errors#error-detail

**Comment by gauravgupta123** [comment]
It's not a logging issue. I need to prevent the script from printing output on the console. Please re-open.
