### ISSUE TITLE
Translations not work

### ISSUE THREAD

**Issue by gbgelado** [spatie/laravel-backup#566]
I have not translation on email, the content has send only:

```backup::notifications.backup_successful_body ```

![image](https://user-images.githubusercontent.com/7469384/32609462-fe6ff1fa-c546-11e7-910f-1e1c1ae86f48.png)

resource lang estruture

![image](https://user-images.githubusercontent.com/7469384/32609415-cf33ca42-c546-11e7-949f-fc6ae6ba59cf.png)

Can you help me?

**Comment by freekmurze** [comment]
Make sure `locale` is set to a correct value in `config/app.php`

**Comment by rafwell** [comment]
Rename pt-BR to pt_BR solved for me.
