### ISSUE TITLE
Error while taking backup to Disk Google

### ISSUE THREAD

**Issue by webribs** [spatie/laravel-backup#572]
Hello,

I'm using Laravel 5.4 and laravel-backup v3. I'm using this driver for Google drive. 
`"nao-pon/flysystem-google-drive": "~1.1"`

I am able to upload files using 
Storage::disk('google')->put('FileName', Content);

But with your package I'm getting the following error while using disk 'google'.

Can you help me regarding this? 

![screenshot_1](https://user-images.githubusercontent.com/10451770/32936507-541ab662-cb96-11e7-8d2c-5304eb7db3c9.png)

**Comment by AlexVanderbist** [comment]
Hi, that's pretty weird. `http---localhost` is a directory, not a file, looks like something is going wrong there. 

Can you check if the backup actually exists locally? It should be in `storage/app/backups/http---localhost/`.

Maybe you can try creating the `http---localhost` directory on your Google drive as well?

**Comment by webribs** [comment]
if I choose destination disk as local then file exists in http---localhost directory. But If I choose google as disk then don't.

**Comment by introwit** [comment]
It's actually a known thing: I wrote about it [in this thread](https://github.com/spatie/laravel-backup/issues/468#issuecomment-333453132). Hope that helps, also do let us know any suggestions or PR's if possible :)

**Comment by introwit** [comment]
Closing this as a similar thread is already open and its good to discuss the same problem at a singular place :) 

- [Similar Issue](#468)
