### ISSUE TITLE
Error: not cleaning the backups

### ISSUE THREAD

**Issue by schonhose** [spatie/laravel-backup#573]
I am using laravel-backup on Laravel 5.1 using `"spatie/laravel-backup": "^3.0.0",` in my composer.json.

In my settings I have the following:

`/*
             * The amount of days that all backups must be kept.
             */
            'keepAllBackupsForDays' => 5,`

`/*
             * The amount of days that all daily backups must be kept.
             */
            'keepDailyBackupsForDays' => 5,`

With my understanding these settings will keep the last 5 daily backups. Backups are run daily using the Laravel scheduler. However, the amount of days mentioned in the above settings are not respected as backups are continuously added to the folder.

**Comment by freekmurze** [comment]
Are you running `php artisan backup:clean`?

**Comment by schonhose** [comment]
The following code is set in the Kernel.php file:

`$schedule->command('backup:clean')
                 ->daily()->at('01:00');
        $schedule->command('backup:run')
                 ->daily()->at('02:00');
`

**Comment by freekmurze** [comment]
What happens in you run `php artisan backup:clean` manually? Could you post your config file here?

**Comment by schonhose** [comment]
Running the command manually seems to work just fine.

`
php artisan backup:clean
Starting cleanup...
Cleaning backups of  on disk dropbox...
Deleted backup 2017-11-14-020001.zip.
Used storage after cleanup: 433.92 MB.
Cleanup completed!
`

Strange thing is, it used to work but after a while it just stopped. Not sure why, as the scheduler is set to run every 5 minutes to check if there is a task.

**Comment by freekmurze** [comment]
Can you verify that the task runs? Might be a problem with your app, and not this package.

**Comment by schonhose** [comment]
`<?php

namespace App\Console;

use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;

class Kernel extends ConsoleKernel
{
    /**
     * The Artisan commands provided by your application.
     *
     * @var array
     */
    protected $commands = [
        \App\Console\Commands\Inspire::class,
        \App\Console\Commands\PracticeAttendance::class,
    ];

    /**
     * Define the application's command schedule.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @return void
     */
    protected function schedule(Schedule $schedule)
    {
        $schedule->command('backup:clean')
                 ->daily()->at('01:00');
        $schedule->command('backup:run')
                 ->daily()->at('02:00');
        $schedule->command('telegram:practice_attendance 10')
                  ->daily()->at('17:30');
    }
}
`

Funny thing is, is that the backup:run and the other task is running perfectly.

**Comment by AlexVanderbist** [comment]
Can you check the application's logs for any errors that might've occurred during `backup:clean`?

**Comment by ralphmorris** [comment]
I'm seem to be having this issue too. 

"laravel/framework": "5.2.*"
"spatie/laravel-backup": "^3.0.0"

Not sure if it is something in my config? I want to hold backups for 30 days.

```    'cleanup' => [
        /*
         * The strategy that will be used to cleanup old backups.
         * The youngest backup will never be deleted.
         */
        'strategy' => \Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy::class,

        'defaultStrategy' => [

            /*
             * The number of days for which all backups must be kept.
             */
            'keepAllBackupsForDays' => 30,

            /*
             * The number of days for which all daily backups must be kept.
             */
            'keepDailyBackupsForDays' => 30,

            /*
             * The number of weeks for which all one weekly backup must be kept.
             */
            'keepWeeklyBackupsForWeeks' => 8,

            /*
             * The number of months for which one monthly backup must be kept.
             */
            'keepMonthlyBackupsForMonths' => 4,

            /*
             * The number of years for which one yearly backup must be kept.
             */
            'keepYearlyBackupsForYears' => 2,

            /*
             * After cleaning up backups, remove the oldest backup until
             * this number of megabytes has been reached.
             */
            'deleteOldestBackupsWhenUsingMoreMegabytesThan' => 5000,
        ],
    ],```

In my Kernel.php
```        $schedule->command('backup:clean')->daily()->at('01:00');
        $schedule->command('backup:run')->daily()->at('02:00');```

I'm backing up to local, S3 and Dropbox. I added Dropbox on October 15 which is the oldest backup I have. On S3 and Local backups go when to when I first launched July 30 2017. 

One thing I'm also noticing is that Dropbox (which happens last) takes WAY longer for the "Used storage after cleanup" message. Though it looks like cleanup wasn't working before I added Dropbox so probably irrelevant.

Nothing in my storage/logs file other than:

```[2017-12-15 07:33:46] production.INFO: http://mydomain.co.uk backups: Successfully cleaned up the backups on local-filesystem
[2017-12-15 07:33:59] production.INFO: http://mydomain.co.uk backups: Successfully cleaned up the backups on awss3adapter-filesystem
[2017-12-15 07:39:41] production.INFO: http://mydomain.co.uk backups: Successfully cleaned up the backups on dropboxadapter-filesystem```

Not a lot to go on but any idea?

**Comment by schonhose** [comment]
I think I managed to fix it, although I am not sure what is the actual fix since I applied multiple.

First, I changed the running times fifteen minutes later (e.g. 1:15 and 2:15). Should not have made a large difference, but you never know.

Second, I changed the code in the Kernel.php file to add a parameter (-n : do  not ask interactive question):
`
$schedule->command('backup:clean -n')->daily()->at('01:15');
$schedule->command('backup:run -n')->daily()->at('02:15');
`
Third,  I cleared the application cache using `php artisan cache:clear`.

And the last thing I did was adding the following code as the first statement in Kernel.php
'
$schedule->command('inspire')->hourly();
'

Funny thing is that I, from what I have read, should see hourly quotes in the log. I do not see them, but the backups work.

**Comment by ralphmorris** [comment]
I think I've got it working for me too. I changed all of the values in the config to 0 other than the main one 'keepAllBackupsForDays' which is set to 30 as my only requirement is to keep my nightly backups for 30 days. I have no need for weekly, monthly etc. I'm not sure really how these other configs work.

So my config now looks like this. 
```
        'defaultStrategy' => [

            /*
             * The number of days for which all backups must be kept.
             */
            'keepAllBackupsForDays' => 30,

            /*
             * The number of days for which all daily backups must be kept.
             */
            'keepDailyBackupsForDays' => 0,

            /*
             * The number of weeks for which all one weekly backup must be kept.
             */
            'keepWeeklyBackupsForWeeks' => 0,

            /*
             * The number of months for which one monthly backup must be kept.
             */
            'keepMonthlyBackupsForMonths' => 0,

            /*
             * The number of years for which one yearly backup must be kept.
             */
            'keepYearlyBackupsForYears' => 0,

            /*
             * After cleaning up backups, remove the oldest backup until
             * this number of megabytes has been reached.
             */
            'deleteOldestBackupsWhenUsingMoreMegabytesThan' => 5000,
        ],
```

This has deleted all of my backups older than 30 days old.
