### ISSUE TITLE
Uninstall the package stops the app.

### ISSUE THREAD

**Issue by saidbakr** [spatie/laravel-backup#574]
> [Symfony\Component\Debug\Exception\FatalThrowableError]  
>   Class 'Spatie\Backup\BackupServiceProvider' not found   

When try to run any `php artisan` command and the application is not loaded too.
I installed the package then I decideed to uninstall it.
I removed its dependency from comoser.json and run `composer update`

**Comment by freekmurze** [comment]
Can you run `php artisan config:clear`?

**Comment by saidbakr** [comment]
Yes I have run it and the artisan command generates the same error while running it. However, I found the solution in [this answer](https://stackoverflow.com/a/46600710/1592845) The regarded file there still undeleted, and after delete it, everthing works fine again.
@freekmurze
