### ISSUE TITLE
Laravel backup and medialibrary

### ISSUE THREAD

**Issue by facundofarias** [spatie/laravel-backup#575]
Hi there,

This is not an issue, just a question for you guys.
We are using the laravel-backup package and also the laravel-medialibrary. We backup the database every day, and so far so good. The thing is that, we would like to backup the media files also (original ones and converted), but with a different cadency, let's say once a week (or something like that). Any ideas how to do it? Is it posible to configure it? Or, should it be a new feature?
Thanks,

Facundo

**Comment by freekmurze** [comment]
You could schedule run this command daily

```php
php aritsan backup:run --only-db
```

And the regular one (without `--only-db`) weekly.

**Comment by facundofarias** [comment]
Hey @freekmurze thanks! 👍
