### ISSUE TITLE
Potential timeout when finding files to backup

### ISSUE THREAD

**Issue by mrwaim** [spatie/laravel-backup#58]
I'm getting a "Killed" message, when running the command, and no debug info for it

I've updated the timeout to 240 seconds, and its no where near that for the kill.

Is there a timeout on the finding files? Can I bump it up?

When I comment out base_path(), the backup is successful.

'files' =>'include' => [base_path(),],

`
$ time php artisan backup:run -vvv
Start backing up
Database dumped
Determining which files should be backed up...
Killed

real	0m21.718s
user	0m1.948s
sys	0m1.388s
`

To have an idea of how many files there are,
$ find -type f | wc -l
16043

**Comment by freekmurze** [comment]
The package does not enforce a timelimit. Maybe you get killed because the
script uses too much memory? Try bumping up the memory limit.

On Saturday, 19 December 2015, Ibrahim Abdul Rahim <notifications@github.com>
wrote:

> I'm getting a "Killed" message, when running the command, and no debug
> info for it
>
> I've updated the timeout to 240 seconds, and its no where near that for
> the kill.
>
> Is there a timeout on the finding files? Can I bump it up?
>
> When I comment out base_path(), the backup is successful.
>
> 'files' =>'include' => [base_path(),],
>
> `
> $ time php artisan backup:run -vvv
> Start backing up
> Database dumped
> Determining which files should be backed up...
> Killed
>
> real 0m21.718s
> user 0m1.948s
> sys 0m1.388s
> `
>
> To have an idea of how many files there are,
> $ find -type f | wc -l
> 16043
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spatie/laravel-backup/issues/58>.
>


-- 
Freek Van der Herten
https://spatie.be
+32 495 84 27 91
