### ISSUE TITLE
Backup failure once a week with DropBox filesystem

### ISSUE THREAD

**Issue by dib258** [spatie/laravel-backup#586]
Hello,

First of all thank you Freek for all the plugins you create, they are so interesting and usefull !

Secondly, I currently use the laravel-backup with the flysystem-dropbox for a website I developped.

Everything is working fine except that once or twice a week (I configured the email with the report) I get a failed backup message by mail.

The backup is happening like a 1am or 2am UTC time (3am in Belgium). Could this be like a dropbox maintenance ?

Here the stack trace I receive in the email :

    Important: An error occurred while backing up mywebsite

    Exception message: Server error: POST https://content.dropboxapi.com/2/files/upload resulted in a 502 Bad Gateway response: {"error": "Internal Server Error"}

    Exception trace: 
    #0 ../mywebsite/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) 
    #1 ../mywebsite/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp{closure}(Object(GuzzleHttp\Psr7\Response)) 
    #2 ../mywebsite/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) 
    #3 ../mywebsite/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise{closure}() 
    #4 ../mywebsite/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true) 
    #5 ../mywebsite/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() 
    #6 ../mywebsite/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() 
    #7 ../mywebsite/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() 
    #8 ../mywebsite/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() 
    #9 ../mywebsite/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Promise\Promise->wait() 
    #10 ../mywebsite/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('post', 'https://content...';, Array) 
    #11 ../mywebsite/vendor/spatie/dropbox-api/src/Client.php(298): GuzzleHttp\Client->__call('post', Array) 
    #12 ../mywebsite/vendor/spatie/dropbox-api/src/Client.php(258): Spatie\Dropbox\Client->contentEndpointRequest('files/upload', Array, Resource id #6529) 
    #13 ../mywebsite/vendor/spatie/flysystem-dropbox/src/DropboxAdapter.php(269): Spatie\Dropbox\Client->upload('/https---mywe...', Resource id #6529, 'add') 
    #14 ../mywebsite/vendor/spatie/flysystem-dropbox/src/DropboxAdapter.php(39): Spatie\FlysystemDropbox\DropboxAdapter->upload('/https---mywe...', Resource id #6529, 'add') 
    #15 ../mywebsite/vendor/league/flysystem/src/Filesystem.php(86): Spatie\FlysystemDropbox\DropboxAdapter->writeStream('https---mywes...', Resource id #6529, Object(League\Flysystem\Config)) 
    #16 ../mywebsite/vendor/spatie/laravel-backup/src/BackupDestination/BackupDestination.php(85): League\Flysystem\Filesystem->writeStream('https---myweb...', Resource id #6529) 
    #17 ../mywebsite/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(238): Spatie\Backup\BackupDestination\BackupDestination->write('.../myweb...') 
    #18 ../mywebsite/vendor/laravel/framework/src/Illuminate/Support/Collection.php(260): Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup{closure}(Object(Spatie\Backup\BackupDestination\BackupDestination), 0) 
    #19 ../mywebsite/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(248): Illuminate\Support\Collection->each(Object(Closure)) 
    #20 ../mywebsite/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(136): Spatie\Backup\Tasks\Backup\BackupJob->copyToBackupDestinations('.../myweb...') 
    #21 ../mywebsite/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(49): Spatie\Backup\Tasks\Backup\BackupJob->run() 
    #22 [internal function]: Spatie\Backup\Commands\BackupCommand->handle() 
    #23 ../mywebsite/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) 
    #24 ../mywebsite/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container{closure}() 
    #25 ../mywebsite/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) 
    #26 ../mywebsite/vendor/laravel/framework/src/Illuminate/Container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) 
    #27 ../mywebsite/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array) 
    #28 ../mywebsite/vendor/symfony/console/Command/Command.php(262): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) 
    #29 ../mywebsite/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) 
    #30 ../mywebsite/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(22): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
    #31 ../mywebsite/vendor/symfony/console/Application.php(826): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
    #32 ../mywebsite/vendor/symfony/console/Application.php(190): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
    #33 ../mywebsite/vendor/symfony/console/Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
    #34 ../mywebsite/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(123): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
    #35 ../mywebsite/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
    #36 {main}

**Comment by AlexVanderbist** [comment]
Hi @dib258,

That's pretty strange. I wouldn't expect Dropbox to have regular downtime during maintenance (or return a 500 when that's happening)...

Have you tried scheduling the backup at a later time?

**Comment by dib258** [comment]
Hi @AlexVanderbist,

Thanks for you answer and no I didn't move the time of the backup yet.

Wanted to know first if it was something faulty in my configuration or something.
And that's so weird I wanted to know if other people had experienced it.

I just added one hours to the cleanup and the backup phase

Before : 

        $schedule->command('backup:clean')->daily()->at('01:00');
        $schedule->command('backup:run')->daily()->at('02:00');

Now : 

        $schedule->command('backup:clean')->daily()->at('02:00');
        $schedule->command('backup:run')->daily()->at('03:00');

I'll see this week if I still get sometimes an error during the backup phase and I'll come back here.

**Comment by dib258** [comment]
Nop, this night at 3AM Belgian time (2AM UTC I think), I got the same error.

    Exception message: Server error: POST https://content.dropboxapi.com/2/files/upload resulted in a 502 Bad Gateway response: {"error": "Internal Server Error"}

Really weird. And I don't know where this could came from...

Since it's working most of the time : /

**Comment by freekmurze** [comment]
Can you see any logging at Dropbox? Can you check with their support?

**Comment by dib258** [comment]
Hi @freekmurze,

I went to my dropbox account to see the logs for the app I linked. It appears after an article I read (https://blogs.dropbox.com/developers/2014/08/debug-your-dropbox-app-with-app-error-logs/) that the logs are disabled on the application. So, not able to see any logs on the Dropbox side... Except if you now another way to do it !

But when I was in the application stats I saw this chart :
<img width="831" alt="screen shot 2017-12-04 at 10 32 43" src="https://user-images.githubusercontent.com/4132137/33545588-f195d822-d8de-11e7-842a-de2b21ca6749.png">

There's huge spikes of api calls. The big one are a 1048 api calls a day. Don't know what causes as much of api calls since I only run 2 commands a day. 

Also just to be sure, I went to see if the backup error were on the same day of the huge spikes and maybe Dropbox could have shut off the access because of too much API calls. In the end, the bug crash report are nowhere near the spike. I've got one November 29th and December second which are respectively 73 and 115 API calls.

No more luck here... So I'm going to try to contact them as you said.

I'll let you know when I get an answer.

**Comment by dib258** [comment]
@freekmurze,

I got an answer from the support I contacted : 

>  Hi,
> 
> Thanks for writing this in. A 502 error like this can occur occasionally due to transient server issues. You should have your app automatically retry these a few times, as they will usually be temporary.
> 
> However, you might see this more if you're uploading large files using /2/files/upload, which is only meant for files up to 150 MB. If you're uploading files larger than that, you should use upload sessions instead:
> 
> https://www.dropbox.com/developers/documentation/http/documentation#files-upload_session-start
> https://www.dropbox.com/developers/documentation/http/documentation#files-upload_session-append_v2
> https://www.dropbox.com/developers/documentation/http/documentation#files-upload_session-finish
> 
> Regards,
> Gregory


Indeed I checked and actually the backup I send to Dropbox is higher than 150MB (226MB for the last one and counting).

How should I proceed to retry if the backup failed ? Is there a command to run after the backup to check if it was successfull or else relaunch the backup ?

And for the long run they say that for larger files we shouldn't use the "upload session" instead.
Is it something we can do easily ? 

Thanks in advance for you help !

**Comment by freekmurze** [comment]
I've just tagged a new version of the underlying package (spatie/dropbox-api) with improvements for uploading large files. Could you run `composer update` and let me know if this works for you?

**Comment by luanrodrigues** [comment]
same here

**Comment by luanrodrigues** [comment]
@freekmurze  i did composer update here, and got same error =(
