### ISSUE TITLE
Read/Write hosts: Error when using 2 read DBs

### ISSUE THREAD

**Issue by django23** [spatie/laravel-backup#587]
In our setup we use multiple read databases:

```
      'mysql' => [
            'driver' => 'mysql',
            'read' => array(
                'host' => explode(',', env('MYSQL_SLAVE_HOSTS', $db_master->host)),
                'database' => ***,
                'username' => ***,
                'password' => ***,
            ),
            'write' => array(
                'host' => $db_master->host,
            ),

            'database' => $db_master->path,
            'username' => $db_master->user,
            'password' => $db_master->pass,

            'sticky' => true,
```

But apparently the packages requires `host` to be of type string instead of array.
More info about the multiple read hosts can be found here:
https://www.neontsunami.com/posts/multiple-database-read-write-connections-in-laravel

> Starting backup...
> 
>   Symfony\Component\Debug\Exception\FatalThrowableError : Type error: Argument 1 passed to Spatie\DbDumper\DbDumper::setHost() must be of the type string, array given, called in */vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php on line 31
> 
>   at */vendor/spatie/db-dumper/src/DbDumper.php: 95
>   91:      * @param string $host
>   92:      *
>   93:      * @return $this
>   94:      */
>   95:     public function setHost(string $host)
>   96:     {
>   97:         $this->host = $host;
>   98: 
>   99:         return $this;
>   100:     }
> 
>   Exception trace:
> 
>   1   Spatie\DbDumper\DbDumper::setHost()
>       */vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php : 31
> 
>   2   Spatie\Backup\Tasks\Backup\DbDumperFactory::createFromConnection("mysql")
>      */vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php : 28
> 
>   3   Spatie\Backup\Tasks\Backup\BackupJobFactory::Spatie\Backup\Tasks\Backup\{closure}("mysql")
>       [internal] : 0
>

**Comment by devinfd** [comment]
I just encountered this error. DbDumperFactory should handle arrays before setting the host on line 31. I'll send a PR to fix this.

**Comment by freekmurze** [comment]
Fixed in latest version.
