### ISSUE TITLE
backup:list doesn't show backups; v3

### ISSUE THREAD

**Issue by noriods** [spatie/laravel-backup#588]
I'm running Laravel 5.3 so I'm using v3 of this package and it seems that the backup:list command isn't picking up my backups in S3.

Everything else seems fine. I have 10 backups. backup:clean works fine.

I think the code for checking the number of backups isn't working because I also get daily notice of unhealthy backups despite them being there and less than a few hours old. (newestBackupsShouldNotBeOlderThanDays is set to 1).

I can't help but think if maybe this is what @magnusjt was referring to here:
https://github.com/spatie/laravel-backup/issues/136

(ie: Maybe he's using version 3 like I am.)

Let me know if there's anything I can do to help squish this.

**Comment by freekmurze** [comment]
We only support the latest version of the package.

**Comment by drbyte** [comment]
I know this is an old post, but one of the causes of a mismatch between backup-success and backup "list"/"clean"/"monitor" is if your `config('backup.monitor')[]['name']` doesn't match your `config('backup.name')`.
Regardless of package version ;)

**Comment by SuddenlyRust** [comment]
I stumbled on the same problem and followed @drbyte his advise. Unfortunately the configuration variables have changed in the new version (6.1). The `config('backup.name')` and `config('monitor_backups.name')` configuration needs to match each other now!

I hope this will help further people 🚀 spread the love and don't forget to send Spatie awesome postcards 💌
