### ISSUE TITLE
backup:list show something not understandable.

### ISSUE THREAD

**Issue by oskarbet** [spatie/laravel-backup#592]
backup:list show me next:
+-------+-------+-----------+---------+--------------+-----------------------+--------------+
| Name  | Disk  | Reachable | Healthy | # of backups | Youngest backup       | Used storage |
+-------+-------+-----------+---------+--------------+-----------------------+--------------+
| local | local | тЬЕ         | тЬЕ       | 5            | 0.70 (16 ╤З╨░╤Б╨╛╨▓ ╨╜╨░╨╖╨░╨┤) | -631193735 B |
+-------+-------+-----------+---------+--------------+-----------------------+--------------+
I use Laravel 5.3. And result is the same on "spatie/laravel-backup": "^3.0.0" and "spatie/laravel-backup": "^4.0.0"

**Comment by freekmurze** [comment]
We don't support L5.3 anymore.
