### ISSUE TITLE
[Feature] add an event b4 the backup start

### ISSUE THREAD

**Issue by ctf0** [spatie/laravel-backup#594]
atm b4 the package start to backup the db it will lock it to prevent any new data being inserted, but if the user at the time of the backing up tried to add a new model he would get an error because the db is currently locked.

so i was thinking maybe we can have an extra event that fires just b4 the db gets locked, this way we can listen to it and show like an alert/notification to the user while the backup is being created & later we can use `BackupZipWasCreated` to hide that alert.

**Comment by freekmurze** [comment]
I'd accept a PR with tests that adds a `BackupStarted` event.
