### ISSUE TITLE
Error: "There is no disk set for the backup destination" if folder outside root

### ISSUE THREAD

**Issue by R3l4x3** [spatie/laravel-backup#598]
Hi folks

I would like to place the backup in a folder outside the root folder. My configuration looks like this:

```
<?php

return [

    'backup' => [

        'name' => config('app.name'),

        'source' => [

            'files' => [

                'include' => [
                    storage_path('app/public/'),
                ],

                'exclude' => [
                    base_path('vendor'),
                    base_path('node_modules'),
                ],

                'followLinks' => false,
            ],

            'databases' => [
                'mysql',
            ],
        ],

        'gzip_database_dump' => false,

        'destination' => [

            'filename_prefix' => '',

            'disks' => [
                'backup',
            ],
        ],
    ],
    
    'notifications' => [

        'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class         => ['mail'],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class        => ['mail'],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class     => ['mail'],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class   => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class    => ['mail'],
        ],
        
        'notifiable' => \Spatie\Backup\Notifications\Notifiable::class,

        'mail' => [
            'to' => '',
        ],

        'slack' => [
            'webhook_url' => '',

            'channel' => null,
        ],
    ],

    'monitorBackups' => [

    ],

    'cleanup' => [

        'strategy' => \Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy::class,

        'defaultStrategy' => [

            'keepAllBackupsForDays' => 7,

            'keepDailyBackupsForDays' => 16,

            'keepWeeklyBackupsForWeeks' => 8,

            'keepMonthlyBackupsForMonths' => 4,

            'keepYearlyBackupsForYears' => 2,

            'deleteOldestBackupsWhenUsingMoreMegabytesThan' => 5000,
        ],
    ],
];
```

This is the disk I added to `config/filesystems.php`:

```
'backup' => [
            'diver' => 'local',
            'root' => '/Users/r3l4x3/Sites/Laravel/dump',
        ]
```

And this is the output if I run `php artisan backup:run`:

> Starting backup...
> Dumping database abc...
> Determining files to backup...
> Zipping 123 files...
> Created zip containing 123 files. Size is 23.94 MB
> Copying zip to disk named backup...
> Copying zip failed because: There is no disk set for the backup destination.
> Backup completed!

No matter where I look, I can't find a backup.

Thank you for your help.

**Comment by AlexVanderbist** [comment]
Hi! Sorry for the late answer;

>Copying zip failed because: There is no disk set for the backup destination.

This makes me think Laravel/Flysystem has some issues with your defined backup disk. Can you try simply writing a file to it using Tinker or a test? This way you can make sure the backup disk is actually available for the package to use.

**Comment by xlith** [comment]
Hi,
I think in your config/filesystems.php you misspelled 'driver'. 

'backup' => [
            'diver' => 'local', **<-- this must be 'driver'**
            'root' => '/Users/r3l4x3/Sites/Laravel/dump',
        ]

**Comment by freekmurze** [comment]
Seems like @xlith found the root of the problem.

**Comment by kingfordCris** [comment]
CANT CREATE COMMENT DONT KNOW WHAT TO DO PLEASE HELP

$ php artisan backup:run

Starting backup...
Dumping database osms...
Backup failed because The dump process failed with exitcode 1 : General error : 'mysqldump' is not recognized as an internal or external command,operable program or batch file.
.
Backup completed!

**Comment by simmbiote** [comment]
> ... General error : 'mysqldump' is not recognized ...

If you're using Windows to test, then you just need to configure your Environment Variables so that you have the path to the folder with your mysql installation in the PATH environment variable. The folder should have mysql.exe and mysqldump.exe in it.
When you restart your console (ie. bash or cmd, etc), `mysqldump --help` should display information. If that's the case then   `php artisan backup:run`  should work.

**Comment by Riyadhahmed** [comment]
Use below code in your config/database.php file

'dump' => [
		   'dump_binary_path' => '/path/to/the/binary', // your mysqldump path [located at xampp/mysql/bin folder]
		   'use_single_transaction',
		   'timeout' => 60 * 5, // 5 minute timeout
		   'exclude_tables' => [],
		]
