### ISSUE TITLE
Storing to local instead of s3

### ISSUE THREAD

**Issue by AllCdnBoy** [spatie/laravel-backup#599]
About a month ago, backups started going to "local" instead of "s3".  There is no reference to local in the laravel-backup.php.  
`'destination' => [

            /*
             * The filename prefix used for the backup zip file.
             */
            'filename_prefix' => '',

            /*
             * The disk names on which the backups will be stored.
             */
            'disks' => [
                's3',
            ],
        ],`

and in my filesystems.php (which correctly works, as it's used in many other places throughout the site)
`'s3' => [
            'driver' => 's3',
            'key' => env('AWS_KEY'),
            'secret' => env('AWS_SECRET'),
            'region' => env('AWS_REGION'),
            'bucket' => env('AWS_BUCKET'),
        ]`

**Comment by AllCdnBoy** [comment]
nvm.  Config file was renamed at v5.0 ... this apparently didn't update the code and I missed it in the changelog

**Comment by aske-cph** [comment]
I also had this problem. 

I think critical changes like this that silently can stop all backups without warning should be avoided. 
It's pretty dangerous in my opinion.

I mean why risk hundreds of systems stopping their backups for a single name change? 

Anyways really great package otherwise!
