### ISSUE TITLE
Support for Digital Ocean's Object Storage

### ISSUE THREAD

**Issue by vmosoti** [spatie/laravel-backup#601]
This could be more of general filesystem question but how could I use this with Digital Ocean's Object Storage (Spaces)?

**Comment by freekmurze** [comment]
This package uses Flysystem to work with external filesystems. Because DO tries to mimick S3 you could try the S3 driver. Some more info on that here: https://www.digitalocean.com/community/questions/the-php-league-flysystem-for-spaces-object-storage
