### ISSUE TITLE
Using emoji for backup status?

### ISSUE THREAD

**Issue by gregrobson** [spatie/laravel-backup#602]
Version: 5.1.3 (and probably many prior versions)

I've just been testing a setup and noticed I was get [?] in the status list:
![image](https://user-images.githubusercontent.com/1911321/34951153-3bdf9edc-fa0d-11e7-8c4f-2d39eecd035c.png)

From what I can see the source code is outputting as emoji. Was there a particular reason why this was added? I've Googled and setting up emoji support on Windows looks tricky (if at all possible!).

I appreciate that it it's visually stronger, but from a devops perspective it's preferable to have as few dependencies as possible for backup systems, the idea of having to configure your console before being able to check backup status doesn't fill me with joy!

Happy to accept guidance from maintainers if you're happy to receive pull requests for this.

P.S. Sorry if this sounds petty. 🙂

**Comment by freekmurze** [comment]
Sorry, I'm not a Windows users, so i'm not going to put time in investigating this problem.
