### ISSUE TITLE
Back keeps emailing your@example.com even after changing config

### ISSUE THREAD

**Issue by warmwhisky** [spatie/laravel-backup#604]
Hi my config is set to email my personal email address, but it keeps emailing your@example.com

I am using Laravel 5.5 & "spatie/laravel-backup": "^5.1"

Am I missing something?

**Comment by warmwhisky** [comment]
I did upgrade from Laravel 5.2 to 5.5. he config is named `backup.php` is that wrong?

**Comment by freekmurze** [comment]
What's the output of `config('backup')` in a tinker session?

**Comment by warmwhisky** [comment]
I'm sorry I do not know what a tinker session is?

**Comment by freekmurze** [comment]
Here's some info on that: https://laravel.com/docs/5.5/artisan#introduction

Section "Laravel REPL"

**Comment by AlexVanderbist** [comment]
Just making sure; did you clear your config cache after changing the email address? `php artisan config:clear`

**Comment by warmwhisky** [comment]
Clearing my config cache worked thanks @AlexVanderbist.

Thanks for the help on this guys.
