### ISSUE TITLE
Parse error: In AttributeMatchingExtension.php line 46

### ISSUE THREAD

**Issue by shsbd** [spatie/laravel-backup#609]
![in attributematchingextension php line 46](https://user-images.githubusercontent.com/12555542/35196488-d5d76260-fefc-11e7-9b09-96d551f6236f.png)

```php
Symfony\Component\Debug\Exception\FatalThrowableErrorartisan backup:run --only-db

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)
```

![attributematchingextension php](https://user-images.githubusercontent.com/12555542/35196455-6b6946e6-fefc-11e7-8f9b-9764b6966cc1.jpg)

**Comment by freekmurze** [comment]
Seems like you're pulling in a version of `symfony/css-selector` that requires PHP 7.1 without you having installed PHP 7.1.

Can you upgrade to PHP 7.1?

**Comment by shsbd** [comment]
Thanks, @freekmurze Sir,

Your given solution works fine. I was also guessed similar kind of issue. Because the backup function works on dev server which has PHP `v7.1` but the live server had `v7.0`. After upgrading to PHP v7.1.* things work fine as expected.

Thank you again for the prompt solution.

**Comment by sureshPprajapati** [comment]
I am getting the same issue, my PHP version 7.2.6 still I am getting an error when using laravel 5.4 forgot password. pls tell me what a issue ?

**Comment by banbooboo** [comment]
> I am getting the same issue, my PHP version 7.2.6 still I am getting an error when using laravel 5.4 forgot password. pls tell me what a issue ?
> 
> https://prnt.sc/jy0g64
hi,I also getting  the same issue,would you tell me how to resolve this problem if you have done? thank you

**Comment by banbooboo** [comment]
> I am getting the same issue, my PHP version 7.2.6 still I am getting an error when using laravel 5.4 forgot password. pls tell me what a issue ?
> 
> https://prnt.sc/jy0g64

hi,I am getting the same issue,my PHP version 7.2.12,laravel 5.4 . 
 would you tell me how to solve this problem if you have done?

**Comment by joseguamanp** [comment]
como podria solucionar este problema sin actualizar mi servidor a una version superior, ya que el servidor trabaja con 5.6
