### ISSUE TITLE
Incremental Backups using Laravel

### ISSUE THREAD

**Issue by JoshuaBedford** [spatie/laravel-backup#610]
I am currently researching to find the best method for incremental backups within laravel projects. I have used your packages before, and they have always been phenomenal! Your website directed me here to ask this question: how can I configure this package to support incremental backups? A large project being zipped and stored continuously will take up large amounts of room, so I was curious if incremental backups had been planned in the making of this package. I apologize if this question belongs in a forum or email I have missed. Thanks!

**Comment by freekmurze** [comment]
No apologies needed. 

Because getting incremental backups right is kinda complicated, I've not implemented it. I want this package to be nice 'n' simple. 

If you need incremental backups, take a look at a solution such as [BackupPC](http://backuppc.sourceforge.net/).
