### ISSUE TITLE
Slack Notifications Incorrect, Google Backup Clean Incorrect

### ISSUE THREAD

**Issue by Braunson** [spatie/laravel-backup#612]
- Laravel 5.5.32
- Package Version: 5.1.5
- Filesystem Package: `nao-pon/flysystem-google-drive`
- Backup to Google

I have Slack notifications turned on for:

- BackupHasFailed
- UnhealthyBackupWasFound
- CleanupHasFailed
- BackupWasSuccessful
- HealthyBackupWasFound
- CleanupWasSuccessful

Commands running are:

- `backup:clean` @ 1am
- `backup:run` @ 2am
- `backup:monitor` @ 3am

Now my issue is the backup is created every day as expected, but the information on Slack about the backup for a few commands is incorrect.

I have a backup every day since the 19th however, each day when the commands run to backup, and this is the error I get when the monitor command runs

```
Spatie Backup Bot APP [3:00 AM]
Important: The backups for MyAcmeApp are unhealthy. There are no backups of this application at all.
Application name: MyAcmeApp
Disk: google
Newest backup size: No backups were made yet
Total storage used: 0 KB
Newest backup date: No backups were made yet
Oldest backup date: No backups were made yet
```

First this isn't true, as there is existing backups already there.

Second error is the successful new backup (the `backup:run` command) does create the backup but reports it as 0 KB on Slack, the other info is also incorrect about there being new previous or latest backups.. this is the Slack notification:

```
Spatie Backup Bot APP [2:00 AM]
Successful new backup!
Application name: MyAcmeApp
Disk: google
Newest backup size: No backups were made yet
Total storage used: 0 KB
Newest backup date: No backups were made yet
Oldest backup date: No backups were made yet
```

Any ideas why the Slack notification information is incorrect and the monitor isn't working properly.

**Comment by sgallard** [comment]
Same with nao-pon/flysystem-google-drive

**Comment by jpussacq** [comment]
In my case the only problem is that it does not **clean in Google** Drive and the disk is getting full. I always receive this message:

> Backup name: 1ibtk0QiroA4yErNjZqncaYQ3oxx5YETl
> Disk: google
> Newest backup size: No backups were made yet
> Total storage used: 0 KB
> Newest backup date: No backups were made yet
> Oldest backup date: No backups were made yet

**Then I have endless backups, because they are never cleaned. The local copies are cleaned well.**

Nota: the backup copies are made correctly, both locally and in Google Drive.

**Comment by jpussacq** [comment]
Is it possible that the system is not able to read information from the copies made in Google Drive? If you need help with more information, please tell me.

**Comment by elamotte** [comment]
I have the same issue with nao-pon/flysystem-google-drive

**Comment by timacdonald** [comment]
I've also just run into this with Backblaze

**Comment by jpussacq** [comment]
Hi. Any news about this issue? Or workaround? Thanks in advance!

**Comment by freekmurze** [comment]
@Braunson Is this still a problem or did #661 and #646 fix this?

**Comment by tridcatij** [comment]
Seems it's working now.  Btw, (I'm not sure this case related to this package) -  for now it's moving deleted files to the trash bin, maybe there is a way for permanent delete? It's very annoying to empty trash manually every time.

**Comment by freekmurze** [comment]
I'd like our package to be flysystem driver agnostic. So this should probably be fixed in the flysystem driver (or in your app).

**Comment by minhdanh** [comment]
Having problem with this as well. The space keeps filling up and one day backup doesn't work anymore.
