### ISSUE TITLE
Specify which database to backup in --only-db

### ISSUE THREAD

**Issue by Corys8646** [spatie/laravel-backup#614]
Hello, I have a site that has two databases. One database isn't updated that frequently so a backups a few days per week is fine, but the other database is updated more frequently so twice daily is what i'm after.

Is it possibly to specify which database to backup via the command line?

**Comment by freekmurze** [comment]
Currently this is not possible, but I'd accept a PR with tests that adds this to the package.

**Comment by mastercoder97** [comment]
hi good day. i have a question is it possible to backup multiple database in laravel. i have 5 databases to backup. if possible. how? thank you.

**Comment by freekmurze** [comment]
See #679
