### ISSUE TITLE
scheduling 'backup:clean' and 'backup:run' not working via crontab

### ISSUE THREAD

**Issue by aacsssh** [spatie/laravel-backup#617]
Hi

I am using Laravel 5.5 an 5.1 of this package. Like in the issue #410, when running 'php artisan backup:run', it works fine. Everything is saved in the storage folder. But, when I included it in the schedeul() method of App\Console\Kernel.php, it is not working. No backup files are created and saved.

Then, I ran command 'php artisan schedule:run' and it works flawlessly.

I have another command in Kernel.php that archives inactive users. It's working just fine via the cronjob. Only backup commands are not working. Below is the example

```
    protected function schedule(Schedule $schedule)
    {
        // Note: everyMinute() is just for testing purpose
        $schedule->command('backup:clean')->everyMinute(); // Not working 
        $schedule->command('backup:run')->everyMinute(); // Not working
        $schedule->command('ArchiveInActiveUsers:run')->everyMinute(); // This works
    }
```

What am I missing here? P.S. Thank you for this wonderful package.

**Comment by freekmurze** [comment]
Does it work if you install the package in a vanilla Laravel application?

**Comment by aacsssh** [comment]
@freekmurze Sorry for the late reply. Yes, it is working in vanilla Laravel application. Do we have any solution for this? What are the possible reasons and solutions? Thank you.

**Comment by jorgeirun** [comment]
I have the same problem, backup:run manually works perfect but not in the scheduler

**Comment by aireenrosas** [comment]
I have the same problem, backup:run manually works perfect but not in the scheduler
        $schedule->command('backup:run --only-db')->dailyAt('14:01');
