### ISSUE TITLE
Upload for Mega.nz? 

### ISSUE THREAD

**Issue by zerutreck** [spatie/laravel-backup#620]
Any prediction if you are interested in putting file upload functionality to the mega cloud?

**Comment by freekmurze** [comment]
Uploads to external filesystems are handled with FlySystem drivers. If there's a FlySystem driver for a filesystem, Laravel (and this package) can make use of it: https://flysystem.thephpleague.com/

If you want to use Mega.nz, check if someone has made a driver for it. If not, consider creating (and open sourcing) your own.
