### ISSUE TITLE
Set GTID to false when doing mysqldump

### ISSUE THREAD

**Issue by necenzurat** [spatie/laravel-backup#625]
I'm using this to backup a db on Google Cloud SQL.
Trying to restore from backup, it fails. 
The problems is that if a master/slave is set up, the backup is done from the slave. 
Solving this, can be done by adding ```--set-gtid-purged=OFF``` to the mysqldump command.

**Comment by AlexVanderbist** [comment]
Hi, that's a good catch! 

The `mysqldump` command is actually defined in https://github.com/spatie/db-dumper. Feel free to create an issue there or send a PR with a fix 👍.

Once the option for that flag is added in the db-dumper package we can add it in here.

**Comment by necenzurat** [comment]
@AlexVanderbist done, and [merged](https://github.com/spatie/db-dumper/commit/f0f17d12a168d543fa2ba0bdd0cddf68f9dac2f6).
