### ISSUE TITLE
Backup environment

### ISSUE THREAD

**Issue by divdax** [spatie/laravel-backup#627]
It is possible to create backups only on production via .env?
A config variable would be nice. e.g.:
```php
'backup' => [
    // value = string / comma list: production,dev
    'environment' => env('BACKUP_ENV', 'production'),
]
```

Or by default every environment is backed up and we exclude:
```php
'backup' => [
    'exclude_environment' => 'local,dev',
]
```

I know i can do this in my ServiceProvider and check for the environment, but an .env var still would be nice.

**Comment by freekmurze** [comment]
You can easily achieve this in your own project by not scheduled in the backup command  in a non-production environment.
