### ISSUE TITLE
backup:run from Artisan:call throws exception Undefined property: DOMDocument::$documentElement

### ISSUE THREAD

**Issue by Gogtsu** [spatie/laravel-backup#629]
Hello,
When i try to do a "php artisan backup:run --only-db" from this line of code : "Artisan::queue('backup:run',['--only-db'=>true]);" I get this exception:

Undefined property: DOMDocument::$documentElement
--
in CssToInlineStyles.php (line 128)
at HandleExceptions->handleError(8, 'Undefined property: DOMDocument::$documentElement', '/var/www/laravel-staging/vendor/tijsverkoyen/css-to-inline-styles/src/CssToInlineStyles.php', 128, array('document' => object(DOMDocument)))in CssToInlineStyles.php (line 128)
at CssToInlineStyles->getHtmlFromDocument(object(DOMDocument))in CssToInlineStyles.php (line 50)

but when I do it from command line, it works fine.

I don't send any emails from that controller method and I tried replacing that like with a simple Artisan:queue('cache clear'); and it works just fine.
So I'm thinking there's some update that messed up the mail system?

I'm using 
"laravel/framework": "5.4.*",
"spatie/laravel-backup": "^4.0.0"

Should I change versions? I tried with laravel-backup: 3.0.0 but I get this error "Method not found BackupWasSuccessful()". From the documentation I understand that v4 is for Laravel 5.4

Any ideas?

**Comment by Ethiel97** [comment]
Having this issue when sending mail from controller.

**Comment by Gogtsu** [comment]
@Ethiel97 I've changed from spatie-backup to https://github.com/spatie/laravel-db-snapshots because I couldn't send any emails because of that error
