### ISSUE TITLE
Schedule backup process

### ISSUE THREAD

**Issue by AEK-BKF** [spatie/laravel-backup#64]
As I can see there's an option " clean " to delete backups having  'maxAgeInDays' => 90,
So is there a possibility to set an option " run " each week run the backup for example ?

**Comment by freekmurze** [comment]
This is how we do it in our own applications

https://github.com/spatie-custom/blender/blob/master/app/Console/Kernel.php#L33
https://github.com/spatie-custom/blender/blob/master/app/Console/Commands/PerformScheduledBackup.php
