### ISSUE TITLE
Export to digitalocean spaces

### ISSUE THREAD

**Issue by hilmanrdn** [spatie/laravel-backup#641]
hey, i'd like to try this in DO Spaces
but seems not working, probably some kind of URL format

i know digitalocean spaces could use the s3 API.
I've tried change the 'disks' option on laravel-backup.php to s3 and It's working normally
but when i change it to DO it doesn't work

has anyone try it?

**Comment by freekmurze** [comment]
Probably this issue should go on the spaces flysystem driver you are using.
