### ISSUE TITLE
Cant dump Postgre database with GIS

### ISSUE THREAD

**Issue by tmoldri** [spatie/laravel-backup#642]
I get this error. I even tried to put it in exclude_tables array in the database.php conf file but it did not help.

`Backup failed because The dump process failed with exitcode 1 : General error : pg_dump: [archiver (db)] query failed: ERROR:  permission denied for schema public
pg_dump: [archiver (db)] query was: LOCK TABLE public.spatial_ref_sys IN ACCESS SHARE MODE`

I also tried creating new  user and granted all privileges to that but the error stll remains. What should i do?

**Comment by freekmurze** [comment]
Could you run `php artisan config:clear` and try again?

**Comment by tmoldri** [comment]
@freekmurze I tried it multiple times.

**Comment by freekmurze** [comment]
In that case, I'm afraid I can't help you, I'm not a Postgres user. Hopefully one of the users of this package can help you.

**Comment by bcalik** [comment]
Same thing also happens when you have a spatial column in a MySQL table.

**Comment by bcalik** [comment]
Adding `--hex-blob` parameter to mysqldump command solved my issue for MySQL. But I'm not a postgres user, so I don't know the solution for that.

@freekmurze So there should be an option in config file that adds `--hex-blob` to mysqldump command.

**Comment by freekmurze** [comment]
You can add any option you want via the the db config.

For an example see: https://docs.spatie.be/laravel-backup/v5/installation-and-setup#dumping-the-database

So I guess the solution here would be to define the db connection like this

```
//config/database.php
'connections' => [
	'mysql' => [
		'driver'    => 'mysql'
		...,
		'dump' => [
		   'add_extra_option' => '--hex-blob', 
		]  
	],
```

**Comment by bcalik** [comment]
I'm using laravel-backup v3. I think this is not valid for v3, right? It isn't documented in v3 docs. @freekmurze

**Comment by freekmurze** [comment]
No, this is only available is the latest versions. Please upgrade.

**Comment by tmoldri** [comment]
I hope there is a postgres user that can help me. I tried to google but i may be doing it wrong because i have not found a solution yet.
