### ISSUE TITLE
weekly and monthly backups are not being kept

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-backup#645]
Not sure what's causing this but I've noticed that using the default policy it seems that only the last 7 days worth of backups is kept

I have a limit of 5000mb and that limit is always "reached" right now so I don't know if that's what's causing all my older backups to be delete.. but still I would really like for at least one monthly backup to be kept for 4 months like the policy defines

I'm using the latest version 5.4.1 and the default policy:

```
        'defaultStrategy' => [

            /*
             * The number of days for which backups must be kept.
             */
            'keepAllBackupsForDays' => 7,

            /*
             * The number of days for which daily backups must be kept.
             */
            'keepDailyBackupsForDays' => 16,

            /*
             * The number of weeks for which one weekly backup must be kept.
             */
            'keepWeeklyBackupsForWeeks' => 8,

            /*
             * The number of months for which one monthly backup must be kept.
             */
            'keepMonthlyBackupsForMonths' => 4,

            /*
             * The number of years for which one yearly backup must be kept.
             */
            'keepYearlyBackupsForYears' => 2,

            /*
             * After cleaning up the backups remove the oldest backup until
             * this amount of megabytes has been reached.
             */
            'deleteOldestBackupsWhenUsingMoreMegabytesThan' => 5000,
        ],
```

My backup schedule looks like this:

```
            $schedule->command('backup:run --only-db')->twiceDaily();
            $schedule->command('backup:run --only-files')->daily()->at('03:33');
            $schedule->command('backup:clean')->daily()->at('04:00');
            $schedule->command('backup:monitor')->daily()->at('05:00');
```

Do I need to actually add a backup that runs monthly in order for "monthly" backups to be kept according to the policy ? Is that how it works? And I'd have to add yearly/weekly backups as well so that these are also kept?

I don't want these backups to be deleted when the limit of 5000mb is reached either. Instead the oldest daily backups should be deleted

**Comment by freekmurze** [comment]
> I don't want these backups to be deleted when the limit of 5000mb is reached either. Instead the oldest daily backups should be deleted

Right now this behaviour isn't supported. If you want this you must write your own strategy and specify the class name here: https://github.com/spatie/laravel-backup/blob/60c6fbc27c9c2cbdf3c7da90b080a63d2599cd2d/config/backup.php#L146
