### ISSUE TITLE
Problems backing up

### ISSUE THREAD

**Issue by eriktobben** [spatie/laravel-backup#65]
Hi!

This plugin have worked great until January 17th. I get the following error:

[2016-01-17 03:02:34] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Spatie\Backup\Commands\BackupCommand::warn()' in /home/forge/domain.com/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php:44

As I can see on line 44, the error message is "The zipfile that will be backupped has a filesize of zero.". The last backup size is 532MB. Is there a limit on backup size?

I am also running a separate backup job with DB only, and there has not been any problems with this.

**Comment by freekmurze** [comment]
Hi,

there is nu limit on the backup size. Could you try upgrading to the latest version of this package?

**Comment by eriktobben** [comment]
Great, thanks :) I think I might have found the problem. I see that my disk space was 94% full. Is it possible that this package temporarily stores the backup before its transmitted, and that it didnt delete this temp as the transfer failed? Or is there any other way there are backups stored on the server that is not deleted?

**Comment by freekmurze** [comment]
There were some problems regarding the cleaning of temp files in version < 2.8.3. If you upgrade to the latest version the package will clean up after itself :-)

**Comment by eriktobben** [comment]
Okey, I will try that :) Is there anything I need to know before upgrading? Any config that has to be done again?

**Comment by freekmurze** [comment]
Nope, there are only breaking changes when upgrading to a major version. If you're using 2.x now you shouldn't have any problem upgrading.

**Comment by eriktobben** [comment]
Thanks!

**Comment by eriktobben** [comment]
Hi again, sorry to bother you. The backup has run as planned for two days since the last problem, but last night I got the following error:

production.ERROR: exception 'Aws\Exception\MultipartUploadException' with message 'An exception occurred while uploading parts to a multipart upload. The following parts had errors:
- Part 10: Error executing "UploadPart" on "https://s3-eu-west-1.amazonaws.com/bucket/bucket/backups/backup-20160122030316.zip?partNumber=10&uploadId=(uploadID)"; AWS HTTP error: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
' in /vendor/aws/aws-sdk-php/src/Multipart/AbstractUploadManager.php:126

Do you know the reason of this error?

**Comment by freekmurze** [comment]
Unfortunately not. This package just uses the Laravel Cloud filesystem which using Flysystem under the hood. Best to check there what the source of this error could be.

**Comment by eriktobben** [comment]
Okey, thanks!
