### ISSUE TITLE
Failed Queues on backup:run

### ISSUE THREAD

**Issue by ralphjesy12** [spatie/laravel-backup#650]
When I try to call:
```
$exitCode = Artisan::queue('backup:run');
```

Job fails, and I'm getting this exception:
```
Symfony\Component\Console\Exception\CommandNotFoundException: There are no commands defined in the "backup" namespace. in ../vendor/symfony/console/Application.php:564
```

**Comment by sawyes** [comment]
add below to app.php
```
Spatie\Backup\BackupServiceProvider::class,
```

**Comment by ralphjesy12** [comment]
Already tried. Still not working. 
Just to add `Artisan::call('backup:run')` works, but what I want is to queue the backup.

**Comment by shez1983** [comment]
Artisan::queue('backup:run')

**Comment by chinmay235** [comment]
I want to download only database and apply following command:

`Artisan::call('backup:run --only-db');`

It is not working. Please help

**Comment by freekmurze** [comment]
@chinmay235 please create a new issue for that.

**Comment by freekmurze** [comment]
@ralphjesy12 If calling the backup command regularly works then your problem is probably related to your app or to Laravel itself, and not this package. Where you already able to fix this?

**Comment by ralphjesy12** [comment]
@freekmurze unfortunately nope, i just used a different method rather than queuing the backup. 
Yes, calling the command works `Artisan::call('backup:run')`, but not `Artisan::queue('backup:run')`.

**Comment by umerzafar2003** [comment]
clearing the cache works for me and showing the command in php artisan list 
php artisan cache:clear
php artisan view:clear
php artisan config:cache
php artisan debugbar:clear
