### ISSUE TITLE
Custom cleanup strategy empty collection with dropbox filesystem

### ISSUE THREAD

**Issue by fredekiel** [spatie/laravel-backup#654]
Hey there.

I've been backing my data with dropbox and have been using the default clean strategy.

I want to change it a little so I copied and renamed the default class but the $backups collection is empty? I have around 40 backups on dropbox.

**Comment by fredekiel** [comment]
Just tried to "manually" see my backups with:

```
$tst = Storage::disk('dropbox')->allFiles();

dd($tst);
```

And it works. 

Is this a known issue? Is it being worked on?

**Comment by larryx64** [comment]
I believe this is the same issue I had with the Google Drive file system.

The backup collection filters files by their extension and only keeps .zip files.

More info here:

https://github.com/spatie/laravel-backup/pull/646
