### ISSUE TITLE
Please update README.md

### ISSUE THREAD

**Issue by jagDanJu** [spatie/laravel-backup#66]
Hey,

please update your readme.md file. Some parts are in laravel 4 style:

>// config/app.php
>
>'providers' => [
>    ...
>    'Spatie\Backup\BackupServiceProvider',
>    ...
>];

it must be:

>// config/app.php
>
>'providers' => [
>    ...
>    Spatie\Backup\BackupServiceProvider::class,
>    ...
>];

**Comment by freekmurze** [comment]
This package is compatible with Laravel 5.0 / PHP5.4. `::class` was introduced in PHP5.5.
