### ISSUE TITLE
Using a B2 bucket

### ISSUE THREAD

**Issue by YakovGoldberger** [spatie/laravel-backup#667]
Hi,

I'm using a B2 bucket for the backups, and when I run `php artisan backup:list` it isn't detecting any existing backups, how would I go about figuring out why that is?

The package I'm using is [hpolthof/laravel-backblaze](https://github.com/hpolthof/laravel-backblaze)

Thank you

**Comment by YakovGoldberger** [comment]
Thank you @timacdonald 

btw, are you also using hpolthof/laravel-backblaze?

**Comment by YakovGoldberger** [comment]
> which hpolthof/laravel-backblaze uses under the hood.

I'm aware, I'm just not as good a developer as you :smile: 

Once the #661 is accepted and it's working, I'll close the issue.

Thank you

**Comment by timacdonald** [comment]
haha - I dunno - your the one who pulled in existing code to solve a problem - and I recreated the wheel. Sounds to me like your the smarter developer!

**Comment by YakovGoldberger** [comment]
Brilliant, thank you @timacdonald #661 solved it.

**Comment by timacdonald** [comment]
Awesome
