### ISSUE TITLE
Did not find Chrome

### ISSUE THREAD

**Issue by MadMikeyB** [spatie/laravel-backup#668]
Hi guys,

Thanks for the great package. How do I disable Chrome browsershots from the package?

Getting this error at 1am every night.

```production.ERROR: Did not find Chrome at: /usr/bin/google-chrome, /usr/bin/chromium {"exception":"[object] (Spatie\\Browsershot\\Exceptions\\CouldNotTakeBrowsershot(code: 0): Did not find Chrome at: /usr/bin/google-chrome, /usr/bin/chromium at /home/forge/forge.laravel.com/vendor/spatie/browsershot/src/Exceptions/CouldNotTakeBrowsershot.php:28)"} []```

**Comment by freekmurze** [comment]
This error is not caused by this package.
