### ISSUE TITLE
Generate daily, weekly and monthly backups

### ISSUE THREAD

**Issue by lowerends** [spatie/laravel-backup#67]
I'd like to know if it would be useful to have the ability to generate and keep daily backups for the last, say, 30 days, and weekly backups for the last 12 weeks and monthly backups for the last 12 months. Of course these numbers should be configurable.

This would allow for less backup storage while still maintaining old backups. How would you guys feel about this and how would you approach this?

**Comment by freekmurze** [comment]
This is a good idea for v3 of the package. ETA: somewhere in March. If it's not part of v3.0, I'll add it in a next point release.

**Comment by lowerends** [comment]
Great news also! I'll leave this open to discuss any possible ins and outs in the meanwhile.

**Comment by freekmurze** [comment]
I'm looking for a good name for this functionality (keep daily backups for the last, say, 30 days, and weekly backups for the last 12 weeks and monthly backups for the last 12 months). Does that strategy have a specific name?

**Comment by lowerends** [comment]
Well, I think the word "strategy" _is_ the name for this functionality. I'm not sure how you will implement this, but I was thinking something with daily, weekly, monthly and yearly folders that would each get their own removal frequency and number of backups to keep. 
Depending on how flexible this will be in terms of number and duration of backups to keep per time frame, you could call this feature "Configure your own backup strategy", or "backup strategy" in short.

**Comment by freekmurze** [comment]
Lots of interesting ideas there. Thanks!

**Comment by freekmurze** [comment]
I coded up the strategy:
https://github.com/spatie/laravel-backup/blob/v3/src/Tasks/Cleanup/Strategies/DefaultStrategy.php

Will probably refactor it in the coming days to make it more readable. Coming up with good function names is hard in this context. 

And of course I'll write some tests to prove that it works :-)

**Comment by mrwaim** [comment]
very cool. I would call it Backup Retention Policy

**Comment by freekmurze** [comment]
It will be included in V3.0

**Comment by lowerends** [comment]
Very nice, looking forward to it! :+1:
