### ISSUE TITLE
Failed to backup  because: The dump process failed with exitcode 127 : Command not found : sh: C:xamppmysqlbin/mysqldump: No such file or directory

### ISSUE THREAD

**Issue by fawel11** [spatie/laravel-backup#677]
My code works in local.But after pushing the code in live i got the error on mail:
Failed to backup  because: The dump process failed with exitcode 127 : Command not found : sh: C:xamppmysqlbin/mysqldump: No such file or directory
==>i am using cpanel shared hosting.

**Comment by freekmurze** [comment]
This problem is caused not by this package by your server configuration. Mysqldump isn't installed on your server or php doesn't have access to call it.

**Comment by gasner** [comment]
It an old question, but it happened to us too.
One of the programmers changing the path of the mysqldump.
In the database.php file, remove this (if you have)
``
            'dump' => [
            'dump_binary_path' => 'C:\xampp\mysql\bin',
            'use_single_transaction',
            'timeout' => 60 * 5, // 5 minute timeout
            ]
``
