### ISSUE TITLE
Need to backup multiple database

### ISSUE THREAD

**Issue by mastercoder97** [spatie/laravel-backup#679]
is it possible to backup multiple database or specify the db you need to back up. i really need to know thank you.

**Comment by freekmurze** [comment]
You can backup multiple databases. Just add all the connection names in this array. 

https://github.com/spatie/laravel-backup/blob/a26bbe95e4807f0cbb0f008e4ae2b6ff4b439060/config/backup.php#L40-L46

**Comment by mastercoder97** [comment]
i mean i have 5 mysql databases and i need to backup them thank you

**Comment by carlosmtrinidad** [comment]
Hi @mastercoder97 a quick fix multiple database backup would be the following:

In `config/database.php` add all the databases you need (just keep in mind the drivers supported)
Example:
```
'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => 'database_name_1',
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],

        'mysql2' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => 'database_name_2',
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
```
Then just add them to your `config/backup.php`
```
'databases' => [
                'mysql',
                'mysql2',
            ],
```

Now you can backup multiple databases.

**Comment by rarobi** [comment]
I want to backup multiple db via calling multiple schedules. I mean that is it possible to backup multiple db separately via calling multiple schedules command?

**Comment by chinmaypurav** [comment]
But will it be able to monitor multiple database backups?

I am having 2-3 applications (1 being a non laravel application, and everthing is dockerized, so I don't want to install mysqldump in the laravel app microservice)

I want one application just for backup up DBs and still be monitored

Is this possible?

**Comment by JeffChurchill** [comment]
@chinmaypurav check this out: https://tim.macdonald.au/backup-multiple-sites-frameworks-laravel-backup/

**Comment by vishalinfyom** [comment]
try this 

            Artisan::call('backup:run --only-db --db-name={new_db_connection_name_here}');
