### ISSUE TITLE
Email upon failure

### ISSUE THREAD

**Issue by lowerends** [spatie/laravel-backup#68]
In order to know whether a backup has failed, it would be good to be notified of this. This could for example be done via a configurable email address that would receive an email in case of a failure during the backup process. 

Would this be something that could be supported by this package via a PR? If so, any input on how to accomplish this would be welcome.

**Comment by freekmurze** [comment]
I'm currently working on [a new major version of the package](https://github.com/spatie/laravel-backup/tree/v3) that wil [send out a notification when a backup fails](https://github.com/spatie/laravel-backup/blob/v3/src/Notifications/Handlers/MailsErrors.php)

It will even [verify the backups of all your servers](https://github.com/spatie/laravel-backup/tree/v3/src/Tasks/Monitor) and will send out a notification when a backup is older than a given amount of days. (Yeah, the sources are still empty for the monitoring part, still have to code that up).

ETA: somewhere in beginning/middle March.

**Comment by lowerends** [comment]
Great news! I'll be testing that once it is released.

**Comment by freekmurze** [comment]
:+1:
