### ISSUE TITLE
different prefixes for database and files

### ISSUE THREAD

**Issue by xitara** [spatie/laravel-backup#682]
is it possible to use different prefixes for database- and file-backups without changing core-files?

**Comment by freekmurze** [comment]
I don't know what you mean. Could you give a practical example?

**Comment by xitara** [comment]
If I make a backup with --only-db i want a filename like 
db_2018-05-14-13-51-29.zip
and with --only-files
files_2018-05-14-13-51-29.zip

I call the backup with registerSchedule() in my Plugin.php (octoberCMS) and if I can do ist with any configuration directive, I feel better than I change the code of backup-plugin itself

**Comment by freekmurze** [comment]
This behaviour is not supported in the package.

**Comment by vesper8** [comment]
I'm achieving this with the code below:

```
            $schedule->command('backup:run --only-db --db-name api --db-name data')
            ->hourly()
            ->before(function () {
                Config::set('backup.backup.destination.filename_prefix', 'db_web_');
            });

            $schedule->command('backup:run --only-db --db-name forums')
            ->daily()
            ->before(function () {
                Config::set('backup.backup.destination.filename_prefix', 'db_forums_');
            });

            $schedule->command('backup:run --only-files')
            ->daily()
            ->before(function () {
                Config::set('backup.backup.destination.filename_prefix', 'files_web_');
            });
```
