### ISSUE TITLE
Backup artisan command issue in controller 

### ISSUE THREAD

**Issue by khizarzaman** [spatie/laravel-backup#684]
Sir i am facing an issue while executing "php artisan backup:run --only-db"  this command working fine in cmd (windows 7) while when i am using this command from laravel(5.6) Controller it shows me error "command is not defined". while artisan backup:run is working fine from controller.. but i want to generate only database backup ..

**Comment by cdcede** [comment]
Are you using Laravel Homestead?

**Comment by joshuajuanillo** [comment]
hi. i get same issue, have you fixed this issue? btw im using laravel 5.4

**Comment by jrmessias** [comment]
Same issue in Laravel v5.6

**Comment by bencomeau** [comment]
Hmm, I don't think this is an issue with the package...

How are you calling the command? If you're using the `Artisan` facade, then you should try passing the options to the command as an array:

    use Illuminate\Support\Facades\Artisan;
    
    Artisan::call('backup:run', [
        '--only-db' => 1
    ]);

https://laravel.com/docs/master/artisan#programmatically-executing-commands

Using that approach, is the issue still present?

**Comment by freekmurze** [comment]
@bencomeau 's suggestion seems like the way to go!

**Comment by NihirRootways** [comment]
@bencomeau iI tried your suggestion, but I received the  same issue
