### ISSUE TITLE
In BackupDestination.php line 138:

### ISSUE THREAD

**Issue by rconfig** [spatie/laravel-backup#687]
got the following error on first backup run.
Starting backup...

In BackupDestination.php line 138:
                                             
  Parse error: syntax error, unexpected '?'  

Resolved by removing '?' from lines 138 and 143.

**Comment by rconfig** [comment]
Similar issue for 

In BaseNotification.php line 57:
Parse error: syntax error, unexpected '?'
&
In BackupCollection.php line 14:

Why are those question marks there? I'm thinking its some php dependency. I'm running 7.0.27
PHP 7.0.27 (cli) (built: Jan 14 2018 09:00:22) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by freekmurze** [comment]
This package requires PHP 7.1

**Comment by rconfig** [comment]
hey man, i'm an open source maintainer with a large community to support. Thanks for what seems like a good tool. I've tried with 7.0, 7.1 and 7.2. All throwing errors for the type hinting (not my strongest area). 
Also getting other type errors when running from a controller using artisan::call.

"Type error: Return value of Spatie\Backup\Notifications\BaseNotification::backupDestination() must be an instance of Spatie\Backup\BackupDestination\BackupDestination, null returned"

might have to give up. Spent 1.5 hours trying to get it work. Looks promising though

**Comment by patriziotomato** [comment]
@freekmurze Would be helpful to reflect that requirement in
https://docs.spatie.be/laravel-backup/v5/requirements

Added a pull request.

**Comment by fendis0709** [comment]
You can downgrade your package to version 5.5.1
```bash
composer require spatie/laravel-backup:5.5.1
```
Tested on Laravel 5.5 using PHP 7.0
