### ISSUE TITLE
Include file by wilcards

### ISSUE THREAD

**Issue by zirikatzaile** [spatie/laravel-backup#688]
I'm trying to get working next config.

```
        'include' => [
          storage_path(),
          //public_path('img/logo.*'),
        ],

```
No way. Backup never takes place when I uncomment secind include line.

**Comment by freekmurze** [comment]
The tests seem to indicate that everything regarding file selection is working properly. Could you submit a failing test?

If you have cache your config, try running `php artisan config:clear` after you've modified the config file.

**Comment by freekmurze** [comment]
Could you submit a failing test?

**Comment by zirikatzaile** [comment]
do you mean a whole app zipped ???
