### ISSUE TITLE
Add/Remove Backup Databases connections at run time

### ISSUE THREAD

**Issue by naushrambo** [spatie/laravel-backup#692]
Hi,
I have multiple databases nearly 8 connections. Have a situation like i want to take 4 database connection backups on weekly, as these are huge db with minimum changes in a week, and 2 database on backups on daily basis and the other two in every 6 hours.
Tried on Laravel 5.6 with Cron and scheduler
Inside Controller 
`$d = config('laravel-backup.backup.source.databases');
$semidb = array('db_1','db_2','db_3');
config(['laravel-backup.backup.source.databases'=>$semidb]);
$exitCode = \Artisan::call('backup:run ');`

Inside config/backup.php
`'databases' => [
                'db_4','db_5','db_6',
            ],`

**Comment by freekmurze** [comment]
the `backup:run` command has [a `db-name` option](https://github.com/spatie/laravel-backup/blob/4d666be08c107c62216f126119d7986cd4456d5f/src/Commands/BackupCommand.php#L13) that you can use to set the databases you wish to backup

You can use the option multiple times to select multiple databases.
