### ISSUE TITLE
tmp files bug/feature

### ISSUE THREAD

**Issue by remcodn** [spatie/laravel-backup#70]
We use laravel-backup with an external file system to backup our DB. The package dumps the db file to the systems tmp dir "sys_get_temp_dir()"

But when an external file system fails to connect the files in the tmp dir will stay, maybe there should be build a fail safe to remove the TMP files when file movement fails.

In our case we noticed our SSD getting filled up very fast all of a sudden, after taking a look we had 22GB of tmp DB files because our backup FTP went offline for a couple of hours.

**Comment by freekmurze** [comment]
I did some work on the clean up of temporary files a few months ago. Are you using the latest version of the package?

**Comment by remcodn** [comment]
Currently where on "spatie/laravel-backup": "^2.8",

So seeing the change logs ill update first!

**Comment by freekmurze** [comment]
Reopen if you still have this problem.
