### ISSUE TITLE
TemporaryDirectory::__construct() must be of the type string, null given.

### ISSUE THREAD

**Issue by jringeisen** [spatie/laravel-backup#702]
I ran composer update yesterday and sense then I have been getting this error.

`TemporaryDirectory::__construct() must be of the type string, null given`

Any ideas?

**Comment by freekmurze** [comment]
I've identified a bug in version 5.9.0 It is fixed in version 5.9.1 which was just released, run `composer update` to pull it in.

**Comment by jringeisen** [comment]
Thank you!
