### ISSUE TITLE
Version 4: ssl read failed

### ISSUE THREAD

**Issue by Jossnaz** [spatie/laravel-backup#705]
getting this error when running `backup:clean`

> Cleanup failed because: ftp_close(): SSL read failed.

> Exception trace: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'ftp_close(): SS...', '/var/www/html/w...', 229, Array) #1 /var/www/html/www.mydomain.com/vendor/league/flysystem/src/Adapter/Ftp.php(229): ftp_close(Resource id #580) #2 /var/www/html/www.mydomain.com/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(577): League\Flysystem\Adapter\Ftp->disconnect() #3 /var/www/html/www.mydomain.com/vendor/league/flysystem/src/Adapter/Ftp.php(561): League\Flysystem\Adapter\AbstractFtpAdapter->getConnection() #4 /var/www/html/www.mydomain.com/vendor/league/flysystem/src/Adapter/Ftp.php(395): League\Flysystem\Adapter\Ftp->ftpRawlist('-A', 'http---www.find...') #5 /var/www/html/www.mydomain.com/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(535): League\Flysystem\Adapter\Ftp->getMetadata('http---www.find...') #6 /var/www/html/www.mydomain.com/vendor/league/flysystem/src/Filesystem.php(57): League\Flysystem\Adapter\AbstractFtpAdapter->has('http---www.find...') #7 /var/www/html/www.mydomain.com/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(48): League\Flysystem\Filesystem->has('http---www.find...') #8 /var/www/html/www.mydomain.com/vendor/spatie/laravel-backup/src/BackupDestination/Backup.php(29): Illuminate\Filesystem\FilesystemAdapter->exists('http---www.find...') #9 /var/www/html/www.mydomain.com/vendor/spatie/laravel-backup/src/BackupDestination/BackupCollection.php(48): Spatie\Backup\BackupDestination\Backup->exists() #10 [internal function]: Spatie\Backup\BackupDestination\BackupCollection->Spatie\Backup\BackupDestination\{closure}(Object(Spatie\Backup\BackupDestination\Backup), 1) #11 /var/www/html/www.mydomain.com/vendor/laravel/framework/src/Illuminate/Support/Arr.php(517): array_filter(Array, Object(Closure), 1) #12 /var/www/html/www.mydomain.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(282): Illuminate\Support\Arr::where(Array, Object(Closure)) #13 /var/www/html/www.mydomain.com/vendor/spatie/laravel-backup/src/BackupDestination/BackupCollection.php(49): Illuminate\Support\Collection->filter(Object(Closure)) #14 /var/www/html/www.mydomain.com/vendor/spatie/laravel-backup/src/Tasks/Cleanup/Strategies/DefaultStrategy.php(105): Spatie\Backup\BackupDestination\BackupCollection->oldest() #15 /var/www/html/www.mydomain.com/vendor/spatie/laravel-backup/src/Tasks/Cleanup/Strategies/DefaultStrategy.php(118): Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy->removeOldBackupsUntilUsingLessThanMaximumStorage(Object(Spatie\Backup\BackupDestination\BackupCollection)) #16 /var/www/html/www.mydomain.com/vendor/spatie/laravel-backup/src/Tasks/Cleanup/Strategies/DefaultStrategy.php(39): Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy->removeOldBackupsUntilUsingLessThanMaximumStorage(Object(Spatie\Backup\BackupDestination\BackupCollection)) #17 /var/www/html/www.mydomain.com/vendor/spatie/laravel-backup/src/Tasks/Cleanup/CleanupJob.php(42): Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy->deleteOldBackups(Object(Spatie\Backup\BackupDestination\BackupCollection)) #18 /var/www/html/www.mydomain.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(228): Spatie\Backup\Tasks\Cleanup\CleanupJob->Spatie\Backup\Tasks\Cleanup\{closure}(Object(Spatie\Backup\BackupDestination\BackupDestination), 1) #19 /var/www/html/www.mydomain.com/vendor/spatie/laravel-backup/src/Tasks/Cleanup/CleanupJob.php(52):

**Comment by freekmurze** [comment]
Seems like there is problem communicating with your ftp server.
