### ISSUE TITLE
Backup fails if mysqldump path is (rightly) empty.

### ISSUE THREAD

**Issue by aand18** [spatie/laravel-backup#706]
mysqldump path can be empty if you have the  `\mysql\bin\` directory in PATH

```
Starting backup...

In DbDumper.php line 151:
Too few arguments to function Spatie\DbDumper\DbDumper::setDumpBinaryPath(), 
0 passed in \vendor\spatie\laravel-backup\src\Tasks\Backup\DbDumperFactory.php on line 88 and exactly 1 expected    
```

The problem is `\Spatie\Backup\Tasks\Backup\DbDumperFactory::callMethodOnDumper` ignores *false-ish* values (like an empty string):

```
 protected static function callMethodOnDumper(DbDumper $dbDumper, string $methodName, $methodValue): DbDumper
    {
        if (! $methodValue) {     // <-------- HERE
            $dbDumper->$methodName();

            return $dbDumper;
        }
...
```

I'm not sure what the best practice is in this case. 
My first instinct would be to do something like this (my gut tells me this is not right, though):

```
 protected static function callMethodOnDumper(DbDumper $dbDumper, string $methodName, $methodValue = 'no value set'): DbDumper
    {
        if ($methodValue === 'no value set' ) {     // <-------- HERE
            $dbDumper->$methodName();

            return $dbDumper;
        }
...
```

Any thoughts?

**Comment by freekmurze** [comment]
The default configuration will just work, no?

**Comment by aand18** [comment]
@freekmurze  I don't see why it should, the default is 
`MYSQL_DUMP_PATH=/Applications/MAMP/Library/bin/` 
but on my machine `mysqldump` is in `C:\Program Files\MySQL\MySQL Server 5.7\bin\`

**Comment by freekmurze** [comment]
That `MYSQL_DUMP_PATH=/Applications/MAMP/Library/bin/` is not set by this package.
