### ISSUE TITLE
The backups for XXX on disk local are unhealthy.

### ISSUE THREAD

**Issue by Grupa-Leonardo** [spatie/laravel-backup#708]
```
The backups are using too much storage. Current usage is 16.32 GB which is higher than the allowed limit of 14.65 GB.
```
I have set limit for 15GB and after this mail, **ALL** backups are removed.

|                |        |
|----------------|--------|
| Laravel        | 5.4    |
| laravel-backup | 4.17   |
| PHP            | 7.1.18 |
| storage        | local  |

**Comment by freekmurze** [comment]
The tests seem to indicate that this is working properly in the latest version. Could you upgrade to the latest version?

If it still fails, PR a failing test.
