### ISSUE TITLE
Database backup more frequently than files backup

### ISSUE THREAD

**Issue by gizburdt** [spatie/laravel-backup#714]
Is it possible to run the files backup once a day, and the database backup 5 times a day?

Awesome package! :)

**Comment by gizburdt** [comment]
Hi Freek,

Thanks for your reply, but not really what I meant.

Is it possible to have a different interval for files and database? For exemple, backup the files once a day, and the database 5 times a day.

Thanks!

**Comment by freekmurze** [comment]
Let me make it more clear with a code example:

```php
// app/Console/Kernel.php

// ...

    protected function schedule(Schedule $schedule)
    {
        $schedule->command('backup:run --only-db')->hourly();
        $schedule->command('backup:run --only-files')->cron('0 */4 * * *'); //run every 4 hours
    }
```

**Comment by gizburdt** [comment]
Thanks! I didn’t know the —only-db flag.
