### ISSUE TITLE
How do I send on success email the backup file attached?

### ISSUE THREAD

**Issue by tudrare555** [spatie/laravel-backup#716]
I want when the backup is done, the notification mail that is sent to contain an attached file with that backup.
How do I do this?

**Comment by freekmurze** [comment]
Listen for the `BackupZipWasCreated` event. It contains a property with the path to the zipfile. 

More info: https://docs.spatie.be/laravel-backup/v5/taking-backups/events

**Comment by tudrare555** [comment]
Thans!

**Comment by farshadff** [comment]
hi @freekmurze  can you please give some advice on how to listen to that event in notification ? i could not find any solution for that . thanks
