### ISSUE TITLE
I want to install this package for Laravel 5.6, but I get an error every time.

### ISSUE THREAD

**Issue by ersengultepe** [spatie/laravel-backup#719]
I want to install this package for Laravel 5.6, but I get an error every time. Is this package not yet suitable for 5.6 version?
Is there a mistake in my practice?

"nao-pon / flysystem-google-drive": "~ 1.1", in my system, can it be an effect?

I add the error message that occurred during installation.
I'm waiting for your help.

C:\xampp\htdocs\pores>composer require "spatie/laravel-backup:^4.0.0"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.6.28
    - Conclusion: don't install laravel/framework v5.6.28
    - spatie/laravel-backup 4.0.0 requires illuminate/filesystem ~5.3.8 -> satisfiable by illuminate/filesystem[5.3.x-dev, v5.3.16, v5.3.23].
    - spatie/laravel-backup 4.0.1 requires illuminate/filesystem ~5.3.8 -> satisfiable by illuminate/filesystem[5.3.x-dev, v5.3.16, v5.3.23].
    - spatie/laravel-backup 4.0.2 requires illuminate/filesystem ~5.3.8 -> satisfiable by illuminate/filesystem[5.3.x-dev, v5.3.16, v5.3.23].
    - spatie/laravel-backup 4.0.3 requires illuminate/filesystem ~5.3.8 -> satisfiable by illuminate/filesystem[5.3.x-dev, v5.3.16, v5.3.23].
    - spatie/laravel-backup 4.0.4 requires illuminate/filesystem ~5.3.8 -> satisfiable by illuminate/filesystem[5.3.x-dev, v5.3.16, v5.3.23].
    - spatie/laravel-backup 4.1.0 requires illuminate/notifications ~5.3.8 -> satisfiable by illuminate/notifications[5.3.x-dev, v5.3.16, v5.3.23].
    - spatie/laravel-backup 4.10.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.11.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.12.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.12.1 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.13.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.13.1 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.14.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.14.1 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.14.2 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.15.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.16.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.17.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.18.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.18.1 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.19.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.19.1 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.19.2 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.2.0 requires illuminate/notifications ~5.3.8 -> satisfiable by illuminate/notifications[5.3.x-dev, v5.3.16, v5.3.23].
    - spatie/laravel-backup 4.3.0 requires illuminate/notifications ~5.3.8 -> satisfiable by illuminate/notifications[5.3.x-dev, v5.3.16, v5.3.23].
    - spatie/laravel-backup 4.3.1 requires illuminate/notifications ~5.3.8 -> satisfiable by illuminate/notifications[5.3.x-dev, v5.3.16, v5.3.23].
    - spatie/laravel-backup 4.3.2 requires illuminate/notifications ~5.3.8 -> satisfiable by illuminate/notifications[5.3.x-dev, v5.3.16, v5.3.23].
    - spatie/laravel-backup 4.3.3 requires illuminate/notifications ~5.3.8 -> satisfiable by illuminate/notifications[5.3.x-dev, v5.3.16, v5.3.23].
    - spatie/laravel-backup 4.3.4 requires illuminate/notifications ~5.3.8 -> satisfiable by illuminate/notifications[5.3.x-dev, v5.3.16, v5.3.23].
    - spatie/laravel-backup 4.4.0 requires illuminate/notifications ~5.3.8|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.3.16, v5.3.23, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.4.1 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.4.2 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.4.3 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.4.4 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.4.5 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.4.6 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.4.7 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.4.8 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.4.9 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.5.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.6.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.6.1 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.6.2 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.6.3 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.6.4 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.6.5 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.6.6 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.7.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.7.1 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.7.2 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.8.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.8.1 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.9.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup v4.x-dev requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[5.3.x-dev, 5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/filesystem 5.3.x-dev|don't install laravel/framework v5.6.28
    - don't install illuminate/filesystem v5.3.16|don't install laravel/framework v5.6.28
    - don't install illuminate/filesystem v5.3.23|don't install laravel/framework v5.6.28
    - don't install illuminate/notifications 5.3.x-dev|don't install laravel/framework v5.6.28
    - don't install illuminate/notifications v5.3.16|don't install laravel/framework v5.6.28
    - don't install illuminate/notifications v5.3.23|don't install laravel/framework v5.6.28
    - don't install illuminate/notifications 5.4.x-dev|don't install laravel/framework v5.6.28
    - don't install illuminate/notifications v5.4.0|don't install laravel/framework v5.6.28
    - don't install illuminate/notifications v5.4.13|don't install laravel/framework v5.6.28
    - don't install illuminate/notifications v5.4.17|don't install laravel/framework v5.6.28
    - don't install illuminate/notifications v5.4.19|don't install laravel/framework v5.6.28
    - don't install illuminate/notifications v5.4.27|don't install laravel/framework v5.6.28
    - don't install illuminate/notifications v5.4.36|don't install laravel/framework v5.6.28
    - don't install illuminate/notifications v5.4.9|don't install laravel/framework v5.6.28
    - Installation request for laravel/framework (locked at v5.6.28, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.28].
    - Installation request for spatie/laravel-backup ^4.0.0 -> satisfiable by spatie/laravel-backup[4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.1.0, 4.10.0, 4.11.0, 4.12.0, 4.12.1, 4.13.0, 4.13.1, 4.14.0, 4.14.1, 4.14.2, 4.15.0, 4.16.0,
 4.17.0, 4.18.0, 4.18.1, 4.19.0, 4.19.1, 4.19.2, 4.2.0, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.3.4, 4.4.0, 4.4.1, 4.4.2, 4.4.3, 4.4.4, 4.4.5, 4.4.6, 4.4.7, 4.4.8, 4.4.9, 4.5.0, 4.6.0, 4.6.1, 4.6.2, 4.6.3, 4.6.4, 4.6.5, 4.6.6, 4.7.0, 4.7.1
, 4.7.2, 4.8.0, 4.8.1, 4.9.0, v4.x-dev].

Installation failed, reverting ./composer.json to its original content.

**Comment by freekmurze** [comment]
Try running `composer require spatie/laravel-backup`. Composer will select the right version for you.

**Comment by ersengultepe** [comment]
I could build it this way, thank you @freekmurze
