### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by Einkoro** [spatie/laravel-backup#72]
Any possibility of supporting Lumen?

**Comment by freekmurze** [comment]
I'm not a Lumen user myself, so I won't probably work on this. If you need Lumen support, send a PR.

**Comment by etiennemarais** [comment]
Hey, It seems like you have to manually bind the filesystem contracts in lumen. Try this in your `bootstrap/app.php` file?

```
$app->singleton('filesystem', function ($app) {
    return $app->loadComponent('filesystems', Illuminate\Filesystem\FilesystemServiceProvider::class, 'filesystem');
});
$app->bind(Illuminate\Contracts\Filesystem\Factory::class, function($app) {
    return $app['filesystem'];
});
```

**Comment by etiennemarais** [comment]
Also, Seems like `Illuminate\Contracts\Logging\Log::class` is a hard dependency and lumen uses raw monolog. So if you want to get around that I suggest adding the illuminate log component to your composer.json like so:

`"illuminate/log": "~5.2"`

Also add this in your `bootstrap/app.php`:

```
$app->bind(Illuminate\Contracts\Logging\Log::class, function($app) {
    return $app['Psr\Log\LoggerInterface'];
});
```

and overwrite your LumenApplication class with your own and add an overwrite for the `registerLogBindings` method like so:

```
protected function registerLogBindings()
    {
        $this->singleton('Psr\Log\LoggerInterface', function () {
            if ($this->monologConfigurator) {
                $monolog = call_user_func($this->monologConfigurator, new Logger('lumen'));
            } else {
                $monolog = new Logger('lumen', [$this->getMonologHandler()]);
            }

            return new \Illuminate\Log\Writer($monolog); // <---this implements the correct contract
        });
    }
```

Worked for me, you might want to refactor the interface binding to an interface binding to a concrete to be cleaner but this works for lumen :)

**Comment by maojindao55** [comment]
but @etiennemarais  the method ``registerLogBindings ()``, where i should put in, which file?

**Comment by maihannijat** [comment]
This might help:
https://gist.github.com/mabasic/21d13eab12462e596120
