### ISSUE TITLE
How to create folder (daily, monthly) backup S3 laravel when using spatie backup?

### ISSUE THREAD

**Issue by abedputra** [spatie/laravel-backup#721]
I use laravel v5.5 and use spatie backup v5.
function backup is success. but when I check to S3, the path folder is **myBackup/2018-04-29-01-00-07.zip.**

I want the backup path is :
myBackup/**daily**/2018-04-29-01-00-07.zip.
myBackup/**monthly**/2018-05-29-01-00-07.zip.

is it possible ?

**Comment by freekmurze** [comment]
This is currently not possible.

**Comment by abedputra** [comment]
Thanks a lot for the information.
