### ISSUE TITLE
[Question] backup:clean - Explain the process & config

### ISSUE THREAD

**Issue by egodsk** [spatie/laravel-backup#723]
Hi. I'm trying to figure out how exactly the backup:clean process works, because I can't figure it out.

I have tried to do:
Create a backup, made 20 copies (so there exists 21 backups), used the following command in terminal:
`touch -mt 201806011800 FolderOfBackups`

Which edited all the modification dates to 1st of June 2018 18:00 according to my Mac finder.

But when i run the backup:clean, with 'keepAllBackupsForDays' => 10 and the rest of the options set to 0, it does nothing. It does not remove any backups. I would have thought that it would remove all of them, as they are older than 10 days?

Can someone explain to me how the backup:clean and the clean config works? (Or just explain what I'm doing wrong ;) ) (I want it to keep the last 30 days worth of daily backups. Meaning that if today is 1st of August, it should keep files from start of July until today. If the files are older than 30 days (lets say from 1st of June (about 60 days old), it should be deleted)

Thank you very much.

Clean config:

        'defaultStrategy' => [

            /*
             * The number of days for which backups must be kept.
             */
            'keepAllBackupsForDays' => 10,

            /*
             * The number of days for which daily backups must be kept.
             */
            'keepDailyBackupsForDays' => 0,

            /*
             * The number of weeks for which one weekly backup must be kept.
             */
            'keepWeeklyBackupsForWeeks' => 0,

            /*
             * The number of months for which one monthly backup must be kept.
             */
            'keepMonthlyBackupsForMonths' => 0,

            /*
             * The number of years for which one yearly backup must be kept.
             */
            'keepYearlyBackupsForYears' => 0,

            /*
             * After cleaning up the backups remove the oldest backup until
             * this amount of megabytes has been reached.
             */
            'deleteOldestBackupsWhenUsingMoreMegabytesThan' => 5000,
        ],
    ],

**Comment by freekmurze** [comment]
Here's a video where I explain it: https://youtu.be/fORNQ06K8LY?t=18m8s

It's also explained in the docs: https://docs.spatie.be/laravel-backup/v5/cleaning-up-old-backups/overview#determining-which-backups-should-be-deleted
