### ISSUE TITLE
Artisan::call('backup:run') failed

### ISSUE THREAD

**Issue by wangyongdong** [spatie/laravel-backup#726]
I have an urgent question.When I Used ` "spatie/laravel-backup": "^5.9.3" ` And ` "spatie/laravel-backup": "dev-master" `, I can get Success In cli run` php artisan backup:run `. But When I Run In Controller Used ` Artisan::call('backup:run') `,I get failed message.My used laravel5.5,The following is the error message sent to my mailbox.

Whoops!

Important: An error occurred while backing up 王永东博客
Exception trace: #0 E:\www\projects\blogL\vendor\spatie\db-dumper\src\DbDumper.php(235): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process)) #1 E:\www\projects\blogL\vendor\spatie\db-dumper\src\Databases\MySql.php(142): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), 'E:\www\projects...') #2 E:\www\projects\blogL\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(240): Spatie\DbDumper\Databases\MySql->dumpToFile('E:\www\projects...') #3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup{closure}(Object(Spatie\DbDumper\Databases\MySql), 'mysql') #4 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Support\Collection.php(861): array_map(Object(Closure), Array, Array) #5 E:\www\projects\blogL\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(243): Illuminate\Support\Collection->map(Object(Closure)) #6 E:\www\projects\blogL\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(165): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases() #7 E:\www\projects\blogL\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(141): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest() #8 E:\www\projects\blogL\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(52): Spatie\Backup\Tasks\Backup\BackupJob->run() #9 [internal function]: Spatie\Backup\Commands\BackupCommand->handle() #10 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array) #11 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container{closure}() #12 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #13 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Container\Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #14 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Console\Command.php(183): Illuminate\Container\Container->call(Array) #15 E:\www\projects\blogL\vendor\symfony\console\Command\Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle)) #16 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Console\Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle)) #17 E:\www\projects\blogL\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(16): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #18 E:\www\projects\blogL\vendor\symfony\console\Application.php(946): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #19 E:\www\projects\blogL\vendor\symfony\console\Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #20 E:\www\projects\blogL\vendor\symfony\console\Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #21 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Console\Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #22 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Console\Application.php(177): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #23 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(249): Illuminate\Console\Application->call('backup:run', Object(Illuminate\Support\Collection), NULL) #24 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(221): Illuminate\Foundation\Console\Kernel->call('backup:run', Array) #25 E:\www\projects\blogL\app\Http\Controllers\Admin\SetController.php(100): Illuminate\Support\Facades\Facade::__callStatic('call', Array) #26 [internal function]: App\Http\Controllers\Admin\SetController->store_backup(Object(Illuminate\Http\Request)) #27 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array) #28 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('store_backup', Array) #29 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Admin\SetController), 'store_backup') #30 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Route.php(169): Illuminate\Routing\Route->runController() #31 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Router.php(658): Illuminate\Routing\Route->run() #32 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #33 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #34 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure)) #35 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #36 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #37 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure)) #38 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #39 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(67): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #40 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure)) #41 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #42 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #43 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #44 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #45 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #46 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #47 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #48 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #49 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure)) #50 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #51 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #52 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure)) #53 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #54 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #55 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #56 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request)) #57 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route)) #58 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Router.php(590): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #59 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #60 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http{closure}(Object(Illuminate\Http\Request)) #61 E:\www\projects\blogL\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #62 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure)) #63 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #64 E:\www\projects\blogL\app\Http\Middleware\CheckForMaintenanceMode.php(48): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #65 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): App\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure)) #66 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #67 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #68 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #69 E:\www\projects\blogL\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request)) #70 E:\www\projects\blogL\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #71 {main}

**Comment by freekmurze** [comment]
This problem is probably caused by your server environment and not by this package. If you find out that this problem is caused by the package, feel free to submit a PR.

**Comment by wangyongdong** [comment]
This is a troublesome thing, I need to work hard to solve it. If you have a solution, I want to learn from it.Thanks.
