### ISSUE TITLE
Allow setting the destination disks using a command option

### ISSUE THREAD

**Issue by SjorsO** [spatie/laravel-backup#728]
I think it would be convenient if the destination disks could be overridden using a command option. That way you don't have to publish the config file for applications that only make simple database backups.

For example: I would like to make database backups to Dropbox. To do this I have to publish the config file, and add dropbox to the `backup.destination.disks` array. Then i can schedule the following command:

`artisan backup:run --only-db`

I would prefer to not have to publish the config file and be able to just schedule a command like this:

`artisan backup:run --only-db --set-destination-disks=dropbox`

Is this something you would accept a PR for?

**Comment by freekmurze** [comment]
We already have the `--only-to-disk` option.

**Comment by SjorsO** [comment]
The `--only-to-disk` option only works for disks you have already defined in the config file.

My suggested `--set-destination-disks` option would set the defined disk so you don't have to publish the config file in applications that only make simple database backups.

**Comment by freekmurze** [comment]
I'm thinking that use case isn't needed for the vast amount of users. Create a custom command and use that in your own project.

**Comment by SjorsO** [comment]
I think the default settings in the config file are good enough for most users (including me), except for the default destination disks. I can imagine that there are a lot of users that publish the (203 line long) config file and then only define the disk they want to send their backups to.

I think that adding a `--set-destination-disks` option would simplify getting basic backups running. If you want to configure more specific features like excluding files, cleanup strategies or health monitoring you can publish the config file. Don't you think so?

**Comment by freekmurze** [comment]
I think most users will just use the disks they defined in the config file and not send their backups to any others destinations.

**Comment by SjorsO** [comment]
Yea, but using this option you can avoid having to publish the config file
at all

**Comment by freekmurze** [comment]
I think most people will want to publish the config file.

**Comment by fabianPas** [comment]
+1 I think this actually would be very useful..
