### ISSUE TITLE
google cloud storage support?

### ISSUE THREAD

**Issue by litan1106** [spatie/laravel-backup#729]
Hello,

I couldn't backup to gcs. (https://github.com/Superbalist/laravel-google-cloud-storage)

Error: 
Copying zip failed because: There is no disk set for the backup destination.

my filesystem config

gcs' => [
    'driver' => 'gcs',
    'project_id' => env('GOOGLE_CLOUD_PROJECT_ID', 'MY-PROJECT-ID'),
    'key_file' => env('GOOGLE_CLOUD_KEY_FILE', null), // inside google cloud engine
    'bucket' => env('GOOGLE_CLOUD_STORAGE_BUCKET', 'database'),
    'path_prefix' => env('GOOGLE_CLOUD_STORAGE_PATH_PREFIX', null),
    'storage_api_uri' => env('GOOGLE_CLOUD_STORAGE_API_URI', null), 
],

**Comment by freekmurze** [comment]
The error indicates that there is no diskname set for the backup destination. Please check config/backup.php

**Comment by litan1106** [comment]
Thanks
