### ISSUE TITLE
Laravel 5.7 Support

### ISSUE THREAD

**Issue by farrance** [spatie/laravel-backup#731]
Hi guys, great package btw.

I'm in the process of updating my Laravel framework from 5.6 to 5.7. If I've understood this correctly, it looks like this package is blocking the update due to it having a dependency on some 5.6 parts of the framework.

An example dependency would be...

"illuminate/support": "~5.5.0|~5.6.0".

Is this correct? Are there any workarounds?

Thanks in advance,

Here's the snippet of the composer error...

`Problem 1
    - spatie/laravel-backup 5.10.0 requires illuminate/support ~5.5.0|~5.6.0 -> satisfiable by laravel/framework[v5.6.33], illuminate/support[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - spatie/laravel-backup 5.10.0 requires illuminate/support ~5.5.0|~5.6.0 -> satisfiable by laravel/framework[v5.6.33], illuminate/support[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.6.33].
    - don't install illuminate/support 5.5.x-dev|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support 5.6.x-dev|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.5.0|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.5.16|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.5.17|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.5.2|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.5.28|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.5.33|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.5.34|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.5.35|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.5.36|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.5.37|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.5.39|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.5.40|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.5.41|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.0|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.1|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.10|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.11|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.12|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.13|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.14|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.15|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.16|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.17|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.19|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.2|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.20|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.21|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.22|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.23|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.24|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.25|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.26|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.27|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.28|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.29|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.3|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.30|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.31|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.32|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.33|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.4|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.5|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.6|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.7|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.8|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v5.6.9|don't install laravel/framework 5.7.x-dev
    - Installation request for laravel/framework 5.7.* -> satisfiable by laravel/framework[5.7.x-dev].
    - Installation request for spatie/laravel-backup ^5.10 -> satisfiable by spatie/laravel-backup[5.10.0].`

**Comment by farrance** [comment]
Just this moment noticed that 5.7 is still pretty new (released August 2018). Sorry I've jumped the gun a bit...

**Comment by EmilMoe** [comment]
Don't worry @farrance I'm with you on this request for `5.7` support

**Comment by freekmurze** [comment]
We'll tag a compatible version as soon as Laravel 5.7 is released.
