### ISSUE TITLE
Backup fails if absolute path contains space

### ISSUE THREAD

**Issue by NSpehler** [spatie/laravel-backup#734]
Hello,

I've noticed that `php artisan backup:run` doesn't work if the website's absolute URL (locally) contains a space.

<img width="754" alt="screenshot 2018-08-23 14 52 11" src="https://user-images.githubusercontent.com/379186/44526672-0b2cb100-a6e5-11e8-88f2-00ab058b3420.png">

Thanks a lot,
Nicolas

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this!

**Comment by zOxta** [comment]
I believe it makes sense the most to handle this issue in the `spatie/db-dumper` package. I just submitted a pull request https://github.com/spatie/db-dumper/pull/80 that should take care of it.

**Comment by freekmurze** [comment]
👍
