### ISSUE TITLE
Backup has stopped at "zipping"

### ISSUE THREAD

**Issue by MikkyX** [spatie/laravel-backup#737]
I've added Laravel Backup to a Laravel 5.6 project and I'm testing it via `php artisan backup:run` on the command line.

It dumps the database, and makes the file list, then outputs to the console that it's zipping the files. The resulting Zip file is around 24gb, and was completed (it's lost the temporary extension, been renamed to <datestamp>.zip, and hasn't changed) , as I write this, half an hour ago - but the backup hasn't moved on to the next stage. The command line is still sat at the "zipping" stage:

```
user@server:~/folder$ php artisan backup:run
Starting backup...
Dumping database thedatabase...
Determining files to backup...
Zipping 10728 files...
```

It hasn't progressed any further. What is the next step it should be executing, and why isn't it getting there?

This is what I'm backing up in the config:
```
'source' => [

            'files' => [

                /*
                 * The list of directories and files that will be included in the backup.
                 */
                'include' => [
                    base_path(),
                ],

                /*
                 * These directories and files will be excluded from the backup.
                 *
                 * Directories used by the backup process will automatically be excluded.
                 */
                'exclude' => [
                    storage_path('framework'),
                    base_path('vendor'),
                    base_path('node_modules'),
                ],

                /*
                 * Determines if symlinks should be followed.
                 */
                'followLinks' => false,
            ],

            /*
             * The names of the connections to the databases that should be backed up
             * MySQL, PostgreSQL, SQLite and Mongo databases are supported.
             */
            'databases' => [
                'mysql',
            ],
        ],
```

`storage_path('framework')` is in there because I was trying to resolve an earlier issue similar to the one seen here: https://github.com/spatie/laravel-backup/issues/138

**Comment by MikkyX** [comment]
This may actually have been an SSH timeout meaning I didn't see what happened next (although the command doesn't appear to have carried on after I was timed out - not sure if that's expected?) - having amended my SSH timeout settings I can now see it completing. I'm going to close this myself as I think I've resolved, but I'll comment again if I notice it happening again.

**Comment by AliRazaLilani** [comment]
Resolved : I was uploading it to google drive and there was not enough space on my drive.
