### ISSUE TITLE
Copying zip failed because: There is no disk set for the backup destination.

### ISSUE THREAD

**Issue by scryba** [spatie/laravel-backup#738]
I tried using b2 using the package [laravel-backblaze-b2](https://github.com/gliterd/laravel-backblaze-b2)

but I get the output :

```
Starting backup...
Dumping database api...
Determining files to backup...
Zipping 1 files...
Created zip containing 1 files. Size is 66 KB
Copying zip to disk named local...
Successfully copied zip to disk named local.
Copying zip to disk named b2...
Copying zip failed because: There is no disk set for the backup destination.
Backup completed!
```

**Comment by scryba** [comment]
I got it working had to do with authentication issues.

**Comment by connecteev** [comment]
@scryba been struggling with this issue myself when I try to save to Dropbox. I followed all the steps here: https://timleland.com/backup-your-laravel-app-to-dropbox/

Any ideas?

**Comment by kuiperr005** [comment]
@scryba having the same issue here. What kind of authentication issues did you have?

**Comment by scryba** [comment]
@kuiperr005 and @connecteev  I had to use Master Application Key for it to work.

**Comment by kuiperr005** [comment]
@scryba Thanks, that was the case also for me, it works now!

**Comment by kyledevelop** [comment]
@scryba  in my case, it worked well on my local.
In only server, it doesn't work, same issue with yours.
I used Master Application key tho.
Any solution?
