### ISSUE TITLE
Multiple MySQL Databases

### ISSUE THREAD

**Issue by kevinjon27** [spatie/laravel-backup#745]
Hi bro, Thanks for this awesome project!

I want asking about, how I can do backup multiple mysql databases? I already open all issues, all of them just about multiple databases (mysql, pg, mongo). 

But, I need backup all my mysql database. Let say, I have 5 database on MySQL. How I do backup all of them? Of course, dynamic multiple database.

Thank you!

**Comment by freekmurze** [comment]
You can add multiple databases connections in the `databases` key in the config file.

https://github.com/spatie/laravel-backup/blob/6ae478be5b55a14e8bd82c57fa77ee3c776f698b/config/backup.php#L60

**Comment by Luksys3** [comment]
Solution: https://github.com/spatie/laravel-backup/issues/998#issuecomment-670687403
