### ISSUE TITLE
 spatie/laravel-backup 

### ISSUE THREAD

**Issue by jusyjk** [spatie/laravel-backup#747]
$ php artisan backup:monitor
The backups on local are considered unhealthy!

   Swift_TransportException  : Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials k8-v6sm58087765pga.80 - gsmtp
"

  at C:\xampp\htdocs\STC\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php:419
    415|         }
    416|
    417|         if (!$valid) {
    418|             $this->throwException(
  > 419|                 new Swift_TransportException(
    420|                     'Expected response code '.implode('/', $wanted).' but got code '.
    421|                     '"'.$code.'", with message "'.$response.'"',
    422|                     $code)
    423|                 );

  Exception trace:

  1   Swift_Transport_AbstractSmtpTransport::assertResponseCode("535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials k8-v6sm58087765pga.80 - gsmtp
")
      C:\xampp\htdocs\STC\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php:317

  2   Swift_Transport_AbstractSmtpTransport::executeCommand("RSET
", [])
      C:\xampp\htdocs\STC\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php:272

  Please use the argument -v to see more details.

**Comment by s1onez** [comment]
what is your question?
seems it a problem with your smtp server.
check you write the correct mail host, username and password
