### ISSUE TITLE
Add support for multiple databases

### ISSUE THREAD

**Issue by georgeboot** [spatie/laravel-backup#75]
We're using this packages to backup all of our apps. For some apps we however have multiple databases per app. This package currently only allows you to backup the default database.

It would be totally awesome if I could specify a list of connections / databases to be backed up!

**Comment by freekmurze** [comment]
O, do I have a treat for you. By the end of next week, a new major version of the `laravel-backup` package gets released. It has many new features, one is [backing up multiple databases](https://github.com/spatie/laravel-backup/blob/v3/config/laravel-backup.php#L35-L42).

So a little more patience, it's coming soon.

**Comment by freekmurze** [comment]
Version 3.0.0, which can backup multiple databases, is available now.

**Comment by Luksys3** [comment]
Solution to backup several databases: https://github.com/spatie/laravel-backup/issues/998#issuecomment-670687403
