### ISSUE TITLE
Feature request for "retry"

### ISSUE THREAD

**Issue by 1e4** [spatie/laravel-backup#752]
I was recently playing around with the Backup tool and it works great, the one problem I have though is if the upload fails for whatever reason I have to rerun the backup, which then zips up all the files again.

It would be great if there was a retry command which simply retries any failed backups.

Thanks for the package 👍

**Comment by freekmurze** [comment]
Because the currenr setup works for the vast majority of users and I like to keep the code base simple, I’m probably not going to include such a feature soon.
