### ISSUE TITLE
Intermittent failures, but working

### ISSUE THREAD

**Issue by McGarryIT** [spatie/laravel-backup#753]
Hi
I am wondering if you have seen intermittent failures which seem to correct themselves.
We backup the database every hour.
Over the last couple of days, a backup will fail, then at the next hour it will work.

The 1st error received was;
`backups backups : error: Failed to backup  because: The dumpfile could not be created`

The next error reported several hours later was;
` backups backups : error: Failed to backup  because: The each() function is deprecated. This message will be suppressed on further calls`

But as I say, subsequent backups worked.
Without us making any changes.

We are running Laravel 5.4, on an Ubuntu 64-bit server, on an AWS EC2 Instance.

Thanks
Paul.

**Comment by freekmurze** [comment]
I'm guessing this has something to do with the servers you are running this on. If there is something we can modify in the package, let us know!
