### ISSUE TITLE
Table 'performance_schema.session_variables' doesn't exist

### ISSUE THREAD

**Issue by batFormat** [spatie/laravel-backup#756]
Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Couldn't execute 'SHOW VARIABLES LIKE 'gtid\_mode'': Table 'performance_schema.session_variables' doesn't exist (1146)

**Comment by freekmurze** [comment]
This has probably something to do with your server setup and is not caused by our package. Try using our package with a freshly installed MySQL installation.

If you find that you problem is caused our package submit a PR that fixes this.
