### ISSUE TITLE
no database selected

### ISSUE THREAD

**Issue by naushrambo** [spatie/laravel-backup#757]
When uploading backup mysql file to another server where spatie library doesn't exist , it says no database selected. The mysql file is 5.3gb cant open and edit this file to add `use mydbname;`
please suggest how do i import mysql file.
i am using cli to import mysql file in my db server

**Comment by freekmurze** [comment]
There's too little information for us to go on here. 

Make sure you installed the package correctly and make sure that `php artisan backup:run` works when you run it manually.

**Comment by naushrambo** [comment]
The package is working perfectly. The problem is only when i want to import the sql file to another database server using cli import command , since DB name is not mention in file and i also cannot open the file since it is 5.3gb . so please help me.
