### ISSUE TITLE
Not taking backup from controller

### ISSUE THREAD

**Issue by shahmir811** [spatie/laravel-backup#758]
I am facing an issue while executing "php artisan backup:run --only-db" from controller.
It is working fine from cmd but give the following error when used in controller or in cron job.

> Exception message: The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2004: "Can't create TCP/IP socket (10106 "Unknown error")" when trying to connect

Kindly dont refer me to [Misuse of shell builtins](https://github.com/spatie/laravel-backup/issues/92) issue.
I tried everything but failed.

I am using **Laravel 5.7, php 7.1.**
Please reply.

**Comment by rizalreza** [comment]
I have same issue on Laravel 5.5 and php 7.1.
It is work when i run from cmd but have that error when i run from controller.
have you fix this issue?

**Comment by shahmir811** [comment]
@rizalreza nopes. Not yet.
No one responded from @spatie-bot yet... Still facing issue

**Comment by freekmurze** [comment]
I'm thinking that your php fpm (or whatever process you use to handle web requests) doesn't have the right permission to execute stuff on the shell. There's nothing our package can do to fix it.

See if you can recreate the problem by creating another artisan command and executing something on the shell from there.

**Comment by joseAlex27** [comment]
> I'm thinking that your php fpm (or whatever process you use to handle web requests) doesn't have the right permission to execute stuff on the shell. There's nothing our package can do to fix it.
> 
> See if you can recreate the problem by creating another artisan command and executing something on the shell from there.
A lot of people facing the same problem, of course that is your package
