### ISSUE TITLE
Google Drive 

### ISSUE THREAD

**Issue by 1m0rt4l** [spatie/laravel-backup#760]
Hello, so I hope that raising this issue might help someone.

I'm currently setting up a Laravel 5.7 app.
With:
_-hyn/multi-tenant
-spatie/laravel-backup
-nao-pon/flysystem-google-drive_

With this I stumbled upon the following issue:

Laravel-backup **hangs** in "**Successfully copied zip to disk named google.**"

What I've done is:

* I have multiple databases created via hyn/multi-tenant.
* I created the required GoogleDriveServiceProvider using nao-pon/flysystem-google-drive.
* I set up all necessary GOOGLE_DRIVE_* API info.
* In filesystems.php added a 'google' disk, related to my google drive configuration.
* I added the disk 'google' to laravel-backup config file.
* I solved the error code "404" - "File not found." setting `\Config::set('backup.backup.name', '');`

Done. It's working. Almost.

Problem is that it hangs after saving the first compressed file. After debugging the problem a bit. I found out the problem is motivated by this line:

`$this->sendNotification(new BackupWasSuccessful($backupDestination));`

After **commenting** this line in` vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php` it works as expected. Creates all backups for each tenant/database local/google drive. Just doesn't send a notification (duh).

Why is this? It works fine as hell locally. But when using my 'google' custom disk, hangs in a hard to debug function.

Sorry for the long post. Please provide any help if you can.

**Comment by HeathMorrisCode** [comment]
I had the exact same problem.

Inside config/backup.php, I made sure to remove 'mail' from all of the notification arrays, since I wasn't using it and didn't have it configured anyways:

`        'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class         => [''],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => [''],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class        => [''],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class     => [''],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class   => [''],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class    => [''],
        ],`

That fixed the hanging for me, hope that helps someone.
