### ISSUE TITLE
ZipArchive::close(): Read Error. No such file or directory.

### ISSUE THREAD

**Issue by rurko** [spatie/laravel-backup#762]
Hello. 
Thank you for your package, it helps greatly.
Making backups in some projects, I encountered an error:
`Backup failed because ZipArchive::close(): Read error: No such file or directory.`
This error occurs when any file added to the archive ( `$zip->add(...)` ) was deleted before calling the `$zip->close();`. 
Thus the use of this package in projects with temporary or changing files may not be possible.
It seems to me that the only solution to this problem is to copy the changing files (specified in the configuration file) to a temporary folder and only then add them to the archive.
_p.s. Sorry for my English._
Best Regards,
Alex.

**Comment by hulkur** [comment]
You should add temporary files to ignore list in backup config.
