### ISSUE TITLE
Mysqldump: Error 2013

### ISSUE THREAD

**Issue by jpussacq** [spatie/laravel-backup#763]
Hi:

I am getting the following error:

> The dump process failed with exitcode 3 : Unknown error : mysqldump: Error 2013: Lost connection to MySQL server during query when dumping table correos at row: 4161

I think the problem is because a large table.
What can I do? My bakcup is failing.

Thanks in advance!

**Comment by freekmurze** [comment]
The package can't help you with this, I think you need to solve this at the mysql level and keep a connection open for a longer time.

**Comment by jpussacq** [comment]
Is it possible tu run a command like the following, before performing the backup?

DB::statement("SSET session wait_timeout=300");

Because I cannot update mySQL server in a shared hosting.

Thanks!

**Comment by freekmurze** [comment]
Fork the package and add it to your own copy.
