### ISSUE TITLE
 General error: "mysqldump" is not recognized as an internal or external command, program or executable batch file.

### ISSUE THREAD

**Issue by LuisRS1** [spatie/laravel-backup#766]
Backup failed because: The dump process failed with exitcode 1: General error: "mysqldump" is not recognized as an internal or external command, program or executable batch file.
The command run on Console but in a Controller don't
![image](https://user-images.githubusercontent.com/38310331/46579708-64724a80-c9dc-11e8-92e4-799a1252bc1e.png)

![image](https://user-images.githubusercontent.com/38310331/46579820-4dccf300-c9de-11e8-8d31-d9eee5d5887d.png)

![image](https://user-images.githubusercontent.com/38310331/46579701-3c82e700-c9dc-11e8-9774-c97c193e96e6.png)

**Comment by hulkur** [comment]
probably due to different PATH declaration for http user

**Comment by freekmurze** [comment]
Indeed, there's nothing here to be fixed in the package.
