### ISSUE TITLE
Misuse of shell builtins : mysqldump: Got error: 2004: "Can't create TCP/IP socket"

### ISSUE THREAD

**Issue by SVIJAY2286** [spatie/laravel-backup#767]
> Starting backup...
> 
> Dumping database hms...
> 
> Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2004: "Can't create TCP/IP socket (10106 "Unknown error")" when trying to connect\r\n 

I got the following error while trying to

> Artisan::call('backup:run'); 
>
>$output=Artisan::output();

using **php artisan backup:run** on the command line works fine.
[![enter image description here][1]][1]

calling it laravel's Artisan gives that error.

I correctly assign the **config/database.php** dump

    'mysql' => [
                ...
                'dump' => [
                   'dump_binary_path' => 'C:\xampp\mysql\bin',
                   'use_single_transaction',
                   'timeout' => 60 * 5, 
                   'exclude_tables' => ['table1', 'table2'],
                ]  
            ],

Please, help me.

  [1]: https://i.stack.imgur.com/QiwkP.jpg

**Comment by freekmurze** [comment]
This error is probably caused by some permission issue on your system and not by our package.

**Comment by wemersonrv** [comment]
What type of permissions are need her ? Because it works when run on CLI, both `myqldump` direct or `php artisan backup:run`...

**Comment by AmrSubZero** [comment]
Having the same issue `Laravel 8.60.0`

Running `php artisan backup:run` from `CLI` works. but doesn't work from web interface,

```
'dump' => [
    'dump_binary_path' => 'c:/xampp/mysql/bin/',
    'use_single_transaction',
    'timeout' => 60 * 5, // 5 minute timeout
    // 'exclude_tables' => ['table1', 'table2'],
    // 'add_extra_option' => '--optionname=optionvalue',
],
```
