### ISSUE TITLE
ZipArchive::close(): Can't open file: No such device or address.

### ISSUE THREAD

**Issue by robinnpca** [spatie/laravel-backup#768]
Backup failed because ZipArchive::close(): Can't open file: No such device or address.
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'ZipArchive::clo...', '/var/www/html/c...', 82, Array)
#1 /var/www/html/comefo/vendor/spatie/laravel-backup/src/Tasks/Backup/Zip.php(82): ZipArchive->close()
....

cannot use php  artisan backup:run

Cannot find the solution

I change my www folder to
chmod -R 777 /var/www
chmod -R www-data:www-data /var/www

still cannot  solve the issue....

**Comment by freekmurze** [comment]
The tests seem to indicate that zipping files is working fine. This error is probably caused by something on your end. If you do find the package itself is in error, please submit a failing test for us to look at.
