### ISSUE TITLE
can use tar.gz to replace .zip as the zip cannot preserve the permisiion

### ISSUE THREAD

**Issue by robinnpca** [spatie/laravel-backup#770]
php artisan backup:run I got the 2018xxx.zip
when I 
unzip 2018xxx.zip
I found the permission owner changed?
how can I preserve the owner and permission or can I backup with the tar.gz as it can perserve the permission by tar -zxvpf 2018xxx.tar.gz

**Comment by freekmurze** [comment]
There's too little info for me to go here. Please submit a failing test for me to look at.
