### ISSUE TITLE
Issues with tests on Windows, Spatie\Backup\Test\Integration\BackupCommandTest::it_includes_files_from_the_local_disks_in_the_backup

### ISSUE THREAD

**Issue by Turtle1363** [spatie/laravel-backup#771]
I have read in other issues that you don't officially support Windows, but that this package should work on Windows.

I'm very eager to have this work on Windows, because it looks like a GREAT package that would suit my needs perfectly.

However, I'm just starting out with the package, and decided to run the unit tests.

I am seeing an error in test:

Spatie\Backup\Test\Integration\BackupCommandTest::it_includes_files_from_the_local_disks_in_the_backup

The cause seems to be related to the function in Zip.php line 34

    protected static function determineNameOfFileInZip(string $pathToFile, string $pathToZip)

The result .zip file does not include any files and I get a message from the test:

    Failed to assert that C:\Users\john.doe\Documents\GitHub\laravel-backup\tests/temp\mysite/2016-01-01-21-01-01.zip contains a file name testing-file.txt

I'm assuming the result of `determineNameOfFileInZip` for that file should be 'testing-file.txt', however when I run the test, the function $zipDirectory and $fileDirectory don't seem to be set correctly, and the `starts_with` call fails.

I just want to verify that the result of `determineNameOfFileInZip` should be 'testing-file.txt' before I go on a wild goose chase.

BTW, there are related errors for other tests.  I'd like to help fix these if I can, and submit pull requests for the fixes.  Any guidance or support you can provide is appreciated.

**Comment by Turtle1363** [comment]
I create a pull request that I think fixes that issue for windows?

https://github.com/spatie/laravel-backup/pull/772

**Comment by freekmurze** [comment]
Let's continue this conversation in #772
