### ISSUE TITLE
Getting File not Found error google backup

### ISSUE THREAD

**Issue by ClickerTech** [spatie/laravel-backup#777]
Hi,

Local backup is working using spatie/laravel-backup but in google backup iam getting beloow error,

Exception message: { "error": { "errors": [ { "domain": "global", "reason": "notFound", "message": "File not found: Example-Company.", "locationType": "parameter", "location": "fileId" } ], "code": 404, "message": "File not found:Example-Company

Filesystem.php
'google' => [ 'driver' => 'google', 'clientId' => env('GOOGLE_DRIVE_CLIENT_ID'), 'clientSecret' => env('GOOGLE_DRIVE_CLIENT_SECRET'), 'refreshToken' => env('GOOGLE_DRIVE_REFRESH_TOKEN'), 'folderId' => env('GOOGLE_DRIVE_FOLDER_ID'), ],

config/backup.php
`<?php

return [

'backup' => [

    /*
 * The name of this application. You can use this name to monitor
 * the backups.
 */
    'name' => config('app.name'),

    'source' => [

        'files' => [

            /*
         * The list of directories and files that will be included in the backup.
         */
            'include' => [
                base_path(),
            ],

            /*
             * These directories and files will be excluded from the backup.
             *
             * Directories used by the backup process will automatically be excluded.
             */
            'exclude' => [
                base_path('vendor'),
                base_path('node_modules'),
            ],

            /*
             * Determines if symlinks should be followed.
             */
            'followLinks' => false,
        ],

        /*
         * The names of the connections to the databases that should be backed up
         * MySQL, PostgreSQL, SQLite and Mongo databases are supported.
         *
         * The content of the database dump may be customized for each connection
         * by adding a 'dump' key to the connection settings in config/database.php.
         * E.g.
         * 'mysql' => [
         *       ...
         *      'dump' => [
         *           'excludeTables' => [
         *                'table_to_exclude_from_backup',
         *                'another_table_to_exclude'
         *            ]
         *       ]
         * ],
         *
         * For a complete list of available customization options, see https://github.com/spatie/db-dumper
         */
        'databases' => [
            'mysql',
        ],
    ],

    /*
     * The database dump can be gzipped to decrease diskspace usage.
     */
    'gzip_database_dump' => false,

    'destination' => [

        /*
     * The filename prefix used for the backup zip file.
     */
        'filename_prefix' => '',

        /*
         * The disk names on which the backups will be stored.
         */
        'disks' => [
            'google',
            'local',
        ],
    ],

    /*
     * The directory where the temporary files will be stored.
     */
    'temporary_directory' => storage_path('app/backup-temp'),
],

/*
 * You can get notified when specific events occur. Out of the box you can use 'mail' and 'slack'.
 * For Slack you need to install guzzlehttp/guzzle.
 *
 * You can also use your own notification classes, just make sure the class is named after one of
 * the `Spatie\Backup\Events` classes.
 */
'notifications' => [

    'notifications' => [
        \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class => ['mail'],
        \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail'],
        \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class => ['mail'],
        \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class => ['mail'],
        \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class => ['mail'],
        \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class => ['mail'],
    ],

    /*
     * Here you can specify the notifiable to which the notifications should be sent. The default
     * notifiable will use the variables specified in this config file.
     */
    'notifiable' => \Spatie\Backup\Notifications\Notifiable::class,

    'mail' => [
        'to' => 'info@clickerstudio.in',

    ],

    'slack' => [
        'webhook_url' => '',

        /*
         * If this is set to null the default channel of the webhook will be used.
         */
        'channel' => null,

        'username' => null,

        'icon' => null,

    ],
],

/*
 * Here you can specify which backups should be monitored.
 * If a backup does not meet the specified requirements the
 * UnHealthyBackupWasFound event will be fired.
 */
'monitorBackups' => [
    [
        'name' => config('app.name'),
        'disks' => ['local'],
        'newestBackupsShouldNotBeOlderThanDays' => 1,
        'storageUsedMayNotBeHigherThanMegabytes' => 5000,
    ],

    /*
    [
        'name' => 'name of the second app',
        'disks' => ['local', 's3'],
        'newestBackupsShouldNotBeOlderThanDays' => 1,
        'storageUsedMayNotBeHigherThanMegabytes' => 5000,
    ],
 */
],

'cleanup' => [
    /*
 * The strategy that will be used to cleanup old backups. The default strategy
 * will keep all backups for a certain amount of days. After that period only
 * a daily backup will be kept. After that period only weekly backups will
 * be kept and so on.
 *
 * No matter how you configure it the default strategy will never
 * delete the newest backup.
 */
    'strategy' => \Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy::class,

    'defaultStrategy' => [

        /*
     * The number of days for which backups must be kept.
     */
        'keepAllBackupsForDays' => 7,

        /*
         * The number of days for which daily backups must be kept.
         */
        'keepDailyBackupsForDays' => 16,

        /*
         * The number of weeks for which one weekly backup must be kept.
         */
        'keepWeeklyBackupsForWeeks' => 8,

        /*
         * The number of months for which one monthly backup must be kept.
         */
        'keepMonthlyBackupsForMonths' => 4,

        /*
         * The number of years for which one yearly backup must be kept.
         */
        'keepYearlyBackupsForYears' => 2,

        /*
         * After cleaning up the backups remove the oldest backup until
         * this amount of megabytes has been reached.
         */
        'deleteOldestBackupsWhenUsingMoreMegabytesThan' => 5000,
    ],
],
];
`
provider

`<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class GoogleDriveServiceProvider extends ServiceProvider
{
/**
* Bootstrap services.
*
* @return void
*/
public function boot()
{
\Storage::extend('google', function ($app, $config) {
$client = new \Google_Client();
$client->setClientId($config['clientId']);
$client->setClientSecret($config['clientSecret']);
$client->refreshToken($config['refreshToken']);
$service = new \Google_Service_Drive($client);
$adapter = new \Hypweb\Flysystem\GoogleDrive\GoogleDriveAdapter($service, $config['folderId']);
return new \League\Flysystem\Filesystem($adapter);
});
}

/**
 * Register services.
 *
 * @return void
 */
public function register()
{
    //
}
}
`

where i am wrong

help

see this https://github.com/ivanvermeyen/laravel-google-drive-demo/issues/44#issuecomment-433702298

**Comment by freekmurze** [comment]
I don't use Google Drive storage so can't help you here. I'm closing this because this error is probably originating in the driver.

If our package should be in error, send a PR.

**Comment by ifarooq** [comment]
> Hi,
> 
> Local backup is working using spatie/laravel-backup but in google backup iam getting beloow error,
> 
> Exception message: { "error": { "errors": [ { "domain": "global", "reason": "notFound", "message": "File not found: Example-Company.", "locationType": "parameter", "location": "fileId" } ], "code": 404, "message": "File not found:Example-Company
> 
> Filesystem.php
> 'google' => [ 'driver' => 'google', 'clientId' => env('GOOGLE_DRIVE_CLIENT_ID'), 'clientSecret' => env('GOOGLE_DRIVE_CLIENT_SECRET'), 'refreshToken' => env('GOOGLE_DRIVE_REFRESH_TOKEN'), 'folderId' => env('GOOGLE_DRIVE_FOLDER_ID'), ],
> 
> config/backup.php
> `<?php
> 
> return [
> 
> 'backup' => [
> 
> ```
> /*
> ```
> 
> * The name of this application. You can use this name to monitor
> * the backups.
>   */
>   'name' => config('app.name'),
>   'source' => [
>   ```
>    'files' => [
>   
>        /*
>     * The list of directories and files that will be included in the backup.
>     */
>        'include' => [
>            base_path(),
>        ],
>   
>        /*
>         * These directories and files will be excluded from the backup.
>         *
>         * Directories used by the backup process will automatically be excluded.
>         */
>        'exclude' => [
>            base_path('vendor'),
>            base_path('node_modules'),
>        ],
>   
>        /*
>         * Determines if symlinks should be followed.
>         */
>        'followLinks' => false,
>    ],
>   
>    /*
>     * The names of the connections to the databases that should be backed up
>     * MySQL, PostgreSQL, SQLite and Mongo databases are supported.
>     *
>     * The content of the database dump may be customized for each connection
>     * by adding a 'dump' key to the connection settings in config/database.php.
>     * E.g.
>     * 'mysql' => [
>     *       ...
>     *      'dump' => [
>     *           'excludeTables' => [
>     *                'table_to_exclude_from_backup',
>     *                'another_table_to_exclude'
>     *            ]
>     *       ]
>     * ],
>     *
>     * For a complete list of available customization options, see https://github.com/spatie/db-dumper
>     */
>    'databases' => [
>        'mysql',
>    ],
>   ```
>   
>   
>   ],
>   /*
>   
>   * The database dump can be gzipped to decrease diskspace usage.
>     */
>     'gzip_database_dump' => false,
>   
>   'destination' => [
>   ```
>    /*
>   ```
>   
>   
>   
>   * The filename prefix used for the backup zip file.
>     */
>     'filename_prefix' => '',
>     /*
>     
>     * The disk names on which the backups will be stored.
>       */
>       'disks' => [
>       'google',
>       'local',
>       ],
>       ],
>   
>   /*
>   
>   * The directory where the temporary files will be stored.
>     */
>     'temporary_directory' => storage_path('app/backup-temp'),
>     ],
> 
> /*
> 
> * You can get notified when specific events occur. Out of the box you can use 'mail' and 'slack'.
> * For Slack you need to install guzzlehttp/guzzle.
> * You can also use your own notification classes, just make sure the class is named after one of
> * the `Spatie\Backup\Events` classes.
>   */
>   'notifications' => [
>   'notifications' => [
>   \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class => ['mail'],
>   \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail'],
>   \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class => ['mail'],
>   \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class => ['mail'],
>   \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class => ['mail'],
>   \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class => ['mail'],
>   ],
>   /*
>   
>   * Here you can specify the notifiable to which the notifications should be sent. The default
>   * notifiable will use the variables specified in this config file.
>     */
>     'notifiable' => \Spatie\Backup\Notifications\Notifiable::class,
>   
>   'mail' => [
>   'to' => '[info@clickerstudio.in](mailto:info@clickerstudio.in)',
>   ],
>   'slack' => [
>   'webhook_url' => '',
>   ```
>    /*
>     * If this is set to null the default channel of the webhook will be used.
>     */
>    'channel' => null,
>   
>    'username' => null,
>   
>    'icon' => null,
>   ```
>   
>   
>   ],
>   ],
> 
> /*
> 
> * Here you can specify which backups should be monitored.
> * If a backup does not meet the specified requirements the
> * UnHealthyBackupWasFound event will be fired.
>   */
>   'monitorBackups' => [
>   [
>   'name' => config('app.name'),
>   'disks' => ['local'],
>   'newestBackupsShouldNotBeOlderThanDays' => 1,
>   'storageUsedMayNotBeHigherThanMegabytes' => 5000,
>   ],
>   /*
>   [
>   'name' => 'name of the second app',
>   'disks' => ['local', 's3'],
>   'newestBackupsShouldNotBeOlderThanDays' => 1,
>   'storageUsedMayNotBeHigherThanMegabytes' => 5000,
>   ],
>   */
>   ],
> 
> 'cleanup' => [
> /*
> 
> * The strategy that will be used to cleanup old backups. The default strategy
> * will keep all backups for a certain amount of days. After that period only
> * a daily backup will be kept. After that period only weekly backups will
> * be kept and so on.
> * No matter how you configure it the default strategy will never
> * delete the newest backup.
>   */
>   'strategy' => \Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy::class,
>   'defaultStrategy' => [
>   ```
>    /*
>   ```
>   
>   
>   
>   * The number of days for which backups must be kept.
>     */
>     'keepAllBackupsForDays' => 7,
>     /*
>     
>     * The number of days for which daily backups must be kept.
>       */
>       'keepDailyBackupsForDays' => 16,
>     
>     /*
>     
>     * The number of weeks for which one weekly backup must be kept.
>       */
>       'keepWeeklyBackupsForWeeks' => 8,
>     
>     /*
>     
>     * The number of months for which one monthly backup must be kept.
>       */
>       'keepMonthlyBackupsForMonths' => 4,
>     
>     /*
>     
>     * The number of years for which one yearly backup must be kept.
>       */
>       'keepYearlyBackupsForYears' => 2,
>     
>     /*
>     
>     * After cleaning up the backups remove the oldest backup until
>     * this amount of megabytes has been reached.
>       */
>       'deleteOldestBackupsWhenUsingMoreMegabytesThan' => 5000,
>       ],
>       ],
>       ];
>       `
>       provider
> 
> `<?php
> 
> namespace App\Providers;
> 
> use Illuminate\Support\ServiceProvider;
> 
> class GoogleDriveServiceProvider extends ServiceProvider
> {
> /**
> 
> * Bootstrap services.
> * @return void
>   */
>   public function boot()
>   {
>   \Storage::extend('google', function ($app, $config) {
>   $client = new \Google_Client();
>   $client->setClientId($config['clientId']);
>   $client->setClientSecret($config['clientSecret']);
>   $client->refreshToken($config['refreshToken']);
>   $service = new \Google_Service_Drive($client);
>   $adapter = new \Hypweb\Flysystem\GoogleDrive\GoogleDriveAdapter($service, $config['folderId']);
>   return new \League\Flysystem\Filesystem($adapter);
>   });
>   }
> 
> /**
> 
> * Register services.
> * @return void
>   */
>   public function register()
>   {
>   //
>   }
>   }
>   `
> 
> where i am wrong
> 
> help
> 
> see this [ivanvermeyen/laravel-google-drive-demo#44 (comment)](https://github.com/ivanvermeyen/laravel-google-drive-demo/issues/44#issuecomment-433702298)

You can fix this issue by sending the backup folder name blank'' in the 'backup'=>[] array in backup.php file, as google drive doesn't recognize the folders by their names.  Alternatively, you can use google api to get the name of the folder.  
So you will replace 
 'name' => env('APP_NAME', 'laravel-backup'),
by 
 'name' => ''
<?php

return [

    'backup' => [

        /*
         * The name of this application. You can use this name to monitor
         * the backups.
         */

        'name' =>'',

**Comment by ifarooq** [comment]
You can fix this issue by sending the backup folder name blank in the 'backup'=>[] array in backup.php file, as google drive doesn't recognize the folders by their names. Alternatively, you can use google drive api to get the name of the folder.
So you will replace
'name' => env('APP_NAME', 'laravel-backup'),
by
'name' => ''

The backup.php file will look something like this. 

`<?php
return [

    'backup' => [

        /*
         * The name of this application. You can use this name to monitor
         * the backups.
         */
        'name' => '',

        'source' => [`

**Comment by Hamzaqureshi401** [comment]
@ifarooq thanx genious great work it is i also have same and worked for me
