### ISSUE TITLE
Let's create v6 of laravel-backup: welcoming all feature requests and PRs (breaking changes allowed)

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-backup#790]
I plan on creating a new major version of the package that contains the breaking changes from this PR:  #789 

If you have a feature request or want to submit a PR that contains breaking changes: now's the time to do it! I can't promise all feature requests will make the cut or that all PRs will get merged, but I'm looking forward to your ideas around this!

**Comment by freekmurze** [comment]
I could investigate on how to add some sort of encryption to this backup package. Seems like it's working perfectly here: https://phpbu.de/manual/current/en/crypt.html

**Comment by michellaurent** [comment]
Encryption before uploading to remote filesystems would be nice in the next release.
https://stefanzweifel.io/posts/how-to-encrypt-file-uploads-with-laravel

**Comment by bbashy** [comment]
1. Maybe support for Restic (restic/restic).
2. Some sort of very simple interface to see backups. As well as creating a new one via a button

**Comment by freekmurze** [comment]
@michellaurent thanks for the link!
@bbashy 
1. what do you mean by support? To me it seems like a separate backup package
2. I don't want to maintain any UI I don't use myself, so that should go in it's own package. I've already created [some screens for Nova](https://github.com/spatie/nova-backup-tool).

**Comment by lofye** [comment]
It'd be great if you could configure the backup directory, or if it defaulted to storage/backups/{app.name} instead of storage/{app.name}

**Comment by freekmurze** [comment]
@lofye can't you already do this by changing the path of your backups disk in the `filesystems.php` config file?

**Comment by freekmurze** [comment]
> I could investigate on how to add some sort of encryption

While it's totally doable to adds phpbu's encryption features (https://phpbu.de/manual/current/en/crypt.html) I currently have no need for this myself. This feature can be added in a non-breaking way. If somebody wants this and has the time to code it up, feel free to send a PR.

**Comment by paras-malhotra** [comment]
I think adding support for Redis backup (as a .rdb file) would be really helpful. Some use cases:

1. Migration of redis server to another while wanting to keep session/queue data intact (if using redis driver)
2. Say you're using Redis for leaderboards/counting (such as page views for popular pages) and need a daily backup
3. Redis pub/sub

**Comment by freekmurze** [comment]
Closing this for now, thanks for the suggestions.
