### ISSUE TITLE
How to use --set-gtid-purged param

### ISSUE THREAD

**Issue by jbardnz** [spatie/laravel-backup#791]
Hi there,

I can see in #625 that the --set-gtid-purged param was added to the underlying spatie/db-dumper package. However I can't see this exposed anywhere in this package?

Is their anyway to set that param when running a backup?

**Comment by freekmurze** [comment]
You can set extra options using the `add_extra_option` key in the database config file.

Here's an example from our docs: https://docs.spatie.be/laravel-backup/v5/installation-and-setup#dumping-the-database
