### ISSUE TITLE
Domain based hostname (like RDS) not working when port appended

### ISSUE THREAD

**Issue by jordanramstad** [spatie/laravel-backup#792]
```
The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2005: Unknown MySQL server host 'rds-instance-example.rds.amazonaws.com:3306' (0) when trying to connect
```

I wrote alot on this issue, but like anything programming related, you solve it as soon as you start to complain about it lol

But this still might trip some people up. Database connections in laravel work with the port appended to the host just fine, but this is not the same for the backups. I am using an RDS instance and had the port appended as it is given like that after setting it up.

Likely solutions for this could be when building the command to just filter out the port, or pull it out and pass it as a second parameter in the command if anything is done in this package to solve it.

But for anyone tripped up by this, if the port is 3306, just remove it from the host, the laravel connection will still work fine. If it is another port I think you can add port to the connection settings seperatly.

Feel free to close this, just wanted to pass a fix for a problem others might run into, but does not really need a fix in the package itself.

**Comment by freekmurze** [comment]
Thanks for the info!
