### ISSUE TITLE
Schedule Backup Not working

### ISSUE THREAD

**Issue by justanothercoder09** [spatie/laravel-backup#796]
My project cannot automatically schedule so what happens is that I had to manually run "backup:run or clean" If you have any solution for this can you please send me specifically Thanks!

**Comment by freekmurze** [comment]
The default way of running it with the scheduler seems the best way: https://laravel.com/docs/master/scheduling#introduction

If you cannot run cron, move to another host or use something like crondog: https://crondog.io/
