### ISSUE TITLE
 The dump process failed with exitcode 2

### ISSUE THREAD

**Issue by nam-co** [spatie/laravel-backup#80]
Hi freekmurze thanks for the upgrade, it works perfect now, but… I need your help once again

Im trying to run a shell command from a controller, I tried both Artisan::call('backup:run’); AND $output = shell_exec('php7.0-sp artisan backup:run');

but I get the same error:
Starting backup...
Dumping database appDB...
Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins.
Backup completed!

Hope you can help me regards
Michael

**Comment by freekmurze** [comment]
Could you verify that your php process has the right permissions to call binaries such as `mysqldump`?

**Comment by nam-co** [comment]
Hi, the command php7.0 artisan backup:run works perfectly, the problem is using the call from the controller

**Comment by adzymaniac** [comment]
Hi.
Same error with Postgres database.

Thanks

**Comment by freekmurze** [comment]
@nam-co Please check with your hosting provider if PHP has the right permissions to execute `mysqldump` when called from a web request. You could try to put the artisan call in a queued job so it'll get called from the command line.

@adzymaniac currently only MySQL databases are supported
