### ISSUE TITLE
Notification not working: Undefined property: Spatie\Backup\Notifications\Notifiable::$id

### ISSUE THREAD

**Issue by jesephan** [spatie/laravel-backup#802]
Hello,

I'm using this package to backup our database going to the google drive. Everything works fine except the email notification after successful backup. Im thinking this might be because i have specified different namespace for our user model? if so, how do fix this one? Our user model is located at App/Models instead of the usual App/. I also tried passing User instance to config('notifications.mail.to) but not working. Here is the error message after trying to run the backup in the terminal...

`Starting backup...
Dumping database wedbooker...
Determining files to backup...
Zipping 1 files...
Created zip containing 1 files. Size is 19.68 KB
Copying zip to disk named google...
Successfully copied zip to disk named google.
Copying zip failed because: Undefined property: Spatie\Backup\Notifications\Notifiable::$id.
Backup failed because Undefined property: Spatie\Backup\Notifications\Notifiable::$id.
#0 /Users/jesusephan/Sites/wedbooker/app/Listeners/ClearCachedNotifications.php(20): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined prope...', '/Users/jesuseph...', 20, Array)
#1 [internal function]: App\Listeners\ClearCachedNotifications->handle(Object(Illuminate\Notifications\Events\NotificationSent))` 

Here is a snapshot of my backup config

`'notifications' => [

        'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class         => ['mail'],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class        => ['mail'],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class     => ['mail'],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class   => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class    => ['mail'],
        ],

        /*
         * Here you can specify the notifiable to which the notifications should be sent. The default
         * notifiable will use the variables specified in this config file.
         */
        'notifiable' => \Spatie\Backup\Notifications\Notifiable::class,

        'mail' => [
            'to' => 'hello@test.com',
        ],`

**Comment by jmadlena** [comment]
@jesephan Did you ever find a solution to this issue? I'm dealing with a similar problem.

**Comment by jessicaplant** [comment]
Same here - did you get anywhere @jmadlena?

**Comment by jmadlena** [comment]
@jessicaplant Unfortunately I didn't. I only get this issue sometimes, but most of the time it works (which seems odd). I found that running it a second time usually works, so I punted on the issue since it was taking up too much of my time. Sorry I couldn't be of more help.
