### ISSUE TITLE
Unable to add 'include' paths using config()

### ISSUE THREAD

**Issue by butcherman** [spatie/laravel-backup#804]
My application has the ability for users to change the root directory of the "local" disk in the .env file.  When they do this, the backup command understandingly does not backup these files.  I have tried to make this possible by modifying the 'include' section of the backup.php file, but the only valid entries seem to be either "base_path('...')" or the absolute path.

In the files section of the config file I have tried the following:
```
'include' => [
     base_path('.env'),                                 //  Only copy the .env file - excluded code files for testing
     config('filesystem.disks.local.root'),     //  I have also tried env('ROOT_FOLDER')
],
```
In my filesystems config file I have the following:
```
'default' => env('FILESYSTEM_DRIVER', 'local'),
'disks' => [
     'local' => [
     'driver' => 'local',
     'root' => env('ROOT_FOLDER', storage_path('app')),
],
```
When the ROOT_FOLDER is defined in the .env file, the backups are loaded to the correct location (with a default backup.php file), but when trying to backup with the config assigned, I get "Backup failed becasue:  The "" directory does not exist.."

**Comment by freekmurze** [comment]
The tests indicated that each directory that is put in `include`  gets backed up.  If this is not working for you, please submit a failing test for us to look at.

Maybe your issue is related to config key caching. Try running `php artisan cache:clear`.

**Comment by butcherman** [comment]
Here is an example log file along with the config file I am trying to pull from, and the backup.php file.  

Note:  I changed both of the php file extensions to .txt so they would upload.

You can view the entire test on https://github.com/butcherman/backup-test

[backup-test.txt](https://github.com/spatie/laravel-backup/files/2666103/backup-test.txt)
[filesystems.txt](https://github.com/spatie/laravel-backup/files/2666106/filesystems.txt)
[backup.txt](https://github.com/spatie/laravel-backup/files/2666107/backup.txt)
