### ISSUE TITLE
Cannot install with Laravel 5.7.16

### ISSUE THREAD

**Issue by neamtua** [spatie/laravel-backup#805]
Hello,

I've tried installing the latest version but it's not compatible with Laravel 5.7.16.

Here's a full dump of composer:

`
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install spatie/laravel-backup 3.10.1
    - Conclusion: don't install spatie/laravel-backup 3.10.0
    - Conclusion: don't install spatie/laravel-backup 3.9.0
    - Conclusion: don't install spatie/laravel-backup 3.8.2
    - Conclusion: don't install spatie/laravel-backup 3.8.1
    - Conclusion: don't install spatie/laravel-backup 3.8.0
    - Conclusion: don't install spatie/laravel-backup 3.7.2
    - Conclusion: don't install spatie/laravel-backup 3.7.1
    - Conclusion: don't install spatie/laravel-backup 3.7.0
    - Conclusion: don't install spatie/laravel-backup 3.6.1
    - Conclusion: don't install spatie/laravel-backup 3.6.0
    - Conclusion: don't install spatie/laravel-backup 3.5.0
    - Conclusion: don't install spatie/laravel-backup 3.4.4
    - Conclusion: don't install spatie/laravel-backup 3.4.3
    - Conclusion: don't install spatie/laravel-backup 3.4.2
    - Conclusion: don't install spatie/laravel-backup 3.4.1
    - Conclusion: don't install spatie/laravel-backup 3.4.0
    - Conclusion: don't install spatie/laravel-backup 3.3.3
    - Conclusion: don't install spatie/laravel-backup 3.3.2
    - Conclusion: don't install spatie/laravel-backup 3.3.1
    - Conclusion: don't install spatie/laravel-backup 3.3.0
    - Conclusion: don't install spatie/laravel-backup 3.2.2
    - Conclusion: don't install spatie/laravel-backup 3.2.1
    - Conclusion: don't install spatie/laravel-backup 3.2.0
    - Conclusion: don't install spatie/laravel-backup 3.1.4
    - Conclusion: don't install spatie/laravel-backup 3.1.3
    - Conclusion: don't install spatie/laravel-backup 3.1.2
    - Conclusion: don't install spatie/laravel-backup 3.1.1
    - Conclusion: don't install spatie/laravel-backup 3.1.0
    - Conclusion: don't install spatie/laravel-backup 3.0.5
    - Conclusion: don't install spatie/laravel-backup 3.0.4
    - Conclusion: don't install spatie/laravel-backup 3.0.3
    - Conclusion: don't install spatie/laravel-backup 3.0.2
    - Conclusion: don't install spatie/laravel-backup 3.0.1
    - Conclusion: don't install spatie/laravel-backup 3.0.0
    - Conclusion: remove laravel/framework v5.7.16
    - Installation request for symfony/finder (locked at v4.2.1) -> satisfiable by symfony/finder[v4.2.1].
    - Conclusion: don't install laravel/framework v5.7.16
    - spatie/laravel-backup 3.10.2 requires illuminate/filesystem ~5.1.20|~5.2.0|~5.3.0 -> satisfiable by illuminate/filesystem[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - spatie/laravel-backup 3.10.3 requires illuminate/filesystem ~5.1.20|~5.2.0|~5.3.0 -> satisfiable by illuminate/filesystem[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - spatie/laravel-backup 3.11.0 requires illuminate/filesystem ~5.1.20|~5.2.0|~5.3.0|~5.4.0 -> satisfiable by illuminate/filesystem[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup v3.x-dev requires illuminate/filesystem ~5.1.20|~5.2.0|~5.3.0|~5.4.0 -> satisfiable by illuminate/filesystem[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/filesystem 5.4.x-dev|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.4.0|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.4.13|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.4.17|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.4.19|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.4.27|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.4.36|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.4.9|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem 5.1.x-dev|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem 5.2.x-dev|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem 5.3.x-dev|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.1.20|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.1.22|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.1.25|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.1.28|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.1.30|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.1.31|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.1.41|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.0|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.19|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.21|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.24|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.25|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.26|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.27|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.28|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.31|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.32|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.37|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.43|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.45|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.6|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.2.7|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.3.0|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.3.16|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.3.23|don't install laravel/framework v5.7.16
    - don't install illuminate/filesystem v5.3.4|don't install laravel/framework v5.7.16
    - Installation request for laravel/framework (locked at v5.7.16, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.16].
    - Installation request for spatie/laravel-backup ^3.0.0 -> satisfiable by spatie/laravel-backup[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.10.0, 3.10.1, 3.10.2, 3.10.3, 3.11.0, 3.2.0, 3.2.1, 3.2.2, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.5.0, 3.6.0, 3.6.1, 3.7.0, 3.7.1, 3.7.2, 3.8.0, 3.8.1, 3.8.2, 3.9.0, v3.x-dev].
`

**Comment by freekmurze** [comment]
Version 3 is not compatible indeed. Use version 5.
