### ISSUE TITLE
Large-ish backup (150MB) fails cloud uploads

### ISSUE THREAD

**Issue by jake-harris** [spatie/laravel-backup#806]
Hi there,

I'm having issues with cloud uploads timing out. The backup runs smoothly when using the `--only-db` flag-- resulting in a smaller `.zip` file-- so I am confident the connections work. The issue is when running the "full" backup, the upload to cloud always times out. I've tried using both AWS S3 and Digital Ocean Spaces. 

```
Copying 2018-12-13-192921.zip (size: 149.75 MB) to disk named do_backups...
Copying .zip file failed because: An exception occurred while uploading parts to a multipart upload. The following parts had errors:
- Part 1: Error executing "UploadPart" on "https://some-fake-bucket.sfo2.digitaloceanspaces.com/https---portal.fake-site.com/2018-12-13-192921.zip?partNumber=1&uploadId=2~MgFlqd2hCNnDrMAk8igaSkv2EpfwivG"; AWS HTTP error: Server error: `PUT https://some-fake-bucket.sfo2.digitaloceanspaces.com/https---portal.fake-site.com/2018-12-13-192921.zip?partNumber=1&uploadId=2~MgFlqd2hCNnDrMAk8igaSkv2EpfwivG` resulted in a `500 Internal Server Error` response:
<?xml version="1.0" encoding="UTF-8"?><Code>UnknownError</Code><BucketName>some-fake-bucket</BucketName><RequestId (truncated...)
 UnknownError (server):  - <?xml version="1.0" encoding="UTF-8"?><Code>UnknownError</Code><BucketName>some-fake-bucket</BucketName><RequestId>tx00000000000000a7bb815-005c12b31b-795c7-sfo2a</RequestId><HostId>795c7-sfo2a-sfo</HostId>
```

There are many more "Part X" errors following.

I'm able to easily transfer the complete backup files using the `awscli` in just a few seconds.

Only other potential issue I can think of is that the `storage/` directory is symlinked (to support rolling deployments).

Any guidance or help is appreciated! Thanks for all the amazing work you guys do!

**Comment by gbalduzzi** [comment]
I have the same problem. Full backup (around 145MB) fails, using `--only-db` or `--only-files` it completes successfully. The backup routine has not changed in the last year, so I assume the only difference is the actual backup size.

I checked my whole `php.ini` but I could not find a suitable parameter that must be increased. Any ideas?

```
Part 17: Error executing "UploadPart" on "https://s3.eu-west-1.amazonaws.com/bucket.name.bucket/Backups/2019-04-01-09-47-33.zip?partNumber=17&uploadId=longUploadId..."; AWS HTTP error: cURL error 55: SSL_write() returned SYSCALL, errno = 104 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)  (server): 100 Continue -
```
