### ISSUE TITLE
Error on php artisan backup:run --only-db

### ISSUE THREAD

**Issue by LeandroEpifani** [spatie/laravel-backup#807]
Hi,
I'm trying to use the spatie package for the first time.
It work fine when i use the comand 'php artisan backup:run --only-files', but when i try to make the backup for the 2 database that i have then i receive this error:
**_Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2059: Authentication plugin 'caching_sha2_password' cannot be loaded_**
Then i have tryed to use this comand in mysql
ALTER USER root@localhost IDENTIFIED WITH mysql_native_password BY 'password'
but then laravel could't have access on the database.
I don't know what i need to do. Please help.

**Comment by freekmurze** [comment]
Are you able to perform a backup by using `mysqldump` directly?

**Comment by LeandroEpifani** [comment]
on mysql workbench yes.. and it work fine when i change the password type to mysql_native but if i do that, eloquent can't access to the database

**Comment by LeandroEpifani** [comment]
thanks a lot for your help
