### ISSUE TITLE
Fatal Memory Error

### ISSUE THREAD

**Issue by kcristella** [spatie/laravel-backup#81]
The backup process is failing after performing a composer update today (3/9/2016). The same configuration was working fine yesterday (3/8/2016) before composer update. I am backing up many files as I have a standalone Laravel app installed on my server for laravel-backup that is backing up four domains (three of which are Laravel apps). 

```
Starting backup...
Dumping database db1...
Dumping database db2...
Dumping database db3...
Dumping database db4...
Determining files to backup...
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in /path/to/zbackup/vendor/spatie/laravel-backup/src/Tasks/Backup/FileSelection.php on line 133
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in /path/to/zbackup/vendor/symfony/debug/Exception/FatalErrorException.php on line 1
```

**Comment by freekmurze** [comment]
Woa, there's a lot of memory being used there. 

Do you know which specific version you were using yesterday? Does that version work if you install that specific version again?

Do you backup significantly more files than yesterday? Or bigger files?

Do you have any more info that'll allow me to recreate your issue?

**Comment by kcristella** [comment]
Thanks for the quick reply. It works in 3.0.4 but fails in 3.0.5 (I just tested by reverting back to 3.0.4). No significant file changes from yesterday or very large files. 

```
 - Removing spatie/laravel-backup (3.0.5)
 - Installing spatie/laravel-backup (3.0.4)
```

**Comment by kcristella** [comment]
Two more tidbits:

1. May be related to PHP 7 (can't reproduce with PHP 5.6 yet but still testing)
2. Backup consists of 7921 files

**Comment by freekmurze** [comment]
One more question before I dive deep into this: what's your Laravel version?

**Comment by kcristella** [comment]
Laravel Framework version 5.2.22

**Comment by kcristella** [comment]
Total backup size for successful backup of 7921 files = 179.7 MB

**Comment by freekmurze** [comment]
Could you try updating to the latests version?

Could you look inside the directory you want to backup if there are any hidden directories (starting with a dot) that you don't want to back up?

**Comment by kcristella** [comment]
Seems to be working well using the newest version + PHP 7. Will continue to monitor and update the issue if anything comes up. Thanks.

**Comment by freekmurze** [comment]
Cool, reopen this issue if anything new comes up.
