### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by Rhincodon** [spatie/laravel-backup#82]
What about bringing back PostgreSQL from version 2? We need to ask @Jamesking56 for pull request?

**Comment by freekmurze** [comment]
@Jamesking56 showed interest in adding PostreSQL to the [db-dumper](https://github.com/spatie/db-dumper) package, see [this issue](https://github.com/spatie/db-dumper/issues/2).

Showing interest is not a promise, so don't blame him if he takes a long time or eventually does not do it. 

In any case, I'm open for PR's that adds support for other types of db's to [db-dumper](https://github.com/spatie/db-dumper). If you have more questions about this, please open up an issue at the db-dumper repo.

**Comment by Jamesking56** [comment]
@Rhincodon I will add PostgreSQL support to db-dumper this weekend as I need it myself for my new SaaS project. I may even extend that later to add SQLite and MSSQL support but I'll see how I get on.

**Comment by freekmurze** [comment]
@Jamesking56 that's great to hear! Make sure you include tests in your PR to db-dumper.

In laravel-backup, there's only {a driver type check](https://github.com/spatie/laravel-backup/search?utf8=%E2%9C%93&q=mysql) that needs to be adjusted.
