### ISSUE TITLE
Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified.

### ISSUE THREAD

**Issue by AndreFabris** [spatie/laravel-backup#834]
Hello I am using version 3 as I have Laravel 5.2

There is an error on Windows Xampp where this bit of code
protected function addDatabaseDumpsToZip(Zip $zip)
    {
        $this->dbDumpers->each(function (DbDumper $dbDumper) use ($zip) {
            consoleOutput()->info("Dumping database {$dbDumper->getDbName()}...");

            $fileName = $dbDumper->getDbName().'.sql';
            $temporaryFile = $this->temporaryDirectory->getPath($fileName);
            $dbDumper->dumpToFile($temporaryFile);

            $zip->add($temporaryFile, $fileName);
        });
   
Incorrectly resolves path, temporary directory etc:
 $temporaryfile = mpp\htdocs\back\myadmin\storage\laravel-backups/temp//back_myadmin.sql"
    $this->temporaryDirectory = "C:
mpp\htdocs\back\myadmin\storage\laravel-backups/temp/"

As you can see for some reason few characters are missing, it should be C:\xampp...... 

Any ideas?

**Comment by vonsogt** [comment]
Need solution for this

**Comment by RobbyAJM** [comment]
Looking for solution...

**Comment by vonsogt** [comment]
> 
> 
> Looking for solution...

I found the solution, just put your project to "xampp/htdocs/folder-name" and the problem will be fixed

**Comment by RobbyAJM** [comment]
> > Looking for solution...
> 
> I found the solution, just put your project to "xampp/htdocs/folder-name" and the problem will be fixed

Thanks for respond but my folder is already inside the xampp/htdocs folder (I only put my folder project inside the xampp directory, but I didn't use XAMPP, I use WAMPP instead), but when I type "php artisan backup:run --only-db" it shows:
> Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified.

But when I tried to backup manually through mysqldump command & inside MySql folder bin, and type "mysqldump --user=root --password=secret school_database > backup.sql" it's worked as well

**Comment by vonsogt** [comment]
> 
> 
> > > Looking for solution...
> > 
> > 
> > I found the solution, just put your project to "xampp/htdocs/folder-name" and the problem will be fixed
> 
> Thanks for respond but my folder is already inside the xampp/htdocs folder (I only put my folder project inside the xampp directory, but I didn't use XAMPP, I use WAMPP instead), but when I type "php artisan backup:run --only-db" it shows:
> 
> > Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified.
> 
> But when I tried to backup manually through mysqldump command & inside MySql folder bin, and type "mysqldump --user=root --password=secret school_database > backup.sql" it's worked as well

if you are using xampp, that should be in there "xampp/htdocs/folder-name", but in WAMPP maybe that you should put at "wampp/www/folder-name" and try to open without _php artisan serve_ just open from browser like "localhost/folder-name"

**Comment by RobbyAJM** [comment]
> > > > Looking for solution...
> > > 
> > > 
> > > I found the solution, just put your project to "xampp/htdocs/folder-name" and the problem will be fixed
> > 
> > 
> > Thanks for respond but my folder is already inside the xampp/htdocs folder (I only put my folder project inside the xampp directory, but I didn't use XAMPP, I use WAMPP instead), but when I type "php artisan backup:run --only-db" it shows:
> > > Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified.
> > 
> > 
> > But when I tried to backup manually through mysqldump command & inside MySql folder bin, and type "mysqldump --user=root --password=secret school_database > backup.sql" it's worked as well
> 
> if you are using xampp, that should be in there "xampp/htdocs/folder-name", but in WAMPP maybe that you should put at "wampp/www/folder-name" and try to open without _php artisan serve_ just open from browser like "localhost/folder-name"

I'm using WAMPP virtual host which let me able to place my project folder anywhere, after configuring the virtual host, I open the browser and use my vhost address as main URL, like "schoolproject.test"

**Comment by maggsweb** [comment]
If you are using Windows with WAMP, you need this setting in your .env file
`DB_MYSQL_BIN_PATH`

Also, check that the path exists..
DB_MYSQL_BIN_PATH=c:/wamp64/bin/mariadb/mariadb10.4.13/bin
