### ISSUE TITLE
APP_NAME not defined in .env results in an error

### ISSUE THREAD

**Issue by mvdnbrk** [spatie/laravel-backup#839]
Prior to v6 the default `backup.name` config key was set to `config('app.name')`.
This changed to `'name' => env('APP_NAME')`

When `APP_NAME` is not set in the env file the backup.name value will be null.
`php artsian run:backup` will throw an error:

```
TypeError: Argument 2 passed to Spatie\Backup\BackupDestination\BackupDestination::create() must be of the type string, null given, called in ~/laravel-backup/src/BackupDestination/BackupDestinationFactory.php on line 15
```

This did not happen before because of the fact that `config('app.name')` will always return a default value of `Laravel` when APP_NAME is not set.

**Comment by fitztrev** [comment]
I also experienced this just now after upgrading.

**Comment by freekmurze** [comment]
`APP_NAME` seems to be set in recent version of Laravel: https://github.com/laravel/laravel/blob/d1db3cd089d6e9f81a4c8a65d401939f85cbbd5c/.env.example#L1

**Comment by mvdnbrk** [comment]
@freekmuze that is true. 

Doesn't change the fact that if someone does not have the `APP_NAME` set an error will be thrown.

Wouldn't it be better to change the default config for this package from:

```
'backup' => [
     'name' => env('APP_NAME'),
```

to 

```
'backup' => [
    'name' => env('APP_NAME', 'Backup'),
```

**Comment by freekmurze** [comment]
Good idea, thanks, I'll do that!

**Comment by mvdnbrk** [comment]
That was fast @freekmuze ;-)

Please change it on line #148 as well to keep it consistent.
See my [PR](#840)

**Comment by freekmurze** [comment]
Thanks!
