### ISSUE TITLE
Not able to backup throwing error

### ISSUE THREAD

**Issue by nitish1986** [spatie/laravel-backup#841]
Hi,

I'm using your package to backup my database, I configured `backup.php` as:

	return [

		'backup' => [

			/*
			 * The name of this application. You can use this name to monitor
			 * the backups.
			 */
			'name' => env('APP_NAME'),

			'source' => [

				'files' => [

					/*
					 * The list of directories and files that will be included in the backup.
					 */
					'include' => [
	//                    base_path(),
					],

					/*
					 * These directories and files will be excluded from the backup.
					 *
					 * Directories used by the backup process will automatically be excluded.
					 */
					'exclude' => [
						base_path('vendor'),
						base_path('node_modules'),
					],

					/*
					 * Determines if symlinks should be followed.
					 */
					'follow_links' => false,
				],

				/*
				 * The names of the connections to the databases that should be backed up
				 * MySQL, PostgreSQL, SQLite and Mongo databases are supported.
				 *
				 * The content of the database dump may be customized for each connection
				 * by adding a 'dump' key to the connection settings in config/database.php.
				 * E.g.
				 * 'mysql' => [
				 *       ...
				 *      'dump' => [
				 *           'excludeTables' => [
				 *                'table_to_exclude_from_backup',
				 *                'another_table_to_exclude'
				 *            ]
				 *       ]
				 * ],
				 *
				 * For a complete list of available customization options, see https://github.com/spatie/db-dumper
				 */
				'databases' => [
					'mysql' => [
						'dump' => [
							'excludeTables' => [
								'telescope_entries',
								'telescope_entries_tag',
								'telescope_monitoring'
							]
						]
					],
				],
			],

			/*
			 * The database dump can be compressed to decrease diskspace usage.
			 *
			 * Out of the box Laravel-backup supplies
			 * Spatie\DbDumper\Compressors\GzipCompressor::class.
			 *
			 * You can also create custom compressor. More info on that here:
			 * https://github.com/spatie/db-dumper#using-compression
			 *
			 * If you do not want any compressor at all, set it to null.
			 */
			'database_dump_compressor' => null,

			'destination' => [

				/*
				 * The filename prefix used for the backup zip file.
				 */
				'filename_prefix' => 'biltrax_database',

				/*
				 * The disk names on which the backups will be stored.
				 */
				'disks' => [
					's3',
				],
			],

			/*
			 * The directory where the temporary files will be stored.
			 */
			'temporary_directory' => storage_path('app/backup-temp'),
		],

		/*
		 * You can get notified when specific events occur. Out of the box you can use 'mail' and 'slack'.
		 * For Slack you need to install guzzlehttp/guzzle.
		 *
		 * You can also use your own notification classes, just make sure the class is named after one of
		 * the `Spatie\Backup\Events` classes.
		 */
		'notifications' => [

			'notifications' => [
				\Spatie\Backup\Notifications\Notifications\BackupHasFailed::class => ['mail'],
				\Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail'],
				\Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class => ['mail'],
				\Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class => ['mail'],
				\Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class => ['mail'],
				\Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class => ['mail'],
			],

			/*
			 * Here you can specify the notifiable to which the notifications should be sent. The default
			 * notifiable will use the variables specified in this config file.
			 */
			'notifiable' => \Spatie\Backup\Notifications\Notifiable::class,

			'mail' => [
				'to' => 'nitishkumar@noeticitservices.com',
			],

			'slack' => [
				'webhook_url' => '',

				/*
				 * If this is set to null the default channel of the webhook will be used.
				 */
				'channel' => null,

				'username' => null,

				'icon' => null,

			],
		],

		/*
		 * Here you can specify which backups should be monitored.
		 * If a backup does not meet the specified requirements the
		 * UnHealthyBackupWasFound event will be fired.
		 */
		'monitor_backups' => [
			[
				'name' => env('APP_NAME'),
				'disks' => ['s3'],
				'health_checks' => [
					\Spatie\Backup\Tasks\Monitor\HealthChecks\MaximumAgeInDays::class => 1,
					\Spatie\Backup\Tasks\Monitor\HealthChecks\MaximumStorageInMegabytes::class => 5000,
				],
			],

			/*
			[
				'name' => 'name of the second app',
				'disks' => ['local', 's3'],
				'health_checks' => [
					\Spatie\Backup\Tasks\Monitor\HealthChecks\MaximumAgeInDays::class => 1,
					\Spatie\Backup\Tasks\Monitor\HealthChecks\MaximumStorageInMegabytes::class => 5000,
				],
			],
			*/
		],

		'cleanup' => [
			/*
			 * The strategy that will be used to cleanup old backups. The default strategy
			 * will keep all backups for a certain amount of days. After that period only
			 * a daily backup will be kept. After that period only weekly backups will
			 * be kept and so on.
			 *
			 * No matter how you configure it the default strategy will never
			 * delete the newest backup.
			 */
			'strategy' => \Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy::class,

			'default_strategy' => [

				/*
				 * The number of days for which backups must be kept.
				 */
				'keep_all_backups_for_days' => 7,

				/*
				 * The number of days for which daily backups must be kept.
				 */
				'keep_daily_backups_for_days' => 16,

				/*
				 * The number of weeks for which one weekly backup must be kept.
				 */
				'keep_weekly_backups_for_weeks' => 8,

				/*
				 * The number of months for which one monthly backup must be kept.
				 */
				'keep_monthly_backups_for_months' => 4,

				/*
				 * The number of years for which one yearly backup must be kept.
				 */
				'keep_yearly_backups_for_years' => 2,

				/*
				 * After cleaning up the backups remove the oldest backup until
				 * this amount of megabytes has been reached.
				 */
				'delete_oldest_backups_when_using_more_megabytes_than' => 5000,
			],
		],
	];

But it throws error:

	Starting backup...

	   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Spatie\Backup\Tasks\Backup\BackupJobFactory::Spatie\Backup\Tasks\Backup\{closure}() must be of the type string, array given, called in /var/www/html/conxn/vendor/laravel/framework/src/Illuminate/Support/Collection.php on line 1096

	  at /var/www/html/conxn/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php:27
		23|     }
		24|
		25|     protected static function createDbDumpers(array $dbConnectionNames): Collection
		26|     {
	  > 27|         return collect($dbConnectionNames)->mapWithKeys(function (string $dbConnectionName) {
		28|             return [$dbConnectionName=>DbDumperFactory::createFromConnection($dbConnectionName)];
		29|         });
		30|     }
		31| }

	  Exception trace:

	  1   Spatie\Backup\Tasks\Backup\BackupJobFactory::Spatie\Backup\Tasks\Backup\{closure}([], "mysql")
		  /var/www/html/conxn/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1096

	  2   Illuminate\Support\Collection::mapWithKeys(Object(Closure))
		  /var/www/html/conxn/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php:29

	  Please use the argument -v to see more details.

Help me out with this. Thanks.

**Comment by nitish1986** [comment]
If I keep my database config in `backup.php` as

	'databases' => [
		'mysql'
	],

I get disk s3 error:

	Starting backup...

	   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 2 passed to Spatie\Backup\BackupDestination\BackupDestination::create() must be of the type string, null given, called in /var/www/html/conxn/vendor/spatie/laravel-backup/src/BackupDestination/BackupDestinationFactory.php on line 13

	  at /var/www/html/conxn/vendor/spatie/laravel-backup/src/BackupDestination/BackupDestination.php:60
		56|
		57|         return strtolower($filesystemType);
		58|     }
		59|
	  > 60|     public static function create(string $diskName, string $backupName): self
		61|     {
		62|         try {
		63|             $disk = app(Factory::class)->disk($diskName);
		64|

	  Exception trace:

	  1   Spatie\Backup\BackupDestination\BackupDestination::create("s3")
		  /var/www/html/conxn/vendor/spatie/laravel-backup/src/BackupDestination/BackupDestinationFactory.php:13

	  2   Spatie\Backup\BackupDestination\BackupDestinationFactory::Spatie\Backup\BackupDestination\{closure}("s3")
		  [internal]:0

	  Please use the argument -v to see more details.

**Comment by freekmurze** [comment]
I guess `env('APP_NAME')` is empty for you. Please set that to something, either in the `.env` file or in the `backup` config file.

**Comment by nitish1986** [comment]
Thanks.

**Comment by bagus-repository** [comment]
I have set the the env, but still get this error

```
Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Spatie\Backup\Tasks\Backup\BackupJobFactory::Spatie\Backup\Tasks\Backup\{closure}() must be of the type string, array given, called in C:\xampp\htdocs\hrms\vendor\laravel\framework\src\Illuminate\Support\Collection.php on line 1197

  at C:\xampp\htdocs\hrms\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJobFactory.php:27

**Comment by briancalma** [comment]
@bagus-repository  i solved that issues of yours by clearing up my cache try this:
 `php artisan config:cache`

**Comment by bagus-repository** [comment]
> @bagus-repository  i solved that issues of yours by clearing up my cache try this:
>  `php artisan config:cache`

I am always running php artisan optimize that config cache will be included too, but still same error, local and production

**Comment by timdue** [comment]
Hope this might help someone else experiencing this error: Like the OP I also mistakenly added a 'dump' key with options like 'useSingleTransaction' and 'excludeTables' to 'mysql' in config/backup.php instead of to 'mysql' in config/database.php where it should be.

**Comment by bagus-repository** [comment]
> Hope this might help someone else experiencing this error: Like the OP I also mistakenly added a 'dump' key with options like 'useSingleTransaction' and 'excludeTables' to 'mysql' in config/backup.php instead of to 'mysql' in config/database.php where it should be.

ah i see, i removed the 'dump' key and work, so this is a misunderstanding when reading the comment section from the config

**Comment by fantasyinfo** [comment]
yes it will work if you try to clear the cache after updating this inside config/database.php

connection => [ 
     'mysql' => [
         // existing database details here 

            // Dump configuration
            'dump' => [
                'dump_binary_path' => env('MYSQL_DUMP_PATH', exec('which mysqldump')), // Automatically detect the path
                'use_single_transaction' => true,
                'timeout' => 60 * 5, // Timeout in seconds
            ],
        ],
]
