### ISSUE TITLE
Clean-up only working on one application folder

### ISSUE THREAD

**Issue by slakbal** [spatie/laravel-backup#842]
I have one code base that is the 100% the same for multiple installations but only the Application URL and Name is different and some style-sheets. Thus the application configuration for each application is the same.

All the applications creates a backup to the same dropbox disk, but each backup is created in it's own folder that is based on the 'name' configuration property in the backup config file: 

```
 'name' => config('app.name')
```

Backups work great and each backup is uploaded as expected into a separate folder eg.

- ApplicationA
- ApplicationB
- ApplicationC

Also Monitoring seems to be working also 100% correctly with the configuration: 
```
'monitorBackups' => [
        [
           'name' => config('app.name'),
            'disks' => ['dropbox'],
            'newestBackupsShouldNotBeOlderThanDays' => 1,
            'storageUsedMayNotBeHigherThanMegabytes' => 1024,
        ],
```

However every night a cron job also runs the clean command on each of the applications to clean-up and delete the old backups. It seems that only as per the example names above that only folder: "ApplicationA" is cleaned up when the job for ApplicationA, ApplicationB and ApplicationC is ran.

Is this the expected behaviour or should the clean-up also look into it's own respective folder when the clean-up run?

Thanks for an amazing package!!!

Kind regards

**Comment by freekmurze** [comment]
I'm thinking the the backup for ApplicationB and C should be cleaned up as well. Are you sure the application names in the `monitorBackups` key are correct? You can check by executing `config('backup')` in a tinker session.

**Comment by slakbal** [comment]
Sorry for the late reply. I will check for you quickly tomorrow.
