### ISSUE TITLE
Bad mysqldump config does not fires Exception

### ISSUE THREAD

**Issue by rderimay** [spatie/laravel-backup#843]
In the case that mysqldump can not be found and leads to a 0 bytes backup, (183 bytes when gzipped), the commands returns 0, does not fire an exception and write "Backup completed!" :-)

This is pretty dangerous as everything looks like it went ok.

**Comment by rubenvanassche** [comment]
It looks like a bug in the db dumper package: https://github.com/spatie/db-dumper/issues/89.

**Comment by rubenvanassche** [comment]
Hi @rderimay 

I have fixed the bug in https://github.com/spatie/db-dumper, can you check if this issue is fixed with this bugfix? We haven't tagged a new release of db-dumper yet, so you will have to use dev-master to test.
