### ISSUE TITLE
The dump process failed with exitcode 127

### ISSUE THREAD

**Issue by cloudwales** [spatie/laravel-backup#844]
Hi. I'm getting this error on my production server but not on my testing server. The servers are both identical with the same settings and modules installed but if I run it through `php artisan backup:run` then it works perfectly. Ive read a few of the same issues here and on google but none have helped solve it. 

```
Exception message: The dump process failed with exitcode 127 : Command not found : sh: 1: mysqldump: not found
```

Is there something im missing??

Cheers

**Comment by freekmurze** [comment]
`mysqldump` is probably missing on your system. Or maybe PHP does not have the right permissions or environment to call that binary. This is not caused by this package, but your configuration.

If you find that the package is in error, feel free to PR a fix.

**Comment by cloudwales** [comment]
Ok thank you. If it works by calling it by the command shouldn't it work in schedule?? I have mysqldump installed on the system and works from console command but not schedule. But on the testing server with exact same settings it works.
