### ISSUE TITLE
MongoDB authenatication error

### ISSUE THREAD

**Issue by Giacomo92** [spatie/laravel-backup#846]
Hi everyone,
when I run the command `php artisan backup:run` on my Laravel application with MongoDB database I get the following error:

server returned error on SASL authentication step: Authentication failed.

I see There is a missing property set of DBdumper Obj so I added [here](https://github.com/spatie/laravel-backup/blob/39c19bc8d5d5aee33f37efaa58977f19fb5cb839/src/Tasks/Backup/DbDumperFactory.php#L36). Check on my pull request @freekmurze and feel free to merge it.

**Comment by freekmurze** [comment]
We'll handle this further in #845
