### ISSUE TITLE
'Undefined index: filesystems' Exception when running 'backup:list'

### ISSUE THREAD

**Issue by teriu** [spatie/laravel-backup#85]
Backup works correctly when running `backup:run`, but `backup:list` throws the *Undefined index: filesystems* Exception. I updated the config from `disks` to `filesystems` and it appears to have resolved the issue.

I'm guessing the dummy config is a little out of date?

**Comment by freekmurze** [comment]
I changed the dummy file to `disks`, but forgot to add it to the deprecated config values function in the service provider. Will fix that now.

Thanks for letting me know.

**Comment by freekmurze** [comment]
Fixed in version 3.1.1
