### ISSUE TITLE
PHP Fatal error:  Cannot use isset() on the result of an expression (you can use "null !== expression" instead)

### ISSUE THREAD

**Issue by shamsuljewel** [spatie/laravel-backup#857]
When I am running php artisan backup:run i got the backup and everything but at the end I get this error!, I am using laravel 5.7 with PHP 7.2.9-1+ubuntu18.04.1+deb.sury.org+1 (cli) 
In 5b6fcc6d69fa3336f6a5157e86c604e49cb30d08.php line 15:
                                                                                                 
  Cannot use isset() on the result of an expression (you can use "null !== expression" instead)
![screen shot 2019-02-01 at 15 31 18](https://user-images.githubusercontent.com/2234477/52128908-7e443700-2636-11e9-92c8-0cbcbec54576.png)

**Comment by freekmurze** [comment]
Seems like this error is originating from somewhere within your own app.

If you find that the package is in error, please submit a failing test for me to fix!
