### ISSUE TITLE
Unable to get zip file name

### ISSUE THREAD

**Issue by webribs** [spatie/laravel-backup#864]
I've created BackupWasSuccessfulListener and trying to get uploaded filename. $event- >backupDestination doesn't return file name.

![screenshot_19](https://user-images.githubusercontent.com/10451770/53039290-b35ae100-34a0-11e9-983c-018cb99a8e00.png)

`class BackupWasSuccessfulListener {
	/**
	 * Handle the event.
	 *
	 * @param  BackupWasSuccessful $event
	 * @return void
	 */

	public function handle(BackupWasSuccessful $event) {
		$path = $event->backupDestination;
		//Get file size
		// $fileSize = $this->formatSizeUnits(filesize(storage_path('app/' . $path)));

		$backup = DatabaseBackup::create([
			'name' => $path,
			'size' => $fileSize,
		]);

		\Log::info("Backup done successfully");

	}

	public function formatSizeUnits($bytes) {
		if ($bytes >= 1073741824) {
			$bytes = number_format($bytes / 1073741824, 2) . ' GB';
		} elseif ($bytes >= 1048576) {
			$bytes = number_format($bytes / 1048576, 2) . ' MB';
		} elseif ($bytes >= 1024) {
			$bytes = number_format($bytes / 1024, 2) . ' KB';
		} elseif ($bytes > 1) {
			$bytes = $bytes . ' bytes';
		} elseif ($bytes == 1) {
			$bytes = $bytes . ' byte';
		} else {
			$bytes = '0 bytes';
		}

		return $bytes;
	}`

While using "spatie/laravel-backup": "3.0.0", this version I was getting the path of file using 

`$event->backupDestination->getNewestBackup()->path();`

**Comment by freekmurze** [comment]
We don't support that version anymore, please upgrade to the latest version of the package.
