### ISSUE TITLE
Backup failed because The dump process failed with exitcode 7 : Unknown error : mysqldump: [ERROR] unknown variable 'optionname=optionvalue'

### ISSUE THREAD

**Issue by haneef5k** [spatie/laravel-backup#865]
I have some issue DB dump laravel-backup 5v, i planned to upgrade to laravel-backup 6.0.
i encounter with below error on server.

**Laravel version: 5.7
laravel-backup version: ^6.0
Server: Digital ocean**

> forge@plateau:~/example.com$ php artisan backup:run --only-db
> Starting backup...
> Dumping database db_name_here...
> Backup failed because The dump process failed with exitcode 7 : Unknown error : mysqldump: [ERROR] unknown variable 'optionname=optionvalue'
> .
> #0 /home/forge/example.com/vendor/spatie/db-dumper/src/DbDumper.php(246): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))

**Comment by aihuaiyang** [comment]
> I have some issue DB dump laravel-backup 5v, i planned to upgrade to laravel-backup 6.0.
> i encounter with below error on server.
> 
> **Laravel version: 5.7 laravel-backup version: ^6.0 Server: Digital ocean**
> 
> > forge@plateau:~/example.com$ php artisan backup:run --only-db
> > Starting backup...
> > Dumping database db_name_here...
> > Backup failed because The dump process failed with exitcode 7 : Unknown error : mysqldump: [ERROR] unknown variable 'optionname=optionvalue'
> > .
> > #0 /home/forge/example.com/vendor/spatie/db-dumper/src/DbDumper.php(246): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))

Have you solved this problem？

**Comment by aihuaiyang** [comment]
@haneef5k 
Have you solved this problem？

Whoops!

Important: An error occurred while backing up DeskLamp

Exception message: The dump process failed with exitcode 127 : Command not found : sh: mysqldump: command not found

**Comment by haneef5k** [comment]
@aihuaiyang not yet.

**Comment by zOxta** [comment]
@haneef5k You probably just need to comment out the following line in your MySQL config (`config/database.php`) since it is getting passed as an argument to the `mysqldump` process.

> // 'add_extra_option' => '--optionname=optionvalue',

**Comment by zOxta** [comment]
@aihuaiyang `mysqldump` does not appear to be installed. 

Or if it is installed, Laravel Backup is unable to find it so you may need to check this out https://docs.spatie.be/laravel-backup/v6/installation-and-setup#dumping-the-database (look at the bottom near `dump_binary_path` where you can define the path of `mysqldump`).

**Comment by haneef5k** [comment]
Thank you @zOxta my issue is fixed now.
