### ISSUE TITLE
The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2004: "Can't create TCP/IP socket (10106 "Unknown error")"

### ISSUE THREAD

**Issue by masami6871** [spatie/laravel-backup#867]
Hi  . I  used of  your package.

 i can  create  backup from my database  with this command : **php artisan backup:run --only-db**
![1](https://user-images.githubusercontent.com/29583593/53417814-a3388980-39eb-11e9-8ba4-af9d0a9276d8.png)

but when i want create  create  backup file with **Artisan::call(' backup:run',array('--only-db'=>true))** 
i see  this error : 
![2](https://user-images.githubusercontent.com/29583593/53418260-a718db80-39ec-11e9-870c-c5402cfb18b0.png)

my config is  :  
![3](https://user-images.githubusercontent.com/29583593/53418326-c9aaf480-39ec-11e9-9667-90f617ce09cc.png)

and  i  try  my app  in those path :
 xampp/htdoc/ => didn't work
otherpath =>  didn't work 
-----------
this is my fail email :
[laravel.txt](https://github.com/spatie/laravel-backup/files/2905857/laravel.txt)
-----------
please  help  me  .  i  confused  .  i  really need to  that  .  
thanks.

**Comment by freekmurze** [comment]
Seems like this is a permission problem on your end. It is not caused by this package.

**Comment by GenedyMohamed** [comment]
Did anyone solve this problem?

**Comment by sirdoro1** [comment]
> 
> 
> Did anyone solve this problem?

Yeah! I solved mine by adding  **;C:\xampp\mysql\bin** to my Windows System Environment Path and here is my config/database.php file attached.
![Database](https://user-images.githubusercontent.com/29659185/76774923-e60b0200-67a4-11ea-890a-35694c8a8539.png)

**Comment by zohaibhassan156** [comment]
I excluded views in exclude_tables then it works without this error
