### ISSUE TITLE
Is encryption planned?

### ISSUE THREAD

**Issue by andreasba** [spatie/laravel-backup#87]
Good morning,

I just heard about this awesome package from Eric's Laravel Newsletter.

When seeing that you can backup on S3 etc, I though: is there a possibility to encrypt the backup? After checking the documentation it seems that this is not the case yet.

So I was wondering whether you have plans to implement such a feature?

Thanks
Andreas

**Comment by freekmurze** [comment]
Currently the package doesn't do encryption on S3. That's something that should be solved at the FlySytem/Laravel side of things.

This Twitter user was researching the situation, he may know more: https://twitter.com/TimothyLoyer/status/707553493255528448
