### ISSUE TITLE
cant install v6 on laravel 5.7 

### ISSUE THREAD

**Issue by shez1983** [spatie/laravel-backup#875]
either the docs are wrong or the code is - 

in the docs v6 (latest version) can be installed on laravel 5.7 which i have but upon trying to install i get:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.7.24
    - Conclusion: don't install laravel/framework v5.7.24
    - spatie/laravel-backup 6.1.0 requires illuminate/support ~5.8.0 -> satisfiable by laravel/framework[5.8.x-dev], illuminate/support[5.8.x-dev, v5.8.0, v5.8.2].
    - spatie/laravel-backup 6.1.1 requires illuminate/support ~5.8.0 -> satisfiable by laravel/framework[5.8.x-dev], illuminate/support[5.8.x-dev, v5.8.0, v5.8.2].
    - Can only install one of: laravel/framework[5.8.x-dev, v5.7.24].
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v5.7.24
    - don't install illuminate/support v5.8.0|don't install laravel/framework v5.7.24
    - don't install illuminate/support v5.8.2|don't install laravel/framework v5.7.24
    - Installation request for laravel/framework (locked at v5.7.24, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.24].
    - Installation request for spatie/laravel-backup ^6.1 -> satisfiable by spatie/laravel-backup[6.1.0, 6.1.1].

**Comment by freekmurze** [comment]
v6.0.7 has L5.7 support: https://github.com/spatie/laravel-backup/blob/6.0.7/composer.json

If you run `composer install spatie/laravel-backup` composer should pick that version for you.

**Comment by CanardDrones** [comment]
Hi! I have the exact same problem.
This is the output of `composer install spatie/laravel-backup`:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.7.27
    - Conclusion: don't install laravel/framework v5.7.27
    - spatie/laravel-backup 6.1.0 requires illuminate/events ~5.8.0 -> satisfiable by illuminate/events[5.8.x-dev, v5.8.0, v5.8.2, v5.8.3].
    - spatie/laravel-backup 6.1.1 requires illuminate/events ~5.8.0 -> satisfiable by illuminate/events[5.8.x-dev, v5.8.0, v5.8.2, v5.8.3].
    - don't install illuminate/events 5.8.x-dev|don't install laravel/framework v5.7.27
    - don't install illuminate/events v5.8.0|don't install laravel/framework v5.7.27
    - don't install illuminate/events v5.8.2|don't install laravel/framework v5.7.27
    - don't install illuminate/events v5.8.3|don't install laravel/framework v5.7.27
    - Installation request for laravel/framework (locked at v5.7.27, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.27].
    - Installation request for spatie/laravel-backup ^6.1 -> satisfiable by spatie/laravel-backup[6.1.0, 6.1.1].


Installation failed, reverting ./composer.json to its original content.
```
What should I do?
Thanks!

**Comment by CanardDrones** [comment]
Ok, I was able to solve it by running `composer require spatie/laravel-backup:6.0.7`

Cheers!
