### ISSUE TITLE
Exception when running backup:run

### ISSUE THREAD

**Issue by folkevil** [spatie/laravel-backup#88]
Hi, 

I got this problem when running backup:run

```php
>php artisan backup:run -vvv
Starting backup...
Dumping database dbname...
Backup failed because The dump process failed with exitcode 1 : General error.
Backup completed!
```

I'm running on L5 5.1 and php 7.0.4, Windows 7.

============

Another problem, how can i config to send notification to my channel on my domain, i don't see it in config file?

**Comment by freekmurze** [comment]
Are you able run to dump a db via `mysqldump` on the command line?

You can specify an endpoint url in [the config file](https://github.com/maknz/slack/blob/master/src/config/config.php#L16) of the [maknz-slack package](https://github.com/maknz/slack).

**Comment by aaronprojects** [comment]
Hey,

I'm discovering the same issue:

`>php artisan backup:run -vvv
Starting backup...
Dumping database dbname...
Backup failed because The dump process failed with exitcode 1 : General error.
Backup completed!`

I also ran:
`pg_dump -h localhost -U postgres dbname > dbname_2016.sql`

Which works perfectly.

I only changed this line in the config:

`'databases' => [
                'pgsql'
],`

I'm on Windows 7, working with L5 5.2 and PHP 5.6.12

Regards,
Verena

**Comment by Rhincodon** [comment]
@aaronprojects What version of this package do you use?

**Comment by Rhincodon** [comment]
@freekmurze On Windows it can be problem with double slashes in temp sql file path, which generated [here](https://github.com/spatie/laravel-backup/blob/master/src/Tasks/Backup/TemporaryDirectory.php#L56-L60)  and then one more time [here](https://github.com/spatie/laravel-backup/blob/master/src/Tasks/Backup/TemporaryDirectory.php#L46).
http://d.pr/i/11MkW

Just as variant.

@aaronprojects Also you can try dump [this](https://github.com/spatie/db-dumper/blob/master/src/Databases/PostgreSql.php#L140) variable and try to run generated command.

**Comment by aaronprojects** [comment]
Hey,

I'm using version 3.1

Dumping the **$command** variable outputs the following:

`pg_dump -d dbname -U postgres -h localhost -p 5432 --file=C:\...\storage\laravel-backups/temp//dbname.sql`

If I run this command manually in the terminal, it works.

**Comment by Rhincodon** [comment]
@aaronprojects It asking for a password before run? You have non empty password for pgsql in laravel config?

**Comment by Rhincodon** [comment]
@aaronprojects And try dump in [this](https://github.com/spatie/db-dumper/blob/master/src/Exceptions/DumpFailed.php#L15) method `$process->getErrorOutput()`.

**Comment by aaronprojects** [comment]
Hey,
it did not ask for a password, but there's one set. Kind of strange...

Drumping the errorOutput gives me the following:

_Der Befehl "pg_dump" ist entweder falsch geschrieben oder\r\n
konnte nicht gefunden werden.\r\n_

It means the pg_dump command could not be found.

**Comment by adzymaniac** [comment]
hi @Rhincodon 

I got same error, my pgsql using no password.

**Comment by Rhincodon** [comment]
@adzymaniac Windows too?

**Comment by freekmurze** [comment]
Reopen if you're still having troubles.
