### ISSUE TITLE
Installing composer SQLSTATE[42S02]: Base table or view not found: 1146 Table 'MYDATABASE.configs' doesn't exist

### ISSUE THREAD

**Issue by giadar** [spatie/laravel-backup#882]
Hi, running

**composer require "spatie/laravel-backup:^5.12.0"**

my composer.json was updated but  installation give me error messages like:
**------------------------------------------------------**
In Connection.php line 664:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'MYDATABASE.conf
  igs' doesn't exist (SQL: select * from `configs` where `section` = login)
....
...
...
**-------------------------------------------------------**
ended with this error message:
**-------------------------------------------------------**
"Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1"
**------------------------------------------------------**
Seems "configs" table doesn't exist but haven't find ay migration.

Is there anything I could  either check?
Thanks

**Comment by freekmurze** [comment]
This package doesn't use a table named `configs`. Probably you're error isn't caused by this package.
