### ISSUE TITLE
Automatic Backup in Laravel not working

### ISSUE THREAD

**Issue by Cyrille09** [spatie/laravel-backup#884]
scheduling 'backup:clean' and 'backup:run' not working in Laravel 5.7

This is the code I have in Kernel
protected function schedule(Schedule $schedule)
    {
        $schedule->command('backup:run')
                 ->everyMinute();
    }

**Comment by freekmurze** [comment]
It seems to work in my applications. Could you create a demo app for me to look at where this does not work?

**Comment by Cyrille09** [comment]
[login.zip](https://github.com/spatie/laravel-backup/files/3003918/login.zip)
Hi Freekmurze
I have uploaded a demo project

**Comment by freekmurze** [comment]
Could you create a repo for me to look at?

**Comment by Cyrille09** [comment]
Well, I follow the instruction until the end. However, the backup system is properly working but it does not work with schedule. 
These are steps I follow 
1. composer require spatie/laravel-backup
2. php artisan vendor:publish --provider="Spatie\Backup\BackupServiceProvider"
3. I add the following code into database.php file in Mysql section
         'dump' => [
                  'dump_binary_path' => 'C:\xampp\mysql\bin',
                        'excludeTables' => [
                             'table_to_exclude_from_backup',
                             'another_table_to_exclude'
                         ]
                  ]
4. Then I run the following code for backup (php artisan backup:run)
Note: from step 1 to step 4 are working. 

5. I run this code:  cd /path-to-your-project && php artisan schedule:run >> /dev/null 2>&1
6. Then I set this code into kernel.php: 
protected function schedule(Schedule $schedule)
    {
        
        $schedule->command('backup:run')
                 ->everyMinute();
    }

**Comment by FrankFlow** [comment]
Hi FreekMurze, 
in Laravel 5.8 it returns:
no scheduled commands are ready to go.

In App\Console\Kernel.php  

```
protected $commands = [];

protected function schedule(Schedule $schedule)
{
  $schedule->command('backup:run')->daily()->at('18:42');
}
```

If I run

`php artisan backup:run`

everything goes fine

**Comment by Quaxxon** [comment]
I'm having issues too, manually running the command is fine but the schedule isn't working anymore.

My last scheduled backup was 26th March 19. did laravel have an update that broke things maybe? hmmm

**Comment by StanBarrows** [comment]
Same problem here: 

If i run it with "php artisan backup:run" everything works thine. But not with the Scheduler.

**Comment by yagogak** [comment]
Same problem here after updating from 6.0.3 to 6.0.7

**Comment by tcnjr** [comment]
> If i run it with "php artisan backup:run" everything works thine. But not with the 

> Scheduler.

Same problem here php 7.3.3 and laravel 5.8. Has anyone found a solution or another plugin to solve this issue?

**Comment by kallekulp** [comment]
Same problem here. Any updates?

**Comment by tranducit95** [comment]
me too....

**Comment by stevecrossuk** [comment]
This is a problem for me too. I can run "php artisan backup:run" but it won't run to the schedule.

**Comment by buiquangduc** [comment]
I am facing the same problem too.

I noticed the PHP CLI version when I run `php -v` on the terminal and the PHP CLI version when the cronjob is run is different.

With `php -v` on the terminal, PHP output version 7.3.1
![image](https://user-images.githubusercontent.com/20354417/59144416-dd112700-8a01-11e9-8229-a892fd15ae86.png)

With `php -v` on the cronjob, PHP output version 7.1.23
![image](https://user-images.githubusercontent.com/20354417/59144422-f87c3200-8a01-11e9-999e-5cd9d17c7e82.png)
![image](https://user-images.githubusercontent.com/20354417/59144435-2bbec100-8a02-11e9-940f-7271b24c6e9a.png)

`spatie/db-dumper` will only work with version PHP version 7.3 or above, so you will need to make sure you run PHP 7.3 on the cronjob. Below is how I do it:

Get the current PHP path on your terminal:
![image](https://user-images.githubusercontent.com/20354417/59144483-fd8db100-8a02-11e9-9d61-3d16d272ba7d.png)
Change your PHP path on the cronjob:
![image](https://user-images.githubusercontent.com/20354417/59144723-f071c180-8a04-11e9-80fc-68177c30d34d.png)

**Comment by kallekulp** [comment]
Okay so... I fixed my issue. 

If you have this issue make sure to check your kernel file.

The thing was that I was running Laravel's "queue:work" in the Kernel.php so when I ran schedule:work then all the commands only ran once since the queue was the last command and it got stuck there. After I removed the queue:work from the kernel and created a separate cron for it, everything started working as expected! 

Awesome package and the issues was on my side.
Thanks

**Comment by jorgeirun** [comment]
Facing the same problem as above, when I run manually all works perfect but scheduler never fires.

**Comment by Cyrille09** [comment]
> Okay so... I fixed my issue.
> 
> If you have this issue make sure to check your kernel file.
> 
> The thing was that I was running Laravel's "queue:work" in the Kernel.php so when I ran schedule:work then all the commands only ran once since the queue was the last command and it got stuck there. After I removed the queue:work from the kernel and created a separate cron for it, everything started working as expected!
> 
> Awesome package and the issues was on my side.
> Thanks

**Comment by Yangwendaxia** [comment]
I am facing the same problem too. 
I tracked the root cause by following code:
```
$schedule->command('backup:run')->everyMinute()->appendOutputTo('/var/www/storage/logs/cron.log');

```
then, I found there are error message in the cron.log file as following:
```
 Starting backup...
Backup failed because: mkdir(): Permission denied.

```
On my side , the owner of database backup directory and temporary directory config in `config\backup.php`  is invalid . After I change the owner of them, backup cron job works fine.

**Comment by AdnanHussainTurki** [comment]
Stil not working for me. Please provide a concrete solution.

**Comment by akoSalman** [comment]
I had the same problem, figured out that I was running commands through Scheduler in the wrong way:
This was my code:
```
$schedule->command('command.backup:clean')->dailyAt("05:00");
```
That should be 
```
$schedule->command('backup:clean')->dailyAt("05:00");
```
Now everything works fine.

**Comment by HugoChiesse** [comment]
So gays, 

I have the same problem. I wrote  **$schedule->command('backup:run')->dailyAt("05:00");**  but not work. I need to inform anythink on $commands???

`protected $commands = [
        //
    ];`

**Comment by tubescreamerz** [comment]
> I am facing the same problem too.
> 
> I noticed the PHP CLI version when I run `php -v` on the terminal and the PHP CLI version when the cronjob is run is different.
> 
> With `php -v` on the terminal, PHP output version 7.3.1
> ![image](https://user-images.githubusercontent.com/20354417/59144416-dd112700-8a01-11e9-8229-a892fd15ae86.png)
> 
> With `php -v` on the cronjob, PHP output version 7.1.23
> ![image](https://user-images.githubusercontent.com/20354417/59144422-f87c3200-8a01-11e9-999e-5cd9d17c7e82.png)
> ![image](https://user-images.githubusercontent.com/20354417/59144435-2bbec100-8a02-11e9-940f-7271b24c6e9a.png)
> 
> `spatie/db-dumper` will only work with version PHP version 7.3 or above, so you will need to make sure you run PHP 7.3 on the cronjob. Below is how I do it:
> 
> Get the current PHP path on your terminal:
> ![image](https://user-images.githubusercontent.com/20354417/59144483-fd8db100-8a02-11e9-9d61-3d16d272ba7d.png)
> Change your PHP path on the cronjob:
> ![image](https://user-images.githubusercontent.com/20354417/59144723-f071c180-8a04-11e9-80fc-68177c30d34d.png)

Is it true that it needs php7.3 - our DO server runs 7.2, so that might be why.

**Comment by sa1if3** [comment]
I faced a similar issue but ultimately solved it by following laravel documentation
I had to add 
* * * * * cd /path-to-your-project && php artisan schedule:run >> /dev/null 2>&1

(Note: I didn't redirect my logs initial to /dev/null instead to a log file so that I could debug the issue )
in cron

and set the current time zone according to my area

$schedule->command('backup:run --only-db')->timezone('Asia/Kolkata')->dailyAt('01:35');

**Comment by ismaail** [comment]
I faced same issue, the source of the problem for me was `temporary_directory` which first created with `root` ownership.
