### ISSUE TITLE
It looks like Laravel 5.7 is not supported

### ISSUE THREAD

**Issue by boobooking** [spatie/laravel-backup#885]
Hi!

According to installation requirements  I should have Laravel 5.7.20 or higher. I have Laravel v5.7.28 installed and trying to install laravel-backup package. And installation is failed.

composer require spatie/laravel-backup
Using version ^6.1 for spatie/laravel-backup
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    **- Conclusion: remove laravel/framework v5.7.28**
    - Conclusion: don't install laravel/framework v5.7.28
    - spatie/laravel-backup 6.1.0 requires illuminate/events ~5.8.0 -> satisfiable by illuminate/events[5.8.x-dev, v5.8.0, v5.8.2, v5.8.3, v5.8.4].
    - spatie/laravel-backup 6.1.1 requires illuminate/events ~5.8.0 -> satisfiable by illuminate/events[5.8.x-dev, v5.8.0, v5.8.2, v5.8.3, v5.8.4].
    - don't install illuminate/events 5.8.x-dev|don't install laravel/framework v5.7.28
    - don't install illuminate/events v5.8.0|don't install laravel/framework v5.7.28
    - don't install illuminate/events v5.8.2|don't install laravel/framework v5.7.28
    - don't install illuminate/events v5.8.3|don't install laravel/framework v5.7.28
    - don't install illuminate/events v5.8.4|don't install laravel/framework v5.7.28
    - Installation request for laravel/framework (locked at v5.7.28, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.28].
    - Installation request for spatie/laravel-backup ^6.1 -> satisfiable by spatie/laravel-backup[6.1.0, 6.1.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by freekmurze** [comment]
Try version 6.0.6
