### ISSUE TITLE
Documentation installation v5

### ISSUE THREAD

**Issue by davidjr82** [spatie/laravel-backup#886]
In this docs: 

[https://docs.spatie.be/laravel-backup/v5/introduction](https://docs.spatie.be/laravel-backup/v5/introduction)

to install v5 it says to use 

`composer require "spatie/laravel-backup:^3.0.0"`

instead of ^5. I would open a PR but I don't know where this documentation is. Sorry!

**Comment by freekmurze** [comment]
Fixed, thanks!

**Comment by davidjr82** [comment]
Thanks to all of you for all your open source work :)
