### ISSUE TITLE
Valid syntax for excludeTables

### ISSUE THREAD

**Issue by PetroGromovo** [spatie/laravel-backup#887]
Hello,
Using laravel-backup("^6.1") for laravel 5.8 I failed to set excludeTables property in config file.
I did it as :

```
        'source' => [
        ...
            'databases' => [
                'mysql',
            ],


             'mysql' => [
                 'dump' => [
                     'excludeTables' => [
                         'activity_log', //Without prefix  vt2_activity_log
                         'migrations'
                     ]
                 ]
             ],
```

But I see that all tables including vt2_activity_log and vt2_migrations are in resulting file?

vt2_ that is an prefix defined in config/database.php :
```
        'mysql' => [
            'driver' => 'mysql',
            'prefix' => 'vt2_',
            ...
```
            
I suppose that I do not have to set prefix in excludeTables array ? I tried both, but failed. Was it correct place/synatx for excludeTables?    
            
Thanks!

**Comment by freekmurze** [comment]
AFAIK The syntax for excluding tables hasn't changed. That  `vt2_` isn't defined in our code.

Should you find that we made an error in code, please submit a failing test for me to look at.
