### ISSUE TITLE
Version 6.1 does not work with S3 disk

### ISSUE THREAD

**Issue by chood531** [spatie/laravel-backup#888]
I am using version 6.1 of this plugin, but it appears that it no longer works with the S3 disk location for backup.

Steps to replicate:

(1) Install version 6.1 into a fresh install of laravel 5.8.

(2) Install spatie backup 6.1

(3) Add .env keys

AWS_ACCESS_KEY_ID=****
AWS_SECRET_ACCESS_KEY=***
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=***
AWS_URL=https://***.s3.amazonaws.com

(4) run `php artisan backup:run`

(5) the backup zip is created, but error occurs when trying to copy to S3:

```
Starting backup...
Dumping database hired_api...
Determining files to backup...
Zipping 1 files...
Created zip containing 1 files. Size is 77.65 KB
Copying zip to disk named s3...
Copying zip failed because: Error executing "PutObject" on "https://laravel/2019-04-01-01-20-06.zip"; AWS HTTP error: cURL error 6: Could not resolve: laravel (Domain name not found) (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).
Backup failed because Error executing "ListObjects" on "https://s3.amazonaws.com/?prefix=Laravel%2F&encoding-type=url"; AWS HTTP error: Client error: `GET https://s3.amazonaws.com/?prefix=Laravel%2F&encoding-type=url` resulted in a `403 Forbidden` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>32E7B8 (truncated...)
 AccessDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?>
```

**Comment by freekmurze** [comment]
My tests seem to indicate that this is working as intended. I guess there's something wrong with the credentials you're using.

Try executing `php artisan config:clear`

**Comment by chood531** [comment]
ok, sorry about that 😞 - I will give it a try and let you know.

**Comment by chood531** [comment]
@freekmurze very strange.  Same issue even if I setup a completely new project.

Just to make sure, these are the correct packages I would need to get this running with S3, correct?

```
"league/flysystem-aws-s3-v3": "^1.0",
"spatie/laravel-backup": "^6.1"
```

(And for reference: `"laravel/framework": "5.8.*"`)

The reason I do not think it is an Copying zip failed because: 

(1) I am using the same keys on another project that runs laravel 5.7 and spatie/laravel-backup version 5

(2) The error message makes it seem like the package is just trying to upload to the wrong bucket.  It looks like it is pulling bucket name from `APP_NAME` for some reason: https://laravel/2019-04-01-06-59-30.zip

Error executing "PutObject" on "https://laravel/2019-04-01-06-59-30.zip"

I'll keep trying to see if I can figure out what is going on.

**Comment by chood531** [comment]
Doh.  I figured it out.

```
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
```

This was defined earlier on in the .env file, and was empty.  didn't see it.  🤦‍♂️

**Comment by freekmurze** [comment]
Glad you could figure it out quickly. Have a great day! 👍

**Comment by ashrasfulalam135** [comment]
'"mysqldump"' is not recognized as an internal or external command, operable program or batch file.

i am faceing this issue. can you please help me.
i am using laravel 5.7.*. i can backup source code. but i am facing problem when i enable mysql back.

**Comment by najathi** [comment]
I face this issue

- please follow this https://spatie.be/docs/laravel-backup/v4/installation-and-setup#dumping-the-database
- please use PHP storm IDE


```
//config/database.php
'connections' => [
    'mysql' => [
        'driver'    => 'mysql'
        ...,
        'dump' => [
                'dump_binary_path' => 'D:/xampp/mysql/bin/', // only the path, so without `mysqldump` or `pg_dump`
                'use_single_transaction',
                'timeout' => 60 * 5, // 5 minute timeout
            ], 
    ],
```

**Comment by najathi** [comment]
> '"mysqldump"' is not recognized as an internal or external command, operable program or batch file.
> 
> i am faceing this issue. can you please help me.
> i am using laravel 5.7.*. i can backup source code. but i am facing problem when i enable mysql back.

**I face this issue**

- please follow this https://spatie.be/docs/laravel-backup/v4/installation-and-setup#dumping-the-database
- please use PHP storm IDE

```
//config/database.php
'connections' => [
    'mysql' => [
        'driver'    => 'mysql'
        ...,
        'dump' => [
                'dump_binary_path' => 'D:/xampp/mysql/bin/', // only the path, so without `mysqldump` or `pg_dump`
                'use_single_transaction',
                'timeout' => 60 * 5, // 5 minute timeout
            ], 
    ],
```
