### ISSUE TITLE
Slack config does not provide an endpoint

### ISSUE THREAD

**Issue by etiennemarais** [spatie/laravel-backup#89]
The slack client requires an endpoint to be instantiated with but the notifier class that fires the slack message sending resolves the Client out of the container with no endpoint available so it gives a guzzle error.

Would you consider adding a config option for endpoint? The current workaround for me is conditionally resolving, ([Contextual binding docs](https://laravel.com/docs/5.1/container#contextual-binding)), the client that gets passed to the Slack notifier like so:

```
$app->when('Spatie\Backup\Notifications\Senders\Slack')
    ->needs('Maknz\Slack\Client')
    ->give(function () {
        return new Maknz\Slack\Client(env('SLACK_WEBHOOK_URL'), [
            'username' => env('SLACK_BOT_NAME'),
            'icon' => env('SLACK_BOT_EMOJI' ,':mushroom:'),
            'channel' => env('SLACK_ERROR_CHANNEL'),
        ]);
    });
```

**Comment by freekmurze** [comment]
You can specify an endpoint url in [the config file](https://github.com/maknz/slack/blob/master/src/config/config.php#L16) of the [maknz-slack package](https://github.com/maknz/slack)
