### ISSUE TITLE
Backup cleanup not working with Laravel 5.8 & spatie/laravel-backup 6.1

### ISSUE THREAD

**Issue by vishalmandora** [spatie/laravel-backup#893]
I've upgraded Laravel version from 5.7 to 5.8 & also upgraded spatie/laravel-backup 6.1 & it seems like `php artisan backup:clean` command is not removing any backup files

**Comment by freekmurze** [comment]
The tests prove that the cleanup is working as expected.

Please submit a failing PR for me to look at.
