### ISSUE TITLE
Backup to Google Drive no longer working

### ISSUE THREAD

**Issue by SuddenlyRust** [spatie/laravel-backup#897]
After upgrading my Laravel Application the backup process to my Google Drive store is no longer working correctly for me. Following my setup:

| Name                                           | Current Version | Old Version |
| ------------------------------------|------------------:|-------------:|
| PHP                                              | 7.3                     | 7.2              |
| laravel/framework                        | v5.8.10              | v5.7.26        |
| spatie/laravel-backup                   | 6.1.2                 | 5.11            |
| nao-pon/flysystem-google-drive | 1.1.10               | 1.1.10          |

When I run `php artisan backup:run --only-db` I get following error and the backup is stopped.
```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 256998320 bytes) in /var/www/html/vendor/league/flysystem/src/Util/MimeType.php
on line 188
```

Now the problem is my ZIP-Archive is around 30MB and the error tells me it is somewhat around 256MB. 

I did some troubleshooting and could pin point out when the exception is thrown. In the following file when `writeStream` is called on line 85. But before we open the file with the access mode `r+`.
https://github.com/spatie/laravel-backup/blob/3b223bf8355d97c4bb9c0afbd7b4c4f7952fc529/src/BackupDestination/BackupDestination.php#L83

When I change the access mode to `w+` everything works fine again.
```
        $handle = fopen($file, 'w+');
```

Anyone else encountered this problem with Google Drive? And is it possible to change the access mode to `w+` or is this a breaking change?

Some more Information. I did follow this guide (some time ago) to backup to my google drive store https://medium.com/@dennissmink/laravel-backup-database-to-your-google-drive-f4728a2b74bd

**Comment by SuddenlyRust** [comment]
Okay I am really sorry. I think my server was not configured correct. Now the backup works fine again with Google Drive and without modifying the access mode.

Sorry to bother you :(

**Comment by salioudiabate** [comment]
Hi I need help, I want to backup my database on Google Drive but I have this error :

Copying zip failed because: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "File not found: Gelico.",
    "locationType": "parameter",
    "location": "fileId"
   }
  ],
  "code": 404,
  "message": "File not found: Gelico."
 }
}
Sending notification failed

**Comment by hkp22** [comment]
@salioudiabate I have explained the solution to this error in this video: 
https://www.youtube.com/watch?v=6kxXkrlRuJU

I am sure it will be helpful. Or you can also check out this article:
https://qirolab.com/posts/how-to-setup-laravel-backup-on-google-drive-1607368130
