### ISSUE TITLE
Password protect zip archive

### ISSUE THREAD

**Issue by Ruud-Gerrits** [spatie/laravel-backup#899]
Is it possible to password protect the zip? Maybe with using the setEncryptionName method in ZipArchive (https://www.php.net/manual/en/ziparchive.setencryptionname.php)?

**Comment by freekmurze** [comment]
The package doesn't do this by default.

You can listen for the `BackupZipWasCreated` event  to do last minute manipulations on the created zip file.

https://docs.spatie.be/laravel-backup/v6/taking-backups/events#backupzipwascreated
