### ISSUE TITLE
[PROPOSAL] Different Storage for every frequency strategy

### ISSUE THREAD

**Issue by Giacomo92** [spatie/laravel-backup#906]
Hi everyone,
I am configuring my application that uses s3 as storage. This service offers different price based on the access frequency. In order to optimize cost I was thinking to associate the frequency of the job to a different storage. 

For example:
when I run :
` $schedule->command('backup:run')->daily();`
the backup will use s3 storage with default frequency access or another storage service

when I run :
` $schedule->command('backup:run')->yearly();`
the backup will use s3 storage with infrequent access (like Glacier) or another storage service

To do so I will add a new set of configuration under '_destionation_' config with this naming convention (keeping the actual '_disks_' as default):

- daily.disks
- weekly.disks
- monthly.disks
- yearly.disks

Can this pull request can be useful to someone?
I think the application will remain simple as now.

What do you think about this idea @freekmurze ?

**Comment by freekmurze** [comment]
Thank you for this suggestion, but I'm going to keep things as they are for now.
