### ISSUE TITLE
error on backup with dropbox 

### ISSUE THREAD

**Issue by menasoft** [spatie/laravel-backup#907]
i have error when request backup but no error when request clean 
`local.ERROR: syntax error, unexpected end of file {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): syntax error, unexpected end of file at /home/...vendor/spatie/db-dumper/src/DbDumper.php:279)
[stacktrace]
#0 /home/...vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/home/magic1/pu...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Spatie\\\\DbDumper...')
#2 /home/...vendor/spatie/db-dumper/src/Databases/MySql.php(9): spl_autoload_call('Spatie\\\\DbDumper...')
#3 /home/...vendor/composer/ClassLoader.php(444): include('/home/magic1/pu...')
#4 /home/...vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/home/magic1/pu...')
#5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Spatie\\\\DbDumper...')
#6 /home/...vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php(51): spl_autoload_call('Spatie\\\\DbDumper...')
#7 /home/...vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php(25): Spatie\\Backup\\Tasks\\Backup\\DbDumperFactory::forDriver('mysql')
#8 /home/...vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php(28): Spatie\\Backup\\Tasks\\Backup\\DbDumperFactory::createFromConnection('mysql')
#9 /home/...vendor/laravel/framework/src/Illuminate/Support/Collection.php(1111): Spatie\\Backup\\Tasks\\Backup\\BackupJobFactory::Spatie\\Backup\\Tasks\\Backup\\{closure}('mysql', 0)
#10 /home/...vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php(29): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#11 /home/...vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php(14): Spatie\\Backup\\Tasks\\Backup\\BackupJobFactory::createDbDumpers(Array)
#12 /home/...vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(27): Spatie\\Backup\\Tasks\\Backup\\BackupJobFactory::createFromArray(Array)
#13 [internal function]: Spatie\\Backup\\Commands\\BackupCommand->handle()
#14 /home/...vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#15 /home/...vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /home/...vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 /home/...vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 /home/...vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#19 /home/...vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#20 /home/...vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#21 /home/...vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /home/...vendor/symfony/console/Application.php(908): Spatie\\Backup\\Commands\\BaseCommand->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /home/...vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Spatie\\Backup\\Commands\\BackupCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /home/...vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /home/...vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /home/...vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /home/...artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 {main}
"} `

**Comment by freekmurze** [comment]
Judging by the error message it seems like you have pulled in a PHP 7.3 specific version of db-dumper, but are not running PHP 7.3

Remove `composer.lock`  and `vendor` and try running `composer install` again. 

If that fails you'll have to dive in yourself. Take a look at the code the error is pointing at.

**Comment by menasoft** [comment]
> Judging by the error message it seems like you have pulled in a PHP 7.3 specific version of db-dumper, but are not running PHP 7.3
> 
> Remove `composer.lock` and `vendor` and try running `composer install` again.
> 
> If that fails you'll have to dive in yourself. Take a look at the code the error is pointing at.
i have in my shared host 
mysqldump  Ver 10.13 Distrib 5.6.39, for Linux (x86_64)
and php 7.2
and using spatie v5 with laravel 5.7

**Comment by menasoft** [comment]
my problem not resolved
