### ISSUE TITLE
Laravel 5.8 backup from controller not working

### ISSUE THREAD

**Issue by tcnjr** [spatie/laravel-backup#911]
I am using 
    Route::get('/backup', function(){
    \Artisan::call('backup:run',['--only-db'=>true]);
     });

Everything works fin in command line and I can run other artisan commands from web.php but when I try to use backup:run from a controller or web.php nothing happens, no errors. If save it to a variable and dd($variable) it gives me a 0.  From a controller and web.php, I have tried migrate, make:migration and make:controller. They all work fine. It is just the  backup:run that's not working or giving any errors. Any suggestions? Thanks

**Comment by sirdoro1** [comment]
Am having the same problem

**Comment by BashirRezaiee** [comment]
Having the same problem

**Comment by tcnjr** [comment]
I created a function to do it but I would like to use something like Spatie for future projects so if anyone figured out the Spatie issue please let me know or if you found a suitable replacement for Spatie that would work to. Thanks

**Comment by sirdoro1** [comment]
> 
> 
> I created a function to do it but I would like to use something like Spatie for future projects so if anyone figured out the Spatie issue please let me know or if you found a suitable replacement for Spatie that would work to. Thanks

I am still yet go resolve mine....maybe you can help me out with how you did it with function.

**Comment by tcnjr** [comment]
> I am still yet go resolve mine....maybe you can help me out with how you did it with function.

I made a new class and imported it but you can do it right in your controller if needed.
I can try. what I did was create a function called backup_

` public function backup_() {

        /**
        * This will get a list of tables then delete the ones past a configured amount
        */
        $tables = collect(DB::connection()->getDoctrineSchemaManager()->listTableNames());
        // Sorting them last to first so I can drop the oldest
       $tables = $tables->sort();
        // keeping count of how many copy tables exist
        $this->copied_table_count = 0;
        $this->tables_to_delete = [];
        // mapping through and making of list of what tables to delete an what to ignore
        $tables->map(function($item, $key) {
            if (preg_match("/backup_.*/i", $item)) {
                // keeping count of how many copy tables exist
                $this->copied_table_count  ++;
                $this->tables_to_delete[] = $item;
            }
        });
        
        $how_many_tables_to_delete = $this->copied_table_count;
        // Keeping 7 tables and deleting the older ones
        if (count($this->tables_to_delete) > 7) {
            // Deleting selected table(s) if more then 7
            for($i=0; $i < $how_many_tables_to_delete - 7; $i ++) {
                Schema::dropIfExists($this->tables_to_delete[$i]);
               
            }
        }

            
          // create_backup_table_and_copy_table
          // This will copy the table to the new table
            function back_up_table($table_name) {
              $db = DB::connection();
              $sql = "INSERT INTO " .$table_name. " SELECT * FROM 'Your_Current_Table Name' ";
              $db->statement($sql);
          }
       /**
        * function to create a new table for back up below
        */
       function create_backup_table_and_copy_table() {
           // The table name of the new table is the same plus the time on the end
           $table_name = 'backup' . time();
           Schema::create($table_name, function (Blueprint $table) {
               $table->increments('id');
               $table->string('FirstName');
               $table->string('LastName');
               
               $table->timestamps();
           });
               // running function to copy  table once the new temp table has been created
               back_up_table($table_name);
       // End create_backup_table_and_copy_
       }
       create_backup_table_and_copy_table();
   
    }`

I had to edit this a little and take out some private info. With that being said I hope you get it to work or find your own solution. Good Luck.

**Comment by BashirRezaiee** [comment]
This is my backup controller. I wrote the store function independent of this package. 
`
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;
use ZipArchive;

class BackupController extends Controller
{
    public function index()
    {
        $results = [];
        $files = Storage::files('backups');
        foreach ($files as $file) {
            $size = Storage::size($file);
            $name = explode('/', $file)[1];
            $lastModified = Storage::lastModified($file);
            $lastModified = date("Y-m-d H:i:s", $lastmodified);

            array_push($results, [
                'name' => $name,
                'last_modified' => $lastModified,
                'size' => $this->humanReadable($size),
            ]);
        }
        return $results;
    }

    public function store()
    {
        // Artisan::call('backup:run', [
        //     '--only-db' => 1
        // ]);

        $filename = Carbon::now()->format('Y-m-d-H-i-s');

        $tempPath = base_path('storage\app\backup-temp\\') . $filename;
        $backPath = base_path('storage\app\backups\\') . $filename;

        $command = 'mysqldump -u root --password= ' . env('DB_DATABASE') . ' > ' . $tempPath . '.sql';
        exec($command);

        // zipping 
        $zip = new ZipArchive;
        if ($zip->open($backPath . '.zip', ZipArchive::CREATE) === TRUE) {
            $zip->addFile($tempPath . '.sql', $filename . '.sql');
            $zip->close();
        }

        // clear temp folder
        $this->clearTempFolder();

        return response()->json(['success' => true]);
    }

    private function clearTempFolder()
    {
        //The name of the folder.
        $folder = base_path('storage\app\backup-temp\\');

        //Get a list of all of the file names in the folder.
        $files = glob($folder . '/*');

        //Loop through the file list.
        foreach ($files as $file) {
            //Make sure that this is a file and not a directory.
            if (is_file($file)) {
                //Use the unlink function to delete the file.
                unlink($file);
            }
        }
    }

    public function show($path)
    {
        $file = Storage::disk('local')->get('backups/' . $path);
        return response()->make($file);
    }

    private function humanReadable($bytes)
    {
        $units = ['B', 'KB', 'MB', 'GB', 'TB', 'PB'];
        for ($i = 0; $bytes > 1024; $i++) {
            $bytes /= 1024;
        }
        return round($bytes, 2) . ' ' . $units[$i];
    }

    public function destroy($path)
    {
        Storage::disk('local')->delete('backups/' . $path);
        return response('deleted');
    }
}

`

**Comment by BashirRezaiee** [comment]
This my backup controller, independent from this package.
```
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;
use ZipArchive;

class BackupController extends Controller
{
    public function index()
    {
        $results = [];
        $files = Storage::files('backups');
        foreach ($files as $file) {
            $size = Storage::size($file);
            $name = explode('/', $file)[1];
            $lastmodified = Storage::lastModified($file);
            $lastmodified = date("Y-m-d H:i:s", $lastmodified);

            array_push($results, [
                'name' => $name,
                'last_modified' => $lastmodified,
                'size' => $this->humanReadable($size),
            ]);
        }
        return $results;
    }

    public function store()
    {
        // Artisan::call('backup:run', [
        //     '--only-db' => 1
        // ]);

        $filename = Carbon::now()->format('Y-m-d-H-i-s');

        $tempPath = base_path('storage\app\backup-temp\\') . $filename;
        $backPath = base_path('storage\app\backups\\') . $filename;

        $command = 'mysqldump -u root --password= ' . env('DB_DATABASE') . ' > ' . $tempPath . '.sql';
        exec($command);

        // zipping 
        $zip = new ZipArchive;
        if ($zip->open($backPath . '.zip', ZipArchive::CREATE) === TRUE) {
            $zip->addFile($tempPath . '.sql', $filename . '.sql');
            $zip->close();
        }

        // clear temp folder
        $this->clearTempFolder();


        return response()->json(['success' => true]);
    }

    private function clearTempFolder()
    {
        //The name of the folder.
        $folder = base_path('storage\app\backup-temp\\');

        //Get a list of all of the file names in the folder.
        $files = glob($folder . '/*');

        //Loop through the file list.
        foreach ($files as $file) {
            //Make sure that this is a file and not a directory.
            if (is_file($file)) {
                //Use the unlink function to delete the file.
                unlink($file);
            }
        }
    }

    public function show($path)
    {
        $file = Storage::disk('local')->get('backups/' . $path);
        return response()->make($file);
    }

    private function humanReadable($bytes)
    {
        $units = ['B', 'KB', 'MB', 'GB', 'TB', 'PB'];
        for ($i = 0; $bytes > 1024; $i++) {
            $bytes /= 1024;
        }
        return round($bytes, 2) . ' ' . $units[$i];
    }

    public function destroy($path)
    {
        Storage::disk('local')->delete('backups/' . $path);
        return response('deleted');
    }
}

```

**Comment by juarezfranco** [comment]
I had the same problem, the solution was to add write permission to the backup folder for the www-data group

**Comment by xlstefan** [comment]
Same issue here.

> I am using
> Route::get('/backup', function(){
> \Artisan::call('backup:run',['--only-db'=>true]);
> });
> 
> Everything works fin in command line and I can run other artisan commands from web.php but when I try to use backup:run from a controller or web.php nothing happens, no errors. If save it to a variable and dd($variable) it gives me a 0. From a controller and web.php, I have tried migrate, make:migration and make:controller. They all work fine. It is just the backup:run that's not working or giving any errors. Any suggestions? Thanks

**Comment by freekmurze** [comment]
If it works from the cli, but not from a webrequest, then the problem is not caused by this package. Probably the PHP process that handles your web request doesn't have permission to call things on the CLI.

**Comment by xlstefan** [comment]
Just to comment for others.

My issue was that I was using PHP 7.3.2 and it didn't work with Laravel 5.8.

**Comment by SamehMourad** [comment]
You can run this using exec 
 
    $projectDir= substr(getcwd(), 0, strpos(getcwd(), '\public'));
    $command = 'cd /d '.$projectDir .'&& php artisan backup:run --only-db';
    exec($command);
    dd('backup run successfully');

**Comment by talha424588** [comment]
> You can run this using exec
> 
> Route::get('/backup', function () { $projectDir= substr(getcwd(), 0, strpos(getcwd(), '\public')); $command = 'cd /d '.$projectDir .'&& php artisan backup:run --only-db'; exec($command); dd('backup run successfully'); });

Thank you so muchhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by rizqi-ardiansyah** [comment]
> You can run this using exec
>
> Route::get('/backup', function () { $projectDir= substr(getcwd(), 0, strpos(getcwd(), '\public')); $command = 'cd /d '.$projectDir .'&& php artisan backup:run --only-db'; exec($command); dd('backup run successfully'); });



> > You can run this using exec
> > Route::get('/backup', function () { $projectDir= substr(getcwd(), 0, strpos(getcwd(), '\public')); $command = 'cd /d '.$projectDir .'&& php artisan backup:run --only-db'; exec($command); dd('backup run successfully'); });
> 
> Thank you so muchhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh



> You can run this using exec
> 
> Route::get('/backup', function () { $projectDir= substr(getcwd(), 0, strpos(getcwd(), '\public')); $command = 'cd /d '.$projectDir .'&& php artisan backup:run --only-db'; exec($command); dd('backup run successfully'); });

Thank you so much, it's the best answerrr

**Comment by Bqss** [comment]
ty bruh
