### ISSUE TITLE
Different disk for clean-up

### ISSUE THREAD

**Issue by sweebee** [spatie/laravel-backup#913]
I'm using TransIP stack for backup. 

I found out that SFTP is VERY slow, so I tried webdav (https://github.com/pascalbaljetmedia/laravel-webdav). Via webdav is very fast, but cleanup doesn't work with webdav.

with SFTP cleanup works fine, is it possible to use a different disk for backing-up and clean-up?

**Comment by freekmurze** [comment]
No, this currently isn't possible.

Maybe you could add another Laravel app on your server where in you configure the package to use the another disk and run only the clean up from there.

**Comment by sweebee** [comment]
Thanks, already extended the cleanup command to get it working.
