### ISSUE TITLE
Dumping database tables with complete column names within INSERT statement

### ISSUE THREAD

**Issue by Aryan1** [spatie/laravel-backup#914]
Please suggest me a way to get complete column names with insert statements in my database dumps. I googled for the same and found that I should use "--complete-insert" with my dump command. How do I use it with this package?

**Comment by freekmurze** [comment]
Here's an example on how you can pass extra options to the db dumper: https://docs.spatie.be/laravel-backup/v6/installation-and-setup#dumping-the-database
