### ISSUE TITLE
How to backup mongodb, project using Laradock

### ISSUE THREAD

**Issue by tranducit95** [spatie/laravel-backup#916]
I am using Laradock and Mongodb, When I run `backup: run` appears a `mongodump: not found` error, what do I need to do to fix this problem?

**Comment by freekmurze** [comment]
I haven’t used laradock, so I can’t help you with this. Make sure mongodump is installed and allowed to be called from PHP.

**Comment by tranducit95** [comment]
> I haven’t used laradock, so I can’t help you with this. Make sure mongodump is installed and allowed to be called from PHP.

I don't know where to install the mongodump, in the workspace or server, I tried it but failed, I tried installing mongodb, mongo tools ... but it doesn't work, can you guide me to solve this problem

**Comment by tranducit95** [comment]
> I haven’t used laradock, so I can’t help you with this. Make sure mongodump is installed and allowed to be called from PHP.
are you there?

**Comment by tranducit95** [comment]
my solution:

workspace/Dockerfile
```
###########################################################################
# Mongodb Tools:
###########################################################################

USER root

ARG INSTALL_MONGO_TOOL=true

RUN if [ ${INSTALL_MONGO_TOOL} = true ]; then \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4 && \
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.0.list && \
    apt-get update -yqq && \
    apt-get -y install mongodb-org-tools \
;fi
```
