### ISSUE TITLE
Google drive backup fails when folder name has underscores

### ISSUE THREAD

**Issue by holymp2006** [spatie/laravel-backup#919]
```
...
"laravel/framework": "5.5.*",
"spatie/laravel-backup": "^5.0.0",
...
```

I've been using Google drive as my default backup disk, and it's been working fine.
Today I tried using a new folder on Google drive, but got an error.

```
Copying zip failed because: {
 "error": {
  "errors": [
   {
    ...
   }
  ],
  "code": 404,
  "message": "File not found: xxxxxx-xxxxx-xxxxx."
 }
}
```

The name of the old folder was just alphanumeric, so all worked well.
The name of the new folder I set is something like `xxxxxx_xxxxx_xxxxx` (with underscores).
The package seems to be renaming the folder to `xxxxxx-xxxxx-xxxxx`, causing the backup to fail when it tries to copy to Google drive - where `xxxxxx-xxxxx-xxxxx` obviously doesn't exist.

Is this the required behaviour?
If yes, please how can I change this behaviour on my own?

**Comment by oriceon** [comment]
Hi @holymp2006. I created a [#917 pull request](https://github.com/spatie/laravel-backup/pull/917) to solve the google drive backup issues but @freekmurze considered it unnecessary...

Anyhow, see what i changed in [src/BackupDestination/BackupDestination.php](https://github.com/spatie/laravel-backup/pull/917/commits/0ffb3d3ddafdb348bf53f12721c14117762a2da4)

**Comment by holymp2006** [comment]
Thank you @oriceon, I'll make the recommended changes.

**Comment by smartsyncio** [comment]
I dont see why this was closed as unnecessary, I am facing the exact same issue trying to backup to both google and digitalocean . Thank you :)
