### ISSUE TITLE
Misuse of shell builtins.

### ISSUE THREAD

**Issue by yadounis** [spatie/laravel-backup#92]
Hi,
I got this problem when running backup:run

`Starting backup...
Dumping database prostats_db...
Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins.
Backup completed!`

I'm running on L5.2, PHP5.6 and Debian 8

**Comment by freekmurze** [comment]
Could you try running a shell command via php?

**Comment by yadounis** [comment]
Yes i can

**Comment by freekmurze** [comment]
Could you try calling mysqldump specifically through php?

**Comment by yadounis** [comment]
Yes i can do that too

**Comment by freekmurze** [comment]
Could you try running a command using `symfony/process` 

http://symfony.com/doc/current/components/process.html

**Comment by heikoeln** [comment]
I have the same problem with two environments:
codeanywhere dev-box: Ubuntu 14.04 with PHP 5.5.9 - Laravel 5.2
digitalocean droplet: Ubuntu 14.04 with PHP 5.5.9 - Laravel 5.2

`php artisan backup:run --only-files`  works! I guess it uses `symfony/process` too.

I think it's a problem with mysqlbackup.

`mysqldump -umyusr -pmypwd --database dbname` works.

`php -r "system('mysqldump -umyusr -pmypwd dbname');"` works too.

But `php artisan backup:run --only-db` fails.

**Comment by freekmurze** [comment]
`--only-files` doesn't use symfony process. Could you try if dumping the db using `spatie/db-dumper` works? (That package is used under the hood of `laravel-backup`)

**Comment by heikoeln** [comment]
Another two tests: 

File backuptest.php:
`include 'vendor/autoload.php';`
`Spatie\DbDumper\Databases\MySql::create()`
`    ->setDbName('dbname')`
`    ->setUserName('myusr')`
`    ->setPassword('mypwd')`
`    ->dumpToFile('test.sql');`

`php backuptest.php` Works fine! (spatie/db-dumper version 1.2.2)
)

File symfonytest.php: 
`<?php`
`use Symfony\Component\Process\Process;`
`use Symfony\Component\Process\Exception\ProcessFailedException;`
`$process = new Process('mysqldump -umyusr -pmypwd dbname');`
`$process->run();`
`if (!$process->isSuccessful()) {`
`    throw new ProcessFailedException($process);`
`}`
`echo $process->getOutput();`

`php symfonytest.php` Was successful too. (symfony/process version 3.0.3)

**Comment by freekmurze** [comment]
Thank you for running these tests. I'm a put stumped because [under the hood](https://github.com/spatie/laravel-backup/blob/master/src/Tasks/Backup/BackupJobFactory.php#L49-L73) laravel-backup does what you've done in your tests. 

Are you running your tests and laravel-backup on the command line?

**Comment by heikoeln** [comment]
Yes, i used the same shell for this three commands:

`me@server:/path/to/approot$ php artisan backup:run`
`me@server:/path/to/approot$ php backuptest.php`
`me@server:/path/to/approot$ php symfonytest.php`

**Comment by sebastiandedeyne** [comment]
Wild guess—

Could you edit `vendor/spatie/db-dumper/src/Databases/MySql.php`, and edit lines 173-178 to this:

```php
$command = [
    "{$this->dumpBinaryPath}mysqldump",
    "-h {$this->host}",
    "--defaults-extra-file={$temporaryCredentialsFile}",
    '--skip-comments',
    $this->useExtendedInserts ? '--extended-insert' : '--skip-extended-insert',
];
```

(the `-h` flag was added)

**Comment by heikoeln** [comment]
The `-h` flag was not the problem... PEBCAK!
I configured `usr/bin/mysqlbackup` for `dump_command_path` in `config/database.php`.

I'm very sorry for the inconvenience... -.-

@yadounis Perhaps you did the same.

**Comment by freekmurze** [comment]
I'll update our documentation to make it more clear that it should only be the path to the binary that should be filled in.

**Comment by yadounis** [comment]
@heikoeln can you please give me more details on how you solved this issue ? Your answer is not clear for me. Thanks.

**Comment by heikoeln** [comment]
@yadounis 
I configured `'dump_command_path' => '/usr/bin/mysqldump',` in `config/database.php`.

But this is right (path only):
`'mysql' => [`
`'driver'    => 'mysql',`
`'dump_command_path' => '/usr/bin',`
[...]
`],`

**Comment by yadounis** [comment]
Both are not working for me, still have the same issue  !

**Comment by heikoeln** [comment]
@yadounis 
Your config is still wrong. 
Change it to  `'dump_command_path' => '/usr/bin',`
(without mysqldump)

**Comment by yadounis** [comment]
I tested both configs : 
`'dump_command_path' => '/usr/bin'`
and 
'dump_command_path' => '/usr/bin/mysqldump'

and both are resulting with the same error

**Comment by heikoeln** [comment]
Ah ok. I understand. Path only is the only way that shoud work.
Are you sure that the conifgured mysql user has the minimum grants for mysqldump? Esp. `LOCK TABLES` is needed.

**Comment by yadounis** [comment]
Yes, it was a privilages issue, its worked when i used the mysql root.

thanks :+1:

**Comment by todayqq** [comment]
和环境是有关系的，如果有用Homestead环境下，必须要进入虚拟机里面执行
> vagrant ssh
> cd /path
> php artisan backup:run

**Comment by shahmir811** [comment]
I am facing the same issue in Laravel 5.7, php 7.1.
Will someone kindly update ?

**Comment by alexbiohacker** [comment]
What privileges it needs?

**Comment by shahmir811** [comment]
Got a solution.
Place your laravel application inside xamp(htdocs) or wamp

stop `php artisan serve`

then enter following in your browser 

localhost/My_APP_NAME/public

**Comment by willbrowningme** [comment]
Was having this same issue on a production server.

```
The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 1045: "Access denied for user 'user'@'localhost' (using password: YES)" when trying to connect
```

I eventually solved it by updating the database user's password and removing special characters such as #.

**Comment by neilodiaz** [comment]
After digging on the `spatie/db-dumper`  library, it seems that the `--defaults-extra-file` on [here](https://github.com/spatie/db-dumper/blob/master/src/Databases/MySql.php#L186) doesn't work for me.  Always returning this error:

`Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 1045: Access denied for user 'root'@'localhost' (using password: YES)...`

I tried changing it to `--defaults-file` and now its working fine. Not sure what happened behind-the-scene. Can someone enlighten me?

My Setup:
```
"laravel/framework": "5.1.*",
"spatie/laravel-backup": "^3.0.0",
```

PS: This is an old project and haven't upgraded the Laravel version since.

**Comment by valiantboymaksud** [comment]
add if you xampp: /Applications/Xampp/bin
if you using Mamp: /Applications/Mamp/Library/bin
