### ISSUE TITLE
Allowed Memory

### ISSUE THREAD

**Issue by joserojasrodriguez** [spatie/laravel-backup#920]
i tried too with `php -d memory_limit=256M artisan backup:run`

`Starting backup...
Dumping database forge...
Dumping database forge2...
Determining files to backup...
Zipping 559 files...
Created zip containing 559 files. Size is 49.16 MB
Copying zip to disk named google...
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 412410536 bytes)`

**Comment by freekmurze** [comment]
This problem is probably related to something in your environment.
