### ISSUE TITLE
Save backup in a subfolder

### ISSUE THREAD

**Issue by henryavila** [spatie/laravel-backup#928]
Hi, I need to save the backups in a specific subfolder of S3. How can I do this? I don`t found in documentation.

Saving in a subfolder is a MUST HAVE for me, because I save multiples sites in one Digital Ocean Space.

Thanks for the help

**Comment by vdbelt** [comment]
You are looking for the filesystems configuration option `root`. 

Example:
```
'disks' => [
    's3' => [
        'root' => 'subfolder/'
    ],
],
```

**Comment by henryavila** [comment]
It works. Thanks
