### ISSUE TITLE
Exclude directory

### ISSUE THREAD

**Issue by jasperf** [spatie/laravel-backup#929]
Is there a built-in way to exclude directory/directories? We would like to store an app excluding some directories in one Digital Ocean Spaces directory and the excluded directories (client data) in another directory. Another directory in the same Digital Ocean Space.

**Comment by atymic** [comment]
You can configure exclusions in the config file.
In terms of backing different files to different locations, I don't think this package supports multiple backup configs.

I would suggest using flysystem or similar to back up this data directly.

**Comment by jasperf** [comment]
Thanks for the feedback @atymic . Figured as much. As for using flysystem instead of this package .. Perhaps we should. We will consider that also.
