### ISSUE TITLE
PHP 7.2 not supported anymore because of db-dumper 7.3 requirement

### ISSUE THREAD

**Issue by Rkallenkoot** [spatie/laravel-backup#932]
In the latest release of spatie/db-dumper, support for PHP7.2 has been dropped. While this package "requires" PHP7.2 but fails composer install because of the 7.3 requirement in db-dumper version 2.14

**Comment by freekmurze** [comment]
If you're on PHP 7.2 you can still use laravel-backup in combination with v2.12 or 2.13 of db-dumper.
