### ISSUE TITLE
Empty View Spatie

### ISSUE THREAD

**Issue by denmaskevin** [spatie/laravel-backup#937]
I have problem when using spatie in laravel to backup my database. it works, but

```
public function index()
    {
        $konfigurasi    =   Konfigurasi::first();
        $level          =   Level::first();
        $user           =   User::get();
        $works          =   Works::get();
        $blog           =   Blog::get();
        $disk 		= Storage::disk(config('laravel-backup.backup.destination.disks')[0]);
        $files 		= $disk->files(config('laravel-backup.backup.name'));
        $backups 	= [];
        foreach ($files as $k => $f)
        {
            if (substr($f, -4) == '.zip' && $disk->exists($f))
            {
                $backups[] = [
                    'file_path' => $f,
                    'file_name' => str_replace(config('laravel-backup.backup.name') . '/', '', $f),
                    'file_size' => $disk->size($f),
                    'last_modified' => $disk->lastModified($f),
                ];
            }
        }
        $backups = array_reverse($backups);
        return view('konfigurasi.backup', compact('konfigurasi', 'level', 'works', 'user', 'kategori', 'blog', 'backups'));
}
```

![Screen Shot 2019-07-22 at 15 42 06](https://user-images.githubusercontent.com/28257878/61614876-5786c500-ac97-11e9-9014-6a1bfca174db.png)

it can't display on my web:

![Screen Shot 2019-07-22 at 15 39 53](https://user-images.githubusercontent.com/28257878/61614711-ffe85980-ac96-11e9-87ad-b7e4f0bc8fc1.png)

**Comment by atymic** [comment]
Can you update your issue to clarify what problem you are having? It's not clear from your post.

**Comment by denmaskevin** [comment]
ok

**Comment by atymic** [comment]
Have you considered trying to do something using the classes the package provides rather than trying to list it manually?
https://github.com/spatie/laravel-backup/blob/master/src/Commands/ListCommand.php

For example, you can get a list of the backups from the `BackupDestination` object:
https://github.com/spatie/laravel-backup/blob/master/src/BackupDestination/BackupDestination.php#L101
