### ISSUE TITLE
Dropbox insufficient_space exception

### ISSUE THREAD

**Issue by rameshtukadiya** [spatie/laravel-backup#941]
When file uploading to dropbox if the insufficient space then cant be a fire exception

**Comment by rameshtukadiya** [comment]
We are using [Flysystem adapter for the Dropbox](https://github.com/spatie/flysystem-dropbox) package to upload backups to Dropbox.

If file upload fails, [it is not](https://github.com/spatie/flysystem-dropbox/blob/master/src/DropboxAdapter.php#L292) throwing an exception. And because of that, the `BackupHasFailed` event is not being triggered.

**Comment by atymic** [comment]
Should this not be an issue on that repo, rather than this one?

**Comment by atymic** [comment]
Unless we should handle `false` as a return code.

**Comment by freekmurze** [comment]
Feel free to PR an improvement on this.
