### ISSUE TITLE
Discontinuing support for JSON-RPC and Global HTTP Batch Endpoints

### ISSUE THREAD

**Issue by jpussacq** [spatie/laravel-backup#942]
On August 9 we received an email from Goolge saying that JSON-RPC and Global HTTP will be discontinued and that projects that use it are required to be migrated.

Within the list of projects that use it, "Laravel-backup" appears.

What can be done with this inconvenience?
Thanks from now.

I transcribe information from Google mail:

> Hello Google API Customer,
> 
> We are writing to let you know that one or more of your Google Cloud projects are currently using either the JSON-RPC or Global HTTP Batch serving endpoint; both of which are scheduled to be turned down on August 12, 2020.
> 
> What do I need to know?
> We had publicly announced our plan to discontinue support for JSON-RPC and Global HTTP Batch serving endpoints for all Google APIs by March 25, 2019. If one or more of your Google Cloud projects were using one of these endpoints at the time of the announcement, you may remember receiving an email regarding this plan to discontinue support for these endpoints.
> 
> It came to our attention that a few customers that would have been highly impacted by this change might not have received the earlier notification. As a result, we are extending the deprecation timeline to August 12, 2020, when we will discontinue support for both features.
> 
> From February 2020 to August 2020, we will periodically inject errors for short windows of time. We will be sending another round of communication close to February 2020, with exact details and schedule of these error injection windows.
> 
> We are moving towards a more distributed, high performance architecture where requests go directly to the appropriate API server. Support for the JSON-RPC protocol and Global HTTP Batch was based on an architecture using a single shared proxy to receive requests for all APIs, so we can no longer support these global endpoints. As a result, we will discontinue support for both of these features.
> 
> What do I need to do?
> Please migrate the applications for your affected projects listed below before August 12, 2020. You only need to migrate those calls made directly by your applications. If the requests are being made on behalf of other services, not directly by you, then no action is required on your part.
> 
> We know that these changes have customer impact and have worked to make the transition steps as clear as possible. Detailed information on how to migrate your existing API Client Libraries can be found on the Google Developers Blog post.
>

**Comment by freekmurze** [comment]
To interact with various cloud filesystems, this package used flysystem drivers. I think it’s best you open an issue for this at flysystem.
