### ISSUE TITLE
The database backup was successful, but an error was reported. Why?

### ISSUE THREAD

**Issue by xiaoxuan6** [spatie/laravel-backup#944]
Copying zip failed because: Expected response code 250 but got code "501", with message "501 mail from address must be same as authorization user
".
Backup failed because Connection to ssl://smtp.qq.com:465 Timed Out.
#0 /home/wwwroot/blogs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(339): Swift_Transport_AbstractSmtpTransport->getFullResponse(20)
#1 /home/wwwroot/blogs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('HELO [127.0.0.1...', Array, Array, false, NULL)
#2 /home/wwwroot/blogs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(365): Swift_Transport_EsmtpTransport->executeCommand('HELO [127.0.0.1...', Array)
#3 /home/wwwroot/blogs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->doHeloCommand()
#4 /home/wwwroot/blogs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand()

**Comment by AdnanMoghal** [comment]
The seems to be the email configuration in you env file. or you can leave the mail->to to empty string.
