### ISSUE TITLE
running on Heroku

### ISSUE THREAD

**Issue by solarsilk** [spatie/laravel-backup#945]
I'm trying to get v6 running on Heroku. I'm using the buildpack at https://github.com/gaumire/heroku-buildpack-mysql.git and I can verify that mysqldump is being installed at `/app/.heroku/vendor/mysql/bin`.  

I've put this into my config/database.php file:
```
'dump' => [
     'dump_binary_path' => '/app/.heroku/vendor/mysql/bin'
] 
```
The backup runs fine, I get the email notification, the zip get stored on S3 and contains a dump file. But the dump file is empty. I've also tried other variations on the `dump_binary_path` but it only generates an empty dump file.  Any ideas? Thank you!

**Comment by atymic** [comment]
Have you checked the log files. Are there any errors in there?

**Comment by solarsilk** [comment]
@atymic I gave up on this, switching to https://github.com/ifsnop/mysqldump-php which is working well.

As far as I can remember, there were no errors. The backup was running but producing an empty dump file.
