### ISSUE TITLE
Potential dependency versioning problem

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/laravel-backup#947]
https://github.com/spatie/db-dumper/blob/master/CHANGELOG.md#2141---2019-05-10 says "drop support for PHP 7.2 and lower"

But in the laravel-backup package, https://github.com/spatie/laravel-backup/blob/36aabc5edac3ea570d9f8b8ea44e656f3d629d0c/CHANGELOG.md doesn't say anything similar, and https://github.com/spatie/laravel-backup/blob/36aabc5edac3ea570d9f8b8ea44e656f3d629d0c/composer.json just says it requires `"php": "^7.0"`

So a recent deployment of mine failed because my server is still PHP 7.2, and my composer.json had said `"spatie/laravel-backup": "^5.0.4",`.

Am I doing something wrong, or was there a mistake in the versioning or the dependencies here?

Thanks.

P.S. I just noticed an existing issue: https://github.com/spatie/laravel-backup/issues/904

But I'll submit this one anyway since it really does seem like a problem (either to fix or at least be aware of so that similar versioning incompatibilities don't happen in the future). Thank you so much for your amazing library!!

**Comment by freekmurze** [comment]
Even though this is really a problem that should be fixed at the composer end (it should be able to find the right combination of packages), I’ll consider tagging a major version when dropping support for a PHP version

**Comment by ryancwalsh** [comment]
@freekmurze Good point, and thanks.
