### ISSUE TITLE
What is a 'dump_binary_path' on AWS Elastic Beanstalk?

### ISSUE THREAD

**Issue by zoran-php** [spatie/laravel-backup#951]
In the config/database.php mysql connection, what should be added as 'dump_binary_path' when deploying on AWS Elastic Beanstalk?
This is my configuration on my local MacMini:
```
'dump' => [
       'dump_binary_path' => '/Applications/MAMP/Library/bin',
       'use_single_transaction',
       'timeout' => 60 * 5, // 5 minute timeout
       'exclude_tables' => ['qwerty']
 ]
```

**Comment by freekmurze** [comment]
I’m not using Beanstalk, best to ask this on a related forum.
