### ISSUE TITLE
save backup files on different path

### ISSUE THREAD

**Issue by falahatiali** [spatie/laravel-backup#954]
How can I save backup files on a different path?
for example in my server with this address: /opt/backup

**Comment by atymic** [comment]
Just create a new disk in the filesystem config:

```php
'backup' => [
   'driver' => 'local',
   'root' => '/opt/backup',
],
```

Then add it as a destination here:
https://github.com/spatie/laravel-backup/blob/master/config/backup.php#L88-L100
