### ISSUE TITLE
queue:work timeouts 

### ISSUE THREAD

**Issue by ChrisSFR** [spatie/laravel-backup#956]
Thanks to the new Flareapp.io I'm monitoring queue Timouts exactly at the hourly backup times . 
I've multiple queue tasks  (~20) which are configured in laravel forge. 

For some of them I get: 
`The process "'/usr/bin/php7.3' 'artisan' 'queue:work' 'database' '--once' '--queue=task-name' '--delay=0' '--memory=128' '--sleep=10' '--tries=1'" exceeded the timeout of 60 seconds.`

Is it possible that it's because of my hourly backups? Because the errors always occurs at the hourly backup times like 6:01:23 , 4:01:12 , 03:01:40 etc.

All jobs are running fine and there are no failed jobs, but I get those exceptions in my flare app.

I think I'll switch to horizon with the redis queue and see if the errors also occurs. 
But I'm interested if someone got a similar behavior. Or if it is even possible that laravel-backup is the trigger of those failures.

**Comment by atymic** [comment]
Are you queuing you backups? If you are running them with the scheduler they shouldn't be using the queue at all.

**Comment by ChrisSFR** [comment]
Thanks for your reply. I've this in my Console Kernel.php

`if (config('backup.backup.active')) {
            $schedule->command('backup:clean')->daily()->withoutOverlapping();
            $schedule->command('backup:run')->hourly()->withoutOverlapping();
        }`

So I'm not queuing my backups. Thats what makes me worry.

**Comment by ChrisSFR** [comment]
@atymic @freekmurze 

I think I found the problem.

The dump process locked our mysql tables. So all Write accesses on the database were locked.

But now I found this hint in the new backup.php config file:

`* If you are using only InnoDB tables on a MySQL server, you can
             * also supply the useSingleTransaction option to avoid table locking.
             *
             * E.g.
             * 'mysql' => [
             *       ...
             *      'dump' => [
             *           'useSingleTransaction' => true,
             *       ],
             * ],`

We are only using InnoDB Tables so adding 'useSingleTransaction' => true, will avoid the table locking.

Maybe adding an explicit hint on the documentation would be helpful? Or in the installation process?

https://docs.spatie.be/laravel-backup/v6/installation-and-setup/

I think it's a very important option or does it have a lot drawbacks?
