### ISSUE TITLE
Backup stops and remaining destinations fail if there is a notification error

### ISSUE THREAD

**Issue by joshhanley** [spatie/laravel-backup#960]
I'm experiencing an issue where remaining backup destinations don't run if sending a notification fails.

I have just setup laravel-backup to backup to local storage and dropbox. 
I have configured email notifications with mailgun.

This was all working fine, then mailgun disabled my account pending business verification.

What happens now is when backup is run, it backs up to local storage, tries to send a notifcation of success, which fails due to mailgun error, then the whole backup process fails and it doesn't copy the zip to dropbox. 

This is a concern if backups stop mid process due to an error on a service such as mailgun. I would expect it to attempt to copy the files to the remaining destinations regardless of notification status.

Is there a way for backup to continue even if notifications fail?

Thanks in advance!

**Comment by freekmurze** [comment]
We'll handle this futher in #961
