### ISSUE TITLE
Exception message: fwrite() expects parameter 1 to be resource, boolean given

### ISSUE THREAD

**Issue by kingsleyudenewu** [spatie/laravel-backup#963]
Hello I am currently using laravel-backup version 5.12.1, when i try the backup from the terminal it works but when i try to backup my db on a request i get the following error.

Exception trace: #0 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'fwrite() expect...', '/Applications/X...', 181, Array) #1 [internal function]: Raven_Breadcrumbs_ErrorHandler->handleError(2, 'fwrite() expect...', '/Applications/X...', 181, Array) #2 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/spatie/db-dumper/src/Databases/MySql.php(181): fwrite(false, '[client]\nuser =...') #3 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(246): Spatie\DbDumper\Databases\MySql->dumpToFile('/Applications/X...') #4 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup{closure}(Object(Spatie\DbDumper\Databases\MySql), 'mysql') #5 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Support/Collection.php(932): array_map(Object(Closure), Array, Array) #6 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(249): Illuminate\Support\Collection->map(Object(Closure)) #7 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(166): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases() #8 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(142): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest() #9 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(52): Spatie\Backup\Tasks\Backup\BackupJob->run() #10 [internal function]: Spatie\Backup\Commands\BackupCommand->handle() #11 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #12 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container{closure}() #13 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(App\Application), Array, Object(Closure)) #14 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(App\Application), Array, Array, NULL) #15 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Console/Command.php(179): Illuminate\Container\Container->call(Array) #16 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle)) #17 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Console/Command.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle)) #18 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #19 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/symfony/console/Application.php(915): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #20 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #21 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #22 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #23 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Console/Application.php(188): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #24 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(250): Illuminate\Console\Application->call('backup:run', Array, NULL) #25 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): Illuminate\Foundation\Console\Kernel->call('backup:run', Array) #26 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/seamlesshr/database-backup/src/Http/Controllers/DatabaseBackupController.php(30): Illuminate\Support\Facades\Facade::__callStatic('call', Array) #27 [internal function]: SeamlessHr\DatabaseBackup\Http\Controllers\DatabaseBackupController->createBackup() #28 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array) #29 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('createBackup', Array) #30 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(SeamlessHr\DatabaseBackup\Http\Controllers\DatabaseBackupController), 'createBackup') #31 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController() #32 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\Routing\Route->run() #33 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #34 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/staffstrength/layout/src/Http/Middleware/AdminAccess.php(35): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #35 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): StaffStrength\Layout\Http\Middleware\AdminAccess->handle(Object(Illuminate\Http\Request), Object(Closure)) #36 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #37 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/app/Http/Middleware/ForceSSL.php(20): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #38 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\Http\Middleware\ForceSSL->handle(Object(Illuminate\Http\Request), Object(Closure)) #39 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #40 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/app/Http/Middleware/SentryContext.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #41 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\Http\Middleware\SentryContext->handle(Object(Illuminate\Http\Request), Object(Closure)) #42 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #43 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #44 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure)) #45 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #46 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #47 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure)) #48 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #49 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #50 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure)) #51 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #52 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #53 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #54 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #55 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #56 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #57 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #58 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #59 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure)) #60 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #61 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #62 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure)) #63 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #64 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #65 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #66 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request)) #67 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route)) #68 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #69 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #70 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http{closure}(Object(Illuminate\Http\Request)) #71 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #72 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure)) #73 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #74 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #75 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure)) #76 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #77 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #78 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure)) #79 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #80 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #81 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure)) #82 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #83 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #84 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure)) #85 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #86 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #87 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\Cors\HandlePreflight->handle(Object(Illuminate\Http\Request), Object(Closure)) #88 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request)) #89 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request)) #90 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #91 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request)) #92 /Applications/XAMPP/xamppfiles/htdocs/staff-strength-core/public_html/index.php(47): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #93 {main}

**Comment by kumarravisingh** [comment]
Seems like, When you are running the command `php artisan backup:run` backup  is getting generated, but when you are passing it on request there is some error and it is trying to write that error in logs file but your storage/logs folder doesn't have 777 permission so rather than getting the actual error you are getting the permission error.
check storage/logs folder permission and change it to 777.
