### ISSUE TITLE
Laravel 6.x - notInstantiable

### ISSUE THREAD

**Issue by whoami213** [spatie/laravel-backup#966]
## Laravel Version
 - 6.0.4

## Installation of Laravel-backup
 - using composer based on the documentation

## Error Encountered
 - after installation using composer then error occured in Exception Trace:
 `Illuminate\Container\Container::notInstantiable("Spatie\Backup\Tasks\Cleanup\CleanupStrategy")`

## Attached Image

![Screenshot from 2019-10-02 08-11-27](https://user-images.githubusercontent.com/18107626/66009459-17409000-e4ed-11e9-8ee1-6e429f73a43f.png)
![Screenshot from 2019-10-02 08-11-55](https://user-images.githubusercontent.com/18107626/66009460-17d92680-e4ed-11e9-92dc-71cf47b2581d.png)

**Comment by rubenvanassche** [comment]
Hi @whoami213,

I have no problems when installing with Laravel 6.0.4, could you please try again? I will close this for now.

**Comment by whoami213** [comment]
Hi @rubenvanassche,
This issue still exists on installing on my app even I updated my laravel version it still exists. It still throws the same error message on me.
