### ISSUE TITLE
Different cleanup strategies for different disks

### ISSUE THREAD

**Issue by zakius** [spatie/laravel-backup#969]
Is there a way to set this up easily (i.e. not setting up multiple cleaning up applications)?
If not could you consider implementing it?

**Comment by freekmurze** [comment]
You can create your own clean up strategy: https://docs.spatie.be/laravel-backup/v6/cleaning-up-old-backups/overview/#creating-your-own-strategy

A `Spatie\Backup\BackupDestination\Backup`  knows on which disk it is saved.

**Comment by patrickomeara** [comment]
Hi @freekmurze 

The `disk` property is protected on `Spatie\Backup\BackupDestination\Backup` with no clean way of accessing it from `deleteOldBackups` method of `CleanupStrategy`.

I can see two options to make this a little easier:
We can either add a public `disk` getter like `Spatie\Backup\BackupDestination\BackupDestination` has

```php
public function disk(): Filesystem
{
    return $this->disk;
}
```

Or we pass the the disk to `deleteOldBackups()` from `CleanupJob`

```php
// separately
$this->strategy->deleteOldBackups($backupDestination->backups(), $backupDestination->disk());
// or pass $backupDestination
$this->strategy->deleteOldBackups($backupDestination);
```

I'm happy to get a PR together for either option.

**Comment by freekmurze** [comment]
Send a PR for the first option 👍

**Comment by patrickomeara** [comment]
@zakius have a look at the code example in #974 it may help you
