### ISSUE TITLE
Backup saved not as zip-file

### ISSUE THREAD

**Issue by Woutje99** [spatie/laravel-backup#97]
Hi,

When i'm running: `php artisan backup:run` and look at my localfile system.
The backup is saved as programme and I can't open it? It's not a zip-file...

What i'm doing wrong?

--- Edit
When i'm looking in the finder, and click show package then I see the zip file..
How is this possible?

**Comment by freekmurze** [comment]
If you can see a zip file in the finder I guess all is good?

**Comment by Woutje99** [comment]
Not really: I see this:
<img width="555" alt="backup" src="https://cloud.githubusercontent.com/assets/2621077/13847097/acc3e17a-ec4b-11e5-80c4-39d7f5ffc57f.png">

When I right click and click show package, then I see the zip files.. 
That's not normal I think?

**Comment by freekmurze** [comment]
Nope, that's not normal.

Could you list your OSX version, PHP version, used webserver.

**Comment by Woutje99** [comment]
OSX 10.11.3
PHP 7.0.1
Webserver is homestead using vagrant

**Comment by freekmurze** [comment]
What was causing this issue?
And how did you solve it?
