### ISSUE TITLE
View status and progress from application

### ISSUE THREAD

**Issue by daar** [spatie/laravel-backup#970]
From what I understand backup will only work from the CLI. Is it also possible to have a log shown via a blade view (out of the box)? This way the end-users can verify themselves if backups are done, what the status is and when one was taken.

In case this is not available, would a pull request be accepted?

**Comment by freekmurze** [comment]
Thank you for your proposal.

I'd like to keep this package simple. Providing a UI is out of scope.

**Comment by pavel-mironchik** [comment]
@daar you can now try this one: https://github.com/pavel-mironchik/laravel-backup-panel
