### ISSUE TITLE
Problems with 32bit php

### ISSUE THREAD

**Issue by schonhoff** [spatie/laravel-backup#975]
Hello,

I run into some problems with a 32 bit php. I can't look up my backup list nor can I look it up in your nova tool. The main problem is described in  #567 .The Fork from CharlieEtienne isn't updated so I don't want to use it. Maybe we can fix it in the real package?

Thanks for the great package and keep up the good work!

If you need more information just reply.

**Comment by freekmurze** [comment]
I'm not running into the problem myself and don't have time to investigate. I'd accept a PR to fix it in this package.

**Comment by schonhoff** [comment]
Did a pull request for the issue. It fixed the problem for me but it needs a validation for a 64bit php system. #976

**Comment by freekmurze** [comment]
We'll continue the conversation in #976
