### ISSUE TITLE
Specify file types to backup

### ISSUE THREAD

**Issue by shahrooz7216** [spatie/laravel-backup#979]
Hi, I wonder if there is any option to specify which file types to backup(only pdf files for example, or only jpg files), or provide an asterisk in source->files->include, (ex: *.jpg) to include all files that have jpg extension.
Can it be done? I would appreciate the help

**Comment by freekmurze** [comment]
You can also use the manifest to have fine grained control over what gets backed up.

https://docs.spatie.be/laravel-backup/v6/advanced-usage/adding-extra-files-to-a-backup/
