### ISSUE TITLE
PostgreSQL dump with column inserts

### ISSUE THREAD

**Issue by willsilvano** [spatie/laravel-backup#98]
Hello,

can you add a option to dump pgsql with command "--inserts" to generate insert commands instead "Copy".

**Comment by freekmurze** [comment]
I'll add this in the near feature. If you need this quick submit a PR on this repo and on [db-dumper](https://github.com/spatie/dbdumper)

**Comment by freekmurze** [comment]
In v3.4.0 you can use the `dump_use_inserts` option. A little note on this was added at the bottom of this page in the docs: https://docs.spatie.be/laravel-backup/v3/installation-and-setup
