### ISSUE TITLE
[PHP 7.4 RC3] Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by HepplerDotNet** [spatie/laravel-backup#981]
After updating development system from PHP 7.3.10 to PHP 7.4 RC3 the cleanup backups job fails with:
Trying to access array offset on value of type null
vendor/spatie/laravel-backup/src/Tasks/Cleanup/Strategies/DefaultStrategy.php(47)

**Comment by HepplerDotNet** [comment]
My fault, I also updated all packages and forgot to re-publish config file, where keys have changed.

**Comment by daaner** [comment]
the same error, didn’t watch that the values changed in the config )))
