### ISSUE TITLE
Version 6.7 Dependency Error

### ISSUE THREAD

**Issue by robinflyhigh** [spatie/laravel-backup#983]
Our laravel framework is 6.0

Using version ^6.7 for spatie/laravel-backup
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-backup ^6.7 -> satisfiable by spatie/laravel-backup[6.7.0].
    - spatie/laravel-backup 6.7.0 requires orchestra/testbench 3.8.* -> satisfiable by orchestra/testbench[3.8.x-dev, v3.8.0, v3.8.1, v3.8.2, v3.8.3, v3.8.4, v3.8.5].
    - orchestra/testbench 3.8.x-dev requires laravel/framework ~5.8.35 -> satisfiable by laravel/framework[5.8.x-dev].
    - orchestra/testbench v3.8.0 requires laravel/framework ~5.8.0 -> satisfiable by laravel/framework[5.8.x-dev].
    - orchestra/testbench v3.8.1 requires laravel/framework ~5.8.2 -> satisfiable by laravel/framework[5.8.x-dev].
    - orchestra/testbench v3.8.2 requires laravel/framework ~5.8.3 -> satisfiable by laravel/framework[5.8.x-dev].
    - orchestra/testbench v3.8.3 requires laravel/framework ~5.8.19 -> satisfiable by laravel/framework[5.8.x-dev].
    - orchestra/testbench v3.8.4 requires laravel/framework ~5.8.19 -> satisfiable by laravel/framework[5.8.x-dev].
    - orchestra/testbench v3.8.5 requires laravel/framework ~5.8.35 -> satisfiable by laravel/framework[5.8.x-dev].
    - Conclusion: don't install laravel/framework 5.8.x-dev

Installation failed, reverting ./composer.json to its original content.

**Comment by freekmurze** [comment]
Does it work for you in a clean Laravel app?

**Comment by coryrose1** [comment]
I think it works on a fresh Laravel install. However, the error is also occuring with an existing application I have on Laravel 6.3.0. Let me know if I can provide any further detail.

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for spatie/laravel-backup ^6.7 -> satisfiable by spatie/laravel-backup[6.7.0].
>     - Can only install one of: laravel/framework[v6.3.0, 5.8.x-dev].
>     - Can only install one of: laravel/framework[5.8.x-dev, v6.3.0].
>     - Can only install one of: laravel/framework[5.8.x-dev, v6.3.0].
>     - Conclusion: install laravel/framework 5.8.x-dev
>     - Installation request for laravel/framework (locked at v6.3.0, required as ^6.0) -> satisfiable by laravel/framework[v6.3.0].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by fitztrev** [comment]
PR #984 should fix this. I believe the `orchestra/testbench` requirement was inadvertently changed in the last release.

**Comment by freekmurze** [comment]
This has been fixed in the latest release. Thanks for bringing this to my attention.
