### ISSUE TITLE
Splitting database backup into multiple .sql file

### ISSUE THREAD

**Issue by blorange2** [spatie/laravel-backup#988]
If I have an absolutely huge database and only need to restore a single table it can be difficult to do so as the file hangs most editors. Is there a way to split the SQL dump into multiple smaller files per each table?

**Comment by atymic** [comment]
I don't think this package supports it, but it's possible with the underlying `db-dumper` package:
https://github.com/spatie/db-dumper

Even a DB dump of a few MBs will hang most editors. You should be executing the file directly against the database server (you don't need to open it).

If you need to check the file, use something like `less` which doesn't load the entire file into RAM.
