### ISSUE TITLE
Calling backup:run from controller issue

### ISSUE THREAD

**Issue by zerocool12** [spatie/laravel-backup#99]
When calling artisan command backup:run from my controller, it doesnot seem to work. where as calling it from my CLI gives me the backup folder. my storage is local.

**Comment by freekmurze** [comment]
From a package standpoint there is no difference if you run the command from a web request or from the cli. If it works on your cli and not via a web request, it's probably a permission issue on your server.

Please verify if PHP is allowed to run shell commands when handling a web request.
