### ISSUE TITLE
[Advice] - Back up multiple MySQL databases

### ISSUE THREAD

**Issue by louisluu** [spatie/laravel-backup#998]
Hi there,

Thanks for the awesome package.

Is there an optimal way to use this package to back up multiple databases (Im talking about a few hundreds so  using the config is not a way to go).

Found this https://github.com/spatie/laravel-backup/issues/745 and https://github.com/spatie/laravel-backup/issues/75 but not really helpful in this case.

Im thinking of a way to programmatically fetch all databases, then loop through each database, update the database name on the fly using `config(['database_name' => 'my_database_name'])` and then call the backup command `backup:run`. The problem is I dont want to receive notifications for each run (gonna be heaps if multiple by the number of databases); and also dont know how the monitoring will work ?!?

So, Im seeking for advice if anyone has a better solution to achieve this?

Cheers,

**Comment by djunehor** [comment]
Most times, a single database user is attached to each database. So, you can't use the same database login to access multiple databases. And that's the ideal settings.

What you can do is create a custom command (`php artisan make:command NewCommand`). The command will fetch each specific database details (from your .env file maybe), then run `php artisan backup:run` via Artisan::call('backup:run'); You can then schedule a job to run the Command at your desired interval

**Comment by louisluu** [comment]
Thanks @djunehor 

We are using 1 sql user per database, and we also have some users that can access to all databases for reporting and admin stuff.

Your suggestion is pretty much what I have mentioned above: fetch all databases, loop and run.
But then, If I run on 1000+ databases, then I will receive 1000+ success (or failed) notification emails, which I dont want.

**Comment by freekmurze** [comment]
Closing this for now, as this isn't an issue for the package. Feel free to continue to conversation here however.

**Comment by Luksys3** [comment]
I had the same problem. I have tenancy in my application and each tenant has his own database. I found a solution how to backup all of those databases with using `php artisan backup:run` once. Hope this helps you.

What I did, I created a new artisan command `php artisan backup:make`. Here's a simplified version:
```php
$otherDatabases = collect([
    'shop-03f42db8-8940-4a28-ab99-d3bfaf724a3a',
    'shop-c1a4930a-7cb8-423e-828e-751f7138367b',
]);

$connections = config('database.connections');
$connectionName = config('database.default');

$newConnections = collect();
$otherDatabases->each(function ($database) use (
    $newConnections,
    $connections,
    $connectionName
) {
    $connection = $connections[$connectionName];
    $connection['database'] = $database;
    $newConnections[$connectionName . '-' . $database] = $connection;
});

config([
    'database.connections' => collect($connections)
        ->merge($newConnections)
        ->toArray(),
]);

$backupDatabases = collect(config('backup.backup.source.databases'));
$newConnections
    ->keys()
    ->each(function ($connectionName) use ($backupDatabases) {
        $backupDatabases->push($connectionName);
    });
config([
    'backup.backup.source.databases' => $backupDatabases->toArray(),
]);

Artisan::call('backup:run');
```

In this command I add additional database connections, which in reality are other databases. Later in the code I also add those "databases" to spatie's backup config. Lastly, I just run `Artisan::call('backup:run')` which start the backup process.

**Comment by caswd** [comment]
Update: I used @Luksys3 solution, but since the newer versions of this package have a non-standard way of reading the config, it did not work.

The way to change the `backup.backup.source.databases` config (or any config for this package) is:

```php
$spatieBackupConfig = app()->get(Spatie\Backup\Config\Config::class);

$spatieBackupConfig->backup->source->databases = [
    'landlord',
    'tenant_1',
    'tenant_2',
    // etc...
];
``` 

There is probably a very smart reason why they did this, but it does make changing the config on the fly different than a Laravel developer would expect.
