### ISSUE TITLE
Change the link in the repository header to the docs instead of a blog post

### ISSUE THREAD

**Issue by robjbrain** [spatie/laravel-backup#999]
Only a small thing but I don't think this is something I can change with a pull request, when looking for the docs the most obvious place you see first is the header of the git repository, but it links to an old blog post discussing V4, it would be better if this was updated to link to the docs instead:

![image](https://user-images.githubusercontent.com/10143910/69683936-aee7e680-110a-11ea-913c-34014fd9c7fb.png)

**Comment by freekmurze** [comment]
Good idea, done!
